<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\StaticCard;
use App\Models\StaticDeck;
use Illuminate\Database\Seeder;

class StaticCardFile5Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all Advanced level static decks
        $advancedDecks = StaticDeck::where('level', 'advanced')->get();

        if ($advancedDecks->isEmpty()) {
            $this->command->error('No Advanced level static decks found. Please run StaticDeckSeeder first.');

            return;
        }

        // Lesson 1 vocabulary
        $lesson1Deck = $advancedDecks->where('lesson_number', 1)->first();
        if ($lesson1Deck) {
            $this->seedLesson1($lesson1Deck);
        }

        // Lesson 2 vocabulary
        $lesson2Deck = $advancedDecks->where('lesson_number', 2)->first();
        if ($lesson2Deck) {
            $this->seedLesson2($lesson2Deck);
        }

        // Lesson 3 vocabulary
        $lesson3Deck = $advancedDecks->where('lesson_number', 3)->first();
        if ($lesson3Deck) {
            $this->seedLesson3($lesson3Deck);
        }

        // Lesson 4 vocabulary
        $lesson4Deck = $advancedDecks->where('lesson_number', 4)->first();
        if ($lesson4Deck) {
            $this->seedLesson4($lesson4Deck);
        }

        // Lesson 5 vocabulary
        $lesson5Deck = $advancedDecks->where('lesson_number', 5)->first();
        if ($lesson5Deck) {
            $this->seedLesson5($lesson5Deck);
        }

        // Lesson 6 vocabulary
        $lesson6Deck = $advancedDecks->where('lesson_number', 6)->first();
        if ($lesson6Deck) {
            $this->seedLesson6($lesson6Deck);
        }

        // Lesson 7 vocabulary
        $lesson7Deck = $advancedDecks->where('lesson_number', 7)->first();
        if ($lesson7Deck) {
            $this->seedLesson7($lesson7Deck);
        }

        // Lesson 8 vocabulary
        $lesson8Deck = $advancedDecks->where('lesson_number', 8)->first();
        if ($lesson8Deck) {
            $this->seedLesson8($lesson8Deck);
        }

        // Lesson 9 vocabulary
        $lesson9Deck = $advancedDecks->where('lesson_number', 9)->first();
        if ($lesson9Deck) {
            $this->seedLesson9($lesson9Deck);
        }

        // Lesson 10 vocabulary
        $lesson10Deck = $advancedDecks->where('lesson_number', 10)->first();
        if ($lesson10Deck) {
            $this->seedLesson10($lesson10Deck);
        }

    }

    protected function seedLesson1($deck)
    {
        $vocabulary = [
            ['front' => 'catch up', 'back' => 'اطلاعات تازه به‌دست آوردن', 'pronunciation' => '/kæʧ ʌp /'],
            ['front' => 'grit one\'s teeth', 'back' => 'دندان قروچه کردن', 'pronunciation' => '/grɪt wʌnz tiθ /'],
            ['front' => 'stick to your guns', 'back' => 'سر حرف خود ماندن', 'pronunciation' => '/stɪk tu jʊər gʌnz /'],
            ['front' => 'know your own mind', 'back' => 'روی عقیده خود پافشاری کردن', 'pronunciation' => '/noʊ jʊər oʊn maɪnd /'],
            ['front' => 'comfort zone', 'back' => 'کنج راحتی', 'pronunciation' => '/ˈkʌmfərt zoʊn /'],
            ['front' => 'fill in', 'back' => 'در جریان گذاشتن', 'pronunciation' => '/fɪl ɪn /'],
            ['front' => 'speak one\'s mind', 'back' => 'حرف دل خود را زدن', 'pronunciation' => '/spik wʌnz maɪnd /'],
            ['front' => 'cross one\'s mind', 'back' => 'به ذهن رسیدن', 'pronunciation' => '/krɔs wʌnz maɪnd /'],
            ['front' => 'Mind your own business!', 'back' => 'سرت به کار خودت باشد!', 'pronunciation' => '/maɪnd jʊər oʊn ˈbɪznəs! /'],
            ['front' => 'be of two minds about something', 'back' => 'دودل بودن راجع به چیزی', 'pronunciation' => '/bi ʌv tu maɪndz əˈbaʊt ˈsʌmθɪŋ /'],
            ['front' => 'in a sense', 'back' => 'از یک جهت', 'pronunciation' => '/ɪn ə sɛns /'],
            ['front' => 'short-term', 'back' => 'کوتاه‌مدت', 'pronunciation' => '/ʃɔːrtˈtɜrm /'],
            ['front' => 'work-life balance', 'back' => 'تعادل زندگی شخصی-زندگی کاری', 'pronunciation' => '/ˌwɜːrk laɪf ˈbæləns /'],
            ['front' => 'contract', 'back' => 'قرارداد', 'pronunciation' => '/ˈkɑːntrækt /'],
            ['front' => 'work', 'back' => 'شغل', 'pronunciation' => '/wɜːrk /'],
            ['front' => 'environment', 'back' => 'محیط', 'pronunciation' => '/enˈvɑɪ.rən.mənt /'],
            ['front' => 'staff', 'back' => 'پرسنل', 'pronunciation' => '/stæf /'],
            ['front' => 'turnover', 'back' => 'نرخ تعدیل و جایگزینی (کارمندان)', 'pronunciation' => '/ˈtɜːrnoʊvər /'],
            ['front' => 'competitive', 'back' => 'رقابتی', 'pronunciation' => '/kəmˈpet̬.ət̬.ɪv /'],
            ['front' => 'salary', 'back' => 'حقوق', 'pronunciation' => '/ˈsæl.ə.ri /'],
            ['front' => 'challenging', 'back' => 'چالش‌برانگیز', 'pronunciation' => '/ˈtʃæl.ən.dʒɪŋ /'],
            ['front' => 'monotonous', 'back' => 'یکنواخت', 'pronunciation' => '/məˈnɑːtənəs /'],
            ['front' => 'repetitive', 'back' => 'تکراری', 'pronunciation' => '/rɪˈpetətɪv /'],
            ['front' => 'rewarding', 'back' => 'پرارزش', 'pronunciation' => '/rɪˈwɔːrdɪŋ /'],
            ['front' => 'motivating', 'back' => 'انگیزه‌بخش', 'pronunciation' => '/ˈmoʊtɪveɪtɪŋ /'],
            ['front' => 'demanding', 'back' => 'دشوار', 'pronunciation' => '/dɪˈmæn.dɪŋ /'],
            ['front' => 'tedious', 'back' => 'خسته‌کننده', 'pronunciation' => '/ˈtidiəs /'],
            ['front' => 'career', 'back' => 'شغل', 'pronunciation' => '/kəˈrɪr /'],
            ['front' => 'position', 'back' => 'کار', 'pronunciation' => '/pəˈzɪʃ.ən /'],
            ['front' => 'profession', 'back' => 'شغل', 'pronunciation' => '/prəˈfeʃ.ən /'],
            ['front' => 'apply', 'back' => 'درخواست دادن', 'pronunciation' => '/əˈplɑɪ /'],
            ['front' => 'human resources', 'back' => 'منابع انسانی', 'pronunciation' => '/ˌhjuːmən rɪˈsɔːrsɪz /'],
            ['front' => 'multinational', 'back' => 'چندملیتی', 'pronunciation' => '/ˌmʌlˌtaɪˈnæʃənəl /'],
            ['front' => 'base', 'back' => '(در مکانی) قرار داشتن', 'pronunciation' => '/beɪs /'],
            ['front' => 'wage', 'back' => 'دستمزد', 'pronunciation' => '/weɪdʒ /'],
            ['front' => 'bonus', 'back' => 'پاداش', 'pronunciation' => '/ˈboʊ.nəs /'],
            ['front' => 'perk', 'back' => 'مزیت', 'pronunciation' => '/pɜːrk /'],
            ['front' => 'benefit', 'back' => 'مزیت', 'pronunciation' => '/ˈben.ə.fɪt /'],
            ['front' => 'money', 'back' => 'حقوق', 'pronunciation' => '/ˈmʌn.i /'],
            ['front' => 'employer', 'back' => 'کارفرما', 'pronunciation' => '/ɪmˈplɔɪ.ər /'],
            ['front' => 'employee', 'back' => 'کارمند', 'pronunciation' => '/ɛmˈplɔɪi /'],
            ['front' => 'skill', 'back' => 'مهارت', 'pronunciation' => '/skɪl /'],
            ['front' => 'training', 'back' => 'آموزش', 'pronunciation' => '/ˈtreɪ.nɪŋ /'],
            ['front' => 'qualification', 'back' => 'صلاحیت', 'pronunciation' => '/ˌkwɑl.ə.fəˈkeɪ.ʃən /'],
            ['front' => 'in charge of', 'back' => 'مسئول', 'pronunciation' => '/ɪn ʧɑrʤ ʌv /'],
            ['front' => 'deal with', 'back' => 'رسیدگی کردن', 'pronunciation' => '/dil wɪð /'],
            ['front' => 'responsible', 'back' => 'مسئول', 'pronunciation' => '/rɪˈspɑn.sə.bəl /'],
            ['front' => 'off', 'back' => 'مرخصی', 'pronunciation' => '/ɔːf /'],
            ['front' => 'opportunity', 'back' => 'فرصت', 'pronunciation' => '/ˌɑp.ərˈtuː.nət̬.i /'],
            ['front' => 'advancement', 'back' => 'ترفیع', 'pronunciation' => '/ədˈvænsmənt /'],
            ['front' => 'get promoted', 'back' => 'ترفیع گرفتن', 'pronunciation' => '/gɛt prəˈmoʊtəd /'],
            ['front' => 'raise', 'back' => 'افزایش حقوق', 'pronunciation' => '/reɪz /'],
            ['front' => 'temporary', 'back' => 'موقت', 'pronunciation' => '/ˈtem.pəˌrer.i /'],
            ['front' => 'job security', 'back' => 'امنیت شغلی', 'pronunciation' => '/ʤɑb sɪˈkjʊrəti /'],
            ['front' => 'fire', 'back' => 'اخراج کردن', 'pronunciation' => '/fɑɪr /'],
            ['front' => 'part-time', 'back' => 'نیمه‌وقت', 'pronunciation' => '/ˈpɑrtˈtaɪm /'],
            ['front' => 'lay off', 'back' => 'اخراج کردن', 'pronunciation' => '/ˈleɪ ɔːf /'],
            ['front' => 'out of work', 'back' => 'بیکار', 'pronunciation' => '/aʊt ʌv wɜrk /'],
            ['front' => 'voluntary', 'back' => 'داوطلبانه', 'pronunciation' => '/ˈvɑːlənteri /'],
            ['front' => 'experience', 'back' => 'تجربه', 'pronunciation' => '/ɪkˈspɪr.iː.əns /'],
            ['front' => 'unpaid', 'back' => 'بدون پول', 'pronunciation' => '/ˌʌnˈpeɪd /'],
            ['front' => 'cautious', 'back' => 'مراقب', 'pronunciation' => '/ˈkɔʃəs /'],
            ['front' => 'conscientious', 'back' => 'باوجدان', 'pronunciation' => '/ˌkɑnʃiˈɛnʃəs /'],
            ['front' => 'curious', 'back' => 'کنجکاو', 'pronunciation' => '/ˈkjʊr.iː.əs /'],
            ['front' => 'easy-going', 'back' => 'بی‌خیال', 'pronunciation' => '/ˌIː.ziːˈgoʊ.ɪŋ /'],
            ['front' => 'independent', 'back' => 'مستقل', 'pronunciation' => '/ˌɪn.dɪˈpen.dənt /'],
            ['front' => 'logical', 'back' => 'منطقی', 'pronunciation' => '/ˈlɑʤɪkəl /'],
            ['front' => 'loyal', 'back' => 'وفادار', 'pronunciation' => '/ˈlɔɪ.əl /'],
            ['front' => 'mature', 'back' => 'بالغ', 'pronunciation' => '/məˈʧʊr /'],
            ['front' => 'quiet', 'back' => 'آرام و کم‌حرف', 'pronunciation' => '/ˈkwɑɪət /'],
            ['front' => 'rebellious', 'back' => 'یاغی', 'pronunciation' => '/rɪˈbeljəs /'],
            ['front' => 'self-sufficient', 'back' => 'خودکفا', 'pronunciation' => '/ˈsɛlfsəˈfɪʃənt /'],
            ['front' => 'sensitive', 'back' => 'حساس', 'pronunciation' => '/ˈsɛnsətɪv /'],
            ['front' => 'in advance', 'back' => 'از پیش', 'pronunciation' => '/ɪn ədˈvæns /'],
            ['front' => 'get stuck', 'back' => 'گیر کردن', 'pronunciation' => '/gɛt stʌk /'],
            ['front' => 'make sure', 'back' => 'اطمینان حاصل کردن', 'pronunciation' => '/meɪk ʃʊr /'],
            ['front' => 'catch one\'s eye', 'back' => 'توجه کسی را به خود جلب کردن', 'pronunciation' => '/kæʧ wʌnz aɪ /'],
            ['front' => 'go with one\'s gut feeling', 'back' => 'به حس درونی خود گوش کردن', 'pronunciation' => '/goʊ wɪð wʌnz gʌt ˈfilɪŋ /'],
            ['front' => 'head on', 'back' => 'رو در رو', 'pronunciation' => '/ˌhed ˈɑːn /'],
            ['front' => 'white lie', 'back' => 'دروغ مصلحتی', 'pronunciation' => '/waɪt laɪ /'],
            ['front' => 'hurt', 'back' => 'ناراحت کردن', 'pronunciation' => '/hɜːrt /'],
            ['front' => 'keep it short', 'back' => 'کوتاه کردن حرف', 'pronunciation' => '/kip ɪt ʃɔrt /'],
            ['front' => 'brother-in-law', 'back' => 'برادر زن/شوهر', 'pronunciation' => '/ˈbrʌð.ər.ɪn.lɔː /'],
            ['front' => 'sister-in-law', 'back' => 'خواهر شوهر', 'pronunciation' => '/ˈsɪstər-ɪn-lɔ /'],
            ['front' => 'take after', 'back' => 'به کسی رفتن', 'pronunciation' => '/teɪk ˈæftər /'],
            ['front' => 'close', 'back' => 'صمیمی', 'pronunciation' => '/kloʊz /'],
            ['front' => 'get along with', 'back' => 'کنار آمدن', 'pronunciation' => '/gɛt əˈlɔŋ wɪð /'],
            ['front' => 'see eye to eye', 'back' => 'توافق نظر داشتن', 'pronunciation' => '/si aɪ tu aɪ /'],
            ['front' => 'be on speaking terms', 'back' => 'آشتی بودن', 'pronunciation' => '/bi ɑn ˈspikɪŋ tɜrmz /'],
            ['front' => 'run in the family', 'back' => 'ارثی بودن در خانواده', 'pronunciation' => '/rʌn ɪn ðə ˈfæməli /'],
            ['front' => 'family get-together', 'back' => 'دورهمی خانوادگی', 'pronunciation' => '/ˈfæməli ˈgɛttəˈgɛðər /'],
            ['front' => 'black sheep', 'back' => 'مایه ننگ', 'pronunciation' => '/blæk ʃip /'],
            ['front' => 'nuclear family', 'back' => 'خانواده هسته‌ای', 'pronunciation' => '/ˌnuːkliər ˈfæməli /'],
            ['front' => 'step-parent', 'back' => 'پدرخوانده یا مادرخوانده', 'pronunciation' => '/ˈstep perənt /'],
            ['front' => 'half-brother', 'back' => 'برادر ناتنی', 'pronunciation' => '/ˈhæf brʌðər /'],
            ['front' => 'half-sister', 'back' => 'خواهر ناتنی', 'pronunciation' => '/ˈhæf sɪstər /'],
            ['front' => 'stepbrother', 'back' => 'برادر ناتنی', 'pronunciation' => '/ˈstepbrʌðər /'],
            ['front' => 'stepsister', 'back' => 'ناخواهری', 'pronunciation' => '/ˈstepsɪstər /'],
            ['front' => 'single-parent', 'back' => 'مادر/پدر تنها (بدون همسر)', 'pronunciation' => '/ˌsɪŋɡl ˈperənt /'],
            ['front' => 'grow up', 'back' => 'بزرگ شدن', 'pronunciation' => '/groʊ ʌp /'],
            ['front' => 'father figure', 'back' => 'مثل پدر', 'pronunciation' => '/ˈfɑːðər fɪɡjər /'],
            ['front' => 'member', 'back' => 'عضو', 'pronunciation' => '/ˈmem.bər /'],
            ['front' => 'extended family', 'back' => 'خانواده گسترده', 'pronunciation' => '/ɪkˌstendɪd ˈfæməli /'],
            ['front' => 'spread out', 'back' => 'پراکنده شدن', 'pronunciation' => '/sprɛd aʊt /'],
            ['front' => 'relative', 'back' => 'خویشاوند', 'pronunciation' => '/ˈrel.ət̬.ɪv /'],
            ['front' => 'great-grandparent', 'back' => 'پدر پدربزرگ/مادربزرگ', 'pronunciation' => '/greɪt-ˈgrændˌpɛrənt /'],
            ['front' => 'look like', 'back' => 'شبیه بودن', 'pronunciation' => '/lʊk laɪk /'],
            ['front' => 'far', 'back' => 'دور', 'pronunciation' => '/fɑːr /'],
            ['front' => 'distant', 'back' => 'دور', 'pronunciation' => '/ˈdɪs.tənt /'],
            ['front' => 'single', 'back' => 'یک', 'pronunciation' => '/ˈsɪŋ.gəl /'],
            ['front' => 'only child', 'back' => 'تک فرزند', 'pronunciation' => '/ˈoʊnli ʧaɪld /'],
            ['front' => 'alike', 'back' => 'شبیه (به هم)', 'pronunciation' => '/əˈlɑɪk /'],
            ['front' => 'like', 'back' => 'مشابه', 'pronunciation' => '/lɑɪk /'],
            ['front' => 'near', 'back' => 'نزدیک', 'pronunciation' => '/nɪr /'],
            ['front' => 'sibling', 'back' => 'خواهر یا/و برادر', 'pronunciation' => '/ˈsɪblɪŋ /'],
            ['front' => 'educate', 'back' => 'آموزش دادن', 'pronunciation' => '/ˈɛʤəˌkeɪt /'],
            ['front' => 'bring up', 'back' => 'تربیت کردن', 'pronunciation' => '/brɪŋ ʌp /'],
            ['front' => 'grow', 'back' => 'رشد کردن', 'pronunciation' => '/groʊ /'],
            ['front' => 'relation', 'back' => 'رابطه', 'pronunciation' => '/rəˈleɪ.ʃən /'],
            ['front' => 'relationship', 'back' => 'رابطه', 'pronunciation' => '/rəˈleɪ.ʃənˌʃɪp /'],
            ['front' => 'ancestor', 'back' => 'جد', 'pronunciation' => '/ˈænˌses.tər /'],
            ['front' => 'descendant', 'back' => 'نواده', 'pronunciation' => '/dɪˈsɛndənt /'],
            ['front' => 'wear the pants in the family', 'back' => 'سرپرست خانواده بودن', 'pronunciation' => '/wɛr ðə pænts ɪn ðə ˈfæməli /'],
            ['front' => 'skeleton in the closet', 'back' => 'راز مگو', 'pronunciation' => '/ˈskɛlətən ɪn ðə ˈklɑzət /'],
            ['front' => 'own flesh and blood', 'back' => 'خویشاوند', 'pronunciation' => '/oʊn flɛʃ ænd blʌd /'],
            ['front' => 'scheme', 'back' => 'دسیسه', 'pronunciation' => '/skiːm /'],
            ['front' => 'venture', 'back' => 'ریسک', 'pronunciation' => '/ˈvɛnʧər /'],
            ['front' => 'insight', 'back' => 'بینش', 'pronunciation' => '/ˈɪnsaɪt /'],
            ['front' => 'solvent', 'back' => 'قادر به پرداخت بدهی', 'pronunciation' => '/ˈsɑlvənt /'],
            ['front' => 'stake', 'back' => 'سهم', 'pronunciation' => '/steɪk /'],
            ['front' => 'launch', 'back' => 'به بازار معرفی کردن', 'pronunciation' => '/lɔːntʃ /'],
            ['front' => 'reputation', 'back' => 'آوازه', 'pronunciation' => '/ˌrɛpjəˈteɪʃən /'],
            ['front' => 'rudimentary', 'back' => 'ابتدایی', 'pronunciation' => '/ˌrudəˈmɛntəri /'],
            ['front' => 'schedule', 'back' => 'برنامه زمانی', 'pronunciation' => '/ˈskedʒ.uːl /'],
            ['front' => 'fundamental', 'back' => 'بنیادی', 'pronunciation' => '/ˌfʌndəˈmɛntəl /'],
            ['front' => 'face to face', 'back' => 'رو در رو', 'pronunciation' => '/feɪs tu feɪs /'],
            ['front' => 'prone', 'back' => 'در معرض', 'pronunciation' => '/proʊn /'],
            ['front' => 'trait', 'back' => 'ویژگی', 'pronunciation' => '/treɪt /'],
            ['front' => 'maintain', 'back' => 'ادعا کردن', 'pronunciation' => '/meɪnˈteɪn /'],
            ['front' => 'diminish', 'back' => 'فروکش کردن', 'pronunciation' => '/dɪˈmɪnɪʃ /'],
            ['front' => 'affliction', 'back' => 'درد', 'pronunciation' => '/əˈflɪkʃn /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 1');

    }

    protected function seedLesson2($deck)
    {
        $vocabulary = [
            ['front' => 'conduct', 'back' => 'انجام دادن', 'pronunciation' => '/ˈkɑndʌkt /'],
            ['front' => 'view', 'back' => 'دانستن', 'pronunciation' => '/vjuː /'],
            ['front' => 'poor', 'back' => 'ضعیف', 'pronunciation' => '/pɔːr /'],
            ['front' => 'transcribe', 'back' => 'به‌صورت نوشتاری درآوردن', 'pronunciation' => '/trænˈskraɪb /'],
            ['front' => 'omit', 'back' => 'حذف کردن', 'pronunciation' => '/oʊˈmɪt /'],
            ['front' => 'require', 'back' => 'نیاز داشتن', 'pronunciation' => '/rɪˈkwaɪər /'],
            ['front' => 'notion', 'back' => 'ایده', 'pronunciation' => '/ˈnoʊʃən /'],
            ['front' => 'remain', 'back' => 'باقی ماندن', 'pronunciation' => '/rɪˈmeɪn /'],
            ['front' => 'adhere to', 'back' => 'پایبند بودن به', 'pronunciation' => '/ədˈhɪr tu /'],
            ['front' => 'thus', 'back' => 'بنابراین', 'pronunciation' => '/ðʌs /'],
            ['front' => 'ensure', 'back' => 'اطمینان حاصل کردن', 'pronunciation' => '/ɛnˈʃʊr /'],
            ['front' => 'terminology', 'back' => 'اصطلاحات (علمی یا فنی)', 'pronunciation' => '/ˌtɜːrməˈnɑːlədʒi /'],
            ['front' => 'collocation', 'back' => 'همایند', 'pronunciation' => '/ˌkɑ.ləˈkeɪ.ʃən /'],
            ['front' => 'colloquial', 'back' => 'محاوره‌ای', 'pronunciation' => '/kəˈloʊkwiəl /'],
            ['front' => 'idiom', 'back' => 'اصطلاح', 'pronunciation' => '/ˈɪd.iː.əm /'],
            ['front' => 'metaphor', 'back' => 'استعاره (صنعت ادبی)', 'pronunciation' => '/ˈmɛtəfɔr /'],
            ['front' => 'phrasal verb', 'back' => 'فعل عبارتی', 'pronunciation' => '/ˌfreɪ.zəlˈvɜːrb /'],
            ['front' => 'register', 'back' => 'گونه کاربردی (زبان‌شناسی)', 'pronunciation' => '/ˈredʒ.ɪ.stər /'],
            ['front' => 'slang', 'back' => 'زبان عامیانه', 'pronunciation' => '/slæŋ /'],
            ['front' => 'synonym', 'back' => 'مترادف', 'pronunciation' => '/ˈsɪnənɪm /'],
            ['front' => 'abstract noun', 'back' => 'اسم انتزاعی', 'pronunciation' => '/ˌæbstrækt ˈnaʊn /'],
            ['front' => 'adulthood', 'back' => 'بلوغ', 'pronunciation' => '/ˈædʌlthʊd /'],
            ['front' => 'fear', 'back' => 'ترس', 'pronunciation' => '/fɪr /'],
            ['front' => 'shame', 'back' => 'شرم', 'pronunciation' => '/ʃeɪm /'],
            ['front' => 'belief', 'back' => 'باور', 'pronunciation' => '/bɪˈliːf /'],
            ['front' => 'boredom', 'back' => 'ملالت', 'pronunciation' => '/ˈbɔrdəm /'],
            ['front' => 'celebration', 'back' => 'جشن', 'pronunciation' => '/ˌsel.əˈbreɪ.ʃən /'],
            ['front' => 'competition', 'back' => 'رقابت', 'pronunciation' => '/ˌkɑm.pəˈtɪʃ.ən /'],
            ['front' => 'death', 'back' => 'مرگ', 'pronunciation' => '/deθ /'],
            ['front' => 'freedom', 'back' => 'آزادی', 'pronunciation' => '/ˈfriːd.əm /'],
            ['front' => 'friendship', 'back' => 'رفاقت', 'pronunciation' => '/ˈfrend.ʃɪp /'],
            ['front' => 'happiness', 'back' => 'خوشحالی', 'pronunciation' => '/ˈhæp.iː.nəs /'],
            ['front' => 'hatred', 'back' => 'نفرت', 'pronunciation' => '/ˈheɪtrəd /'],
            ['front' => 'imagination', 'back' => 'قوه‌ تخیل', 'pronunciation' => '/ɪˌmædʒ.əˈneɪ.ʃən /'],
            ['front' => 'sickness', 'back' => 'مریضی', 'pronunciation' => '/ˈsɪk.nəs /'],
            ['front' => 'kindness', 'back' => 'مهربانی', 'pronunciation' => '/ˈkaɪnd.nəs /'],
            ['front' => 'loss', 'back' => 'ضرر', 'pronunciation' => '/lɑːs /'],
            ['front' => 'membership', 'back' => 'عضویت', 'pronunciation' => '/ˈmem.bərˌʃɪp /'],
            ['front' => 'neighborhood', 'back' => 'محله', 'pronunciation' => '/ˈneɪbərˌhʊd /'],
            ['front' => 'partnership', 'back' => 'شراکت', 'pronunciation' => '/ˈpɑːrtnərʃɪp /'],
            ['front' => 'poverty', 'back' => 'فقر', 'pronunciation' => '/ˈpɑːvərti /'],
            ['front' => 'sadness', 'back' => 'غم', 'pronunciation' => '/ˈsæd.nəs /'],
            ['front' => 'wisdom', 'back' => 'عقل', 'pronunciation' => '/ˈwɪzdəm /'],
            ['front' => 'extinct', 'back' => 'منقرض‌شده', 'pronunciation' => '/ɪkˈstɪŋkt /'],
            ['front' => 'settlement', 'back' => 'کوچگاه', 'pronunciation' => '/ˈsetlmənt /'],
            ['front' => 'handful', 'back' => 'تعداد کمی', 'pronunciation' => '/ˈhændˌfʊl /'],
            ['front' => 'migrate', 'back' => 'مهاجرت کردن', 'pronunciation' => '/ˈmaɪˌgreɪt /'],
            ['front' => 'extensive', 'back' => 'وسیع', 'pronunciation' => '/ɪkˈstɛnsɪv /'],
            ['front' => 'hand down', 'back' => 'منتقل کردن', 'pronunciation' => '/hænd daʊn /'],
            ['front' => 'gender', 'back' => 'جنسیت', 'pronunciation' => '/ˈdʒen.dər /'],
            ['front' => 'inanimate', 'back' => 'بی‌جان', 'pronunciation' => '/ɪnˈænɪmət /'],
            ['front' => 'coin', 'back' => 'ساختن (واژه یا عبارت زبانی)', 'pronunciation' => '/kɔɪn /'],
            ['front' => 'shelter', 'back' => 'محافظت کردن', 'pronunciation' => '/ˈʃel.t̬ər /'],
            ['front' => 'unwittingly', 'back' => 'ناآگاهانه', 'pronunciation' => '/ʌnˈwɪtɪŋli /'],
            ['front' => 'entice', 'back' => 'وسوسه کردن', 'pronunciation' => '/ɪnˈtaɪs /'],
            ['front' => 'roam', 'back' => 'پرسه زدن', 'pronunciation' => '/roʊm /'],
            ['front' => 'turn back the clock', 'back' => 'زمان را به عقب برگرداندن', 'pronunciation' => '/tɜrn bæk ðə klɑk /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 2');

    }

    protected function seedLesson3($deck)
    {
        $vocabulary = [
            ['front' => 'reject', 'back' => 'بی‌توجهی کردن', 'pronunciation' => '/ˈriʤɛkt /'],
            ['front' => 'dump', 'back' => 'ول کردن', 'pronunciation' => '/dʌmp /'],
            ['front' => 'break up', 'back' => 'بهم زدن (رابطه عاشقانه)', 'pronunciation' => '/breɪk ʌp /'],
            ['front' => 'praise', 'back' => 'تعریف و تمجید کردن', 'pronunciation' => '/preɪz /'],
            ['front' => 'blame', 'back' => 'مقصر شناختن', 'pronunciation' => '/bleɪm /'],
            ['front' => 'ridicule', 'back' => 'مسخره کردن', 'pronunciation' => '/ˈrɪdɪkjuːl /'],
            ['front' => 'replace', 'back' => 'جایگزین کردن', 'pronunciation' => '/rɪˈpleɪs /'],
            ['front' => 'substitute', 'back' => 'جایگزین کردن', 'pronunciation' => '/ˈsʌb.stəˌtuːt /'],
            ['front' => 'revive', 'back' => 'احیا کردن', 'pronunciation' => '/rɪˈvaɪv /'],
            ['front' => 'unwillingly', 'back' => 'از روی بی‌میلی', 'pronunciation' => '/ʌnˈwɪlɪŋli /'],
            ['front' => 'obviously', 'back' => 'آشکارا', 'pronunciation' => '/ˈɑb.viː.ə.sli /'],
            ['front' => 'unbearably', 'back' => 'به طرز غیرقابل تحمل', 'pronunciation' => '/ʌnˈbeərəbli /'],
            ['front' => 'stuck', 'back' => 'گیرکرده', 'pronunciation' => '/stʌk /'],
            ['front' => 'invent', 'back' => 'اختراع کردن', 'pronunciation' => '/ɪnˈvent /'],
            ['front' => 'attach', 'back' => 'وصل کردن', 'pronunciation' => '/əˈtætʃ /'],
            ['front' => 'post', 'back' => 'پست کردن', 'pronunciation' => '/poʊst /'],
            ['front' => 'make up', 'back' => 'درست کردن', 'pronunciation' => '/meɪk ʌp /'],
            ['front' => 'peak', 'back' => 'اوج', 'pronunciation' => '/piːk /'],
            ['front' => 'top', 'back' => 'بالا', 'pronunciation' => '/tɑːp /'],
            ['front' => 'crowning', 'back' => 'باشکوه', 'pronunciation' => '/ˈkraʊnɪŋ /'],
            ['front' => 'get over', 'back' => '(بر چیزی) غلبه کردن', 'pronunciation' => '/gɛt ˈoʊvər /'],
            ['front' => 'get rid of', 'back' => 'از شر (چیزی) خلاص شدن', 'pronunciation' => '/gɛt rɪd ɒv /'],
            ['front' => 'reciprocal', 'back' => 'دوجانبه', 'pronunciation' => '/rɪˈsɪprəkl /'],
            ['front' => 'mutual', 'back' => 'متقابل', 'pronunciation' => '/ˈmjuʧuəl /'],
            ['front' => 'share', 'back' => 'سهیم بودن', 'pronunciation' => '/ʃer /'],
            ['front' => 'smoke', 'back' => 'دود', 'pronunciation' => '/smoʊk /'],
            ['front' => 'fuel', 'back' => 'سوخت', 'pronunciation' => '/ˈfjuː.əl /'],
            ['front' => 'gasoline', 'back' => 'بنزین', 'pronunciation' => '/ˈgæsəˌlin /'],
            ['front' => 'get even', 'back' => 'تلافی کردن', 'pronunciation' => '/gɛt ˈivɪn /'],
            ['front' => 'get a hold of', 'back' => 'نگه داشتن', 'pronunciation' => '/gɛt ə hoʊld ʌv /'],
            ['front' => 'get in trouble', 'back' => 'به دردسر افتادن', 'pronunciation' => '/gɛt ɪn ˈtrʌbəl /'],
            ['front' => 'get out of the way', 'back' => 'از سر راه کنار رفتن', 'pronunciation' => '/gɛt aʊt ʌv ðə weɪ /'],
            ['front' => 'get back at', 'back' => 'انتقام گرفتن', 'pronunciation' => '/gɛt bæk æt /'],
            ['front' => 'get to know', 'back' => '(کسی/چیزی را) شناختن', 'pronunciation' => '/gɛt tu noʊ /'],
            ['front' => 'get', 'back' => 'دریافت کردن', 'pronunciation' => '/get /'],
            ['front' => 'get the impression', 'back' => 'متوجه شدن', 'pronunciation' => '/gɛt ði ɪmˈprɛʃən /'],
            ['front' => 'get real', 'back' => 'واقع‌گرا شدن', 'pronunciation' => '/gɛt riəl /'],
            ['front' => 'get a life', 'back' => 'این قدر بی‌حوصله نباش', 'pronunciation' => '/gɛt ə laɪf /'],
            ['front' => 'get anywhere', 'back' => 'پیشرفت کردن', 'pronunciation' => '/gɛt ˈɛniˌwɛr /'],
            ['front' => 'get on one\'s nerves', 'back' => 'روی اعصاب کسی رفتن', 'pronunciation' => '/gɛt ɑn wʌnz nɜrvz /'],
            ['front' => 'get your act together', 'back' => 'خود را جمع و جور کردن', 'pronunciation' => '/gɛt jʊər ækt təˈgɛðər /'],
            ['front' => 'get along', 'back' => 'کنار آمدن', 'pronunciation' => '/gɛt əˈlɔŋ /'],
            ['front' => 'get the short end of the stick', 'back' => 'بدبیاری آوردن', 'pronunciation' => '/gɛt ðə ʃɔrt ɛnd ʌv ðə stɪk /'],
            ['front' => 'get the message', 'back' => 'متوجه منظور شدن', 'pronunciation' => '/gɛt ðə ˈmɛsəʤ /'],
            ['front' => 'get one\'s own way', 'back' => 'کار خود را کردن (علیرغم مخالفت دیگران)', 'pronunciation' => '/gɛt wʌnz oʊn weɪ /'],
            ['front' => 'get together', 'back' => 'دور هم جمع شدن', 'pronunciation' => '/gɛt təˈgɛðər /'],
            ['front' => 'get into', 'back' => 'وارد حرفه‌ای شدن', 'pronunciation' => '/gɛt ˈɪntu /'],
            ['front' => 'get around', 'back' => 'رفت‌و‌آمد کردن', 'pronunciation' => '/gɛt əˈraʊnd /'],
            ['front' => 'get away with', 'back' => 'قسر در رفتن', 'pronunciation' => '/gɛt əˈweɪ wɪð /'],
            ['front' => 'get by', 'back' => 'امورات خود را گذراندن', 'pronunciation' => '/gɛt baɪ /'],
            ['front' => 'get ahead', 'back' => 'موفق شدن', 'pronunciation' => '/gɛt əˈhɛd /'],
            ['front' => 'get somebody down', 'back' => '(کسی را) ناراحت کردن', 'pronunciation' => '/gɛt ˈsʌmˌbɑdi daʊn /'],
            ['front' => 'get out', 'back' => 'بیرون رفتن', 'pronunciation' => '/gɛt aʊt /'],
            ['front' => 'get back to', 'back' => 'تماس گرفتن', 'pronunciation' => '/gɛt bæk tu /'],
            ['front' => 'arrow', 'back' => 'تیر', 'pronunciation' => '/ˈær.oʊ /'],
            ['front' => 'outnumber', 'back' => 'بیشتر بودن (تعداد)', 'pronunciation' => '/aʊtˈnʌmbər /'],
            ['front' => 'overthrow', 'back' => 'سرنگون کردن', 'pronunciation' => '/ˌoʊvərˈθroʊ /'],
            ['front' => 'rebel', 'back' => 'شورش کردن', 'pronunciation' => '/ˈrebl /'],
            ['front' => 'troop', 'back' => 'گروه سربازان', 'pronunciation' => '/truːp /'],
            ['front' => 'victorious', 'back' => 'پیروز', 'pronunciation' => '/vɪkˈtɔriəs /'],
            ['front' => 'besiege', 'back' => 'محاصره کردن', 'pronunciation' => '/bɪˈsiːdʒ /'],
            ['front' => 'civil war', 'back' => 'جنگ داخلی', 'pronunciation' => '/ˈsɪvəl wɔr /'],
            ['front' => 'loot', 'back' => 'غارت کردن', 'pronunciation' => '/luːt /'],
            ['front' => 'capture', 'back' => 'اسیر کردن', 'pronunciation' => '/ˈkæpʧər /'],
            ['front' => 'casualty', 'back' => 'کشته', 'pronunciation' => '/ˈkæʒəwəlti /'],
            ['front' => 'defeat', 'back' => 'شکست دادن', 'pronunciation' => '/dəˈfiːt /'],
            ['front' => 'force', 'back' => 'نیرو', 'pronunciation' => '/fɔːrs /'],
            ['front' => 'rebellion', 'back' => 'شورش', 'pronunciation' => '/rɪˈbeljən /'],
            ['front' => 'weapon', 'back' => 'سلاح', 'pronunciation' => '/ˈwep.ən /'],
            ['front' => 'lead', 'back' => 'اصلی', 'pronunciation' => '/liːd /'],
            ['front' => 'female', 'back' => 'مؤنث', 'pronunciation' => '/ˈfiˌmeɪl /'],
            ['front' => 'première', 'back' => 'نمایش افتتاحیه', 'pronunciation' => '/prɪˈmjɪr /'],
            ['front' => 'credit', 'back' => 'وام', 'pronunciation' => '/ˈkredɪt /'],
            ['front' => 'plot', 'back' => 'پیرنگ', 'pronunciation' => '/plɑːt /'],
            ['front' => 'sequence', 'back' => 'سکانس', 'pronunciation' => '/ˈsiːkwəns /'],
            ['front' => 'dialogue', 'back' => 'دیالوگ', 'pronunciation' => '/ˈdaɪəlɑːɡ /'],
            ['front' => 'screen', 'back' => 'به نمایش در آوردن', 'pronunciation' => '/skrin /'],
            ['front' => 'big screen', 'back' => 'سینما', 'pronunciation' => '/ˌbɪɡ ˈskriːn /'],
            ['front' => 'period film', 'back' => 'فیلم تاریخی', 'pronunciation' => '/ˈpɪriəd fɪlm /'],
            ['front' => 'release', 'back' => 'منتشر کردن', 'pronunciation' => '/rɪˈliːs /'],
            ['front' => 'review', 'back' => 'نقد', 'pronunciation' => '/rɪˈvjuː /'],
            ['front' => 'see red', 'back' => 'عصبانی شدن', 'pronunciation' => '/si rɛd /'],
            ['front' => 'dispute', 'back' => 'مشاجره', 'pronunciation' => '/dɪˈspjut /'],
            ['front' => 'charge', 'back' => 'متهم کردن', 'pronunciation' => '/tʃɑːrdʒ /'],
            ['front' => 'lick', 'back' => 'لیس زدن', 'pronunciation' => '/lɪk /'],
            ['front' => 'bring back', 'back' => 'به یاد (کسی) آوردن', 'pronunciation' => '/brɪŋ bæk /'],
            ['front' => 'recoverable', 'back' => 'قابل بازیابی', 'pronunciation' => '/rɪˈkʌvərəbl /'],
            ['front' => 'drop by', 'back' => 'به کسی سر زدن (بدون خبر قبلی)', 'pronunciation' => '/drɑp baɪ /'],
            ['front' => 'withdraw', 'back' => 'عقب نشینی کردن', 'pronunciation' => '/wɪðˈdrɔː /'],
            ['front' => 'declare', 'back' => 'اعلام کردن', 'pronunciation' => '/dɪˈkler /'],
            ['front' => 'wounded', 'back' => 'مجروح', 'pronunciation' => '/ˈwuːndɪd /'],
            ['front' => 'break out', 'back' => '(ناگهان) آغاز شدن', 'pronunciation' => '/breɪk aʊt /'],
            ['front' => 'shell', 'back' => 'تیراندازی کردن', 'pronunciation' => '/ʃel /'],
            ['front' => 'blow up', 'back' => 'منفجر کردن', 'pronunciation' => '/bloʊ ʌp /'],
            ['front' => 'treaty', 'back' => 'عهدنامه', 'pronunciation' => '/ˈtriːti /'],
            ['front' => 'ceasefire', 'back' => 'آتش‌بس (جنگ و ...)', 'pronunciation' => '/ˈsiˈsfaɪər /'],
            ['front' => 'surrender', 'back' => 'تسلیم شدن', 'pronunciation' => '/səˈrendər /'],
            ['front' => 'refugee', 'back' => 'پناهنده', 'pronunciation' => '/ˌref.jʊˈdʒiː /'],
            ['front' => 'survivor', 'back' => 'بازمانده', 'pronunciation' => '/sərˈvɑɪ.vər /'],
            ['front' => 'mold', 'back' => 'قالب‌گیری کردن', 'pronunciation' => '/moʊld /'],
            ['front' => 'pivotal', 'back' => 'حیاتی', 'pronunciation' => '/ˈpɪvətəl /'],
            ['front' => 'slaughter', 'back' => 'قتل‌عام کردن', 'pronunciation' => '/ˈslɔːtər /'],
            ['front' => 'advance', 'back' => 'پیشروی کردن', 'pronunciation' => '/ədˈvæns /'],
            ['front' => 'mercilessly', 'back' => 'بی‌رحمانه', 'pronunciation' => '/ˈmɜːrsɪləsli /'],
            ['front' => 'credits', 'back' => 'تیتراژ پایانی', 'pronunciation' => '/ˈkrɛdɪts /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 3');

    }

    protected function seedLesson4($deck)
    {
        $vocabulary = [
            ['front' => 'bang', 'back' => 'کوبیدن', 'pronunciation' => '/bæŋ /'],
            ['front' => 'bang', 'back' => 'صدای بلند (و ناگهانی)', 'pronunciation' => '/bæŋ /'],
            ['front' => 'buzz', 'back' => 'وز وز (صدای زنبور و ...)', 'pronunciation' => '/bʌz /'],
            ['front' => 'click', 'back' => 'صدای تق دادن', 'pronunciation' => '/klɪk /'],
            ['front' => 'click', 'back' => 'صدای تق', 'pronunciation' => '/klɪk /'],
            ['front' => 'crash', 'back' => 'برخورد کردن', 'pronunciation' => '/kræʃ /'],
            ['front' => 'crash', 'back' => 'صدای بلند', 'pronunciation' => '/kræʃ /'],
            ['front' => 'creak', 'back' => 'غژغژ کردن', 'pronunciation' => '/krik /'],
            ['front' => 'creak', 'back' => 'صدای غژغژ', 'pronunciation' => '/krik /'],
            ['front' => 'crunch', 'back' => '(با صدای) قرچ قرچ خوردن', 'pronunciation' => '/krʌntʃ /'],
            ['front' => 'crunch', 'back' => 'صدای خرت خرت', 'pronunciation' => '/krʌntʃ /'],
            ['front' => 'drip', 'back' => 'چکه کردن', 'pronunciation' => '/drɪp /'],
            ['front' => 'drip', 'back' => 'چکه', 'pronunciation' => '/drɪp /'],
            ['front' => 'hiss', 'back' => 'هیس کردن', 'pronunciation' => '/hɪs /'],
            ['front' => 'hiss', 'back' => 'صدای هیس', 'pronunciation' => '/hɪs /'],
            ['front' => 'honk', 'back' => 'صدا کردن غاز', 'pronunciation' => '/hɑŋk /'],
            ['front' => 'honk', 'back' => 'بوق (اتومبیل و ...)', 'pronunciation' => '/hɑŋk /'],
            ['front' => 'hum', 'back' => '(پیوسته) وزوز کردن', 'pronunciation' => '/hʌm /'],
            ['front' => 'hum', 'back' => 'وزوز (صدا)', 'pronunciation' => '/hʌm /'],
            ['front' => 'rattle', 'back' => 'تلق‌تلوق کردن', 'pronunciation' => '/ˈrætl /'],
            ['front' => 'rattle', 'back' => 'صدای تلق تلوق', 'pronunciation' => '/ˈrætl /'],
            ['front' => 'roar', 'back' => 'غریدن', 'pronunciation' => '/rɔːr /'],
            ['front' => 'roar', 'back' => 'غرش', 'pronunciation' => '/rɔːr /'],
            ['front' => 'screech', 'back' => 'صدایی شبیه جیغ تولید کردن', 'pronunciation' => '/skriːtʃ /'],
            ['front' => 'screech', 'back' => 'صدای زیر و گوشخراش', 'pronunciation' => '/skriːtʃ /'],
            ['front' => 'slurp', 'back' => 'هورت کشیدن', 'pronunciation' => '/slɜːrp /'],
            ['front' => 'slurp', 'back' => 'هورت', 'pronunciation' => '/slɜːrp /'],
            ['front' => 'sniff', 'back' => 'فین‌فین', 'pronunciation' => '/snɪf /'],
            ['front' => 'sniff', 'back' => 'بو کشیدن', 'pronunciation' => '/snɪf /'],
            ['front' => 'snore', 'back' => 'خروپف کردن', 'pronunciation' => '/snɔːr /'],
            ['front' => 'snore', 'back' => 'خروپف', 'pronunciation' => '/snɔːr /'],
            ['front' => 'splash', 'back' => 'صدای شلپ شلوپ (آب)', 'pronunciation' => '/splæʃ /'],
            ['front' => 'splash', 'back' => 'شلپ‌شلوپ کردن', 'pronunciation' => '/splæʃ /'],
            ['front' => 'tap', 'back' => 'ضربه آرام (با انگشت دست)', 'pronunciation' => '/tæp /'],
            ['front' => 'tap', 'back' => 'به آرامی ضربه زدن (با انگشتان)', 'pronunciation' => '/tæp /'],
            ['front' => 'tick', 'back' => 'تیک‌تاک کردن', 'pronunciation' => '/tɪk /'],
            ['front' => 'tick', 'back' => 'صدای تیک تیک', 'pronunciation' => '/tɪk /'],
            ['front' => 'whistle', 'back' => 'سوت زدن', 'pronunciation' => '/ˈwɪs.l /'],
            ['front' => 'whistle', 'back' => 'سوت', 'pronunciation' => '/ˈwɪs.l /'],
            ['front' => 'giggle', 'back' => 'هرهر خندیدن', 'pronunciation' => '/ˈgɪgəl /'],
            ['front' => 'giggle', 'back' => '(صدای) هرهر خنده', 'pronunciation' => '/ˈgɪgəl /'],
            ['front' => 'groan', 'back' => 'ناله کردن', 'pronunciation' => '/groʊn /'],
            ['front' => 'groan', 'back' => 'ناله', 'pronunciation' => '/groʊn /'],
            ['front' => 'mumble', 'back' => 'زیر لب سخن گفتن', 'pronunciation' => '/ˈmʌmbəl /'],
            ['front' => 'mumble', 'back' => 'من من', 'pronunciation' => '/ˈmʌmbəl /'],
            ['front' => 'scream', 'back' => 'جیغ', 'pronunciation' => '/skriːm /'],
            ['front' => 'scream', 'back' => 'فریاد زدن', 'pronunciation' => '/skriːm /'],
            ['front' => 'sigh', 'back' => 'آه', 'pronunciation' => '/sɑɪ /'],
            ['front' => 'sigh', 'back' => 'آه کشیدن', 'pronunciation' => '/sɑɪ /'],
            ['front' => 'sob', 'back' => 'هق هق کردن', 'pronunciation' => '/sɒb /'],
            ['front' => 'sob', 'back' => 'هق هق', 'pronunciation' => '/sɒb /'],
            ['front' => 'stutter', 'back' => 'لکنت زبان', 'pronunciation' => '/ˈstʌtər /'],
            ['front' => 'stutter', 'back' => 'با لکنت زبان گفتن', 'pronunciation' => '/ˈstʌtər /'],
            ['front' => 'whisper', 'back' => 'در گوشی حرف زدن', 'pronunciation' => '/ˈwɪs.pər /'],
            ['front' => 'whisper', 'back' => 'درگوشی', 'pronunciation' => '/ˈwɪs.pər /'],
            ['front' => 'yell', 'back' => 'داد زدن', 'pronunciation' => '/jel /'],
            ['front' => 'yell', 'back' => 'فریاد', 'pronunciation' => '/jel /'],
            ['front' => 'nickname', 'back' => 'لقب دادن', 'pronunciation' => '/ˈnɪkneɪm /'],
            ['front' => 'day in and day out', 'back' => 'هر روز هر روز پشت سر هم', 'pronunciation' => '/deɪ ɪn ænd deɪ aʊt /'],
            ['front' => 'childcare', 'back' => 'نگهداری از کودک', 'pronunciation' => '/ˈtʃaɪldker /'],
            ['front' => 'apply', 'back' => 'مربوط بودن', 'pronunciation' => '/əˈplɑɪ /'],
            ['front' => 'come by', 'back' => 'سر زدن', 'pronunciation' => '/kʌm baɪ /'],
            ['front' => 'acknowledge', 'back' => 'توجه کردن (به حضور کسی)', 'pronunciation' => '/ækˈnɑlɪʤ /'],
            ['front' => 'small talk', 'back' => 'گفت‌وگوی خودمانی (مؤدبانه)', 'pronunciation' => '/smɔl tɔk /'],
            ['front' => 'overly', 'back' => 'بیش از حد', 'pronunciation' => '/ˈoʊvərli /'],
            ['front' => 'commute', 'back' => 'رفت و آمد کردن (مکرر یا روزانه)', 'pronunciation' => '/kəmˈjut /'],
            ['front' => 'nod', 'back' => 'عمل تکان دادن سر (به منظور خاصی)', 'pronunciation' => '/nɑd /'],
            ['front' => 'depressing', 'back' => 'غم‌انگیز', 'pronunciation' => '/dəˈpres.ɪŋ /'],
            ['front' => 'entertaining', 'back' => 'سرگرم‌کننده', 'pronunciation' => '/ˌen.tərˈteɪ.nɪŋ /'],
            ['front' => 'fast-paced', 'back' => 'پر شتاب', 'pronunciation' => '/fæst-peɪst /'],
            ['front' => 'riveting', 'back' => 'خیره‌کننده', 'pronunciation' => '/ˈrɪvɪtɪŋ /'],
            ['front' => 'haunting', 'back' => 'تاثیرگذار و فراموش‌نشدنی', 'pronunciation' => '/ˈhɔːntɪŋ /'],
            ['front' => 'slow-paced', 'back' => 'با روند کند', 'pronunciation' => '/sloʊ-peɪst /'],
            ['front' => 'implausible', 'back' => 'نامحتمل', 'pronunciation' => '/ɪmˈplɔzəbəl /'],
            ['front' => 'intriguing', 'back' => 'مجذوب‌کننده', 'pronunciation' => '/ɪnˈtrigɪŋ /'],
            ['front' => 'moving', 'back' => 'تکان‌دهنده', 'pronunciation' => '/ˈmuːvɪŋ /'],
            ['front' => 'thought-provoking', 'back' => 'تامل‌برانگیز', 'pronunciation' => '/θɔt-prəˈvoʊkɪŋ /'],
            ['front' => 'lowly', 'back' => 'دون‌پایه', 'pronunciation' => '/ˈloʊli /'],
            ['front' => 'profoundly', 'back' => 'عمیقا', 'pronunciation' => '/proʊˈfaʊndli /'],
            ['front' => 'vast', 'back' => 'وسیع', 'pronunciation' => '/væst /'],
            ['front' => 'neatly', 'back' => 'مرتب', 'pronunciation' => '/ˈniːtli /'],
            ['front' => 'staccato', 'back' => 'منقطع (موسیقی)', 'pronunciation' => '/stəˈkɑˌtoʊ /'],
            ['front' => 'quirky', 'back' => 'عجیب و غریب', 'pronunciation' => '/ˈkwɜːrki /'],
            ['front' => 'arguably', 'back' => 'احتمالا', 'pronunciation' => '/ˈɑːrɡjuəbli /'],
            ['front' => 'awkward', 'back' => 'معذب', 'pronunciation' => '/ˈɑkwərd /'],
            ['front' => 'bland', 'back' => 'معمولی و کسل‌کننده', 'pronunciation' => '/blænd /'],
            ['front' => 'smooth', 'back' => 'صاف', 'pronunciation' => '/smuːð /'],
            ['front' => 'barely', 'back' => 'تقریبا', 'pronunciation' => '/ˈbɛrli /'],
            ['front' => 'faithful', 'back' => 'وفادار', 'pronunciation' => '/ˈfeɪθ.fəl /'],
            ['front' => 'alert', 'back' => 'هشدار دادن', 'pronunciation' => '/əˈlɜrt /'],
            ['front' => 'kin', 'back' => 'خویشاوند', 'pronunciation' => '/kɪn /'],
            ['front' => 'din', 'back' => 'صدای بلند و گوش خراش', 'pronunciation' => '/dɪn /'],
            ['front' => 'belt out', 'back' => 'هوار زدن', 'pronunciation' => '/bɛlt aʊt /'],
            ['front' => 'nourish', 'back' => 'تغذیه کردن', 'pronunciation' => '/ˈnɜrɪʃ /'],
            ['front' => 'breed', 'back' => 'بچه به دنیا آوردن', 'pronunciation' => '/briːd /'],
            ['front' => 'offspring', 'back' => 'فرزند', 'pronunciation' => '/ˈɔːfsprɪŋ /'],
            ['front' => 'mask', 'back' => 'پوشاندن', 'pronunciation' => '/mæsk /'],
            ['front' => 'get a leg up', 'back' => 'کمک کردن', 'pronunciation' => '/gɛt ə lɛg ʌp /'],
            ['front' => 'chunk', 'back' => 'تکه بزرگ', 'pronunciation' => '/ʧʌŋk /'],
            ['front' => 'spot', 'back' => 'دیدن', 'pronunciation' => '/spɑt /'],
            ['front' => 'slip-up', 'back' => 'اشتباه', 'pronunciation' => '/ˈslɪp ʌp /'],
            ['front' => 'baffle', 'back' => 'گیج کردن', 'pronunciation' => '/ˈbæfəl /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 4');

    }

    protected function seedLesson5($deck)
    {
        $vocabulary = [
            ['front' => 'appear', 'back' => 'به‌نظر رسیدن', 'pronunciation' => '/əˈpɪr /'],
            ['front' => 'according to', 'back' => 'طبق', 'pronunciation' => '/əˈkɔːrd.ɪŋ.tuː /'],
            ['front' => 'apparently', 'back' => 'ظاهرا', 'pronunciation' => '/əˈpɛrəntli /'],
            ['front' => 'seem', 'back' => 'به نظر رسیدن', 'pronunciation' => '/siːm /'],
            ['front' => 'considered to be', 'back' => 'در نظر گرفته شدن', 'pronunciation' => '/kənˈsɪdərd tu bi /'],
            ['front' => 'waste', 'back' => 'هدر دادن', 'pronunciation' => '/weɪst /'],
            ['front' => 'spare time', 'back' => 'اوقات فراغت', 'pronunciation' => '/spɛr taɪm /'],
            ['front' => 'time is up', 'back' => 'وقت تمام است', 'pronunciation' => '/taɪm ɪz ʌp /'],
            ['front' => 'give someone a hard time', 'back' => 'سخت گرفتن به کسی', 'pronunciation' => '/gɪv ˈsʌmˌwʌn ə hɑrd taɪm /'],
            ['front' => 'off', 'back' => 'مرخصی', 'pronunciation' => '/ɔːf /'],
            ['front' => 'spend', 'back' => 'صرف کردن', 'pronunciation' => '/spend /'],
            ['front' => 'kill time', 'back' => 'وقت گذراندن', 'pronunciation' => '/kɪl taɪm /'],
            ['front' => 'take one\'s time', 'back' => 'عجله نکردن', 'pronunciation' => '/teɪk wʌnz taɪm /'],
            ['front' => 'make up for lost time', 'back' => 'زمان از دست رفته را جبران کردن', 'pronunciation' => '/meɪk ʌp fɔr lɔst taɪm /'],
            ['front' => 'take', 'back' => 'طول کشیدن', 'pronunciation' => '/teɪk /'],
            ['front' => 'have the time of your life', 'back' => 'بسیار خوش گذراندن', 'pronunciation' => '/hæv ðə taɪm ʌv jʊər laɪf /'],
            ['front' => 'run out', 'back' => 'تمام شدن', 'pronunciation' => '/rʌn aʊt /'],
            ['front' => 'on time', 'back' => 'به موقع', 'pronunciation' => '/ɑn taɪm /'],
            ['front' => 'before', 'back' => 'قبل از', 'pronunciation' => '/bɪˈfɔːr /'],
            ['front' => 'before one\'s time', 'back' => 'به سن کسی قد دادن', 'pronunciation' => '/bɪˈfɔr wʌnz taɪm /'],
            ['front' => 'by', 'back' => 'تا', 'pronunciation' => '/bɑɪ /'],
            ['front' => 'at', 'back' => 'در (زمان)', 'pronunciation' => '/æt /'],
            ['front' => 'from time to time', 'back' => 'گهگاه', 'pronunciation' => '/frʌm taɪm tu taɪm /'],
            ['front' => 'at times', 'back' => 'برخی اوقات', 'pronunciation' => '/æt taɪmz /'],
            ['front' => 'whole', 'back' => 'تمام', 'pronunciation' => '/hoʊl /'],
            ['front' => 'short on time', 'back' => 'وقت کم آوردن', 'pronunciation' => '/ʃɔrt ɑn taɪm /'],
            ['front' => 'have time on one\'s hands', 'back' => 'وقت آزاد داشتن', 'pronunciation' => '/hæv taɪm ɑn wʌnz hændz /'],
            ['front' => 'for the time being', 'back' => 'فعلاً', 'pronunciation' => '/fɔr ðə taɪm ˈbiɪŋ /'],
            ['front' => 'a long time ago', 'back' => 'مدت‌ها پیش', 'pronunciation' => '/ə lɔŋ taɪm əˈgoʊ /'],
            ['front' => 'a question of time', 'back' => 'باید صبر کرد و دید', 'pronunciation' => '/ə ˈkwɛsʧən ʌv taɪm /'],
            ['front' => 'There isn’t much time left.', 'back' => 'وقت زیادی باقی نمانده است.', 'pronunciation' => '/ðɛr ˈɪzənt mʌʧ taɪm lɛft. /'],
            ['front' => 'budget', 'back' => 'بودجه', 'pronunciation' => '/ˈbʌʤɪt /'],
            ['front' => 'charge', 'back' => 'هزینه', 'pronunciation' => '/tʃɑːrdʒ /'],
            ['front' => 'down payment', 'back' => 'پیش‌پرداخت', 'pronunciation' => '/ˌdaʊn ˈpeɪmənt /'],
            ['front' => 'donation', 'back' => 'اهدا', 'pronunciation' => '/doʊˈneɪ.ʃən /'],
            ['front' => 'fare', 'back' => 'کرایه (تاکسی و...)', 'pronunciation' => '/fer /'],
            ['front' => 'fee', 'back' => 'دستمزد', 'pronunciation' => '/fiː /'],
            ['front' => 'fine', 'back' => 'جریمه', 'pronunciation' => '/fɑɪn /'],
            ['front' => 'grant', 'back' => 'کمک‌هزینه (تحصیلی و...)', 'pronunciation' => '/ɡrænt /'],
            ['front' => 'installment', 'back' => 'قسط', 'pronunciation' => '/ɪnˈstɔlmənt /'],
            ['front' => 'loan', 'back' => 'وام', 'pronunciation' => '/loʊn /'],
            ['front' => 'lump sum', 'back' => 'مبلغ کل', 'pronunciation' => '/ˌlʌmp ˈsʌm /'],
            ['front' => 'overdraft', 'back' => 'اضافه‌برداشت', 'pronunciation' => '/ˈoʊvərdræft /'],
            ['front' => 'savings', 'back' => 'پس‌انداز', 'pronunciation' => '/ˈseɪ.vɪŋz /'],
            ['front' => 'will', 'back' => 'وصیت‌نامه', 'pronunciation' => '/wɪl /'],
            ['front' => 'consumer', 'back' => 'مصرف‌کننده', 'pronunciation' => '/kənˈsuːmər /'],
            ['front' => 'standard of living', 'back' => 'سطح زندگی', 'pronunciation' => '/ˌstændərd əv ˈlɪvɪŋ /'],
            ['front' => 'income', 'back' => 'درآمد', 'pronunciation' => '/ˈɪnkʌm /'],
            ['front' => 'inflation', 'back' => 'تورم', 'pronunciation' => '/ɪnˈfleɪʃn /'],
            ['front' => 'cost of living', 'back' => 'مخارج اصلی زندگی', 'pronunciation' => '/ˌkɔːst əv ˈlɪvɪŋ /'],
            ['front' => 'afford', 'back' => 'بضاعت داشتن', 'pronunciation' => '/əˈfɔːrd /'],
            ['front' => 'interest rate', 'back' => 'نرخ بهره', 'pronunciation' => '/ˈɪntrəst reɪt /'],
            ['front' => 'in debt', 'back' => 'بدهکار', 'pronunciation' => '/ɪn dɛt /'],
            ['front' => 'mortgage', 'back' => 'وام مسکن', 'pronunciation' => '/ˈmɔːrɡɪdʒ /'],
            ['front' => 'share', 'back' => 'سهم', 'pronunciation' => '/ʃer /'],
            ['front' => 'stock', 'back' => 'سهام', 'pronunciation' => '/stɑːk /'],
            ['front' => 'stock market', 'back' => 'بازار بورس', 'pronunciation' => '/ˈstɑːk mɑːrkɪt /'],
            ['front' => 'currency', 'back' => 'پول رایج', 'pronunciation' => '/ˈkɜr.ən.si /'],
            ['front' => 'exchange rate', 'back' => 'نرخ تبدیل ارز', 'pronunciation' => '/ɪksˈtʃeɪndʒˌreɪt /'],
            ['front' => 'rich', 'back' => 'ثروتمند', 'pronunciation' => '/rɪtʃ /'],
            ['front' => 'affluent', 'back' => 'ثروتمند', 'pronunciation' => '/ˈæfluənt /'],
            ['front' => 'loaded', 'back' => 'خرپول', 'pronunciation' => '/ˈloʊdəd /'],
            ['front' => 'wealthy', 'back' => 'ثروتمند', 'pronunciation' => '/ˈwɛlθi /'],
            ['front' => 'well-off', 'back' => 'ثروتمند', 'pronunciation' => '/ˌwel ˈɔːf /'],
            ['front' => 'poor', 'back' => 'فقیر', 'pronunciation' => '/pɔːr /'],
            ['front' => 'broke', 'back' => 'ورشکسته', 'pronunciation' => '/broʊk /'],
            ['front' => 'hard up', 'back' => 'نیازمند (به پول)', 'pronunciation' => '/hɑrd ʌp /'],
            ['front' => 'penniless', 'back' => 'بی‌پول', 'pronunciation' => '/ˈpeniləs /'],
            ['front' => 'have more money than sense', 'back' => 'ولخرج بودن', 'pronunciation' => '/hæv mɔr ˈmʌni ðæn sɛns /'],
            ['front' => 'tight-fisted', 'back' => 'خسیس', 'pronunciation' => '/ˌtaɪt ˈfɪstɪd /'],
            ['front' => 'in the red', 'back' => 'بدهکار بودن', 'pronunciation' => '/ɪn ðə rɛd /'],
            ['front' => 'in the black', 'back' => 'سودآور بودن', 'pronunciation' => '/ɪn ðə blæk /'],
            ['front' => 'cost a fortune', 'back' => 'خدا تومن قیمت داشتن', 'pronunciation' => '/kɑst ə ˈfɔrʧən /'],
            ['front' => 'good deal', 'back' => 'به قیمت مناسب خریدن', 'pronunciation' => '/gʊd diːl /'],
            ['front' => 'spend money like water', 'back' => 'مثل ریگ پول خرج کردن', 'pronunciation' => '/spɛnd ˈmʌni laɪk ˈwɔtər /'],
            ['front' => 'live beyond one\'s means', 'back' => 'بیشتر از وسع خود خرج کردن', 'pronunciation' => '/ˈlɪvɪŋ bɪˈɑnd ðɛr minz /'],
            ['front' => 'make both ends meet', 'back' => 'دخل و خرج را جور در آوردن', 'pronunciation' => '/meɪk boʊθ ɛndz mit /'],
            ['front' => 'disgruntled', 'back' => 'ناراضی', 'pronunciation' => '/dɪsˈɡrʌntld /'],
            ['front' => 'excruciating', 'back' => 'مشقت‌بار', 'pronunciation' => '/ɪkˈskruːʃieɪtɪŋ /'],
            ['front' => 'flip through', 'back' => 'تورق کردن', 'pronunciation' => '/flɪp θru /'],
            ['front' => 'can\'t help but', 'back' => 'چاره‌ای جز ... نداشتن', 'pronunciation' => '/kænt hɛlp bʌt /'],
            ['front' => 'indifferent', 'back' => 'بی‌تفاوت', 'pronunciation' => '/ɪnˈdɪfrənt /'],
            ['front' => 'fracture', 'back' => 'شکستگی', 'pronunciation' => '/ˈfræktʃər /'],
            ['front' => 'paw', 'back' => 'پنجه', 'pronunciation' => '/pɔː /'],
            ['front' => 'limp', 'back' => 'لنگیدن', 'pronunciation' => '/lɪmp /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 5');

    }

    protected function seedLesson6($deck)
    {
        $vocabulary = [
            ['front' => 'self-help', 'back' => 'خودیاری', 'pronunciation' => '/ˈsɛlfˈhɛlp /'],
            ['front' => 'bad-tempered', 'back' => 'تندخو', 'pronunciation' => '/ˌbædˈtemp.ərd /'],
            ['front' => 'well-off', 'back' => 'ثروتمند', 'pronunciation' => '/ˌwel ˈɔːf /'],
            ['front' => 'last-minute', 'back' => 'لحظه‌آخری', 'pronunciation' => '/ˈlæstˌmɪnɪt /'],
            ['front' => 'secondhand', 'back' => 'دست‌دوم', 'pronunciation' => '/ˈsɛkəndˌhænd /'],
            ['front' => 'long-term', 'back' => 'درازمدت', 'pronunciation' => '/ˌlɔːŋˈtɜrm /'],
            ['front' => 'duty-free', 'back' => 'معاف از عوارض گمرکی', 'pronunciation' => '/ˈduti-fri /'],
            ['front' => 'worn out', 'back' => 'کهنه', 'pronunciation' => '/wɔrn aʊt /'],
            ['front' => 'homemade', 'back' => 'خانگی', 'pronunciation' => '/ˈhoʊmˈmeɪd /'],
            ['front' => 'narrow-minded', 'back' => 'کوته‌فکر', 'pronunciation' => '/ˈnɛroʊ-ˈmaɪndəd /'],
            ['front' => 'part-time', 'back' => 'نیمه‌وقت', 'pronunciation' => '/ˈpɑrtˈtaɪm /'],
            ['front' => 'well behaved', 'back' => 'خوش رفتار', 'pronunciation' => '/ˌwel bɪˈheɪvd /'],
            ['front' => 'air-conditioned', 'back' => 'خنک‌شده', 'pronunciation' => '/ɛr kənˈdɪʃənər /'],
            ['front' => 'mass-produced', 'back' => 'به میزان انبوه تولیدشده', 'pronunciation' => '/ˌmæs prəˈduːst /'],
            ['front' => 'nearsighted', 'back' => 'نزدیک‌بین', 'pronunciation' => '/ˈnɪrˌsɑɪt̬·əd /'],
            ['front' => 'high-class', 'back' => 'مرغوب', 'pronunciation' => '/ˌhaɪ ˈklæs /'],
            ['front' => 'kindhearted', 'back' => 'خوش‌قلب', 'pronunciation' => '/ˌkaɪnd ˈhɑːrtɪd /'],
            ['front' => 'high-heeled', 'back' => 'پاشنه بلند', 'pronunciation' => '/haɪ-hild /'],
            ['front' => 'first-class', 'back' => 'عالی', 'pronunciation' => '/fɜrst-klæs /'],
            ['front' => 'blue-eyed', 'back' => 'چشم‌آبی', 'pronunciation' => '/blu-aɪd /'],
            ['front' => 'hands-free', 'back' => 'آزاد دست', 'pronunciation' => '/hændz-fri /'],
            ['front' => 'easy-going', 'back' => 'بی‌خیال', 'pronunciation' => '/ˌIː.ziːˈgoʊ.ɪŋ /'],
            ['front' => 'left-handed', 'back' => 'چپ‌دست', 'pronunciation' => '/lɛft-ˈhændəd /'],
            ['front' => 'absent-minded', 'back' => 'حواس‌پرت', 'pronunciation' => '/ˈæbsənt-ˈmaɪndəd /'],
            ['front' => 'phone', 'back' => 'تماس گرفتن', 'pronunciation' => '/foʊn /'],
            ['front' => 'call', 'back' => 'زنگ زدن', 'pronunciation' => '/kɔːl /'],
            ['front' => 'give someone a call', 'back' => 'با کسی تماس گرفتن', 'pronunciation' => '/gɪv ˈsʌmˌwʌn ə kɔl /'],
            ['front' => 'make a call', 'back' => 'تماس گرفتن (تلفن)', 'pronunciation' => '/meɪk ə kɔl /'],
            ['front' => 'hang up', 'back' => '(تلفن را) قطع کردن', 'pronunciation' => '/hæŋ ʌp /'],
            ['front' => 'turn off', 'back' => 'خاموش کردن', 'pronunciation' => '/tɜrn ɔf /'],
            ['front' => 'cut off', 'back' => 'قطع کردن', 'pronunciation' => '/kʌt ɔf /'],
            ['front' => 'write down', 'back' => 'یادداشت کردن', 'pronunciation' => '/raɪt daʊn /'],
            ['front' => 'run out', 'back' => 'تمام شدن', 'pronunciation' => '/rʌn aʊt /'],
            ['front' => 'speak up', 'back' => 'بلندتر حرف زدن', 'pronunciation' => '/spik ʌp /'],
            ['front' => 'put through', 'back' => 'وصل کردن (به خط تلفنی خاص)', 'pronunciation' => '/pʊt θru /'],
            ['front' => 'get through', 'back' => 'تماس برقرار کردن (تلفنی)', 'pronunciation' => '/gɛt θru /'],
            ['front' => 'charge', 'back' => 'شارژ کردن (وسایل برقی و ...)', 'pronunciation' => '/tʃɑːrdʒ /'],
            ['front' => 'busy', 'back' => 'اشغال (خط تلفن)', 'pronunciation' => '/ˈbɪz.i /'],
            ['front' => 'missed call', 'back' => 'تماس از دست رفته', 'pronunciation' => '/mɪst kɔl /'],
            ['front' => 'directory', 'back' => 'کتاب راهنما', 'pronunciation' => '/diˈrɛktəri /'],
            ['front' => 'voice mail', 'back' => 'پیغام صوتی', 'pronunciation' => '/ˈvɔɪsmeɪl /'],
            ['front' => 'pay phone', 'back' => 'تلفن عمومی', 'pronunciation' => '/ˈpeɪfoʊn /'],
            ['front' => 'substance dependence', 'back' => 'اعتیاد به مواد', 'pronunciation' => '/ˈsʌbstəns dɪˈpɛndəns /'],
            ['front' => 'harmless', 'back' => 'بی‌خطر', 'pronunciation' => '/ˈhɑrm.ləs /'],
            ['front' => 'behavioral addiction', 'back' => 'اعتیاد رفتاری', 'pronunciation' => '/bɪˈheɪvjərəl əˈdɪkʃən /'],
            ['front' => 'destroy', 'back' => 'نابود کردن', 'pronunciation' => '/dəˈstrɔɪ /'],
            ['front' => 'enormous', 'back' => 'عظیم', 'pronunciation' => '/ɪˈnɔrməs /'],
            ['front' => 'high', 'back' => 'نشئگی (بعد از مصرف مواد مخدر)', 'pronunciation' => '/hɑɪ /'],
            ['front' => 'overcome', 'back' => 'غالب آمدن', 'pronunciation' => '/ˈoʊvərˌkʌm /'],
            ['front' => 'get hooked on', 'back' => 'معتاد شدن', 'pronunciation' => '/gɛt hʊkt ɑn /'],
            ['front' => 'seek', 'back' => 'به‌دنبال گشتن', 'pronunciation' => '/siːk /'],
            ['front' => 'treatment', 'back' => 'درمان', 'pronunciation' => '/ˈtriːt.mənt /'],
            ['front' => 'overwhelmingly', 'back' => 'به شدت', 'pronunciation' => '/ˌoʊvərˈwɛlmɪŋli /'],
            ['front' => 'anxious', 'back' => 'مضطرب', 'pronunciation' => '/ˈæŋk.ʃəs /'],
            ['front' => 'obsessed', 'back' => 'دچار وسواس فکری', 'pronunciation' => '/əbˈsɛst /'],
            ['front' => 'addicted', 'back' => 'معتاد', 'pronunciation' => '/əˈdɪk.tɪd /'],
            ['front' => 'helpful', 'back' => 'مفید', 'pronunciation' => '/ˈhelp.fəl /'],
            ['front' => 'dependent', 'back' => 'وابسته', 'pronunciation' => '/dəˈpen.dənt /'],
            ['front' => 'fed up', 'back' => 'خسته', 'pronunciation' => '/ˌfedˈʌp /'],
            ['front' => 'open', 'back' => 'پذیرا', 'pronunciation' => '/ˈoʊ.pən /'],
            ['front' => 'sick', 'back' => 'خسته', 'pronunciation' => '/sɪk /'],
            ['front' => 'famous', 'back' => 'مشهور', 'pronunciation' => '/ˈfeɪ.məs /'],
            ['front' => 'hooked', 'back' => 'معتاد', 'pronunciation' => '/hʊkt /'],
            ['front' => 'proud', 'back' => 'مفتخر', 'pronunciation' => '/prɑʊd /'],
            ['front' => 'fond', 'back' => 'علاقه‌مند', 'pronunciation' => '/fɑnd /'],
            ['front' => 'correlate', 'back' => 'ارتباط داشتن', 'pronunciation' => '/ˈkɔrəˌleɪt /'],
            ['front' => 'severe', 'back' => 'شدید', 'pronunciation' => '/səˈvɪr /'],
            ['front' => 'hefty', 'back' => 'سنگین', 'pronunciation' => '/ˈhefti /'],
            ['front' => 'pry', 'back' => 'باز کردن (به‌زور)', 'pronunciation' => '/praɪ /'],
            ['front' => 'tackle', 'back' => 'مقابله کردن', 'pronunciation' => '/ˈtæk.l /'],
            ['front' => 'perpetuate', 'back' => 'زنده نگه داشتن', 'pronunciation' => '/pərˈpetʃueɪt /'],
            ['front' => 'mildly', 'back' => 'کمی', 'pronunciation' => '/ˈmaɪldli /'],
            ['front' => 'disorder', 'back' => 'اختلال', 'pronunciation' => '/dɪˈsɔrdər /'],
            ['front' => 'soaring', 'back' => 'رو به افزایش', 'pronunciation' => '/ˈsɔrɪŋ /'],
            ['front' => 'full-blown', 'back' => 'با تمام علائم (بیماری)', 'pronunciation' => '/ˌfʊl ˈbloʊn /'],
            ['front' => 'powerless', 'back' => 'ناتوان', 'pronunciation' => '/ˈpaʊərləs /'],
            ['front' => 'override', 'back' => 'لغو کردن', 'pronunciation' => '/ˈoʊvərˌraɪd /'],
            ['front' => 'trigger', 'back' => 'به کار انداختن', 'pronunciation' => '/ˈtrɪɡər /'],
            ['front' => 'faulty', 'back' => 'معیوب', 'pronunciation' => '/ˈfɔːl.ti /'],
            ['front' => 'handicapped', 'back' => 'معلول', 'pronunciation' => '/ˈhændikæpt /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 6');

    }

    protected function seedLesson7($deck)
    {
        $vocabulary = [
            ['front' => 'stand up for', 'back' => 'دفاع کردن', 'pronunciation' => '/stænd ʌp fɔr /'],
            ['front' => 'call for', 'back' => 'تقاضا کردن', 'pronunciation' => '/kɔl fɔr /'],
            ['front' => 'come across', 'back' => 'اتفاقی ملاقات کردن', 'pronunciation' => '/kʌm əˈkrɔs /'],
            ['front' => 'answer', 'back' => 'پاسخ دادن', 'pronunciation' => '/ˈæn.sər /'],
            ['front' => 'keep down', 'back' => 'پایین نگه داشتن', 'pronunciation' => '/kip daʊn /'],
            ['front' => 'look into', 'back' => '(بادقت) بررسی کردن', 'pronunciation' => '/lʊk ˈɪntu /'],
            ['front' => 'stand out', 'back' => 'بهتر بودن', 'pronunciation' => '/stænd aʊt /'],
            ['front' => 'outnumber', 'back' => 'بیشتر بودن (تعداد)', 'pronunciation' => '/aʊtˈnʌmbər /'],
            ['front' => 'overrated', 'back' => 'اغراق شده', 'pronunciation' => '/ˌoʊvərˈreɪtɪd /'],
            ['front' => 'reawaken', 'back' => 'دوباره زنده کردن', 'pronunciation' => '/ˌriːəˈweɪkən /'],
            ['front' => 'misrepresent', 'back' => 'اشتباه بیان کردن', 'pronunciation' => '/ˌmɪsˌreprɪˈzent /'],
            ['front' => 'underestimate', 'back' => 'دست کم گرفتن', 'pronunciation' => '/ˈʌndəˈrɛstəmət /'],
            ['front' => 'prosocially', 'back' => 'به طرز جامعه‌دوستانه', 'pronunciation' => '/proʊˈsoʊʃəli /'],
            ['front' => 'prematurely', 'back' => 'زودهنگام', 'pronunciation' => '/ˌpriːməˈtʃʊrli /'],
            ['front' => 'devalue', 'back' => 'از ارزش پول کم کردن', 'pronunciation' => '/ˌdiːˈvæljuː /'],
            ['front' => 'misjudge', 'back' => 'اشتباه قضاوت کردن', 'pronunciation' => '/ˌmɪsˈdʒʌdʒ /'],
            ['front' => 'rewrite', 'back' => 'بازنویسی کردن', 'pronunciation' => '/riːˈraɪt /'],
            ['front' => 'undervalue', 'back' => 'کم ارزش نمایاندن', 'pronunciation' => '/ˌʌndərˈvæljuː /'],
            ['front' => 'prearrangement', 'back' => '(هر چیز) از پیش تنظیم شده', 'pronunciation' => '/ˌpriəˈreɪnʤmənt /'],
            ['front' => 'illegible', 'back' => 'ناخوانا', 'pronunciation' => '/ɪˈlɛʤəbəl /'],
            ['front' => 'inconvenient', 'back' => 'زحمت‌آور', 'pronunciation' => '/ɪn.kənˈviːn.jənt /'],
            ['front' => 'overcharge', 'back' => 'گران حساب کردن', 'pronunciation' => '/ˈoʊvərˌʧɑrʤ /'],
            ['front' => 'outdoor', 'back' => 'بیرون', 'pronunciation' => '/ˌɑʊtˈdɔːr /'],
            ['front' => 'above', 'back' => 'بالای', 'pronunciation' => '/əˈbʌv /'],
            ['front' => 'over', 'back' => 'بر فراز', 'pronunciation' => '/ˈoʊ.vər /'],
            ['front' => 'below', 'back' => 'زیر', 'pronunciation' => '/bɪˈləʊ /'],
            ['front' => 'under', 'back' => 'زیر', 'pronunciation' => '/ˈʌndər /'],
            ['front' => 'beneath', 'back' => '(در) زیر', 'pronunciation' => '/bɪˈniθ /'],
            ['front' => 'off', 'back' => 'مرخصی', 'pronunciation' => '/ɔːf /'],
            ['front' => 'away', 'back' => 'دور', 'pronunciation' => '/əˈweɪ /'],
            ['front' => 'in', 'back' => 'در', 'pronunciation' => '/ɪn /'],
            ['front' => 'inside', 'back' => 'داخل', 'pronunciation' => '/ɪnˈsɑɪd /'],
            ['front' => 'into', 'back' => '(به) داخل', 'pronunciation' => '/ˈɪn.tuː /'],
            ['front' => 'on', 'back' => 'روی', 'pronunciation' => '/ɔːn /'],
            ['front' => 'on top of', 'back' => 'روی', 'pronunciation' => '/ɑn tɑp ʌv /'],
            ['front' => 'top', 'back' => 'بالا', 'pronunciation' => '/tɑːp /'],
            ['front' => 'onto', 'back' => 'به', 'pronunciation' => '/ˈɔːn.tu /'],
            ['front' => 'upon', 'back' => 'روی', 'pronunciation' => '/əˈpɑn /'],
            ['front' => 'outside', 'back' => 'بیرون', 'pronunciation' => '/ɑʊtˈsɑɪd /'],
            ['front' => 'out', 'back' => 'بیرون', 'pronunciation' => '/ɑʊt /'],
            ['front' => 'out of', 'back' => 'خارج از', 'pronunciation' => '/ˈɑʊt̬.əv /'],
            ['front' => 'across', 'back' => 'آن طرف', 'pronunciation' => '/əˈkrɑs /'],
            ['front' => 'through', 'back' => 'از میان', 'pronunciation' => '/θruː /'],
            ['front' => 'along', 'back' => 'در امتداد', 'pronunciation' => '/əˈlɑŋ /'],
            ['front' => 'past', 'back' => 'فراتر', 'pronunciation' => '/pæst /'],
            ['front' => 'around', 'back' => 'دور', 'pronunciation' => '/əˈrɑʊnd /'],
            ['front' => 'to', 'back' => 'به', 'pronunciation' => '/tu /'],
            ['front' => 'toward', 'back' => 'به سوی', 'pronunciation' => '/tɔːrd /'],
            ['front' => 'at', 'back' => 'در (مکان)', 'pronunciation' => '/æt /'],
            ['front' => 'heated', 'back' => 'پر جوش و خروش', 'pronunciation' => '/ˈhitəd /'],
            ['front' => 'debate', 'back' => 'مناظره', 'pronunciation' => '/dəˈbeɪt /'],
            ['front' => 'gain', 'back' => 'به‌دست آوردن', 'pronunciation' => '/geɪn /'],
            ['front' => 'reputation', 'back' => 'آوازه', 'pronunciation' => '/ˌrɛpjəˈteɪʃən /'],
            ['front' => 'outrageous', 'back' => 'زننده', 'pronunciation' => '/ɑʊtˈreɪ.dʒəs /'],
            ['front' => 'deranged', 'back' => 'آشفته', 'pronunciation' => '/dɪˈreɪndʒd /'],
            ['front' => 'gaze', 'back' => 'خیره شدن', 'pronunciation' => '/geɪz /'],
            ['front' => 'smirk', 'back' => 'پوزخند زدن', 'pronunciation' => '/smɜːrk /'],
            ['front' => 'unfounded', 'back' => 'بی‌اساس', 'pronunciation' => '/ənˈfaʊndɪd /'],
            ['front' => 'flock', 'back' => 'دسته دسته رفتن', 'pronunciation' => '/flɑk /'],
            ['front' => 'spark', 'back' => 'برانگیختن', 'pronunciation' => '/spɑːrk /'],
            ['front' => 'gear', 'back' => 'تنظیم کردن', 'pronunciation' => '/gɪr /'],
            ['front' => 'draw the line', 'back' => 'محدوده تعیین کردن', 'pronunciation' => '/drɔ ðə laɪn /'],
            ['front' => 'heavy-handed', 'back' => 'ستمگرانه', 'pronunciation' => '/ˈhɛvi-ˈhændəd /'],
            ['front' => 'pave the way', 'back' => 'راه را هموار کردن', 'pronunciation' => '/peɪv ðə weɪ /'],
            ['front' => 'steer clear', 'back' => 'دوری کردن', 'pronunciation' => '/stɪr klɪr /'],
            ['front' => 'vent', 'back' => 'خشم یا دق دلی سر کسی خالی کردن', 'pronunciation' => '/vɛnt /'],
        ];
        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 7');

    }

    protected function seedLesson8($deck)
    {
        $vocabulary = [
            ['front' => 'worry', 'back' => 'نگران شدن', 'pronunciation' => '/ˈwɜːri /'],
            ['front' => 'virus', 'back' => 'ویروس', 'pronunciation' => '/ˈvaɪrəs /'],
            ['front' => 'density', 'back' => 'چگالی (فیزیک)', 'pronunciation' => '/ˈdɛnsɪti /'],
            ['front' => 'syndrome', 'back' => 'نشانگان', 'pronunciation' => '/ˈsɪndroʊm /'],
            ['front' => 'as stubborn as a mule', 'back' => 'کله شق', 'pronunciation' => '/æz ˈstʌbərn æz ə mjul /'],
            ['front' => 'as white as a sheet', 'back' => 'بسیار رنگ‌پریده', 'pronunciation' => '/æz waɪt æz ə ʃit /'],
            ['front' => 'sick as a dog', 'back' => 'شدیدا بیمار', 'pronunciation' => '/sɪk æz ə dɔg /'],
            ['front' => 'as deaf as a post', 'back' => 'کاملاً کر', 'pronunciation' => '/æz dɛf æz ə poʊst /'],
            ['front' => 'sleep like a log', 'back' => 'به خواب سنگین فرو رفتن', 'pronunciation' => '/slip laɪk ə lɔg /'],
            ['front' => 'as blind as a bat', 'back' => 'واقعاً کور', 'pronunciation' => '/æz blaɪnd æz ə bæt /'],
            ['front' => 'as good as gold', 'back' => 'مثل طلا اصل', 'pronunciation' => '/æz gʊd æz goʊld /'],
            ['front' => 'work like a horse', 'back' => 'مثل اسب کار کردن', 'pronunciation' => '/wɜrk laɪk ə hɔrs /'],
            ['front' => 'as quick as a flash', 'back' => 'به سرعت برق و باد', 'pronunciation' => '/æz kwɪk æz ə flæʃ /'],
            ['front' => 'work like a dream', 'back' => 'خیلی خوب کار کردن', 'pronunciation' => '/wɜrk laɪk ə drim /'],
            ['front' => 'eat like a horse', 'back' => 'مثل اسب غذا خوردن', 'pronunciation' => '/it laɪk ə hɔrs /'],
            ['front' => 'homeopathy', 'back' => 'همسان درمانی', 'pronunciation' => '/ˌhoʊmiˈɑːpəθi /'],
            ['front' => 'osteopathy', 'back' => 'استخوان درمانی', 'pronunciation' => '/ˌɑːstiˈɑːpəθi /'],
            ['front' => 'aromatherapy', 'back' => 'رایحه‌درمانی', 'pronunciation' => '/əˌroʊməˈθerəpi /'],
            ['front' => 'herbal medicine', 'back' => 'گیاه‌درمانی', 'pronunciation' => '/ˈɜrbəl ˈmɛdəsən /'],
            ['front' => 'chiropractic', 'back' => 'ماساژ درمانی', 'pronunciation' => '/ˌkaɪəroʊˈpræktɪk /'],
            ['front' => 'reflexology', 'back' => 'انعکاس‌ درمانی', 'pronunciation' => '/ˌriːfleksˈɑːlədʒi /'],
            ['front' => 'hypnotherapy', 'back' => 'هیپنوتیزم درمانی', 'pronunciation' => '/ˌhɪpnoʊˈθerəpi /'],
            ['front' => 'acupuncture', 'back' => 'طب سوزنی', 'pronunciation' => '/ˈækjuˌpʌŋkʧər /'],
            ['front' => 'acupuncturist', 'back' => 'متخصص طب سوزنی', 'pronunciation' => '/ˈækjupʌŋktʃərɪst /'],
            ['front' => 'chiropractor', 'back' => 'کایروپراکتور (درمانگر با دست)', 'pronunciation' => '/ˈkaɪrəˌpræktər /'],
            ['front' => 'homeopath', 'back' => 'همسان درمانگر', 'pronunciation' => '/ˈhoʊmiəpæθ /'],
            ['front' => 'homeopathic', 'back' => 'وابسته به همسان درمانی یا هومئوپاتی', 'pronunciation' => '/ˌhoʊmioʊˈpæθək /'],
            ['front' => 'hypnosis', 'back' => 'هیپنوتیزم', 'pronunciation' => '/hɪpˈnoʊsəs /'],
            ['front' => 'hypnotherapist', 'back' => 'متخصص هیپنوتیزم‌درمانی', 'pronunciation' => '/ˌhɪpnoʊˈθerəpst /'],
            ['front' => 'osteopath', 'back' => 'متخصص استخوان', 'pronunciation' => '/ˈɑːstiəpæθ /'],
            ['front' => 'reflexologist', 'back' => 'متخصص انعکاس‌ درمانی', 'pronunciation' => '/ˌriːflekˈsɑːlədʒist /'],
            ['front' => 'alternative medicine', 'back' => 'پزشکی جایگزین', 'pronunciation' => '/ɔːlˌtɜːrnətɪv ˈmedɪsn /'],
            ['front' => 'conventional medicine', 'back' => 'پزشکی متداول', 'pronunciation' => '/kənˈvɛnʃənəl ˈmɛdəsən /'],
            ['front' => 'proven', 'back' => 'اثبات‌شده', 'pronunciation' => '/ˈproʊvən /'],
            ['front' => 'effective', 'back' => 'موثر', 'pronunciation' => '/ɪˈfek.tɪv /'],
            ['front' => 'useful', 'back' => 'سودمند', 'pronunciation' => '/ˈjuːs.fəl /'],
            ['front' => 'bargain', 'back' => 'خرید ارزان', 'pronunciation' => '/ˈbɑr.gən /'],
            ['front' => 'travel', 'back' => 'سفر', 'pronunciation' => '/ˈtrævl /'],
            ['front' => 'journey', 'back' => 'سفر', 'pronunciation' => '/ˈdʒɜr.ni /'],
            ['front' => 'trip', 'back' => 'سفر', 'pronunciation' => '/trɪp /'],
            ['front' => 'getaway', 'back' => 'تعطیلات (کوتاه)', 'pronunciation' => '/ˈgɛtəˌweɪ /'],
            ['front' => 'round-trip', 'back' => 'رفت و برگشت', 'pronunciation' => '/ˌraʊnd ˈtrɪp /'],
            ['front' => 'guided tour', 'back' => 'تور گردشگری با راهنمای تور', 'pronunciation' => '/ˈgaɪdəd tʊr /'],
            ['front' => 'sight', 'back' => 'مکان دیدنی', 'pronunciation' => '/sɑɪt /'],
            ['front' => 'cancel', 'back' => 'لغو کردن', 'pronunciation' => '/ˈkænsəl /'],
            ['front' => 'extend', 'back' => 'تمدید کردن', 'pronunciation' => '/ɪkˈstɛnd /'],
            ['front' => 'go on a tour', 'back' => 'به گردش رفتن', 'pronunciation' => '/goʊ ɑn ə tʊr /'],
            ['front' => 'postpone', 'back' => 'عقب انداختن', 'pronunciation' => '/poʊstˈpoʊn /'],
            ['front' => 'put off', 'back' => 'به تعویق انداختن', 'pronunciation' => '/pʊt ɔf /'],
            ['front' => 'start out', 'back' => 'شروع کردن (کار، زندگی، سفر)', 'pronunciation' => '/stɑrt aʊt /'],
            ['front' => 'take out', 'back' => 'سند، مدرک یا وام گرفتن', 'pronunciation' => '/teɪk aʊt /'],
            ['front' => 'travel insurance', 'back' => 'بیمه مسافرتی', 'pronunciation' => '/ˈtrævəl ɪnˈʃʊrəns /'],
            ['front' => 'visit', 'back' => 'دیدار', 'pronunciation' => '/ˈvɪz.ɪt /'],
            ['front' => 'camping', 'back' => 'اردو', 'pronunciation' => '/ˈkæm.pɪŋ /'],
            ['front' => 'go camping', 'back' => 'به اردوی تفریحی رفتن', 'pronunciation' => '/goʊ ˈkæmpɪŋ /'],
            ['front' => 'backpacking', 'back' => 'کوله پشتی گردی', 'pronunciation' => '/ˈbæk.pæk.ɪŋ /'],
            ['front' => 'sightseeing', 'back' => 'تماشای اماکن دیدنی', 'pronunciation' => '/ˈsɑɪtˌsiː.ɪŋ /'],
            ['front' => 'go sightseeing', 'back' => 'به گردش و بازدید از اماکن دیدنی رفتن', 'pronunciation' => '/goʊ ˈsaɪtˈsiɪŋ /'],
            ['front' => 'outing', 'back' => 'اردو', 'pronunciation' => '/ˈaʊtɪŋ /'],
            ['front' => 'vacation', 'back' => 'مرخصی', 'pronunciation' => '/veɪˈkeɪʃən /'],
            ['front' => 'safari', 'back' => 'سیاحت اکتشافی (به ویژه در افریقا)', 'pronunciation' => '/səˈfɑri /'],
            ['front' => 'cruise', 'back' => 'سفر دریایی (تفریحی)', 'pronunciation' => '/kruz /'],
            ['front' => 'reschedule', 'back' => 'تاریخ (چیزی) را تغییر دادن', 'pronunciation' => '/ˌriːˈskedʒuːl /'],
            ['front' => 'flight', 'back' => 'پرواز', 'pronunciation' => '/flɑɪt /'],
            ['front' => 'breathtaking', 'back' => 'خیره‌کننده', 'pronunciation' => '/ˈbreθˌteɪ.kɪŋ /'],
            ['front' => 'dull', 'back' => 'کسل‌کننده', 'pronunciation' => '/dʌl /'],
            ['front' => 'lively', 'back' => 'پرشوروحرارت', 'pronunciation' => '/ˈlɑɪv.li /'],
            ['front' => 'off the beaten track', 'back' => 'بکر و دورافتاده', 'pronunciation' => '/ɔf ðə ˈbitən træk /'],
            ['front' => 'overcrowded', 'back' => 'پر ازدحام', 'pronunciation' => '/ˌoʊvərˈkraʊdɪd /'],
            ['front' => 'overrated', 'back' => 'اغراق شده', 'pronunciation' => '/ˌoʊvərˈreɪtɪd /'],
            ['front' => 'picturesque', 'back' => 'تماشایی', 'pronunciation' => '/ˌpɪk.tʃəˈresk /'],
            ['front' => 'spoiled', 'back' => 'ویران‌شده', 'pronunciation' => '/spɔɪld /'],
            ['front' => 'touristy', 'back' => 'توریستی', 'pronunciation' => '/ˈtʊrɪsti /'],
            ['front' => 'masquerade', 'back' => 'تظاهر', 'pronunciation' => '/ˌmæskəˈreɪd /'],
            ['front' => 'vast', 'back' => 'وسیع', 'pronunciation' => '/væst /'],
            ['front' => 'array', 'back' => 'صف', 'pronunciation' => '/əˈreɪ /'],
            ['front' => 'underestimate', 'back' => 'دست کم گرفتن', 'pronunciation' => '/ˈʌndəˈrɛstəmət /'],
            ['front' => 'tricky', 'back' => 'دشوار', 'pronunciation' => '/ˈtrɪki /'],
            ['front' => 'baffle', 'back' => 'گیج کردن', 'pronunciation' => '/ˈbæfəl /'],
            ['front' => 'clench', 'back' => 'به هم فشردن', 'pronunciation' => '/klentʃ /'],
            ['front' => 'aesthetic', 'back' => 'زیباشناختی', 'pronunciation' => '/ɛˈsθɛtɪk /'],
            ['front' => 'effortlessly', 'back' => 'بدون زحمت', 'pronunciation' => '/ˈefərtləsli /'],
            ['front' => 'conspicuously', 'back' => 'به طرز قابل توجهی', 'pronunciation' => '/kənˈspɪkjuəsli /'],
            ['front' => 'scramble', 'back' => 'چهاردست‌وپا رفتن', 'pronunciation' => '/ˈskræmbl /'],
            ['front' => 'momentous', 'back' => 'مهم', 'pronunciation' => '/moʊˈmentəs /'],
            ['front' => 'witness', 'back' => 'شاهد (چیزی) بودن', 'pronunciation' => '/ˈwɪtnəs /'],
            ['front' => 'ramp', 'back' => 'جاده ارتباطی', 'pronunciation' => '/ræmp /'],
            ['front' => 'start off', 'back' => 'شروع کردن', 'pronunciation' => '/stɑrt ɔf /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 8');

    }

    protected function seedLesson9($deck)
    {
        $vocabulary = [
            ['front' => 'nest', 'back' => 'آشیانه', 'pronunciation' => '/nɛst /'],
            ['front' => 'hive', 'back' => 'کندو', 'pronunciation' => '/haɪv /'],
            ['front' => 'stable', 'back' => 'اسطبل', 'pronunciation' => '/ˈsteɪbl /'],
            ['front' => 'kennel', 'back' => 'سگدانی', 'pronunciation' => '/ˈkɛnəl /'],
            ['front' => 'tank', 'back' => 'تنگ ماهی', 'pronunciation' => '/tæŋk /'],
            ['front' => 'cage', 'back' => 'قفس', 'pronunciation' => '/keɪʤ /'],
            ['front' => 'squeak', 'back' => 'جیرجیر کردن', 'pronunciation' => '/skwiːk /'],
            ['front' => 'bark', 'back' => 'واق‌واق کردن', 'pronunciation' => '/bɑrk /'],
            ['front' => 'neigh', 'back' => 'شیهه کشیدن (اسب)', 'pronunciation' => '/neɪ /'],
            ['front' => 'meow', 'back' => 'میومیو کردن', 'pronunciation' => '/miˈaʊ /'],
            ['front' => 'roar', 'back' => 'غریدن', 'pronunciation' => '/rɔːr /'],
            ['front' => 'grunt', 'back' => 'خرخر کردن (مانند خوک)', 'pronunciation' => '/grʌnt /'],
            ['front' => 'wing', 'back' => 'بال (پرنده و هواپیما و...)', 'pronunciation' => '/wɪŋ /'],
            ['front' => 'shell', 'back' => 'لاک', 'pronunciation' => '/ʃel /'],
            ['front' => 'paw', 'back' => 'پنجه', 'pronunciation' => '/pɔː /'],
            ['front' => 'beak', 'back' => 'منقار', 'pronunciation' => '/biːk /'],
            ['front' => 'horn', 'back' => 'شاخ', 'pronunciation' => '/hɔːrn /'],
            ['front' => 'tail', 'back' => 'دم (حیوان)', 'pronunciation' => '/teɪl /'],
            ['front' => 'claw', 'back' => 'پنجه', 'pronunciation' => '/klɔː /'],
            ['front' => 'fur', 'back' => 'مو (حیوانات)', 'pronunciation' => '/fɜːr /'],
            ['front' => 'fin', 'back' => 'باله (ماهی)', 'pronunciation' => '/fɪn /'],
            ['front' => 'bite', 'back' => 'گاز گرفتن', 'pronunciation' => '/bɑɪt /'],
            ['front' => 'sting', 'back' => 'نیش زدن', 'pronunciation' => '/stɪŋ /'],
            ['front' => 'scratch', 'back' => 'پنجه کشیدن', 'pronunciation' => '/skrætʃ /'],
            ['front' => 'kick', 'back' => 'لگد زدن', 'pronunciation' => '/kɪk /'],
            ['front' => 'spit', 'back' => 'تف کردن', 'pronunciation' => '/spɪt /'],
            ['front' => 'protect', 'back' => 'محافظت کردن', 'pronunciation' => '/prəˈtekt /'],
            ['front' => 'environment', 'back' => 'محیط‌زیست', 'pronunciation' => '/enˈvɑɪ.rən.mənt /'],
            ['front' => 'charity', 'back' => 'خیریه (موسسه و سازمان)', 'pronunciation' => '/ˈʧɛrɪti /'],
            ['front' => 'animal', 'back' => 'حیوان', 'pronunciation' => '/ˈæn.ə.məl /'],
            ['front' => 'activist', 'back' => 'فعال', 'pronunciation' => '/ˈæktɪvɪst /'],
            ['front' => 'treat', 'back' => 'رفتار کردن', 'pronunciation' => '/trit /'],
            ['front' => 'cruelly', 'back' => 'بی‌رحمانه', 'pronunciation' => '/ˈkruː.əl.i /'],
            ['front' => 'wild', 'back' => 'جنگل', 'pronunciation' => '/wɑɪld /'],
            ['front' => 'endangered species', 'back' => 'گونه‌های در معرض خطر', 'pronunciation' => '/ɛnˈdeɪnʤərd ˈspiʃiz /'],
            ['front' => 'hunt', 'back' => 'شکار کردن', 'pronunciation' => '/hʌnt /'],
            ['front' => 'breed', 'back' => 'بچه به دنیا آوردن', 'pronunciation' => '/briːd /'],
            ['front' => 'captivity', 'back' => 'اسارت', 'pronunciation' => '/kæpˈtɪvəti /'],
            ['front' => 'veal', 'back' => 'گوشت گوساله', 'pronunciation' => '/viːl /'],
            ['front' => 'calf', 'back' => 'گوساله', 'pronunciation' => '/kæf /'],
            ['front' => 'work like a dog', 'back' => 'مثل سگ کار کردن', 'pronunciation' => '/wɜrk laɪk ə dɔg /'],
            ['front' => 'like water off a duck’s back', 'back' => 'بیهوده', 'pronunciation' => '/laɪk ˈwɔtər ɔf ə dʌks bæk /'],
            ['front' => 'like a fish out of water', 'back' => 'معذب', 'pronunciation' => '/laɪk ə fɪʃ aʊt ʌv ˈwɔtər /'],
            ['front' => 'Don\'t count your chickens before they\'re hatched.', 'back' => 'جوجه را آخر پاییز می‌شمارند', 'pronunciation' => '/doʊnt kaʊnt jʊər ˈʧɪkənz bɪˈfɔr ðɛr hæʧt. /'],
            ['front' => 'take the bull by the horns', 'back' => 'با شاخ گاو در افتادن', 'pronunciation' => '/teɪk ðə bʊl baɪ ðə hɔrnz /'],
            ['front' => 'the lion\'s share', 'back' => 'بزرگترين و بهترين بخش چیزی', 'pronunciation' => '/ðə ˈlaɪənz ʃɛr /'],
            ['front' => 'dark horse', 'back' => 'نامزد انتخاباتی کمتر شناخته شده', 'pronunciation' => '/dɑrk hɔrs /'],
            ['front' => 'in the doghouse', 'back' => 'در هچل (افتادن)', 'pronunciation' => '/ɪn ðə ˈdɔgˌhaʊs /'],
            ['front' => 'make a pig of oneself', 'back' => 'زیاده روی کردن در خوردن غذا', 'pronunciation' => '/meɪk ə pɪg ʌv ˌwʌnˈsɛlf /'],
            ['front' => 'last straw', 'back' => 'دفعه آخر', 'pronunciation' => '/læst strɔ /'],
            ['front' => 'smell a rat', 'back' => 'مشکوک بودن', 'pronunciation' => '/smɛl ə ræt /'],
            ['front' => 'Kill two birds with one stone.', 'back' => 'با یک تیر دو نشان زدن', 'pronunciation' => '/kɪl tu bɜrdz wɪð wʌn stoʊn. /'],
            ['front' => 'one\'s bark is worse than one\'s bite', 'back' => 'واق واق کردنش بدتر از گاز گرفتنش است', 'pronunciation' => '/wʌnz bɑrk ɪz wɜrs ðæn wʌnz baɪt /'],
            ['front' => 'with one\'s tail between one\'s legs', 'back' => 'دست از پا درازتر', 'pronunciation' => '/wɪð wʌnz teɪl bɪˈtwin wʌnz lɛgz /'],
            ['front' => 'let sleeping dogs lie', 'back' => 'پا روی دم شیر نگذاشتن', 'pronunciation' => '/lɛt ˈslipɪŋ dɑgz laɪ /'],
            ['front' => 'starter', 'back' => 'پیش‌غذا', 'pronunciation' => '/ˈstɑːrtər /'],
            ['front' => 'salad', 'back' => 'سالاد', 'pronunciation' => '/ˈsæləd /'],
            ['front' => 'grilled', 'back' => 'کبابی', 'pronunciation' => '/grɪld /'],
            ['front' => 'chicken', 'back' => '(گوشت) مرغ', 'pronunciation' => '/ˈtʃɪkən /'],
            ['front' => 'avocado', 'back' => 'آووکادو', 'pronunciation' => '/ˌæv.əˈkɑː.doʊ /'],
            ['front' => 'blue cheese', 'back' => 'پنیر رگه‌آبی', 'pronunciation' => '/blu ʧiz /'],
            ['front' => 'arugula', 'back' => 'شابانک (گیاه خوراکی)', 'pronunciation' => '/əˈruːɡələ /'],
            ['front' => 'raspberry', 'back' => 'تمشک', 'pronunciation' => '/ˈræz.ber.i /'],
            ['front' => 'vinaigrette', 'back' => 'وینگرت', 'pronunciation' => '/ˌvɪn.əˈɡret /'],
            ['front' => 'steamed', 'back' => 'بخارپز', 'pronunciation' => '/stiːmd /'],
            ['front' => 'mussel', 'back' => 'صدف سیاه', 'pronunciation' => '/ˈmʌsəl /'],
            ['front' => 'coconut', 'back' => 'نارگیل', 'pronunciation' => '/ˈkoʊ.kəˌnʌt /'],
            ['front' => 'chili pepper', 'back' => 'فلفل تند', 'pronunciation' => '/ˈʧɪli ˈpɛpər /'],
            ['front' => 'sardine', 'back' => 'ماهی ساردین', 'pronunciation' => '/ˌsɑːrˈdiːn /'],
            ['front' => 'parsley', 'back' => 'جعفری (سبزی)', 'pronunciation' => '/ˈpɑːrsli /'],
            ['front' => 'lemon', 'back' => 'لیمو', 'pronunciation' => '/ˈlemən /'],
            ['front' => 'garlic', 'back' => 'سیر (سبزیجات)', 'pronunciation' => '/ˈgɑr.lɪk /'],
            ['front' => 'main course', 'back' => 'وعده اصلی (غذا)', 'pronunciation' => '/ˌmeɪnˈkɔːrs /'],
            ['front' => 'stir-fried', 'back' => 'سرخ شده', 'pronunciation' => '/stɜr-fraɪd /'],
            ['front' => 'spice', 'back' => 'ادویه', 'pronunciation' => '/spɑɪs /'],
            ['front' => 'pepper', 'back' => 'فلفل', 'pronunciation' => '/ˈpepər /'],
            ['front' => 'onion', 'back' => 'پیاز', 'pronunciation' => '/ˈʌnjən /'],
            ['front' => 'cashew', 'back' => 'بادام هندی', 'pronunciation' => '/ˈkæʃuː /'],
            ['front' => 'rice', 'back' => 'برنج', 'pronunciation' => '/rɑɪs /'],
            ['front' => 'noodle', 'back' => 'رشته‌فرنگی', 'pronunciation' => '/ˈnuːdl /'],
            ['front' => 'sausage', 'back' => 'سوسیس', 'pronunciation' => '/ˈsɔː.sɪdʒ /'],
            ['front' => 'mashed', 'back' => 'له شده', 'pronunciation' => '/mæʃt /'],
            ['front' => 'purée', 'back' => 'پوره', 'pronunciation' => '/pjʊˈreɪ /'],
            ['front' => 'green bean', 'back' => 'لوبیاسبز', 'pronunciation' => '/ˌɡriːn ˈbiːn /'],
            ['front' => 'smoked', 'back' => 'دودی (غذا)', 'pronunciation' => '/smoʊkt /'],
            ['front' => 'poach', 'back' => 'آب‌پز کردن', 'pronunciation' => '/poʊtʃ /'],
            ['front' => 'baked', 'back' => 'پخته شده', 'pronunciation' => '/beɪkt /'],
            ['front' => 'eggplant', 'back' => 'بادمجان', 'pronunciation' => '/ˈegplænt /'],
            ['front' => 'dessert', 'back' => 'دسر', 'pronunciation' => '/dɪˈzɜrt /'],
            ['front' => 'tart', 'back' => 'تارت', 'pronunciation' => '/tɑːrt /'],
            ['front' => 'pie', 'back' => 'پای', 'pronunciation' => '/paɪ /'],
            ['front' => 'heat', 'back' => 'گرم کردن', 'pronunciation' => '/hiːt /'],
            ['front' => 'beat', 'back' => 'هم زدن', 'pronunciation' => '/biːt /'],
            ['front' => 'stir', 'back' => 'هم زدن', 'pronunciation' => '/stɜr /'],
            ['front' => 'mix', 'back' => 'مخلوط کردن', 'pronunciation' => '/mɪks /'],
            ['front' => 'drain', 'back' => 'آبکش کردن', 'pronunciation' => '/dreɪn /'],
            ['front' => 'pour', 'back' => 'ریختن', 'pronunciation' => '/pɔːr /'],
            ['front' => 'simmer', 'back' => 'آرام پز کردن', 'pronunciation' => '/ˈsɪmər /'],
            ['front' => 'saucepan', 'back' => 'قابلمه', 'pronunciation' => '/ˈsɔːspæn /'],
            ['front' => 'frying pan', 'back' => 'ماهیتابه', 'pronunciation' => '/ˈfrɑɪ.ɪŋˌpæn /'],
            ['front' => 'cutting board', 'back' => 'تخته آشپزخانه', 'pronunciation' => '/ˈkʌtɪŋ bɔrd /'],
            ['front' => 'baking pan', 'back' => 'سینی فر', 'pronunciation' => '/ˈbeɪkɪŋ pæn /'],
            ['front' => 'oven', 'back' => 'فر', 'pronunciation' => '/ˈʌv.ən /'],
            ['front' => 'fig', 'back' => 'انجیر', 'pronunciation' => '/fɪɡ /'],
            ['front' => 'melted', 'back' => 'آب شده', 'pronunciation' => '/ˈmɛltəd /'],
            ['front' => 'roast', 'back' => 'بریان', 'pronunciation' => '/roʊst /'],
            ['front' => 'stuffed', 'back' => 'پرشده (از ماده‌ای)', 'pronunciation' => '/stʌft /'],
            ['front' => 'scrambled eggs', 'back' => 'تخم‌مرغ همزده', 'pronunciation' => '/ˈskræmbəld ɛgz /'],
            ['front' => 'scrambled eggs', 'back' => 'تخم‌مرغ همزده', 'pronunciation' => '/ˈskræmbəld ɛgz /'],
            ['front' => 'grate', 'back' => 'رنده کردن', 'pronunciation' => '/ɡreɪt /'],
            ['front' => 'chop', 'back' => 'ریز کردن', 'pronunciation' => '/tʃɑːp /'],
            ['front' => 'peel', 'back' => 'پوست گرفتن', 'pronunciation' => '/pil /'],
            ['front' => 'whip', 'back' => 'هم زدن', 'pronunciation' => '/wɪp /'],
            ['front' => 'sliced bread', 'back' => 'نان برش‌خورده', 'pronunciation' => '/slaɪst brɛd /'],
            ['front' => 'slice', 'back' => 'حلقه حلقه کردن', 'pronunciation' => '/slɑɪs /'],
            ['front' => 'press', 'back' => 'فشار دادن', 'pronunciation' => '/pres /'],
            ['front' => 'ground beef', 'back' => 'گوشت چرخ‌کرده', 'pronunciation' => '/graʊnd bif /'],
            ['front' => 'pork', 'back' => 'گوشت خوک', 'pronunciation' => '/pɔːrk /'],
            ['front' => 'rib', 'back' => 'گوشت دنده', 'pronunciation' => '/rɪb /'],
            ['front' => 'turkey', 'back' => 'بوقلمون (پرنده‌شناسی)', 'pronunciation' => '/ˈtɜːrki /'],
            ['front' => 'breast', 'back' => '(گوشت) سینه', 'pronunciation' => '/brest /'],
            ['front' => 'shellfish', 'back' => 'آبزیان صدف‌دار', 'pronunciation' => '/ˈʃelfɪʃ /'],
            ['front' => 'herb', 'back' => 'سبزی', 'pronunciation' => '/ɜrb /'],
            ['front' => 'kin', 'back' => 'خویشاوند', 'pronunciation' => '/kɪn /'],
            ['front' => 'plight', 'back' => 'مخمصه', 'pronunciation' => '/plaɪt /'],
            ['front' => 'dismay', 'back' => 'نگرانی و حیرت', 'pronunciation' => '/dɪˈsmeɪ /'],
            ['front' => 'crackdown', 'back' => 'سخت‌گیری بیشتر', 'pronunciation' => '/ˈkrækˌdaʊn /'],
            ['front' => 'run-in', 'back' => 'مجادله', 'pronunciation' => '/rʌn-ɪn /'],
            ['front' => 'enforce', 'back' => 'به اجرا درآوردن', 'pronunciation' => '/ɪnˈfɔːrs /'],
            ['front' => 'ban', 'back' => 'ممنوعیت', 'pronunciation' => '/bæn /'],
            ['front' => 'welfare', 'back' => 'رفاه', 'pronunciation' => '/ˈwel.fer /'],
            ['front' => 'stringent', 'back' => 'محکم', 'pronunciation' => '/ˈstrɪnʤənt /'],
            ['front' => 'flesh', 'back' => 'گوشت (میوه)', 'pronunciation' => '/flɛʃ /'],
            ['front' => 'pass on', 'back' => 'رساندن (به‌دست کسی)', 'pronunciation' => '/pæs ɑn /'],
            ['front' => 'get into', 'back' => 'وارد شدن', 'pronunciation' => '/gɛt ˈɪntu /'],
            ['front' => 'pastry', 'back' => 'شیرینی', 'pronunciation' => '/ˈpeɪstri /'],
            ['front' => 'scheme', 'back' => 'دسیسه', 'pronunciation' => '/skiːm /'],
            ['front' => 'intoxicating', 'back' => 'هیجان‌آور', 'pronunciation' => '/ɪnˈtɑksɪˌkeɪtɪŋ /'],
            ['front' => 'risk life and limb', 'back' => 'از جان گذشتن', 'pronunciation' => '/rɪsk laɪf ænd lɪm /'],
            ['front' => 'in vain', 'back' => 'بیهوده', 'pronunciation' => '/ɪn veɪn /'],
            ['front' => 'happy-go-lucky', 'back' => 'بی‌خیال', 'pronunciation' => '/ˈhæpi-goʊ-ˈlʌki /'],
            ['front' => 'undeterred', 'back' => 'دلسردنشده', 'pronunciation' => '/ˌʌndɪˈtɜːrd /'],
            ['front' => 'sibling', 'back' => 'خواهر یا/و برادر', 'pronunciation' => '/ˈsɪblɪŋ /'],
            ['front' => 'smuggler', 'back' => 'قاچاقچی', 'pronunciation' => '/ˈsmʌɡlər /'],
            ['front' => 'lose track', 'back' => 'چیزی از دست کسی در رفتن', 'pronunciation' => '/luz træk /'],
        ];
        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 9');

    }

    protected function seedLesson10($deck)
    {
        $vocabulary = [
            ['front' => 'foreigner', 'back' => 'بیگانه', 'pronunciation' => '/ˈfɔːr.ə.nər /'],
            ['front' => 'outsider', 'back' => 'بیگانه', 'pronunciation' => '/aʊtˈsaɪdər /'],
            ['front' => 'stranger', 'back' => 'غریبه', 'pronunciation' => '/ˈstreɪn.dʒər /'],
            ['front' => 'suit', 'back' => 'کت‌شلوار', 'pronunciation' => '/suːt /'],
            ['front' => 'suite', 'back' => 'اتاق مجلل (در هتل)', 'pronunciation' => '/swiːt /'],
            ['front' => 'beside', 'back' => 'کنار', 'pronunciation' => '/bəˈsɑɪd /'],
            ['front' => 'besides', 'back' => 'گذشته از این', 'pronunciation' => '/bɪˈsaɪdz /'],
            ['front' => 'lay', 'back' => '(روی چیزی) گذاشتن', 'pronunciation' => '/leɪ /'],
            ['front' => 'lie', 'back' => 'دراز کشیدن', 'pronunciation' => '/lɑɪ /'],
            ['front' => 'actually', 'back' => 'درواقع', 'pronunciation' => '/ˈæk.tʃu.ə.li /'],
            ['front' => 'currently', 'back' => 'در حال حاضر', 'pronunciation' => '/ˈkɜr.ənt.li /'],
            ['front' => 'announce', 'back' => 'اعلام کردن', 'pronunciation' => '/əˈnɑʊns /'],
            ['front' => 'advertise', 'back' => 'تبلیغ کردن', 'pronunciation' => '/ˈædvərtaɪz /'],
            ['front' => 'affect', 'back' => 'تحت‌تأثیر قرار دادن', 'pronunciation' => '/əˈfɛkt /'],
            ['front' => 'effect', 'back' => 'تأثیر', 'pronunciation' => '/ɪˈfekt /'],
            ['front' => 'ashamed', 'back' => 'خجالت‌زده', 'pronunciation' => '/əˈʃeɪmd /'],
            ['front' => 'embarrassed', 'back' => 'خجالت‌زده', 'pronunciation' => '/ɪmˈbær.əst /'],
            ['front' => 'deny', 'back' => 'تکذیب کردن', 'pronunciation' => '/dɪˈnɑɪ /'],
            ['front' => 'refuse', 'back' => 'رد کردن', 'pronunciation' => '/rɪˈfjuːz /'],
            ['front' => 'compromise', 'back' => 'مصالحه', 'pronunciation' => '/ˈkɑm.prəˌmɑɪz /'],
            ['front' => 'commitment', 'back' => 'تعهد', 'pronunciation' => '/kəˈmɪt.mənt /'],
            ['front' => 'economic', 'back' => 'اقتصادی', 'pronunciation' => '/ˌiː.kəˈnɑm.ɪk /'],
            ['front' => 'economical', 'back' => 'مقرون‌به‌صرفه', 'pronunciation' => '/ˌɛkəˈnɑmɪkəl /'],
            ['front' => 'strength', 'back' => 'قدرت', 'pronunciation' => '/streŋθ /'],
            ['front' => 'strengthen', 'back' => 'تقویت کردن', 'pronunciation' => '/ˈstreŋ.θən /'],
            ['front' => 'length', 'back' => 'طول', 'pronunciation' => '/lɛŋkθ /'],
            ['front' => 'lengthen', 'back' => 'بلند کردن (طول لباس و...)', 'pronunciation' => '/ˈlɛŋθən /'],
            ['front' => 'depth', 'back' => 'عمق', 'pronunciation' => '/depθ /'],
            ['front' => 'deepen', 'back' => 'عمیق کردن', 'pronunciation' => '/ˈdiːpən /'],
            ['front' => 'shortness', 'back' => 'کوتاهی', 'pronunciation' => '/ˈʃɔrtnəs /'],
            ['front' => 'shorten', 'back' => 'کوتاه کردن', 'pronunciation' => '/ˈʃɔːrtn /'],
            ['front' => 'width', 'back' => 'عرض', 'pronunciation' => '/wɪdθ /'],
            ['front' => 'widen', 'back' => 'عریض کردن', 'pronunciation' => '/ˈwaɪ.dən /'],
            ['front' => 'height', 'back' => 'ارتفاع', 'pronunciation' => '/haɪt /'],
            ['front' => 'heighten', 'back' => 'بالا بردن', 'pronunciation' => '/ˈhaɪtən /'],
            ['front' => 'weakness', 'back' => 'ضعف', 'pronunciation' => '/ˈwiːk.nəs /'],
            ['front' => 'weaken', 'back' => 'ضعیف کردن', 'pronunciation' => '/ˈwiːkən /'],
            ['front' => 'thickness', 'back' => 'ضخامت', 'pronunciation' => '/ˈθɪknəs /'],
            ['front' => 'thicken', 'back' => 'سفت شدن', 'pronunciation' => '/ˈθɪkən /'],
            ['front' => 'flatness', 'back' => 'صافی', 'pronunciation' => '/ˈflætnəs /'],
            ['front' => 'flatten', 'back' => 'صاف کردن', 'pronunciation' => '/ˈflætən /'],
            ['front' => 'to come under fire', 'back' => 'موردانتقاد شدید قرار گرفتن', 'pronunciation' => '/tə ˈkʌm ˌʌndɚ fˈaɪɚ /'],
            ['front' => 'skepticism', 'back' => 'شک‌گرایی', 'pronunciation' => '/ˈskeptɪsɪzəm /'],
            ['front' => 'prior', 'back' => 'قبل', 'pronunciation' => '/ˈpraɪər /'],
            ['front' => 'tip of the iceberg', 'back' => 'ذره‌ای از خروار (مشکلات فراوان و پنهانی)', 'pronunciation' => '/tɪp ʌv ði ˈaɪsbərg /'],
            ['front' => 'allure', 'back' => 'جاذبه', 'pronunciation' => '/əˈlʊr /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 5 - Lesson 10');

    }

    private function seedVocabulary($deck, $vocabulary, $lessonName)
    {
        foreach ($vocabulary as $cardData) {
            StaticCard::updateOrCreate(
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                ],
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                    'audio' => $cardData['pronunciation'] ? ['pronunciation' => $cardData['pronunciation']] : null,
                    'interval' => 1,
                    'revised_at' => null,
                    'last_reviewed' => null,
                ]
            );
        }

        $this->command->info('Seeded ' . count($vocabulary) . ' cards for ' . $lessonName);
    }
}
