<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\StaticCard;
use App\Models\StaticDeck;
use Illuminate\Database\Seeder;

class StaticCardFile1Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all Elementary level static decks
        $elementaryDecks = StaticDeck::where('level', 'elementary')->get();

        if ($elementaryDecks->isEmpty()) {
            $this->command->error('No Elementary level static decks found. Please run StaticDeckSeeder first.');

            return;
        }

        // Lesson 1 vocabulary
        $lesson1Deck = $elementaryDecks->where('lesson_number', 1)->first();
        if ($lesson1Deck) {
            $this->seedLesson1($lesson1Deck);
        }

        // Lesson 2 vocabulary
        $lesson2Deck = $elementaryDecks->where('lesson_number', 2)->first();
        if ($lesson2Deck) {
            $this->seedLesson2($lesson2Deck);
        }

        // Lesson 3 vocabulary
        $lesson3Deck = $elementaryDecks->where('lesson_number', 3)->first();
        if ($lesson3Deck) {
            $this->seedLesson3($lesson3Deck);
        }

        // Lesson 4 vocabulary
        $lesson4Deck = $elementaryDecks->where('lesson_number', 4)->first();
        if ($lesson4Deck) {
            $this->seedLesson4($lesson4Deck);
        }

        // Lesson 5 vocabulary
        $lesson5Deck = $elementaryDecks->where('lesson_number', 5)->first();
        if ($lesson5Deck) {
            $this->seedLesson5($lesson5Deck);
        }

        // Lesson 6 vocabulary
        $lesson6Deck = $elementaryDecks->where('lesson_number', 6)->first();
        if ($lesson6Deck) {
            $this->seedLesson6($lesson6Deck);
        }

        // Lesson 7 vocabulary
        $lesson7Deck = $elementaryDecks->where('lesson_number', 7)->first();
        if ($lesson7Deck) {
            $this->seedLesson7($lesson7Deck);
        }

        // Lesson 8 vocabulary
        $lesson8Deck = $elementaryDecks->where('lesson_number', 8)->first();
        if ($lesson8Deck) {
            $this->seedLesson8($lesson8Deck);
        }

        // Lesson 9 vocabulary
        $lesson9Deck = $elementaryDecks->where('lesson_number', 9)->first();
        if ($lesson9Deck) {
            $this->seedLesson9($lesson9Deck);
        }

        // Lesson 10 vocabulary
        $lesson10Deck = $elementaryDecks->where('lesson_number', 10)->first();
        if ($lesson10Deck) {
            $this->seedLesson10($lesson10Deck);
        }

        // Lesson 11 vocabulary
        $lesson11Deck = $elementaryDecks->where('lesson_number', 11)->first();
        if ($lesson11Deck) {
            $this->seedLesson11($lesson11Deck);
        }

        // Lesson 12 vocabulary
        $lesson12Deck = $elementaryDecks->where('lesson_number', 12)->first();
        if ($lesson12Deck) {
            $this->seedLesson12($lesson12Deck);
        }
    }

    private function seedLesson1($deck)
    {
        $vocabulary = [
            ['front' => 'please', 'back' => 'لطفاً', 'pronunciation' => '/pliːz/'],
            ['front' => 'listen', 'back' => 'گوش دادن', 'pronunciation' => '/ˈlɪs.ən/'],
            ['front' => 'ten', 'back' => 'ده', 'pronunciation' => '/ten/'],
            ['front' => 'Thailand', 'back' => 'تایلند', 'pronunciation' => '/ˈtaɪˌlænd/'],
            ['front' => 'Thursday', 'back' => 'پنجشنبه', 'pronunciation' => '/ˈθɜrzdeɪ/'],
            ['front' => 'thirteen', 'back' => 'سیزده', 'pronunciation' => '/θɜrtˈtiːn/'],
            ['front' => 'Mexican', 'back' => 'مکزیکی', 'pronunciation' => '/mɛksɪkən/'],
            ['front' => 'ninety', 'back' => 'نود', 'pronunciation' => '/ˈnɑɪnti/'],
            ['front' => 'European', 'back' => 'اروپایی', 'pronunciation' => '/ˌjʊrəˈpiən/'],
            ['front' => 'double room', 'back' => 'اتاق دونفره', 'pronunciation' => '/ˌdʌbl ˈruːm/'],
            ['front' => 'Canadian', 'back' => 'کانادایی', 'pronunciation' => '/kəˈneɪdiən/'],
            ['front' => 'Australia', 'back' => 'استرالیا', 'pronunciation' => '/ɔˈstreɪljə/'],
            ['front' => 'Friday', 'back' => 'جمعه', 'pronunciation' => '/ˈfrɑɪdeɪ/'],
            ['front' => 'eleven', 'back' => 'یازده', 'pronunciation' => '/ɪˈlevən/'],
            ['front' => 'page', 'back' => 'صفحه', 'pronunciation' => '/peɪdʒ/'],
            ['front' => 'repeat', 'back' => 'تکرار کردن', 'pronunciation' => '/rəˈpiːt/'],
            ['front' => 'Mexico', 'back' => 'مکزیک', 'pronunciation' => '/ˈmɛksəˌkoʊ/'],
            ['front' => 'can', 'back' => 'توانستن', 'pronunciation' => '/kæn/'],
            ['front' => 'fifty-nine', 'back' => 'پنجاه و نه', 'pronunciation' => '/ˈfɪfti-naɪn/'],
            ['front' => 'he', 'back' => '[ضمیر سوم شخص مفرد مذکر]', 'pronunciation' => '/hiː/'],
            ['front' => 'fourteen', 'back' => 'چهارده', 'pronunciation' => '/ˌfɔːrtˈtiːn/'],
            ['front' => 'forty', 'back' => 'چهل', 'pronunciation' => '/ˈfɔːrti/'],
            ['front' => 'Saturday', 'back' => 'شنبه', 'pronunciation' => '/ˈsætərdeɪ/'],
            ['front' => 'Europe', 'back' => 'اروپا', 'pronunciation' => '/ˈjʊrəp/'],
            ['front' => 'twelve', 'back' => 'دوازده', 'pronunciation' => '/twelv/'],
            ['front' => 'stand up', 'back' => 'بلند شدن', 'pronunciation' => '/stænd ʌp/'],
            ['front' => 'fifteen', 'back' => 'پانزده', 'pronunciation' => '/ˌfɪfˈtiːn/'],
            ['front' => 'go', 'back' => 'رفتن', 'pronunciation' => '/goʊ/'],
            ['front' => 'where', 'back' => 'کجا', 'pronunciation' => '/wer/'],
            ['front' => 'fifty', 'back' => 'پنجاه', 'pronunciation' => '/ˈfɪfti/'],
            ['front' => 'sixty', 'back' => 'شصت', 'pronunciation' => '/ˈsɪksti/'],
            ['front' => 'Thai', 'back' => 'تایلندی', 'pronunciation' => '/taɪ/'],
            ['front' => 'sixteen', 'back' => 'شانزده', 'pronunciation' => '/sɪksˈtiːn/'],
            ['front' => 'North America', 'back' => 'آمریکای شمالی', 'pronunciation' => '/nɔrθ əˈmɛrəkə/'],
            ['front' => 'sit down', 'back' => 'نشستن', 'pronunciation' => '/sɪt daʊn/'],
            ['front' => 'for example', 'back' => 'برای مثال', 'pronunciation' => '/fɔːr ɪgˈzæm.pəl/'],
            ['front' => 'Sunday', 'back' => 'یکشنبه', 'pronunciation' => '/ˈsʌndeɪ/'],
            ['front' => 'how', 'back' => 'چطور', 'pronunciation' => '/hɑʊ/'],
            ['front' => 'do', 'back' => 'انجام دادن', 'pronunciation' => '/du/'],
            ['front' => 'ninety-four', 'back' => 'نود و چهار', 'pronunciation' => '/ˈnaɪnti-fɔr/'],
            ['front' => 'South Korea', 'back' => 'کره جنوبی', 'pronunciation' => '/saʊθ kɔˈriə/'],
            ['front' => 'one hundred', 'back' => 'یک صد', 'pronunciation' => '/wʌn ˈhʌndrəd/'],
            ['front' => 'South America', 'back' => 'آمریکای جنوبی', 'pronunciation' => '/saʊθ əˈmɛrəkə/'],
            ['front' => 'seventeen', 'back' => 'هفده', 'pronunciation' => '/ˌsevənˈtiːn/'],
            ['front' => 'seventy', 'back' => 'هفتاد', 'pronunciation' => '/ˈsevənti/'],
            ['front' => 'turn off', 'back' => 'خاموش کردن', 'pronunciation' => '/tɜrn ɔf/'],
            ['front' => 'meaning', 'back' => 'معنی', 'pronunciation' => '/ˈmiː.nɪŋ/'],
            ['front' => 'exercise', 'back' => 'ورزش', 'pronunciation' => '/ˈeksərsɑɪz/'],
            ['front' => 'she', 'back' => '[ضمیر سوم شخص مفرد مونث]', 'pronunciation' => '/ʃiː/'],
            ['front' => 'what', 'back' => 'چی', 'pronunciation' => '/wɒt/'],
            ['front' => 'eighty', 'back' => 'هشتاد', 'pronunciation' => '/ˈeɪti/'],
            ['front' => 'Turkey', 'back' => 'ترکیه', 'pronunciation' => '/ˈtɜːrki/'],
            ['front' => 'African', 'back' => 'آفریقایی', 'pronunciation' => '/ˈæfrəkən/'],
            ['front' => 'eighteen', 'back' => 'هجده', 'pronunciation' => '/ˌeɪˈtiːn/'],
            ['front' => 'cell phone', 'back' => 'تلفن همراه', 'pronunciation' => '/ˈsel foʊn/'],
            ['front' => 'hundred', 'back' => 'صد', 'pronunciation' => '/ˈhʌn.drəd/'],
            ['front' => 'my', 'back' => '[صفت ملکی اول شخص مفرد]', 'pronunciation' => '/maɪ/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 1');
    }

    private function seedLesson2($deck)
    {
        $vocabulary = [
            ['front' => 'coin', 'back' => 'سکه', 'pronunciation' => '/kɔɪn/'],
            ['front' => 'magazine', 'back' => 'مجله', 'pronunciation' => '/ˌmæg.əˈziːn/'],
            ['front' => 'thirsty', 'back' => 'تشنه', 'pronunciation' => '/ˈθɜr.sti/'],
            ['front' => 'thing', 'back' => 'چیز', 'pronunciation' => '/θɪŋ/'],
            ['front' => 'new', 'back' => 'جدید', 'pronunciation' => '/nuː/'],
            ['front' => 'color', 'back' => 'رنگ', 'pronunciation' => '/ˈkʌlər/'],
            ['front' => 'beautiful', 'back' => 'زیبا', 'pronunciation' => '/ˈbjuː.tɪ.fəl/'],
            ['front' => 'window', 'back' => 'پنجره', 'pronunciation' => '/ˈwɪndoʊ/'],
            ['front' => 'credit card', 'back' => 'کارت اعتباری', 'pronunciation' => '/ˈkred.ɪtˌkɑrd/'],
            ['front' => 'old', 'back' => 'پیر', 'pronunciation' => '/oʊld/'],
            ['front' => 'a', 'back' => 'یک', 'pronunciation' => '/eɪ/'],
            ['front' => 'ugly', 'back' => 'زشت', 'pronunciation' => '/ˈʌg.li/'],
            ['front' => 'give', 'back' => 'دادن', 'pronunciation' => '/gɪv/'],
            ['front' => 'poor', 'back' => 'فقیر', 'pronunciation' => '/pɔːr/'],
            ['front' => 'worried', 'back' => 'نگران', 'pronunciation' => '/ˈwɜːrid/'],
            ['front' => 'dictionary', 'back' => 'واژه‌نامه', 'pronunciation' => '/ˈdɪkʃəneri/'],
            ['front' => 'red', 'back' => 'قرمز', 'pronunciation' => '/rɛd/'],
            ['front' => 'common', 'back' => 'متداول', 'pronunciation' => '/ˈkɑmən/'],
            ['front' => 'fat', 'back' => 'چاق', 'pronunciation' => '/fæt/'],
            ['front' => 'binder', 'back' => 'کلاسور', 'pronunciation' => '/ˈbaɪndər/'],
            ['front' => 'rich', 'back' => 'ثروتمند', 'pronunciation' => '/rɪtʃ/'],
            ['front' => 'right', 'back' => 'درست', 'pronunciation' => '/rɑɪt/'],
            ['front' => 'thin', 'back' => 'لاغر', 'pronunciation' => '/θɪn/'],
            ['front' => 'white', 'back' => 'سفید', 'pronunciation' => '/wɑɪt/'],
            ['front' => 'adjective', 'back' => 'صفت', 'pronunciation' => '/ˈædʒ.ɪk.tɪv/'],
            ['front' => 'bored', 'back' => 'کسل', 'pronunciation' => '/bɔrd/'],
            ['front' => 'strong', 'back' => 'نیرومند', 'pronunciation' => '/strɔːŋ/'],
            ['front' => 'stressed', 'back' => 'مضطرب', 'pronunciation' => '/strest/'],
            ['front' => 'an', 'back' => 'یک', 'pronunciation' => '/æn/'],
            ['front' => 'file', 'back' => 'فایل', 'pronunciation' => '/fɑɪl/'],
            ['front' => 'blue', 'back' => 'آبی', 'pronunciation' => '/bluː/'],
            ['front' => 'safe', 'back' => 'امن', 'pronunciation' => '/seɪf/'],
            ['front' => 'wrong', 'back' => 'اشتباه', 'pronunciation' => '/rɑŋ/'],
            ['front' => 'good-looking', 'back' => 'خوش‌قیافه', 'pronunciation' => '/gʊdˈlʊkɪŋ/'],
            ['front' => 'newspaper', 'back' => 'روزنامه', 'pronunciation' => '/ˈnuːzˌpeɪ.pər/'],
            ['front' => 'money', 'back' => 'پول', 'pronunciation' => '/ˈmʌn.i/'],
            ['front' => 'black', 'back' => 'سیاه', 'pronunciation' => '/blæk/'],
            ['front' => 'quiet', 'back' => 'ساکت', 'pronunciation' => '/ˈkwɑɪət/'],
            ['front' => 'bad', 'back' => 'بد', 'pronunciation' => '/bæd/'],
            ['front' => 'attractive', 'back' => 'جذاب', 'pronunciation' => '/əˈtræk.tɪv/'],
            ['front' => 'short', 'back' => 'کوتاه', 'pronunciation' => '/ʃɔːrt/'],
            ['front' => 'pen', 'back' => 'خودکار', 'pronunciation' => '/pen/'],
            ['front' => 'for example', 'back' => 'برای مثال', 'pronunciation' => '/fɔːr ɪgˈzæm.pəl/'],
            ['front' => 'yellow', 'back' => 'زرد', 'pronunciation' => '/ˈjeloʊ/'],
            ['front' => 'very', 'back' => 'خیلی', 'pronunciation' => '/ˈveri/'],
            ['front' => 'pencil', 'back' => 'مداد', 'pronunciation' => '/ˈpensəl/'],
            ['front' => 'big', 'back' => 'بزرگ', 'pronunciation' => '/bɪg/'],
            ['front' => 'come on', 'back' => 'زود باش!', 'pronunciation' => '/kʌm ɑn/'],
            ['front' => 'pretty', 'back' => 'زیبا', 'pronunciation' => '/ˈprɪti/'],
            ['front' => 'slow', 'back' => 'آهسته', 'pronunciation' => '/sloʊ/'],
            ['front' => 'gray', 'back' => 'خاکستری', 'pronunciation' => '/greɪ/'],
            ['front' => 'dangerous', 'back' => 'خطرناک', 'pronunciation' => '/ˈdeɪn.dʒə.rəs/'],
            ['front' => 'meaning', 'back' => 'معنی', 'pronunciation' => '/ˈmiː.nɪŋ/'],
            ['front' => 'photo', 'back' => 'عکس', 'pronunciation' => '/ˈfoʊt̬.oʊ/'],
            ['front' => 'let\'s', 'back' => 'بیا', 'pronunciation' => '/lɛts/'],
            ['front' => 'really', 'back' => 'واقعاً', 'pronunciation' => '/ˈriː.li/'],
            ['front' => 'writer', 'back' => 'نویسنده', 'pronunciation' => '/ˈraɪtər/'],
            ['front' => 'small', 'back' => 'کوچک', 'pronunciation' => '/smɔːl/'],
            ['front' => 'pink', 'back' => 'صورتی', 'pronunciation' => '/pɪŋk/'],
            ['front' => 'dirty', 'back' => 'کثیف', 'pronunciation' => '/ˈdɜrti/'],
            ['front' => 'paper', 'back' => 'کاغذ', 'pronunciation' => '/ˈpeɪ.pər/'],
            ['front' => 'turn', 'back' => 'پیچیدن', 'pronunciation' => '/tɜrn/'],
            ['front' => 'easy', 'back' => 'ساده', 'pronunciation' => '/ˈiː.zi/'],
            ['front' => 'end', 'back' => 'به پایان رسیدن', 'pronunciation' => '/end/'],
            ['front' => 'this', 'back' => '[حرف اشاره مفرد نزدیک]', 'pronunciation' => '/ðɪs/'],
            ['front' => 'orange', 'back' => 'نارنجی', 'pronunciation' => '/ˈɑrɪndʒ/'],
            ['front' => 'weak', 'back' => 'سست', 'pronunciation' => '/wiːk/'],
            ['front' => 'piece', 'back' => 'قطعه', 'pronunciation' => '/piːs/'],
            ['front' => 'that', 'back' => 'آن', 'pronunciation' => '/ðæt/'],
            ['front' => 'same', 'back' => 'یکسان', 'pronunciation' => '/seɪm/'],
            ['front' => 'brown', 'back' => 'قهوه‌ای', 'pronunciation' => '/braʊn/'],
            ['front' => 'these', 'back' => '[ضمیر اشاره جمع نزدیک]', 'pronunciation' => '/ðiːz/'],
            ['front' => 'stamp', 'back' => 'تمبر', 'pronunciation' => '/stæmp/'],
            ['front' => 'careful', 'back' => 'مراقب', 'pronunciation' => '/ˈker.fəl/'],
            ['front' => 'green', 'back' => 'سبز', 'pronunciation' => '/griːn/'],
            ['front' => 'different', 'back' => 'متفاوت', 'pronunciation' => '/ˈdɪf.rənt/'],
            ['front' => 'empty', 'back' => 'خالی', 'pronunciation' => '/ˈem.ti/'],
            ['front' => 'cheap', 'back' => 'ارزان', 'pronunciation' => '/tʃiːp/'],
            ['front' => 'those', 'back' => '[حرف اشاره جمع دور]', 'pronunciation' => '/ðəʊz/'],
            ['front' => 'flag', 'back' => 'پرچم', 'pronunciation' => '/flæg/'],
            ['front' => 'scissors', 'back' => 'قیچی', 'pronunciation' => '/ˈsɪz.ərz/'],
            ['front' => 'slow down', 'back' => '(از) سرعت کم کردن', 'pronunciation' => '/sloʊ daʊn/'],
            ['front' => 'similar', 'back' => 'مشابه', 'pronunciation' => '/ˈsɪmələr/'],
            ['front' => 'expensive', 'back' => 'گران', 'pronunciation' => '/ɪkˈspensɪv/'],
            ['front' => 'clean', 'back' => 'تمیز', 'pronunciation' => '/kliːn/'],
            ['front' => 'sunglasses', 'back' => 'عینک آفتابی', 'pronunciation' => '/ˈsʌnglæsɪz/'],
            ['front' => 'cold', 'back' => 'سرد', 'pronunciation' => '/koʊld/'],
            ['front' => 'appearance', 'back' => 'ظاهر', 'pronunciation' => '/əˈpɪrəns/'],
            ['front' => 'ticket', 'back' => 'بلیت', 'pronunciation' => '/ˈtɪk.ət/'],
            ['front' => 'accent', 'back' => 'لهجه', 'pronunciation' => '/ˈæk.sent/'],
            ['front' => 'glasses', 'back' => 'عینک', 'pronunciation' => '/ˈglæsɪz/'],
            ['front' => 'far', 'back' => 'دور', 'pronunciation' => '/fɑːr/'],
            ['front' => 'book', 'back' => 'کتاب', 'pronunciation' => '/bʊk/'],
            ['front' => 'difficult', 'back' => 'مشکل', 'pronunciation' => '/ˈdɪf.ə.kəlt/'],
            ['front' => 'tissue', 'back' => 'دستمال کاغذی', 'pronunciation' => '/ˈtɪʃ.uː/'],
            ['front' => 'vice versa', 'back' => 'برعکس', 'pronunciation' => '/ˌvaɪs ˈvɜːrsə/'],
            ['front' => 'fast', 'back' => 'سریع', 'pronunciation' => '/fæst/'],
            ['front' => 'feeling', 'back' => 'احساس', 'pronunciation' => '/ˈfiː.lɪŋ/'],
            ['front' => 'blond', 'back' => 'طلایی', 'pronunciation' => '/blɑnd/'],
            ['front' => 'wallet', 'back' => 'کیف پول', 'pronunciation' => '/ˈwɑl.ɪt/'],
            ['front' => 'full', 'back' => 'پر', 'pronunciation' => '/fʊl/'],
            ['front' => 'headphones', 'back' => 'هدفون', 'pronunciation' => '/ˈhedfoʊnz/'],
            ['front' => 'watch', 'back' => 'ساعت مچی', 'pronunciation' => '/wɒtʃ/'],
            ['front' => 'cell phone', 'back' => 'تلفن همراه', 'pronunciation' => '/ˈsel foʊn/'],
            ['front' => 'good', 'back' => 'خوب', 'pronunciation' => '/gʊd/'],
            ['front' => 'ID card', 'back' => 'کارت شناسایی', 'pronunciation' => '/ɑɪˈdiːˌkɑːrd/'],
            ['front' => 'high', 'back' => 'بلند', 'pronunciation' => '/hɑɪ/'],
            ['front' => 'dark', 'back' => 'سبزه (پوست)', 'pronunciation' => '/dɑːrk/'],
            ['front' => 'hungry', 'back' => 'گرسنه', 'pronunciation' => '/ˈhʌŋɡri/'],
            ['front' => 'umbrella', 'back' => 'چتر', 'pronunciation' => '/ʌmˈbrelə/'],
            ['front' => 'calendar', 'back' => 'تقویم', 'pronunciation' => '/ˈkæl.ən.dər/'],
            ['front' => 'hot', 'back' => 'داغ', 'pronunciation' => '/hɑːt/'],
            ['front' => 'park', 'back' => 'پارک کردن', 'pronunciation' => '/pɑrk/'],
            ['front' => 'stripe', 'back' => 'خط', 'pronunciation' => '/strɑɪp/'],
            ['front' => 'young', 'back' => 'جوان', 'pronunciation' => '/jʌŋ/'],
            ['front' => 'long', 'back' => 'بلند', 'pronunciation' => '/lɔːŋ/'],
            ['front' => 'angry', 'back' => 'عصبانی', 'pronunciation' => '/ˈæŋ.gri/'],
            ['front' => 'key', 'back' => 'کلید', 'pronunciation' => '/kiː/'],
            ['front' => 'turn on', 'back' => 'روشن کردن', 'pronunciation' => '/tɜrn ɑn/'],
            ['front' => 'low', 'back' => 'کوتاه', 'pronunciation' => '/loʊ/'],
            ['front' => 'printer', 'back' => 'چاپگر', 'pronunciation' => '/ˈprɪntər/'],
            ['front' => 'change', 'back' => 'پول خرد', 'pronunciation' => '/tʃeɪndʒ/'],
            ['front' => 'tired', 'back' => 'خسته', 'pronunciation' => '/tɑɪrd/'],
            ['front' => 'air conditioning', 'back' => 'تهویه هوا', 'pronunciation' => '/ˈer.kənˌdɪʃ.ən.ɪŋ/'],
            ['front' => 'tall', 'back' => 'بلندقد', 'pronunciation' => '/tɔl/'],
            ['front' => 'purse', 'back' => 'کیف (زنانه)', 'pronunciation' => '/pɜrs/'],
            ['front' => 'near', 'back' => 'نزدیک', 'pronunciation' => '/nɪr/'],
            ['front' => 'sad', 'back' => 'غمگین', 'pronunciation' => '/sæd/'],
            ['front' => 'phone', 'back' => 'تلفن', 'pronunciation' => '/foʊn/'],
            ['front' => 'laptop', 'back' => 'لپ‌تاپ', 'pronunciation' => '/ˈlæptɑp/'],
            ['front' => 'star', 'back' => 'ستاره', 'pronunciation' => '/stɑr/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 2');
    }

    private function seedLesson3($deck)
    {
        $vocabulary = [
            ['front' => 'apartment', 'back' => 'آپارتمان', 'pronunciation' => '/əˈpɑrtmənt/'],
            ['front' => 'nurse', 'back' => 'پرستار', 'pronunciation' => '/nɜrs/'],
            ['front' => 'worker', 'back' => 'کارگر', 'pronunciation' => '/ˈwɜr.kər/'],
            ['front' => 'too', 'back' => 'هم', 'pronunciation' => '/tu/'],
            ['front' => 'menu', 'back' => 'منو', 'pronunciation' => '/ˈmen.juː/'],
            ['front' => 'dinner', 'back' => 'شام', 'pronunciation' => '/ˈdɪnər/'],
            ['front' => 'read', 'back' => 'خواندن', 'pronunciation' => '/riːd/'],
            ['front' => 'pilot', 'back' => 'خلبان', 'pronunciation' => '/ˈpɑɪlət/'],
            ['front' => 'drink', 'back' => 'نوشیدنی', 'pronunciation' => '/drɪŋk/'],
            ['front' => 'quarter', 'back' => 'ربع (ساعت)', 'pronunciation' => '/ˈkwɔːrtər/'],
            ['front' => 'office', 'back' => 'اداره', 'pronunciation' => '/ˈɔːfɪs/'],
            ['front' => 'Americano', 'back' => 'امریکانو', 'pronunciation' => '/əmɛriˈkɑːnəʊ/'],
            ['front' => 'say', 'back' => 'گفتن', 'pronunciation' => '/seɪ/'],
            ['front' => 'cake', 'back' => 'کیک', 'pronunciation' => '/keɪk/'],
            ['front' => 'coffee', 'back' => 'قهوه', 'pronunciation' => '/ˈkɑːfi/'],
            ['front' => 'police officer', 'back' => 'افسر پلیس', 'pronunciation' => '/pəˈliːs ɑfəsər/'],
            ['front' => 'flight attendant', 'back' => 'مهماندار هواپیما', 'pronunciation' => '/ˈflaɪt əˌten.dənt/'],
            ['front' => 'children', 'back' => 'کودکان', 'pronunciation' => '/ˈʧɪldrən/'],
            ['front' => 'latte', 'back' => 'کافه لاته', 'pronunciation' => '/ˈlɑˌteɪ/'],
            ['front' => 'speak', 'back' => 'صحبت کردن', 'pronunciation' => '/spiːk/'],
            ['front' => 'uniform', 'back' => 'لباس فرم', 'pronunciation' => '/ˈjuː.nəˌfɔːrm/'],
            ['front' => 'espresso', 'back' => 'قهوه اسپرسو', 'pronunciation' => '/ˌɛˈsprɛsoʊ/'],
            ['front' => 'salesperson', 'back' => 'فروشنده', 'pronunciation' => '/ˈseɪlzˌpɜr.sən/'],
            ['front' => 'interesting', 'back' => 'جالب', 'pronunciation' => '/ˈɪntrəstɪŋ/'],
            ['front' => 'cappuccino', 'back' => 'کاپوچینو', 'pronunciation' => '/ˌkæp.əˈtʃiː.noʊ/'],
            ['front' => 'o\'clock', 'back' => 'ساعت', 'pronunciation' => '/əˈklɑk/'],
            ['front' => 'love', 'back' => 'عاشق بودن', 'pronunciation' => '/lʌv/'],
            ['front' => 'front desk', 'back' => '(میز) پذیرش', 'pronunciation' => '/ˌfrʌnt ˈdesk/'],
            ['front' => 'for', 'back' => 'موافق', 'pronunciation' => '/fɔːr/'],
            ['front' => 'study', 'back' => 'درس خواندن', 'pronunciation' => '/ˈstʌdi/'],
            ['front' => 'economics', 'back' => 'علم اقتصاد', 'pronunciation' => '/ˌiːkəˈnɑːmɪks/'],
            ['front' => 'tea', 'back' => 'چای', 'pronunciation' => '/tiː/'],
            ['front' => 'against', 'back' => 'مخالف', 'pronunciation' => '/əˈgenst/'],
            ['front' => 'administrative', 'back' => 'اجرایی', 'pronunciation' => '/ədˈmɪnɪstreɪtɪv/'],
            ['front' => 'tie', 'back' => 'کراوات', 'pronunciation' => '/taɪ/'],
            ['front' => 'German', 'back' => 'آلمانی', 'pronunciation' => '/ˈʤɜrmən/'],
            ['front' => 'how', 'back' => 'چقدر', 'pronunciation' => '/hɑʊ/'],
            ['front' => 'shine', 'back' => 'تابیدن', 'pronunciation' => '/ʃɑɪn/'],
            ['front' => 'to', 'back' => 'مانده به (ساعت)', 'pronunciation' => '/tu/'],
            ['front' => 'take', 'back' => 'برداشتن', 'pronunciation' => '/teɪk/'],
            ['front' => 'assistant', 'back' => 'دستیار', 'pronunciation' => '/əˈsɪs.tənt/'],
            ['front' => 'cook', 'back' => 'درست کردن (غذا)', 'pronunciation' => '/kʊk/'],
            ['front' => 'skirt', 'back' => 'دامن', 'pronunciation' => '/skɜrt/'],
            ['front' => 'car', 'back' => 'خودرو', 'pronunciation' => '/kɑːr/'],
            ['front' => 'change', 'back' => 'تغییر دادن', 'pronunciation' => '/tʃeɪndʒ/'],
            ['front' => 'when', 'back' => 'چه زمانی', 'pronunciation' => '/wen/'],
            ['front' => 'get dressed', 'back' => 'لباس پوشیدن', 'pronunciation' => '/gɛt drɛst/'],
            ['front' => 'half', 'back' => 'نیم', 'pronunciation' => '/hæf/'],
            ['front' => 'job', 'back' => 'شغل', 'pronunciation' => '/dʒɑːb/'],
            ['front' => 'animal', 'back' => 'حیوان', 'pronunciation' => '/ˈæn.ə.məl/'],
            ['front' => 'how many', 'back' => 'چند', 'pronunciation' => '/haʊ ˈmɛni/'],
            ['front' => 'soccer player', 'back' => 'بازیکن فوتبال', 'pronunciation' => '/ˈsɑkər ˈpleɪər/'],
            ['front' => 'do', 'back' => 'انجام دادن', 'pronunciation' => '/du/'],
            ['front' => 'get', 'back' => 'شدن', 'pronunciation' => '/get/'],
            ['front' => 'pants', 'back' => 'شلوار', 'pronunciation' => '/pænts/'],
            ['front' => 'where', 'back' => 'کجا', 'pronunciation' => '/wer/'],
            ['front' => 'soldier', 'back' => 'سرباز', 'pronunciation' => '/ˈsoʊl.dʒər/'],
            ['front' => 'drink', 'back' => 'نوشیدن', 'pronunciation' => '/drɪŋk/'],
            ['front' => 'movie', 'back' => 'فیلم', 'pronunciation' => '/ˈmuː.vi/'],
            ['front' => 'architect', 'back' => 'معمار', 'pronunciation' => '/ˈɑrkəˌtɛkt/'],
            ['front' => 'what', 'back' => 'چی', 'pronunciation' => '/wɒt/'],
            ['front' => 'TV', 'back' => 'تلویزیون', 'pronunciation' => '/ˈtiˈvi/'],
            ['front' => 'which', 'back' => 'کدام', 'pronunciation' => '/wɪtʃ/'],
            ['front' => 'jacket', 'back' => 'کت', 'pronunciation' => '/ˈdʒækɪt/'],
            ['front' => 'want', 'back' => 'خواستن', 'pronunciation' => '/wɒnt/'],
            ['front' => 'adverb', 'back' => 'قید', 'pronunciation' => '/ˈæd.vɜrb/'],
            ['front' => 'music', 'back' => 'موسیقی', 'pronunciation' => '/ˈmjuː.zɪk/'],
            ['front' => 'why', 'back' => 'چرا', 'pronunciation' => '/waɪ/'],
            ['front' => 'clerk', 'back' => 'منشی', 'pronunciation' => '/klɜrk/'],
            ['front' => 'shirt', 'back' => 'پیراهن', 'pronunciation' => '/ʃɜrt/'],
            ['front' => 'frequency', 'back' => 'تناوب', 'pronunciation' => '/ˈfrikwənsi/'],
            ['front' => 'tennis', 'back' => 'تنیس', 'pronunciation' => '/ˈten.ɪs/'],
            ['front' => 'brownie', 'back' => 'براونی', 'pronunciation' => '/ˈbraʊni/'],
            ['front' => 'watch', 'back' => 'تماشا کردن', 'pronunciation' => '/wɒtʃ/'],
            ['front' => 'who', 'back' => 'چه کسی', 'pronunciation' => '/huː/'],
            ['front' => 'always', 'back' => 'همیشه', 'pronunciation' => '/ˈɔːl.weɪz/'],
            ['front' => 'comfortable', 'back' => 'راحت', 'pronunciation' => '/ˈkʌmf.tə.bəl/'],
            ['front' => 'veterinarian', 'back' => 'دامپزشک', 'pronunciation' => '/ˌvetərɪˈneriən/'],
            ['front' => 'receptionist', 'back' => 'متصدی پذیرش', 'pronunciation' => '/rɪˈsep.ʃə.nəst/'],
            ['front' => 'often', 'back' => 'اغلب', 'pronunciation' => '/ˈɔː.fən/'],
            ['front' => 'wear', 'back' => 'پوشیدن', 'pronunciation' => '/wer/'],
            ['front' => 'croissant', 'back' => 'کروسان', 'pronunciation' => '/krəˈsɑːnt/'],
            ['front' => 'eat', 'back' => 'خوردن', 'pronunciation' => '/iːt/'],
            ['front' => 'homework', 'back' => 'تکلیف منزل', 'pronunciation' => '/ˈhoʊmwɜːrk/'],
            ['front' => 'chef', 'back' => 'آشپز (حرفه‌ای)', 'pronunciation' => '/ʃef/'],
            ['front' => 'usually', 'back' => 'معمولاً', 'pronunciation' => '/ˈjuː.ʒu.ə.li/'],
            ['front' => 'work', 'back' => 'کار کردن', 'pronunciation' => '/wɜːrk/'],
            ['front' => 'teacher', 'back' => 'معلم', 'pronunciation' => '/ˈtiːtʃər/'],
            ['front' => 'online', 'back' => 'آنلاین', 'pronunciation' => '/ˌɑːnˈlaɪn/'],
            ['front' => 'cook', 'back' => 'آشپز', 'pronunciation' => '/kʊk/'],
            ['front' => 'waiter', 'back' => 'پیشخدمت (آقا)', 'pronunciation' => '/ˈweɪtər/'],
            ['front' => 'hairstylist', 'back' => 'آرایشگر', 'pronunciation' => '/ˈherstaɪlɪst/'],
            ['front' => 'housework', 'back' => 'کار خانه (نظافت و آشپزی و...)', 'pronunciation' => '/ˈhɑʊs.wɜrk/'],
            ['front' => 'sometimes', 'back' => 'گاهی', 'pronunciation' => '/ˈsʌm.tɑɪmz/'],
            ['front' => 'go', 'back' => 'رفتن', 'pronunciation' => '/goʊ/'],
            ['front' => 'waitress', 'back' => 'پیشخدمت (خانم)', 'pronunciation' => '/ˈweɪtrəs/'],
            ['front' => 'construction worker', 'back' => 'کارگر ساختمانی', 'pronunciation' => '/kənˈstrʌkʃən ˈwɜrkər/'],
            ['front' => 'have', 'back' => 'داشتن', 'pronunciation' => '/hæv/'],
            ['front' => 'hardly ever', 'back' => 'به‌ندرت', 'pronunciation' => '/ˈhɑrdli ˈɛvər/'],
            ['front' => 'journalist', 'back' => 'روزنامه‌نگار', 'pronunciation' => '/ˈʤɜrnələst/'],
            ['front' => 'like', 'back' => 'دوست داشتن', 'pronunciation' => '/lɑɪk/'],
            ['front' => 'never', 'back' => 'هرگز', 'pronunciation' => '/ˈnev.ər/'],
            ['front' => 'dentist', 'back' => 'دندانپزشک', 'pronunciation' => '/ˈden.t̬ɪst/'],
            ['front' => 'lawyer', 'back' => 'وکیل', 'pronunciation' => '/ˈlɔɪ.ər/'],
            ['front' => 'tell', 'back' => 'گفتن', 'pronunciation' => '/tel/'],
            ['front' => 'guitar', 'back' => 'گیتار', 'pronunciation' => '/ɡɪˈtɑːr/'],
            ['front' => 'listen', 'back' => 'گوش دادن', 'pronunciation' => '/ˈlɪs.ən/'],
            ['front' => 'coffee shop', 'back' => 'کافی‌شاپ', 'pronunciation' => '/ˈkɑːfi ʃɑːp/'],
            ['front' => 'manager', 'back' => 'مدیر', 'pronunciation' => '/ˈmæn.ɪdʒ.ər/'],
            ['front' => 'time', 'back' => 'ساعت', 'pronunciation' => '/tɑɪm/'],
            ['front' => 'doctor', 'back' => 'پزشک', 'pronunciation' => '/ˈdɑk.tər/'],
            ['front' => 'normally', 'back' => 'معمولاً', 'pronunciation' => '/ˈnɔːr.mə.li/'],
            ['front' => 'live', 'back' => 'زندگی کردن', 'pronunciation' => '/lɪv/'],
            ['front' => 'meet', 'back' => 'ملاقات کردن', 'pronunciation' => '/miːt/'],
            ['front' => 'model', 'back' => 'مانکن', 'pronunciation' => '/ˈmɑd.əl/'],
            ['front' => 'water', 'back' => 'آب', 'pronunciation' => '/ˈwɔːtər/'],
            ['front' => 'engineer', 'back' => 'مهندس', 'pronunciation' => '/ˌen.dʒəˈnɪr/'],
            ['front' => 'sun', 'back' => 'خورشید', 'pronunciation' => '/sʌn/'],
            ['front' => 'musician', 'back' => 'نوازنده', 'pronunciation' => '/mjʊˈzɪʃ.ən/'],
            ['front' => 'after', 'back' => 'بعد از', 'pronunciation' => '/ˈæftər/'],
            ['front' => 'play', 'back' => 'بازی کردن', 'pronunciation' => '/pleɪ/'],
            ['front' => 'fast food', 'back' => 'فست فود', 'pronunciation' => '/ˌfæstˈfuːd/'],
            ['front' => 'what', 'back' => 'چه', 'pronunciation' => '/wɒt/'],
            ['front' => 'which', 'back' => 'کدام', 'pronunciation' => '/wɪtʃ/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 3');
    }

    private function seedLesson4($deck)
    {
        $vocabulary = [
            ['front' => 'make dinner', 'back' => 'شام درست کردن', 'pronunciation' => '/meɪk ˈdɪnər/'],
            ['front' => 'have', 'back' => 'خوردن', 'pronunciation' => '/hæv/'],
            ['front' => 'stressed', 'back' => 'مضطرب', 'pronunciation' => '/strest/'],
            ['front' => 'girlfriend', 'back' => 'دوست‌دختر', 'pronunciation' => '/ˈgɜrl.frend/'],
            ['front' => 'grandfather', 'back' => 'پدربزرگ', 'pronunciation' => '/ˈgrændˌfɑðər/'],
            ['front' => 'make', 'back' => 'درست کردن', 'pronunciation' => '/meɪk/'],
            ['front' => 'healthy', 'back' => 'سالم', 'pronunciation' => '/ˈhel.θi/'],
            ['front' => 'mother', 'back' => 'مادر', 'pronunciation' => '/ˈmʌðər/'],
            ['front' => 'boyfriend', 'back' => 'دوست‌پسر', 'pronunciation' => '/ˈbɔɪ.frend/'],
            ['front' => 'adverb', 'back' => 'قید', 'pronunciation' => '/ˈæd.vɜrb/'],
            ['front' => 'take a bath', 'back' => 'حمام کردن', 'pronunciation' => '/teɪk ə bæθ/'],
            ['front' => 'spend', 'back' => 'صرف کردن', 'pronunciation' => '/spend/'],
            ['front' => 'on', 'back' => 'در (زمان)', 'pronunciation' => '/ɔːn/'],
            ['front' => 'nephew', 'back' => 'برادرزاده (مذکر)', 'pronunciation' => '/ˈnɛfju/'],
            ['front' => 'niece', 'back' => 'برادرزاده (مونث)', 'pronunciation' => '/nis/'],
            ['front' => 'housework', 'back' => 'کار خانه (نظافت و آشپزی و...)', 'pronunciation' => '/ˈhɑʊs.wɜrk/'],
            ['front' => 'always', 'back' => 'همیشه', 'pronunciation' => '/ˈɔːl.weɪz/'],
            ['front' => 'often', 'back' => 'اغلب', 'pronunciation' => '/ˈɔː.fən/'],
            ['front' => 'sister', 'back' => 'خواهر', 'pronunciation' => '/ˈsɪstər/'],
            ['front' => 'start', 'back' => 'آغاز کردن', 'pronunciation' => '/stɑrt/'],
            ['front' => 'son', 'back' => '(فرزند) پسر', 'pronunciation' => '/sʌn/'],
            ['front' => 'usually', 'back' => 'معمولاً', 'pronunciation' => '/ˈjuː.ʒu.ə.li/'],
            ['front' => 'finish', 'back' => 'تمام کردن', 'pronunciation' => '/ˈfɪn.ɪʃ/'],
            ['front' => 'sometimes', 'back' => 'گاهی', 'pronunciation' => '/ˈsʌm.tɑɪmz/'],
            ['front' => 'uncle', 'back' => 'عمو/دایی/شوهرخاله/شوهرعمه', 'pronunciation' => '/ˈʌŋ.kəl/'],
            ['front' => 'every month', 'back' => 'هر ماه', 'pronunciation' => '/ˈɛvəri mʌnθ/'],
            ['front' => 'wife', 'back' => 'همسر', 'pronunciation' => '/waɪf/'],
            ['front' => 'hardly ever', 'back' => 'به‌ندرت', 'pronunciation' => '/ˈhɑrdli ˈɛvər/'],
            ['front' => 'class', 'back' => 'کلاس', 'pronunciation' => '/klæs/'],
            ['front' => 'never', 'back' => 'هرگز', 'pronunciation' => '/ˈnev.ər/'],
            ['front' => 'life', 'back' => 'زندگی', 'pronunciation' => '/lɑɪf/'],
            ['front' => 'work', 'back' => 'شغل', 'pronunciation' => '/wɜːrk/'],
            ['front' => 'own', 'back' => 'خود', 'pronunciation' => '/oʊn/'],
            ['front' => 'wake up', 'back' => 'از خواب بیدار شدن', 'pronunciation' => '/weɪk ʌp/'],
            ['front' => 'to', 'back' => 'به', 'pronunciation' => '/tu/'],
            ['front' => 'stressful', 'back' => 'پراسترس', 'pronunciation' => '/ˈstrɛsfəl/'],
            ['front' => 'shopping', 'back' => 'خرید', 'pronunciation' => '/ˈʃɑp.ɪŋ/'],
            ['front' => 'busy', 'back' => 'پرمشغله', 'pronunciation' => '/ˈbɪz.i/'],
            ['front' => 'husband', 'back' => 'شوهر', 'pronunciation' => '/ˈhʌz.bənd/'],
            ['front' => 'morning', 'back' => 'صبح', 'pronunciation' => '/ˈmɔːr.nɪŋ/'],
            ['front' => 'also', 'back' => 'همچنین', 'pronunciation' => '/ˈɔːl.soʊ/'],
            ['front' => 'every year', 'back' => 'هر سال', 'pronunciation' => '/ˈɛvəri jɪr/'],
            ['front' => 'mother-in-law', 'back' => 'مادر شوهر', 'pronunciation' => '/ˈmʌð.ər.ɪn.lɔː/'],
            ['front' => 'get up', 'back' => 'بیدار شدن', 'pronunciation' => '/gɛt ʌp/'],
            ['front' => 'afternoon', 'back' => 'بعدازظهر', 'pronunciation' => '/ˌæf.tərˈnuːn/'],
            ['front' => 'everyone', 'back' => 'همه', 'pronunciation' => '/ˈev.riː.wʌn/'],
            ['front' => 'bed', 'back' => 'تختخواب', 'pronunciation' => '/bed/'],
            ['front' => 'brother-in-law', 'back' => 'برادر زن/شوهر', 'pronunciation' => '/ˈbrʌð.ər.ɪn.lɔː/'],
            ['front' => 'evening', 'back' => 'عصر', 'pronunciation' => '/ˈiːv.nɪŋ/'],
            ['front' => 'enjoy', 'back' => 'لذت بردن', 'pronunciation' => '/enˈdʒɔɪ/'],
            ['front' => 'whose', 'back' => 'مال چه کسی', 'pronunciation' => '/huz/'],
            ['front' => 'day', 'back' => 'روز', 'pronunciation' => '/deɪ/'],
            ['front' => 'exercise', 'back' => 'تمرین کردن', 'pronunciation' => '/ˈeksərsɑɪz/'],
            ['front' => 'couple', 'back' => 'زوج', 'pronunciation' => '/ˈkʌpəl/'],
            ['front' => 'breakfast', 'back' => 'صبحانه', 'pronunciation' => '/ˈbrekfəst/'],
            ['front' => 'stepfather', 'back' => 'ناپدری', 'pronunciation' => '/ˈstepfɑːðər/'],
            ['front' => 'hour', 'back' => 'ساعت (60 دقیقه)', 'pronunciation' => '/ˈaʊər/'],
            ['front' => 'stepsister', 'back' => 'ناخواهری', 'pronunciation' => '/ˈstepsɪstər/'],
            ['front' => 'early', 'back' => 'زود', 'pronunciation' => '/ˈɜr.li/'],
            ['front' => 'get', 'back' => 'رسیدن به (مکان)', 'pronunciation' => '/get/'],
            ['front' => 'ready', 'back' => 'آماده', 'pronunciation' => '/ˈred.i/'],
            ['front' => 'every', 'back' => 'هر', 'pronunciation' => '/ˈev.ri/'],
            ['front' => 'home', 'back' => 'خانه', 'pronunciation' => '/hoʊm/'],
            ['front' => 'everything', 'back' => 'همه‌چیز', 'pronunciation' => '/ˈev.riːˌθɪŋ/'],
            ['front' => 'walk', 'back' => 'راه رفتن', 'pronunciation' => '/wɔːk/'],
            ['front' => 'expression', 'back' => 'اصطلاح', 'pronunciation' => '/ɪkˈspreʃ.ən/'],
            ['front' => 'about', 'back' => 'حدود', 'pronunciation' => '/əˈbɑʊt/'],
            ['front' => 'family', 'back' => 'خانواده', 'pronunciation' => '/ˈfæm.ə.li/'],
            ['front' => 'watch TV', 'back' => 'تلویزیون تماشا کردن', 'pronunciation' => '/wɑʧ tivi/'],
            ['front' => 'frequency', 'back' => 'تناوب', 'pronunciation' => '/ˈfrikwənsi/'],
            ['front' => 'everyday', 'back' => 'روزانه', 'pronunciation' => '/ˈɛvriˈdeɪ/'],
            ['front' => 'year', 'back' => 'سال', 'pronunciation' => '/jɪr/'],
            ['front' => 'go shopping', 'back' => 'به خرید رفتن', 'pronunciation' => '/goʊ ˈʃɑpɪŋ/'],
            ['front' => 'relax', 'back' => 'آرامیدن', 'pronunciation' => '/rɪˈlæks/'],
            ['front' => 'at', 'back' => 'در (مکان)', 'pronunciation' => '/æt/'],
            ['front' => 'couple', 'back' => 'چند (تا)', 'pronunciation' => '/ˈkʌpəl/'],
            ['front' => 'aunt', 'back' => 'خاله/عمه/زن‌عمو/زن‌دایی', 'pronunciation' => '/ænt/'],
            ['front' => 'activity', 'back' => 'فعالیت', 'pronunciation' => '/ækˈtɪvəti/'],
            ['front' => 'every day', 'back' => 'هر روز', 'pronunciation' => '/ˈɛvəri deɪ/'],
            ['front' => 'once', 'back' => 'یک بار', 'pronunciation' => '/wʌns/'],
            ['front' => 'check', 'back' => 'چک کردن', 'pronunciation' => '/tʃek/'],
            ['front' => 'normally', 'back' => 'معمولاً', 'pronunciation' => '/ˈnɔːr.mə.li/'],
            ['front' => 'brother', 'back' => 'برادر', 'pronunciation' => '/ˈbrʌðər/'],
            ['front' => 'take', 'back' => 'گرفتن', 'pronunciation' => '/teɪk/'],
            ['front' => 'twice', 'back' => 'دوبرابر', 'pronunciation' => '/twɑɪs/'],
            ['front' => 'email', 'back' => 'ایمیل', 'pronunciation' => '/ˈiː.meɪl/'],
            ['front' => 'take a shower', 'back' => 'دوش گرفتن', 'pronunciation' => '/teɪk ə ˈʃaʊər/'],
            ['front' => 'cousin', 'back' => 'پسر عمو/ دختر عمو/ پسر دایی/ دختر دایی/ پسر خاله/ دختر خاله/ پسر عمه/ دختر عمه', 'pronunciation' => '/ˈkʌz.ən/'],
            ['front' => 'in', 'back' => 'در', 'pronunciation' => '/ɪn/'],
            ['front' => 'pizza', 'back' => 'پیتزا', 'pronunciation' => '/ˈpiːtsə/'],
            ['front' => 'time', 'back' => 'دفعه', 'pronunciation' => '/tɑɪm/'],
            ['front' => 'daughter', 'back' => '(فرزند) دختر', 'pronunciation' => '/ˈdɔːtər/'],
            ['front' => 'walk', 'back' => 'پیاده‌روی', 'pronunciation' => '/wɔːk/'],
            ['front' => 'minute', 'back' => 'دقیقه', 'pronunciation' => '/ˈmɪn.ɪt/'],
            ['front' => 'father', 'back' => 'پدر', 'pronunciation' => '/ˈfɑðər/'],
            ['front' => 'sleep', 'back' => 'خوابیدن', 'pronunciation' => '/sliːp/'],
            ['front' => 'month', 'back' => 'ماه (30 روز)', 'pronunciation' => '/mʌnθ/'],
            ['front' => 'every week', 'back' => 'هر هفته', 'pronunciation' => '/ˈɛvəri wik/'],
            ['front' => 'ex', 'back' => 'همسر سابق', 'pronunciation' => '/eks/'],
            ['front' => 'grandmother', 'back' => 'مادربزرگ', 'pronunciation' => '/ˈɡrænmʌðər/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 4');
    }

    private function seedLesson5($deck)
    {
        $vocabulary = [
            ['front' => 'look for', 'back' => '(به) دنبال گشتن', 'pronunciation' => '/lʊk fɔr/'],
            ['front' => 'cry', 'back' => 'گریه کردن', 'pronunciation' => '/krɑɪ/'],
            ['front' => 'jacket', 'back' => 'کت', 'pronunciation' => '/ˈdʒækɪt/'],
            ['front' => 'nice', 'back' => 'خوب', 'pronunciation' => '/nɑɪs/'],
            ['front' => 'paint', 'back' => '(نقاشی) کشیدن', 'pronunciation' => '/peɪnt/'],
            ['front' => 'can', 'back' => 'توانستن', 'pronunciation' => '/kæn/'],
            ['front' => 'jeans', 'back' => 'شلوار جین', 'pronunciation' => '/dʒiːnz/'],
            ['front' => 'bark', 'back' => 'واق‌واق کردن', 'pronunciation' => '/bɑrk/'],
            ['front' => 'cool', 'back' => 'خنک', 'pronunciation' => '/kuːl/'],
            ['front' => 'shirt', 'back' => 'پیراهن', 'pronunciation' => '/ʃɜrt/'],
            ['front' => 'baby', 'back' => 'بچه', 'pronunciation' => '/ˈbeɪ.bi/'],
            ['front' => 'copy', 'back' => 'نسخه', 'pronunciation' => '/ˈkɑp.i/'],
            ['front' => 'season', 'back' => 'فصل', 'pronunciation' => '/ˈsiːzən/'],
            ['front' => 'dog', 'back' => 'سگ', 'pronunciation' => '/dɔːɡ/'],
            ['front' => 'remember', 'back' => 'به یاد آوردن', 'pronunciation' => '/rəˈmem.bər/'],
            ['front' => 'spring', 'back' => 'بهار', 'pronunciation' => '/sprɪŋ/'],
            ['front' => 'loudly', 'back' => 'با صدای بلند', 'pronunciation' => '/ˈlaʊdli/'],
            ['front' => 'sun', 'back' => 'خورشید', 'pronunciation' => '/sʌn/'],
            ['front' => 'summer', 'back' => 'تابستان', 'pronunciation' => '/ˈsʌmər/'],
            ['front' => 'a lot', 'back' => 'خیلی', 'pronunciation' => '/ə lɑt/'],
            ['front' => 'next', 'back' => 'چیز بعدی', 'pronunciation' => '/nekst/'],
            ['front' => 'fall', 'back' => 'پاییز', 'pronunciation' => '/fɔːl/'],
            ['front' => 'argue', 'back' => 'بحث کردن', 'pronunciation' => '/ˈɑr.gjuː/'],
            ['front' => 'T-shirt', 'back' => 'تی‌شرت', 'pronunciation' => '/ˈtiːʃɜːt/'],
            ['front' => 'winter', 'back' => 'زمستان', 'pronunciation' => '/ˈwɪntər/'],
            ['front' => 'neighbor', 'back' => 'همسایه', 'pronunciation' => '/ˈneɪbər/'],
            ['front' => 'party', 'back' => 'مهمانی', 'pronunciation' => '/ˈpɑrti/'],
            ['front' => 'skirt', 'back' => 'دامن', 'pronunciation' => '/skɜrt/'],
            ['front' => 'song', 'back' => 'آهنگ', 'pronunciation' => '/sɔːŋ/'],
            ['front' => 'weather', 'back' => 'آب‌وهوا', 'pronunciation' => '/ˈweðər/'],
            ['front' => 'all the time', 'back' => 'همیشه', 'pronunciation' => '/ɔl ðə taɪm/'],
            ['front' => 'album', 'back' => 'آلبوم (عکس، موسیقی و...)', 'pronunciation' => '/ˈæl.bəm/'],
            ['front' => 'shout', 'back' => 'داد زدن', 'pronunciation' => '/ʃɑʊt/'],
            ['front' => 'date', 'back' => 'تاریخ', 'pronunciation' => '/deɪt/'],
            ['front' => 'run', 'back' => 'دویدن', 'pronunciation' => '/rʌn/'],
            ['front' => 'cloudy', 'back' => 'ابری', 'pronunciation' => '/ˈklɑʊdi/'],
            ['front' => 'buy', 'back' => 'خریدن', 'pronunciation' => '/baɪ/'],
            ['front' => 'cold', 'back' => 'سرد', 'pronunciation' => '/koʊld/'],
            ['front' => 'see', 'back' => 'دیدن', 'pronunciation' => '/siː/'],
            ['front' => 'noisy', 'back' => 'پرسروصدا', 'pronunciation' => '/ˈnɔɪzi/'],
            ['front' => 'on', 'back' => 'روشن (لوازم الکتریکی)', 'pronunciation' => '/ɔːn/'],
            ['front' => 'foggy', 'back' => 'مه‌آلود', 'pronunciation' => '/ˈfɔːg.i/'],
            ['front' => 'call', 'back' => 'زنگ زدن', 'pronunciation' => '/kɔːl/'],
            ['front' => 'sing', 'back' => 'آواز خواندن', 'pronunciation' => '/sɪŋ/'],
            ['front' => 'shoe', 'back' => 'کفش', 'pronunciation' => '/ʃu/'],
            ['front' => 'loud', 'back' => 'بلند', 'pronunciation' => '/lɑʊd/'],
            ['front' => 'dance', 'back' => 'رقصیدن', 'pronunciation' => '/dæns/'],
            ['front' => 'noise', 'back' => 'صدا', 'pronunciation' => '/nɔɪz/'],
            ['front' => 'hot', 'back' => 'داغ', 'pronunciation' => '/hɑːt/'],
            ['front' => 'sweater', 'back' => 'ژاکت', 'pronunciation' => '/ˈswetər/'],
            ['front' => 'swim', 'back' => 'شنا کردن', 'pronunciation' => '/swɪm/'],
            ['front' => 'hit', 'back' => '(آهنگ، فیلم و ...) موفق و پرفروش', 'pronunciation' => '/hɪt/'],
            ['front' => 'snowy', 'back' => 'برفی', 'pronunciation' => '/ˈsnoʊi/'],
            ['front' => 'draw', 'back' => 'نقاشی کشیدن', 'pronunciation' => '/drɔː/'],
            ['front' => 'musical instrument', 'back' => 'آلت موسیقی', 'pronunciation' => '/ˌmjuːzɪkl ˈɪnstrəmənt/'],
            ['front' => 'sunny', 'back' => 'آفتابی', 'pronunciation' => '/ˈsʌni/'],
            ['front' => 'single', 'back' => 'تک‌آهنگ', 'pronunciation' => '/ˈsɪŋ.gəl/'],
            ['front' => 'drive', 'back' => 'رانندگی کردن', 'pronunciation' => '/drɑɪv/'],
            ['front' => 'rainy', 'back' => 'بارانی', 'pronunciation' => '/ˈreɪn.i/'],
            ['front' => 'find', 'back' => 'پیدا کردن', 'pronunciation' => '/fɑɪnd/'],
            ['front' => 'windy', 'back' => 'طوفانی', 'pronunciation' => '/ˈwɪndi/'],
            ['front' => 'forget', 'back' => 'فراموش کردن', 'pronunciation' => '/fərˈget/'],
            ['front' => 'use', 'back' => 'استفاده کردن', 'pronunciation' => '/juːz/'],
            ['front' => 'rain', 'back' => 'باران آمدن', 'pronunciation' => '/reɪn/'],
            ['front' => 'next door', 'back' => 'خانه مجاور', 'pronunciation' => '/nɛkst dɔr/'],
            ['front' => 'audience', 'back' => 'حضار', 'pronunciation' => '/ɔːd.iː.əns/'],
            ['front' => 'wait', 'back' => 'صبر کردن', 'pronunciation' => '/weɪt/'],
            ['front' => 'snow', 'back' => 'برف آمدن', 'pronunciation' => '/snoʊ/'],
            ['front' => 'upstairs', 'back' => 'به (سمت) طبقه بالا', 'pronunciation' => '/ˌʌpˈsterz/'],
            ['front' => 'give', 'back' => 'دادن', 'pronunciation' => '/gɪv/'],
            ['front' => 'clothing', 'back' => 'لباس', 'pronunciation' => '/ˈkloʊ.ðɪŋ/'],
            ['front' => 'version', 'back' => 'نسخه', 'pronunciation' => '/ˈvɜr.ʒən/'],
            ['front' => 'hear', 'back' => 'شنیدن', 'pronunciation' => '/hɪr/'],
            ['front' => 'top', 'back' => 'اصلی', 'pronunciation' => '/tɑːp/'],
            ['front' => 'downstairs', 'back' => 'طبقه پایین', 'pronunciation' => '/ˌdɑʊnˈsterz/'],
            ['front' => 'temperature', 'back' => 'دما', 'pronunciation' => '/ˈtemprətʃər/'],
            ['front' => 'concert', 'back' => 'کنسرت', 'pronunciation' => '/ˈkɑnsɜrt/'],
            ['front' => 'help', 'back' => 'کمک کردن', 'pronunciation' => '/help/'],
            ['front' => 'problem', 'back' => 'مشکل', 'pronunciation' => '/ˈprɑb.ləm/'],
            ['front' => 'warm', 'back' => 'گرم', 'pronunciation' => '/wɔrm/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 4');
    }

    private function seedLesson6($deck)
    {
        $vocabulary = [
            ['front' => 'concert hall', 'back' => 'سالن کنسرت', 'pronunciation' => '/ˈkɑnsɜrt hɔl/'],
            ['front' => 'January', 'back' => 'ژانویه', 'pronunciation' => '/ˈdʒænjʊeri/'],
            ['front' => 'orchestra', 'back' => 'ارکستر', 'pronunciation' => '/ˈɔːr.kɪ.strə/'],
            ['front' => 'second', 'back' => 'دومین', 'pronunciation' => '/ˈsekənd/'],
            ['front' => 'conductor', 'back' => 'رهبر ارکستر', 'pronunciation' => '/kənˈdʌktər/'],
            ['front' => 'February', 'back' => 'فوریه', 'pronunciation' => '/ˈfebrueri/'],
            ['front' => 'famous', 'back' => 'مشهور', 'pronunciation' => '/ˈfeɪ.məs/'],
            ['front' => 'third', 'back' => 'سوم', 'pronunciation' => '/θɜrd/'],
            ['front' => 'music', 'back' => 'موسیقی', 'pronunciation' => '/ˈmjuː.zɪk/'],
            ['front' => 'favorite', 'back' => 'مورد علاقه', 'pronunciation' => '/ˈfeɪvərɪt/'],
            ['front' => 'seventeenth', 'back' => 'هفدهم', 'pronunciation' => '/ˌsevənˈtiːnθ/'],
            ['front' => 'practice', 'back' => 'تمرین کردن', 'pronunciation' => '/ˈpræk.təs/'],
            ['front' => 'eighteenth', 'back' => 'هجدهم', 'pronunciation' => '/ˌeɪˈtiːnθ/'],
            ['front' => 'fourth', 'back' => 'چهارم', 'pronunciation' => '/fɔːrθ/'],
            ['front' => 'March', 'back' => 'مارس', 'pronunciation' => '/mɑrtʃ/'],
            ['front' => 'hip hop', 'back' => 'موسیقی هیپ هاپ', 'pronunciation' => '/ˈhɪp hɑːp/'],
            ['front' => 'viola', 'back' => 'ویولا (آلت موسیقی)', 'pronunciation' => '/viˈoʊlə/'],
            ['front' => 'rock', 'back' => 'موسیقی راک', 'pronunciation' => '/rɑk/'],
            ['front' => 'April', 'back' => 'آوریل', 'pronunciation' => '/ˈeɪprəl/'],
            ['front' => 'you', 'back' => '[ضمیر دوم شخص مفعولی مفرد و جمع]', 'pronunciation' => '/juː/'],
            ['front' => 'stay', 'back' => 'ماندن', 'pronunciation' => '/steɪ/'],
            ['front' => 'nineteenth', 'back' => 'نوزدهم', 'pronunciation' => '/ˌnaɪnˈtiːnθ/'],
            ['front' => 'classical', 'back' => 'کلاسیک', 'pronunciation' => '/ˈklæs.ɪ.kəl/'],
            ['front' => 'him', 'back' => '[ضمیر مفعولی سوم شخص مفرد مذکر]', 'pronunciation' => '/hɪm/'],
            ['front' => 'May', 'back' => 'مه', 'pronunciation' => '/meɪ/'],
            ['front' => 'mood', 'back' => 'حالت', 'pronunciation' => '/muːd/'],
            ['front' => 'fifth', 'back' => 'پنجم', 'pronunciation' => '/fɪfθ/'],
            ['front' => 'singer', 'back' => 'خواننده', 'pronunciation' => '/ˈsɪŋər/'],
            ['front' => 'latin', 'back' => 'لاتین (موسیقی)', 'pronunciation' => '/ˈlætən/'],
            ['front' => 'twentieth', 'back' => 'بیستم', 'pronunciation' => '/ˈtwentiəθ/'],
            ['front' => 'her', 'back' => '[ضمیر مفعولی سوم شخص مفرد مونث]', 'pronunciation' => '/hɜːr/'],
            ['front' => 'June', 'back' => 'ژوئن', 'pronunciation' => '/dʒuːn/'],
            ['front' => 'sixth', 'back' => 'ششم', 'pronunciation' => '/sɪksθ/'],
            ['front' => 'asleep', 'back' => 'خوابیده', 'pronunciation' => '/əˈsliːp/'],
            ['front' => 'jazz', 'back' => 'جاز', 'pronunciation' => '/dʒæz/'],
            ['front' => 'it', 'back' => '[ضمیر سوم شخص مفرد اجسام]', 'pronunciation' => '/ɪt/'],
            ['front' => 'band', 'back' => 'گروه (موسیقی و ...)', 'pronunciation' => '/bænd/'],
            ['front' => 'July', 'back' => 'ژوئیه', 'pronunciation' => '/dʒʊˈlɑɪ/'],
            ['front' => 'us', 'back' => '[ضمیر مفعولی اول شخص جمع]', 'pronunciation' => '/ʌs/'],
            ['front' => 'seventh', 'back' => 'هفتم', 'pronunciation' => '/ˈsevənθ/'],
            ['front' => 'twenty-first', 'back' => 'بیست و یکم', 'pronunciation' => '/ˈtwɛnti-fɜrst/'],
            ['front' => 'them', 'back' => '[ضمیر مفعولی سوم شخص جمع]', 'pronunciation' => '/ðem/'],
            ['front' => 'soundtrack', 'back' => 'موسیقی متن', 'pronunciation' => '/ˈsaʊndtræk/'],
            ['front' => 'eighth', 'back' => 'هشتم', 'pronunciation' => '/eɪtθ/'],
            ['front' => 'August', 'back' => 'اوت', 'pronunciation' => '/ˈɑgəst/'],
            ['front' => 'twenty-second', 'back' => 'بیست و دوم', 'pronunciation' => '/ˈtwɛnti-ˈsɛkənd/'],
            ['front' => 'ninth', 'back' => 'نهم', 'pronunciation' => '/nɑɪnθ/'],
            ['front' => 'September', 'back' => 'سپتامبر', 'pronunciation' => '/sepˈtembər/'],
            ['front' => 'twenty-third', 'back' => 'بیست و سوم', 'pronunciation' => '/ˈtwɛnti-θɜrd/'],
            ['front' => 'reggae', 'back' => 'موسیقی رِگِی', 'pronunciation' => '/ˈreɡeɪ/'],
            ['front' => 'leaf', 'back' => 'برگ', 'pronunciation' => '/liːf/'],
            ['front' => 'tenth', 'back' => 'دهم', 'pronunciation' => '/tenθ/'],
            ['front' => 'October', 'back' => 'اکتبر', 'pronunciation' => '/ɑkˈtoʊ.bər/'],
            ['front' => 'twenty-fourth', 'back' => 'بیست و چهارم', 'pronunciation' => '/ˈtwɛnti-fɔrθ/'],
            ['front' => 'blues', 'back' => 'موسیقی بلوز', 'pronunciation' => '/bluːz/'],
            ['front' => 'eleventh', 'back' => 'یازدهم', 'pronunciation' => '/ɪˈlevnθ/'],
            ['front' => 'November', 'back' => 'نوامبر', 'pronunciation' => '/noʊˈvembər/'],
            ['front' => 'fall', 'back' => 'افتادن', 'pronunciation' => '/fɔːl/'],
            ['front' => 'thirtieth', 'back' => 'سی‌ام', 'pronunciation' => '/ˈθɜːrtiəθ/'],
            ['front' => 'twelfth', 'back' => 'دوازدهم', 'pronunciation' => '/twelfθ/'],
            ['front' => 'December', 'back' => 'دسامبر', 'pronunciation' => '/dɪˈsembər/'],
            ['front' => 'put down', 'back' => 'زمین گذاشتن', 'pronunciation' => '/pʊt daʊn/'],
            ['front' => 'heavy metal', 'back' => 'هوی متال (ژانر موسیقی)', 'pronunciation' => '/ˌhevi ˈmetl/'],
            ['front' => 'thirty-first', 'back' => 'سی و یکم', 'pronunciation' => '/ˈθɜrdi-fɜrst/'],
            ['front' => 'pick up', 'back' => 'بلند کردن', 'pronunciation' => '/pɪk ʌp/'],
            ['front' => 'thirteenth', 'back' => 'سیزدهم', 'pronunciation' => '/ˌθɜːrˈtiːnθ/'],
            ['front' => 'holiday', 'back' => 'روز تعطیل', 'pronunciation' => '/ˈhɑːlədeɪ/'],
            ['front' => 'R&B', 'back' => 'آراندبی (ژانر موسیقی)', 'pronunciation' => '/ˌɑːr ən ˈbiː/'],
            ['front' => 'fourteenth', 'back' => 'چهاردهم', 'pronunciation' => '/ˌfɔːrˈtiːnθ/'],
            ['front' => 'first', 'back' => 'اولین', 'pronunciation' => '/fɜːrst/'],
            ['front' => 'time', 'back' => 'موقع', 'pronunciation' => '/tɑɪm/'],
            ['front' => 'fifteenth', 'back' => 'پانزدهم', 'pronunciation' => '/ˌfɪfˈtiːnθ/'],
            ['front' => 'hate', 'back' => 'متنفر بودن', 'pronunciation' => '/heɪt/'],
            ['front' => 'sixteenth', 'back' => 'شانزدهم', 'pronunciation' => '/ˌsɪkˈstiːnθ/'],
            ['front' => 'mind', 'back' => 'اهمیت دادن', 'pronunciation' => '/mɑɪnd/'],
            ['front' => 'second', 'back' => 'دومین', 'pronunciation' => '/ˈsekənd/'],
            ['front' => 'first', 'back' => 'اولین', 'pronunciation' => '/fɜːrst/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 6');
    }

    private function seedLesson7($deck)
    {
        $vocabulary = [
            ['front' => 'art', 'back' => 'هنر', 'pronunciation' => '/ɑːrt/'],
            ['front' => 'come', 'back' => 'آمدن', 'pronunciation' => '/kʌm/'],
            ['front' => 'direction', 'back' => 'جهت', 'pronunciation' => '/dəˈrɛkʃən/'],
            ['front' => 'artist', 'back' => 'هنرمند', 'pronunciation' => '/ˈɑːrtɪst/'],
            ['front' => 'collection', 'back' => 'مجموعه', 'pronunciation' => '/kəˈlekʃn/'],
            ['front' => 'invent', 'back' => 'اختراع کردن', 'pronunciation' => '/ɪnˈvent/'],
            ['front' => 'feel', 'back' => 'احساس کردن', 'pronunciation' => '/fiːl/'],
            ['front' => 'on the corner of', 'back' => '(در) نبش', 'pronunciation' => '/ɑn ðə ˈkɔrnər ʌv/'],
            ['front' => 'inventor', 'back' => 'مخترع', 'pronunciation' => '/ɪnˈvɛntər/'],
            ['front' => 'the day before yesterday', 'back' => 'پریروز', 'pronunciation' => '/ðə deɪ bɪˈfɔːr jɛstərdeɪ/'],
            ['front' => 'get', 'back' => 'خریدن', 'pronunciation' => '/get/'],
            ['front' => 'traffic light', 'back' => 'چراغ راهنمایی', 'pronunciation' => '/ˈtræf.ɪkˌlaɪt/'],
            ['front' => 'painting', 'back' => 'نقاشی (تصویر)', 'pronunciation' => '/ˈpeɪnt.ɪŋ/'],
            ['front' => 'at', 'back' => 'در (مکان)', 'pronunciation' => '/æt/'],
            ['front' => 'photograph', 'back' => 'عکس', 'pronunciation' => '/ˈfoʊt̬.əˌgræf/'],
            ['front' => 'bridge', 'back' => 'پل', 'pronunciation' => '/brɪdʒ/'],
            ['front' => 'across from', 'back' => 'آن طرف', 'pronunciation' => '/əˈkrɔs frʌm/'],
            ['front' => 'leave', 'back' => 'ترک کردن', 'pronunciation' => '/liːv/'],
            ['front' => 'last', 'back' => 'قبل', 'pronunciation' => '/læst/'],
            ['front' => 'turn', 'back' => 'پیچیدن', 'pronunciation' => '/tɜrn/'],
            ['front' => 'yesterday', 'back' => 'دیروز', 'pronunciation' => '/ˈjestərdeɪ/'],
            ['front' => 'lose', 'back' => 'باختن', 'pronunciation' => '/luːz/'],
            ['front' => 'night', 'back' => 'شب', 'pronunciation' => '/nɑɪt/'],
            ['front' => 'left', 'back' => '(به) چپ', 'pronunciation' => '/left/'],
            ['front' => 'ago', 'back' => 'پیش', 'pronunciation' => '/əˈgoʊ/'],
            ['front' => 'right', 'back' => '(سمت) راست', 'pronunciation' => '/rɑɪt/'],
            ['front' => 'have', 'back' => 'خوردن', 'pronunciation' => '/hæv/'],
            ['front' => 'compose', 'back' => 'ساختن (موسیقی)', 'pronunciation' => '/kəmˈpoʊz/'],
            ['front' => 'straight', 'back' => 'مستقیم', 'pronunciation' => '/streɪt/'],
            ['front' => 'composer', 'back' => 'آهنگساز', 'pronunciation' => '/kəmˈpoʊzər/'],
            ['front' => 'ahead', 'back' => 'جلو', 'pronunciation' => '/əˈhed/'],
            ['front' => 'politics', 'back' => 'سیاست', 'pronunciation' => '/ˈpɑl.əˌtɪks/'],
            ['front' => 'act', 'back' => '(نقش) بازی کردن', 'pronunciation' => '/ækt/'],
            ['front' => 'direct', 'back' => 'کارگردانی کردن', 'pronunciation' => '/dəˈrekt/'],
            ['front' => 'politician', 'back' => 'سیاستمدار', 'pronunciation' => '/ˌpɑl.əˈtɪʃ.ən/'],
            ['front' => 'past', 'back' => 'آن طرف', 'pronunciation' => '/pæst/'],
            ['front' => 'science', 'back' => 'علم', 'pronunciation' => '/ˈsɑɪ.əns/'],
            ['front' => 'director', 'back' => 'مدیر', 'pronunciation' => '/dəˈrɛktər/'],
            ['front' => 'scientist', 'back' => 'دانشمند', 'pronunciation' => '/ˈsɑɪ.ən.tɪst/'],
            ['front' => 'actor', 'back' => 'هنرپیشه', 'pronunciation' => '/ˈæktər/'],
            ['front' => 'dance', 'back' => 'رقصیدن', 'pronunciation' => '/dæns/'],
            ['front' => 'sail', 'back' => 'قایقرانی کردن', 'pronunciation' => '/seɪl/'],
            ['front' => 'dancer', 'back' => 'رقاص', 'pronunciation' => '/ˈdæn.sər/'],
            ['front' => 'sailor', 'back' => 'ملوان', 'pronunciation' => '/ˈseɪ.lər/'],
            ['front' => 'go for a walk', 'back' => 'پیاده روی کردن', 'pronunciation' => '/goʊ fɔr ə wɔk/'],
            ['front' => 'novel', 'back' => 'رمان', 'pronunciation' => '/ˈnɑvəl/'],
            ['front' => 'player', 'back' => 'بازیکن', 'pronunciation' => '/ˈpleɪ.ər/'],
            ['front' => 'last', 'back' => 'آخرین', 'pronunciation' => '/læst/'],
            ['front' => 'go out', 'back' => 'بیرون رفتن', 'pronunciation' => '/goʊ ɑʊt/'],
            ['front' => 'novelist', 'back' => 'رمان‌نویس', 'pronunciation' => '/ˈnɑːvəlɪst/'],
            ['front' => 'write', 'back' => 'نوشتن', 'pronunciation' => '/raɪt/'],
            ['front' => 'go back', 'back' => 'برگشتن', 'pronunciation' => '/goʊ bæk/'],
            ['front' => 'sport', 'back' => 'ورزش', 'pronunciation' => '/spɔːrt/'],
            ['front' => 'writer', 'back' => 'نویسنده', 'pronunciation' => '/ˈraɪtər/'],
            ['front' => 'sportsman', 'back' => 'ورزشکار (مرد)', 'pronunciation' => '/ˈspɔːrtsmən/'],
            ['front' => 'national', 'back' => 'ملی', 'pronunciation' => '/ˈnæʃ.ən.əl/'],
            ['front' => 'portrait', 'back' => 'پرتره', 'pronunciation' => '/ˈpɔːrtrət/'],
            ['front' => 'sportswoman', 'back' => 'ورزشکار (زن)', 'pronunciation' => '/ˈspɔːrtswʊmən/'],
            ['front' => 'designer', 'back' => 'طراح', 'pronunciation' => '/dɪˈzaɪnər/'],
            ['front' => 'gallery', 'back' => 'گالری', 'pronunciation' => '/ˈɡæləri/'],
            ['front' => 'painter', 'back' => 'نقاش', 'pronunciation' => '/ˈpeɪnt.ər/'],
            ['front' => 'get lost', 'back' => 'گم شدن', 'pronunciation' => '/gɛt lɔst/'],
            ['front' => 'design', 'back' => 'طراحی کردن', 'pronunciation' => '/dɪˈzaɪn/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 7');
    }

    private function seedLesson8($deck)
    {
        $vocabulary = [
            ['front' => 'from', 'back' => 'از', 'pronunciation' => '/frʌm/'],
            ['front' => 'suite', 'back' => 'اتاق مجلل (در هتل)', 'pronunciation' => '/swiːt/'],
            ['front' => 'ghost', 'back' => 'روح', 'pronunciation' => '/goʊst/'],
            ['front' => 'dead', 'back' => 'مرده', 'pronunciation' => '/ded/'],
            ['front' => 'yard', 'back' => 'حیاط', 'pronunciation' => '/jɑːrd/'],
            ['front' => 'to', 'back' => 'به', 'pronunciation' => '/tu/'],
            ['front' => 'kill', 'back' => 'کشتن', 'pronunciation' => '/kɪl/'],
            ['front' => 'online', 'back' => 'آنلاین', 'pronunciation' => '/ˌɑːnˈlaɪn/'],
            ['front' => 'part', 'back' => 'بخش', 'pronunciation' => '/pɑrt/'],
            ['front' => 'sit', 'back' => 'نشستن', 'pronunciation' => '/sɪt/'],
            ['front' => 'into', 'back' => '(به) داخل', 'pronunciation' => '/ˈɪn.tuː/'],
            ['front' => 'lamp', 'back' => 'چراغ', 'pronunciation' => '/læmp/'],
            ['front' => 'there', 'back' => '[وجود داشتن]', 'pronunciation' => '/ðer/'],
            ['front' => 'detective', 'back' => 'کارآگاه', 'pronunciation' => '/dɪˈtektɪv/'],
            ['front' => 'balcony', 'back' => 'بالکن', 'pronunciation' => '/ˈbælkəni/'],
            ['front' => 'ceiling', 'back' => 'سقف (درونی)', 'pronunciation' => '/ˈsiː.lɪŋ/'],
            ['front' => 'house', 'back' => 'خانه', 'pronunciation' => '/hɑʊs/'],
            ['front' => 'out of', 'back' => 'خارج از', 'pronunciation' => '/ˈɑʊt̬.əv/'],
            ['front' => 'with', 'back' => 'با', 'pronunciation' => '/wɪð/'],
            ['front' => 'light', 'back' => 'چراغ', 'pronunciation' => '/lɑʪt/'],
            ['front' => 'in', 'back' => 'در', 'pronunciation' => '/ɪn/'],
            ['front' => 'any', 'back' => 'هیچ', 'pronunciation' => '/ˈen.i/'],
            ['front' => 'up', 'back' => 'بالا', 'pronunciation' => '/ʌp/'],
            ['front' => 'history', 'back' => 'تاریخ', 'pronunciation' => '/ˈhɪs.tə.ri/'],
            ['front' => 'floor', 'back' => 'کف', 'pronunciation' => '/flɔːr/'],
            ['front' => 'mirror', 'back' => 'آینه', 'pronunciation' => '/ˈmɪrər/'],
            ['front' => 'arrive', 'back' => 'رسیدن', 'pronunciation' => '/əˈrɑɪv/'],
            ['front' => 'down', 'back' => 'انتها', 'pronunciation' => '/dɑʊn/'],
            ['front' => 'stairs', 'back' => 'پله', 'pronunciation' => '/sterz/'],
            ['front' => 'plant', 'back' => 'گیاه', 'pronunciation' => '/plænt/'],
            ['front' => 'in front of', 'back' => 'در مقابل', 'pronunciation' => '/ɪn frʌnt ʌv/'],
            ['front' => 'rent', 'back' => 'اجاره', 'pronunciation' => '/rent/'],
            ['front' => 'wall', 'back' => 'دیوار', 'pronunciation' => '/wɔːl/'],
            ['front' => 'die', 'back' => 'مردن', 'pronunciation' => '/dɑɪ/'],
            ['front' => 'on', 'back' => 'در (مکان)', 'pronunciation' => '/ɔːn/'],
            ['front' => 'refrigerator', 'back' => 'یخچال', 'pronunciation' => '/rɪˈfrɪdʒəreɪtər/'],
            ['front' => 'under', 'back' => 'زیر', 'pronunciation' => '/ˈʌndər/'],
            ['front' => 'fridge', 'back' => 'یخچال', 'pronunciation' => '/frɪdʒ/'],
            ['front' => 'country house', 'back' => 'خانه ییلاقی', 'pronunciation' => '/ˌkʌntri ˈhaʊs/'],
            ['front' => 'toward', 'back' => 'به سوی', 'pronunciation' => '/tɔːrd/'],
            ['front' => 'armchair', 'back' => 'مبل راحتی', 'pronunciation' => '/ˈɑrm.tʃer/'],
            ['front' => 'rug', 'back' => 'قالیچه', 'pronunciation' => '/rʌg/'],
            ['front' => 'some', 'back' => 'بعضی (از)', 'pronunciation' => '/sʌm/'],
            ['front' => 'behind', 'back' => 'پشت', 'pronunciation' => '/bəˈhaɪnd/'],
            ['front' => 'shelf', 'back' => 'قفسه', 'pronunciation' => '/ʃelf/'],
            ['front' => 'bathtub', 'back' => 'وان حمام', 'pronunciation' => '/ˈbæθtʌb/'],
            ['front' => 'room', 'back' => 'اتاق', 'pronunciation' => '/ruːm/'],
            ['front' => 'between', 'back' => 'بین', 'pronunciation' => '/bɪˈtwiːn/'],
            ['front' => 'shower', 'back' => 'دوش', 'pronunciation' => '/ˈʃɑʊər/'],
            ['front' => 'bathroom', 'back' => 'حمام - دستشویی', 'pronunciation' => '/ˈbæθruːm/'],
            ['front' => 'sofa', 'back' => 'مبل راحتی', 'pronunciation' => '/ˈsoʊfə/'],
            ['front' => 'haunted', 'back' => 'روح زده (خانه و ...)', 'pronunciation' => '/ˈhɔntəd/'],
            ['front' => 'bedroom', 'back' => 'اتاق‌خواب', 'pronunciation' => '/ˈbedrʊm/'],
            ['front' => 'cupboard', 'back' => 'قفسه', 'pronunciation' => '/ˈkʌb.ərd/'],
            ['front' => 'couch', 'back' => 'مبل', 'pronunciation' => '/kɑʊtʃ/'],
            ['front' => 'stove', 'back' => 'اجاق', 'pronunciation' => '/stoʊv/'],
            ['front' => 'dining room', 'back' => 'اتاق غذاخوری', 'pronunciation' => '/ˈdɑɪnɪŋ ruːm/'],
            ['front' => 'fireplace', 'back' => 'شومینه', 'pronunciation' => '/ˈfaɪərˌpleɪs/'],
            ['front' => 'toilet', 'back' => 'توالت', 'pronunciation' => '/ˈtɔɪlət/'],
            ['front' => 'follow', 'back' => 'به دنبال رفتن', 'pronunciation' => '/ˈfɑl.oʊ/'],
            ['front' => 'garage', 'back' => 'گاراژ', 'pronunciation' => '/ˈɡærɑːʒ/'],
            ['front' => 'washing machine', 'back' => 'ماشین لباسشویی', 'pronunciation' => '/ˈwɑʃ.ɪŋ.məˌʃiːn/'],
            ['front' => 'hall', 'back' => 'سالن', 'pronunciation' => '/hɔːl/'],
            ['front' => 'lounge', 'back' => 'اتاق نشیمن', 'pronunciation' => '/laʊndʒ/'],
            ['front' => 'heat', 'back' => 'شوفاژ', 'pronunciation' => '/hiːt/'],
            ['front' => 'over', 'back' => 'روی', 'pronunciation' => '/ˈoʊ.vər/'],
            ['front' => 'owner', 'back' => 'مالک', 'pronunciation' => '/ˈoʊ.nər/'],
            ['front' => 'kitchen', 'back' => 'آشپزخانه', 'pronunciation' => '/ˈkɪtʃən/'],
            ['front' => 'check out', 'back' => 'حساب خود را تسویه کردن و رفتن (در هتل و بیمارستان و...)', 'pronunciation' => '/ʧɛk aʊt/'],
            ['front' => 'next to', 'back' => 'کنار', 'pronunciation' => '/nɛkst tʊ/'],
            ['front' => 'murder', 'back' => 'قتل (عمد)', 'pronunciation' => '/ˈmɜːrdər/'],
            ['front' => 'living room', 'back' => 'اتاق نشیمن', 'pronunciation' => '/ˈlɪvɪŋ rʊm/'],
            ['front' => 'think', 'back' => 'فکر کردن', 'pronunciation' => '/θɪŋk/'],
            ['front' => 'guest', 'back' => 'مهمان', 'pronunciation' => '/gest/'],
            ['front' => 'story', 'back' => 'داستان', 'pronunciation' => '/ˈstɔːr.i/'],
            ['front' => 'study', 'back' => 'اتاق مطالعه', 'pronunciation' => '/ˈstʌdi/'],
            ['front' => 'place', 'back' => 'مکان', 'pronunciation' => '/pleɪs/'],
            ['front' => 'movement', 'back' => 'حرکت', 'pronunciation' => '/ˈmuːv.mənt/'],
            ['front' => 'go to sleep', 'back' => 'به خواب رفتن', 'pronunciation' => '/goʊ tu slip/'],
            ['front' => 'there', 'back' => '[وجود داشتن]', 'pronunciation' => '/ðer/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 8');
    }

    private function seedLesson9($deck)
    {
        $vocabulary = [
            ['front' => 'tomato', 'back' => 'گوجه‌فرنگی', 'pronunciation' => '/təˈmeɪtoʊ/'],
            ['front' => 'fish', 'back' => '(گوشت) ماهی', 'pronunciation' => '/fɪʃ/'],
            ['front' => 'jar', 'back' => 'شیشه (مربا، عسل و...)', 'pronunciation' => '/dʒɑr/'],
            ['front' => 'fruit', 'back' => 'میوه', 'pronunciation' => '/fruːt/'],
            ['front' => 'dish', 'back' => 'ظرف', 'pronunciation' => '/dɪʃ/'],
            ['front' => 'meat', 'back' => 'گوشت', 'pronunciation' => '/miːt/'],
            ['front' => 'package', 'back' => 'بسته', 'pronunciation' => '/ˈpæk.ɪdʒ/'],
            ['front' => 'apple', 'back' => 'سیب', 'pronunciation' => '/ˈæpəl/'],
            ['front' => 'steak', 'back' => 'استیک', 'pronunciation' => '/steɪk/'],
            ['front' => 'soup', 'back' => 'سوپ', 'pronunciation' => '/suːp/'],
            ['front' => 'banana', 'back' => 'موز', 'pronunciation' => '/bəˈnɑːnə/'],
            ['front' => 'chicken', 'back' => '(گوشت) مرغ', 'pronunciation' => '/ˈtʃɪkən/'],
            ['front' => 'bag', 'back' => 'کیسه', 'pronunciation' => '/bæg/'],
            ['front' => 'meal', 'back' => 'وعده غذایی', 'pronunciation' => '/miːl/'],
            ['front' => 'orange', 'back' => 'پرتقال', 'pronunciation' => '/ˈɑrɪndʒ/'],
            ['front' => 'sausage', 'back' => 'سوسیس', 'pronunciation' => '/ˈsɔː.sɪdʒ/'],
            ['front' => 'fact', 'back' => 'حقیقت', 'pronunciation' => '/fækt/'],
            ['front' => 'how much', 'back' => 'چقدر', 'pronunciation' => '/haʊ mʌʧ/'],
            ['front' => 'oil', 'back' => 'روغن', 'pronunciation' => '/ɔɪl/'],
            ['front' => 'pineapple', 'back' => 'آناناس', 'pronunciation' => '/ˈpɑɪˌnæp.əl/'],
            ['front' => 'about', 'back' => 'درباره', 'pronunciation' => '/əˈbɑʊt/'],
            ['front' => 'how many', 'back' => 'چند', 'pronunciation' => '/haʊ ˈmɛni/'],
            ['front' => 'pasta', 'back' => 'پاستا', 'pronunciation' => '/ˈpɑːstə/'],
            ['front' => 'rice', 'back' => 'برنج', 'pronunciation' => '/rɑɪs/'],
            ['front' => 'a lot', 'back' => 'خیلی', 'pronunciation' => '/ə lɑt/'],
            ['front' => 'eight hundred and seventy-five', 'back' => 'هشتصد و هفتاد و پنج', 'pronunciation' => '/eɪt ˈhʌndrəd ænd ˈsɛvənti-faɪv/'],
            ['front' => 'strawberry', 'back' => 'توت‌فرنگی', 'pronunciation' => '/ˈstrɔːberi/'],
            ['front' => 'two million three hundred thousand', 'back' => 'دو میلیون و سیصد هزار', 'pronunciation' => '/tu ˈmɪljən θri ˈhʌndrəd ˈθaʊzənd/'],
            ['front' => 'five thousand four hundred and twenty', 'back' => 'پنج هزار و چهارصد و بیست', 'pronunciation' => '/faɪv ˈθaʊzənd fɔr ˈhʌndrəd ænd ˈtwɛnti/'],
            ['front' => 'much', 'back' => 'زیاد', 'pronunciation' => '/mʌtʃ/'],
            ['front' => 'dessert', 'back' => 'دسر', 'pronunciation' => '/dɪˈzɜrt/'],
            ['front' => 'mashed', 'back' => 'له شده', 'pronunciation' => '/mæʃt/'],
            ['front' => 'better', 'back' => 'بهتر', 'pronunciation' => '/ˈbet.ər/'],
            ['front' => 'main course', 'back' => 'وعده اصلی (غذا)', 'pronunciation' => '/ˌmeɪnˈkɔːrs/'],
            ['front' => 'cake', 'back' => 'کیک', 'pronunciation' => '/keɪk/'],
            ['front' => 'worse', 'back' => 'بدتر', 'pronunciation' => '/wɜːrs/'],
            ['front' => 'appetizer', 'back' => 'پیش‌غذا', 'pronunciation' => '/ˈæpɪtaɪzər/'],
            ['front' => 'one hundred and five', 'back' => 'صد و پنج', 'pronunciation' => '/wʌn ˈhʌndrəd ænd faɪv/'],
            ['front' => 'than', 'back' => 'از', 'pronunciation' => '/ðæn/'],
            ['front' => 'fruit salad', 'back' => 'سالاد میوه', 'pronunciation' => '/frut ˈsæləd/'],
            ['front' => 'breakfast', 'back' => 'صبحانه', 'pronunciation' => '/ˈbrekfəst/'],
            ['front' => 'wheat', 'back' => 'گندم', 'pronunciation' => '/wit/'],
            ['front' => 'course', 'back' => 'بخش (وعده غذا)', 'pronunciation' => '/kɔːrs/'],
            ['front' => 'ice cream', 'back' => 'بستنی', 'pronunciation' => '/ˈɑɪs.kriːm/'],
            ['front' => 'one thousand', 'back' => 'یک هزار', 'pronunciation' => '/wʌn ˈθaʊzənd/'],
            ['front' => 'more', 'back' => 'تر (نشانه صفت تفضیلی)', 'pronunciation' => '/mɔːr/'],
            ['front' => 'twenty-five thousand', 'back' => 'بیست و پنج هزار', 'pronunciation' => '/ˈtwɛnti-faɪv ˈθaʊzənd/'],
            ['front' => 'lunch', 'back' => 'ناهار', 'pronunciation' => '/lʌntʃ/'],
            ['front' => 'seafood', 'back' => 'غذای دریایی', 'pronunciation' => '/ˈsiː.fuːd/'],
            ['front' => 'a little', 'back' => 'کمی', 'pronunciation' => '/ə ˈlɪtəl/'],
            ['front' => 'thousand', 'back' => 'هزار', 'pronunciation' => '/ˈθaʊznd/'],
            ['front' => 'snack', 'back' => 'خوراک سبک', 'pronunciation' => '/snæk/'],
            ['front' => 'dinner', 'back' => 'شام', 'pronunciation' => '/ˈdɪnər/'],
            ['front' => 'homemade', 'back' => 'خانگی', 'pronunciation' => '/ˈhoʊmˈmeɪd/'],
            ['front' => 'contestant', 'back' => 'مسابقه دهنده', 'pronunciation' => '/kənˈtɛstənt/'],
            ['front' => 'two hundred', 'back' => 'دویست', 'pronunciation' => '/tu ˈhʌndrəd/'],
            ['front' => 'salt', 'back' => 'نمک', 'pronunciation' => '/sɔːlt/'],
            ['front' => 'bread', 'back' => 'نان', 'pronunciation' => '/bred/'],
            ['front' => 'sauce', 'back' => 'سس', 'pronunciation' => '/sɔːs/'],
            ['front' => 'chocolate', 'back' => 'شکلات', 'pronunciation' => '/ˈtʃɑk.lət/'],
            ['front' => 'butter', 'back' => 'کره', 'pronunciation' => '/ˈbʌtər/'],
            ['front' => 'salad', 'back' => 'سالاد', 'pronunciation' => '/ˈsæləd/'],
            ['front' => 'cookie', 'back' => 'کلوچه', 'pronunciation' => '/ˈkʊk.i/'],
            ['front' => 'one hundred thousand', 'back' => 'یکصد هزار', 'pronunciation' => '/wʌn ˈhʌndrəd ˈθaʊzənd/'],
            ['front' => 'cereal', 'back' => 'غله (گندم و ...)', 'pronunciation' => '/ˈsɪr.iː.əl/'],
            ['front' => 'cheese', 'back' => 'پنیر', 'pronunciation' => '/tʃiːz/'],
            ['front' => 'potato chip', 'back' => 'چیپس (سیب زمینی)', 'pronunciation' => '/pəˈteɪt̬.oʊˌtʃɪp/'],
            ['front' => 'none', 'back' => 'هیچ', 'pronunciation' => '/nʌn/'],
            ['front' => 'vegetable', 'back' => 'سبزیجات', 'pronunciation' => '/ˈvedʒtəbl/'],
            ['front' => 'fresh', 'back' => 'تازه', 'pronunciation' => '/freʃ/'],
            ['front' => 'coffee', 'back' => 'قهوه', 'pronunciation' => '/ˈkɑːfi/'],
            ['front' => 'quiz', 'back' => 'امتحان', 'pronunciation' => '/kwɪz/'],
            ['front' => 'general knowledge', 'back' => 'دانش عمومی', 'pronunciation' => '/ˈʤɛnərəl ˈnɑləʤ/'],
            ['front' => 'sandwich', 'back' => 'ساندویچ', 'pronunciation' => '/ˈsæn.dwɪtʃ/'],
            ['front' => 'carrot', 'back' => 'هویج', 'pronunciation' => '/ˈkærət/'],
            ['front' => 'egg', 'back' => 'تخم مرغ', 'pronunciation' => '/eg/'],
            ['front' => 'prize', 'back' => 'جایزه', 'pronunciation' => '/prɑɪz/'],
            ['front' => 'French fries', 'back' => 'سیب‌زمینی سرخ‌کرده', 'pronunciation' => '/ˈfrentʃ ˈfrɑɪz/'],
            ['front' => 'approximate', 'back' => 'تقریبی', 'pronunciation' => '/əˈprɑk.sə.mət/'],
            ['front' => 'food', 'back' => 'غذا', 'pronunciation' => '/fuːd/'],
            ['front' => 'lettuce', 'back' => 'کاهو', 'pronunciation' => '/ˈletəs/'],
            ['front' => 'jam', 'back' => 'مربا', 'pronunciation' => '/dʒæm/'],
            ['front' => 'gold', 'back' => 'طلا', 'pronunciation' => '/goʊld/'],
            ['front' => 'one thousand five hundred', 'back' => '(یک) هزار و پانصد', 'pronunciation' => '/wʌn ˈθaʊzənd faɪv ˈhʌndrəd/'],
            ['front' => 'mushroom', 'back' => 'قارچ', 'pronunciation' => '/ˈmʌʃ.ruːm/'],
            ['front' => 'juice', 'back' => 'آبمیوه', 'pronunciation' => '/dʒuːs/'],
            ['front' => 'three hundred and fifty', 'back' => 'سیصد و پنجاه', 'pronunciation' => '/θri ˈhʌndrəd ænd ˈfɪfti/'],
            ['front' => 'grilled', 'back' => 'کبابی', 'pronunciation' => '/grɪld/'],
            ['front' => 'one million', 'back' => 'یک میلیون', 'pronunciation' => '/wʌn ˈmɪljən/'],
            ['front' => 'population', 'back' => 'جمعیت', 'pronunciation' => '/ˌpɑpjəˈleɪʃən/'],
            ['front' => 'container', 'back' => 'ظرف', 'pronunciation' => '/kənˈteɪ.nər/'],
            ['front' => 'compete', 'back' => 'رقابت کردن', 'pronunciation' => '/kəmˈpit/'],
            ['front' => 'onion', 'back' => 'پیاز', 'pronunciation' => '/ˈʌnjən/'],
            ['front' => 'milk', 'back' => 'شیر', 'pronunciation' => '/mɪlk/'],
            ['front' => 'bottle', 'back' => 'بطری', 'pronunciation' => '/ˈbɑːtl/'],
            ['front' => 'million', 'back' => 'میلیون', 'pronunciation' => '/ˈmɪl.jən/'],
            ['front' => 'champion', 'back' => 'قهرمان', 'pronunciation' => '/ˈtʃæm.pi.ən/'],
            ['front' => 'pea', 'back' => 'نخودفرنگی', 'pronunciation' => '/piː/'],
            ['front' => 'sugar', 'back' => 'شکر', 'pronunciation' => '/ˈʃʊgər/'],
            ['front' => 'calorie', 'back' => 'کالری', 'pronunciation' => '/ˈkæləri/'],
            ['front' => 'straw', 'back' => 'نی (برای نوشیدن)', 'pronunciation' => '/strɔː/'],
            ['front' => 'beat', 'back' => 'شکست دادن', 'pronunciation' => '/biːt/'],
            ['front' => 'potato', 'back' => 'سیب‌زمینی', 'pronunciation' => '/pəˈteɪtoʊ/'],
            ['front' => 'tea', 'back' => 'چای', 'pronunciation' => '/tiː/'],
            ['front' => 'box', 'back' => 'جعبه', 'pronunciation' => '/bɑːks/'],
            ['front' => 'how far', 'back' => 'تا چه حد', 'pronunciation' => '/haʊ fɑr/'],
            ['front' => 'can', 'back' => 'کنسرو', 'pronunciation' => '/kæn/'],
            ['front' => 'toast', 'back' => 'نان برشته', 'pronunciation' => '/toʊst/'],
            ['front' => 'two thousand and twelve', 'back' => 'دو هزار و دوازده', 'pronunciation' => '/tu ˈθaʊzənd ænd twɛlv/'],
            ['front' => 'about', 'back' => 'حدود', 'pronunciation' => '/əˈbɑʊt/'],
            ['front' => 'cream cheese', 'back' => 'پنیر خامه ای', 'pronunciation' => '/krim ʧiz/'],
            ['front' => 'much', 'back' => 'زیاد', 'pronunciation' => '/mʌtʃ/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 9');
    }

    private function seedLesson10($deck)
    {
        $vocabulary = [
            ['front' => 'going to', 'back' => 'قصد (انجام کاری را) داشتن', 'pronunciation' => '/ˈgoʊɪŋ tu/'],
            ['front' => 'street', 'back' => 'خیابان', 'pronunciation' => '/striːt/'],
            ['front' => 'most', 'back' => '-ترین (نشانه صفت یا قید عالی)', 'pronunciation' => '/moʊst/'],
            ['front' => 'supermarket', 'back' => 'سوپرمارکت', 'pronunciation' => '/ˈsuːpərˌmɑrkɪt/'],
            ['front' => 'building', 'back' => 'ساختمان', 'pronunciation' => '/ˈbɪl.dɪŋ/'],
            ['front' => 'lucky', 'back' => 'خوش‌شانس', 'pronunciation' => '/ˈlʌk.i/'],
            ['front' => 'around', 'back' => 'سرتاسر', 'pronunciation' => '/əˈrɑʊnd/'],
            ['front' => 'town', 'back' => 'شهر (کوچک)', 'pronunciation' => '/tɑʊn/'],
            ['front' => 'temple', 'back' => 'معبد', 'pronunciation' => '/ˈtem.pəl/'],
            ['front' => 'mostly', 'back' => 'اکثرا', 'pronunciation' => '/ˈmoʊs.tli/'],
            ['front' => 'art gallery', 'back' => 'گالری آثار هنری', 'pronunciation' => '/ˈɑːrt ɡæləri/'],
            ['front' => 'theater', 'back' => 'تئاتر', 'pronunciation' => '/ˈθiətər/'],
            ['front' => 'card', 'back' => 'کارت', 'pronunciation' => '/kɑrd/'],
            ['front' => 'tour', 'back' => 'گردش', 'pronunciation' => '/tʊr/'],
            ['front' => 'below', 'back' => 'زیر', 'pronunciation' => '/bɪˈləʊ/'],
            ['front' => 'bridge', 'back' => 'پل', 'pronunciation' => '/brɪdʒ/'],
            ['front' => 'bus station', 'back' => 'ایستگاه اتوبوس', 'pronunciation' => '/ˈbʌsˌsteɪʃən/'],
            ['front' => 'people', 'back' => 'مردم', 'pronunciation' => '/ˈpiː.pəl/'],
            ['front' => 'kind', 'back' => 'نوع', 'pronunciation' => '/kɑɪnd/'],
            ['front' => 'fewer', 'back' => 'کمتر', 'pronunciation' => '/ˈfjuər/'],
            ['front' => 'church', 'back' => 'کلیسا', 'pronunciation' => '/tʃɜrtʃ/'],
            ['front' => 'town hall', 'back' => 'ساختمان شهرداری', 'pronunciation' => '/ˌtaʊn ˈhɔːl/'],
            ['front' => 'all', 'back' => 'همه', 'pronunciation' => '/ɔːl/'],
            ['front' => 'department store', 'back' => 'فروشگاه بزرگ', 'pronunciation' => '/dɪˈpɑrt.məntˌstɔːr/'],
            ['front' => 'train station', 'back' => 'ایستگاه راه‌آهن', 'pronunciation' => '/ˈtreɪn ˌsteɪʃən/'],
            ['front' => 'fortune-telling', 'back' => 'فال‌گیری', 'pronunciation' => '/ˈfɔrʧən-ˈtɛlɪŋ/'],
            ['front' => 'above', 'back' => 'بالای', 'pronunciation' => '/əˈbʌv/'],
            ['front' => 'fortune-teller', 'back' => 'فال‌گیر', 'pronunciation' => '/ˈfɔrʧən-ˈtɛlər/'],
            ['front' => 'become', 'back' => 'شدن', 'pronunciation' => '/bɪˈkʌm/'],
            ['front' => 'hospital', 'back' => 'بیمارستان', 'pronunciation' => '/ˈhɑːspɪtl/'],
            ['front' => 'nearly', 'back' => 'تقریبا', 'pronunciation' => '/ˈnɪr.li/'],
            ['front' => 'market', 'back' => 'بازار', 'pronunciation' => '/ˈmɑr.kɪt/'],
            ['front' => 'narrow', 'back' => 'باریک', 'pronunciation' => '/ˈnær.oʊ/'],
            ['front' => 'mosque', 'back' => 'مسجد', 'pronunciation' => '/mɑsk/'],
            ['front' => 'get married', 'back' => 'ازدواج کردن', 'pronunciation' => '/gɛt ˈmærɪd/'],
            ['front' => 'museum', 'back' => 'موزه', 'pronunciation' => '/mjʊˈziːəm/'],
            ['front' => 'work out', 'back' => '(به گونه‌ای) پیش رفتن (به‌خصوص خوب)', 'pronunciation' => '/wɜrk aʊt/'],
            ['front' => 'fall in love', 'back' => 'عاشق (کسی) شدن', 'pronunciation' => '/fɔl ɪn lʌv/'],
            ['front' => 'parking lot', 'back' => 'پارکینگ', 'pronunciation' => '/ˈpɑr.kɪŋˌlɑt/'],
            ['front' => 'pharmacy', 'back' => 'داروخانه', 'pronunciation' => '/ˈfɑrməsi/'],
            ['front' => 'prediction', 'back' => 'پیش‌بینی', 'pronunciation' => '/prɪˈdɪk.ʃən/'],
            ['front' => 'police station', 'back' => 'اداره پلیس', 'pronunciation' => '/pəˈliːsˌsteɪ.ʃən/'],
            ['front' => 'experienced', 'back' => 'باتجربه', 'pronunciation' => '/ɪkˈspɪr.iː.ənst/'],
            ['front' => 'surprise', 'back' => 'متعجب ساختن', 'pronunciation' => '/surprise/'],
            ['front' => 'vacation', 'back' => 'مرخصی', 'pronunciation' => '/veɪˈkeɪʃən/'],
            ['front' => 'fun', 'back' => 'سرگرم‌کننده', 'pronunciation' => '/fʌn/'],
            ['front' => 'post office', 'back' => 'اداره پست', 'pronunciation' => '/ˈpoʊstˌɔː.fəs/'],
            ['front' => 'river', 'back' => 'رود', 'pronunciation' => '/ˈrɪv.ər/'],
            ['front' => 'road', 'back' => 'جاده', 'pronunciation' => '/roʊd/'],
            ['front' => 'travel', 'back' => 'سفر کردن', 'pronunciation' => '/ˈtrævl/'],
            ['front' => 'happen', 'back' => 'اتفاق افتادن', 'pronunciation' => '/ˈhæp.ən/'],
            ['front' => 'shopping mall', 'back' => 'پاساژ خرید', 'pronunciation' => '/ˈʃɑːpɪŋ mɔːl/'],
            ['front' => 'move', 'back' => 'اسباب‌کشی کردن', 'pronunciation' => '/muːv/'],
            ['front' => 'square', 'back' => 'میدان', 'pronunciation' => '/skwer/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 10');
    }

    private function seedLesson11($deck)
    {
        $vocabulary = [
            ['front' => 'plane', 'back' => 'هواپیما', 'pronunciation' => '/pleɪn/'],
            ['front' => 'website', 'back' => 'تارنما', 'pronunciation' => '/ˈweb.saɪt/'],
            ['front' => 'log in', 'back' => 'وارد سیستم شدن (کامپیوتر)', 'pronunciation' => '/lɔg ɪn/'],
            ['front' => 'taxi', 'back' => 'تاکسی', 'pronunciation' => '/ˈtæksi/'],
            ['front' => 'page', 'back' => 'صفحه (اینترنتی)', 'pronunciation' => '/peɪdʒ/'],
            ['front' => 'bus', 'back' => 'اتوبوس', 'pronunciation' => '/bʌs/'],
            ['front' => 'ferry', 'back' => 'فرابر (نوعی کشتی مسافربری و یا باربری)', 'pronunciation' => '/ˈfer.i/'],
            ['front' => 'hard', 'back' => 'سخت', 'pronunciation' => '/hɑːrd/'],
            ['front' => 'subway', 'back' => 'مترو', 'pronunciation' => '/ˈsʌbweɪ/'],
            ['front' => 'attachment', 'back' => 'پیوست', 'pronunciation' => '/əˈtætʃ.mənt/'],
            ['front' => 'badly', 'back' => 'به‌طور بد', 'pronunciation' => '/ˈbædli/'],
            ['front' => 'upload', 'back' => 'بارگذاری کردن', 'pronunciation' => '/ˈʌp.loʊd/'],
            ['front' => 'carefully', 'back' => 'بادقت', 'pronunciation' => '/ˈker.fə.li/'],
            ['front' => 'cab', 'back' => 'تاکسی', 'pronunciation' => '/kæb/'],
            ['front' => 'possibly', 'back' => 'احتمالا', 'pronunciation' => '/ˈpɑs.ə.bli/'],
            ['front' => 'unhealthily', 'back' => 'به طرز ناسالمی', 'pronunciation' => '/ənˈhɛlθɪli/'],
            ['front' => 'easily', 'back' => 'به راحتی', 'pronunciation' => '/ˈiː.zə.li/'],
            ['front' => 'very', 'back' => 'خیلی', 'pronunciation' => '/ˈveri/'],
            ['front' => 'download', 'back' => 'دانلود کردن', 'pronunciation' => '/ˈdɑʊn.loʊd/'],
            ['front' => 'need', 'back' => 'بایستن', 'pronunciation' => '/niːd/'],
            ['front' => 'happily', 'back' => 'با خوشحالی', 'pronunciation' => '/ˈhæp.ə.li/'],
            ['front' => 'airport', 'back' => 'فرودگاه', 'pronunciation' => '/ˈerpɔːrt/'],
            ['front' => 'google', 'back' => 'گوگل کردن', 'pronunciation' => '/ˈgugəl/'],
            ['front' => 'station', 'back' => 'ایستگاه', 'pronunciation' => '/ˈsteɪ.ʃən/'],
            ['front' => 'well', 'back' => 'به‌خوبی', 'pronunciation' => '/wel/'],
            ['front' => 'friendly', 'back' => 'دوستانه', 'pronunciation' => '/ˈfrendli/'],
            ['front' => 'Wi-Fi', 'back' => 'وای-فای', 'pronunciation' => '/ˈwʌɪfʌɪ/'],
            ['front' => 'stop', 'back' => 'ایستگاه', 'pronunciation' => '/stɑp/'],
            ['front' => 'incredibly', 'back' => 'به‌طور باور نکردنی', 'pronunciation' => '/ɪnˈkred.ə.bli/'],
            ['front' => 'would like', 'back' => 'خواستن', 'pronunciation' => '/wʊd laɪk/'],
            ['front' => 'search', 'back' => 'به‌دنبال یافتن چیزی بودن', 'pronunciation' => '/sɜrtʃ/'],
            ['front' => 'slowly', 'back' => 'به آرامی', 'pronunciation' => '/ˈsloʊ.li/'],
            ['front' => 'politely', 'back' => 'مودبانه', 'pronunciation' => '/pəˈlaɪt.li/'],
            ['front' => 'social network', 'back' => 'شبکه اجتماعی', 'pronunciation' => '/ˈsoʊʃəl ˈnɛˌtwɜrk/'],
            ['front' => 'impression', 'back' => 'نظر', 'pronunciation' => '/ɪmˈpreʃ.ən/'],
            ['front' => 'fashionably', 'back' => 'مطابق مد روز', 'pronunciation' => '/ˈfæʃənəbli/'],
            ['front' => 'hope', 'back' => 'امیدوار بودن', 'pronunciation' => '/hoʊp/'],
            ['front' => 'travel', 'back' => 'سفر', 'pronunciation' => '/ˈtrævl/'],
            ['front' => 'plan', 'back' => 'قصد داشتن', 'pronunciation' => '/plæn/'],
            ['front' => 'perfectly', 'back' => 'کاملاً', 'pronunciation' => '/ˈpɜr.fɪk.tli/'],
            ['front' => 'driving', 'back' => 'رانندگی', 'pronunciation' => '/ˈdraɪvɪŋ/'],
            ['front' => 'learn', 'back' => 'یاد گرفتن', 'pronunciation' => '/lɜːrn/'],
            ['front' => 'man', 'back' => 'مرد', 'pronunciation' => '/mæn/'],
            ['front' => 'dangerously', 'back' => 'به طرز خطرناکی', 'pronunciation' => '/ˈdeɪn.dʒə.rəs.li/'],
            ['front' => 'woman', 'back' => 'زن', 'pronunciation' => '/ˈwʊmən/'],
            ['front' => 'beautifully', 'back' => 'به زیبایی', 'pronunciation' => '/ˈbjuːt̬.ɪ.fəl.i/'],
            ['front' => 'Internet', 'back' => 'اینترنت', 'pronunciation' => '/ˈɪntərnet/'],
            ['front' => 'fast', 'back' => 'سریع', 'pronunciation' => '/fæst/'],
            ['front' => 'public transportation', 'back' => 'حمل و نقل عمومی', 'pronunciation' => '/ˌpʌb.lɪk.træn.spɔːrˈteɪ.ʃən/'],
            ['front' => 'train', 'back' => 'قطار', 'pronunciation' => '/treɪn/'],
            ['front' => 'quickly', 'back' => 'سریع', 'pronunciation' => '/ˈkwɪk.li/'],
            ['front' => 'Skype', 'back' => 'با نرم‌افزار اسکایپ تماس گرفتن', 'pronunciation' => '/skaɪp/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 11');
    }

    private function seedLesson12($deck)
    {
        $vocabulary = [
            ['front' => 'bed', 'back' => 'تختخواب', 'pronunciation' => '/bed/'],
            ['front' => 'send', 'back' => 'فرستادن', 'pronunciation' => '/sɛnd/'],
            ['front' => 'spend', 'back' => 'خرج کردن', 'pronunciation' => '/spend/'],
            ['front' => 'lose', 'back' => 'گم کردن', 'pronunciation' => '/luːz/'],
            ['front' => 'pay', 'back' => 'پرداخت کردن', 'pronunciation' => '/peɪ/'],
            ['front' => 'win', 'back' => 'پیروز شدن', 'pronunciation' => '/wɪn/'],
            ['front' => 'questionnaire', 'back' => 'پرسشنامه', 'pronunciation' => '/ˌkwes.tʃəˈner/'],
            ['front' => 'taste', 'back' => 'سلیقه', 'pronunciation' => '/teɪst/'],
            ['front' => 'thing', 'back' => 'چیز', 'pronunciation' => '/θɪŋ/'],
            ['front' => 'close to', 'back' => 'نزدیک به', 'pronunciation' => '/kloʊs tu/'],
            ['front' => 'break', 'back' => 'شکستن', 'pronunciation' => '/breɪk/'],
            ['front' => 'job', 'back' => 'شغل', 'pronunciation' => '/dʒɑːb/'],
            ['front' => 'prefer', 'back' => 'ترجیح دادن', 'pronunciation' => '/prɪˈfɜr/'],
            ['front' => 'traditional', 'back' => 'سنتی', 'pronunciation' => '/trəˈdɪʃ.ən.əl/'],
            ['front' => 'furniture', 'back' => 'اسباب و اثاثیه', 'pronunciation' => '/ˈfɜr.nɪ.tʃər/'],
            ['front' => 'biography', 'back' => 'زندگینامه', 'pronunciation' => '/baɪˈɑgrəfi/'],
            ['front' => 'routine', 'back' => 'کار همیشگی', 'pronunciation' => '/ruˈtin/'],
            ['front' => 'character', 'back' => 'شخصیت', 'pronunciation' => '/ˈkær.ɪk.tər/'],
            ['front' => 'daily', 'back' => 'روزانه', 'pronunciation' => '/ˈdeɪ.li/'],
            ['front' => 'historical', 'back' => 'تاریخی', 'pronunciation' => '/hɪˈstɔːr.ɪ.kəl/'],
            ['front' => 'adjective', 'back' => 'صفت', 'pronunciation' => '/ˈædʒ.ɪk.tɪv/'],
            ['front' => 'small', 'back' => 'کوچک', 'pronunciation' => '/smɔːl/'],
            ['front' => 'answer', 'back' => 'پاسخ دادن', 'pronunciation' => '/ˈæn.sər/'],
            ['front' => 'desk', 'back' => 'میز تحریر', 'pronunciation' => '/desk/'],
            ['front' => 'there', 'back' => 'آنجا (مکان)', 'pronunciation' => '/ðer/'],
            ['front' => 'living room', 'back' => 'اتاق نشیمن', 'pronunciation' => '/ˈlɪvɪŋ rʊm/'],
            ['front' => 'relax', 'back' => 'آرامیدن', 'pronunciation' => '/rɪˈlæks/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 1 - Lesson 12');
    }

    private function seedVocabulary($deck, $vocabulary, $lessonName)
    {
        foreach ($vocabulary as $cardData) {
            StaticCard::updateOrCreate(
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                ],
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                    'interval' => 1,
                    'revised_at' => null,
                    'last_reviewed' => null,
                ]
            );
        }

        $this->command->info('Seeded ' . count($vocabulary) . ' cards for ' . $lessonName);
    }
}
