<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\StaticCard;
use App\Models\StaticDeck;
use Illuminate\Database\Seeder;

class StaticCardFile3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all Intermediate level static decks
        $intermediateDecks = StaticDeck::where('level', 'intermediate')->get();

        if ($intermediateDecks->isEmpty()) {
            $this->command->error('No Intermediate level static decks found. Please run StaticDeckSeeder first.');

            return;
        }

        // Lesson 1 vocabulary
        $lesson1Deck = $intermediateDecks->where('lesson_number', 1)->first();
        if ($lesson1Deck) {
            $this->seedLesson1($lesson1Deck);
        }

        // Lesson 2 vocabulary
        $lesson2Deck = $intermediateDecks->where('lesson_number', 2)->first();
        if ($lesson2Deck) {
            $this->seedLesson2($lesson2Deck);
        }

        // Lesson 3 vocabulary
        $lesson3Deck = $intermediateDecks->where('lesson_number', 3)->first();
        if ($lesson3Deck) {
            $this->seedLesson3($lesson3Deck);
        }

        // Lesson 4 vocabulary
        $lesson4Deck = $intermediateDecks->where('lesson_number', 4)->first();
        if ($lesson4Deck) {
            $this->seedLesson4($lesson4Deck);
        }

        // Lesson 5 vocabulary
        $lesson5Deck = $intermediateDecks->where('lesson_number', 5)->first();
        if ($lesson5Deck) {
            $this->seedLesson5($lesson5Deck);
        }

        // Lesson 6 vocabulary
        $lesson6Deck = $intermediateDecks->where('lesson_number', 6)->first();
        if ($lesson6Deck) {
            $this->seedLesson6($lesson6Deck);
        }

        // Lesson 7 vocabulary
        $lesson7Deck = $intermediateDecks->where('lesson_number', 7)->first();
        if ($lesson7Deck) {
            $this->seedLesson7($lesson7Deck);
        }

        // Lesson 8 vocabulary
        $lesson8Deck = $intermediateDecks->where('lesson_number', 8)->first();
        if ($lesson8Deck) {
            $this->seedLesson8($lesson8Deck);
        }

        // Lesson 9 vocabulary
        $lesson9Deck = $intermediateDecks->where('lesson_number', 9)->first();
        if ($lesson9Deck) {
            $this->seedLesson9($lesson9Deck);
        }

        // Lesson 10 vocabulary
        $lesson10Deck = $intermediateDecks->where('lesson_number', 10)->first();
        if ($lesson10Deck) {
            $this->seedLesson10($lesson10Deck);
        }

    }

    protected function seedLesson1($deck)
    {
        $vocabulary = [
            ['front' => 'gathering', 'back' => 'دورهمی', 'pronunciation' => '/ˈgæð.ə.rɪŋ/'],
            ['front' => 'squid', 'back' => 'ماهی مرکب', 'pronunciation' => '/skwɪd/'],
            ['front' => 'red pepper', 'back' => 'فلفل قرمز', 'pronunciation' => '/ˌred ˈpepər/'],
            ['front' => 'rebellious', 'back' => 'یاغی', 'pronunciation' => '/rɪˈbeljəs/'],
            ['front' => 'baked', 'back' => 'پخته شده', 'pronunciation' => '/beɪkt/'],
            ['front' => 'spoiled', 'back' => 'نازپرورده', 'pronunciation' => '/spɔɪld/'],
            ['front' => 'stupid', 'back' => 'احمق', 'pronunciation' => '/ˈstuː.pɪd/'],
            ['front' => 'tuna', 'back' => 'ماهی تن', 'pronunciation' => '/ˈtuːnə/'],
            ['front' => 'take-out', 'back' => 'بیرونی', 'pronunciation' => '/teɪk-aʊt/'],
            ['front' => 'zucchini', 'back' => 'کدو سبز', 'pronunciation' => '/zuˈkini/'],
            ['front' => 'grilled', 'back' => 'کبابی', 'pronunciation' => '/grɪld/'],
            ['front' => 'emotional', 'back' => 'احساسی', 'pronunciation' => '/ɪˈmoʊʃənəl/'],
            ['front' => 'immediate family', 'back' => 'خانواده درجه یک', 'pronunciation' => '/ɪˈmidiət ˈfæməli/'],
            ['front' => 'talkative', 'back' => 'پرحرف', 'pronunciation' => '/ˈtɔkətɪv/'],
            ['front' => 'beneficial', 'back' => 'سودمند', 'pronunciation' => '/ˌben.əˈfɪʃ.əl/'],
            ['front' => 'stubborn', 'back' => 'کله‌شق', 'pronunciation' => '/ˈstʌb.ərn/'],
            ['front' => 'steamed', 'back' => 'بخارپز', 'pronunciation' => '/stiːmd/'],
            ['front' => 'courgette', 'back' => 'کدو سبز', 'pronunciation' => '/kʊɹˈʒɛt/'],
            ['front' => 'generous', 'back' => 'بخشنده', 'pronunciation' => '/ˈdʒenərəs/'],
            ['front' => 'beef', 'back' => 'گوشت گاو', 'pronunciation' => '/biːf/'],
            ['front' => 'crab', 'back' => 'خرچنگ', 'pronunciation' => '/kræb/'],
            ['front' => 'cherry', 'back' => 'گیلاس', 'pronunciation' => '/ˈtʃer.i/'],
            ['front' => 'eat out', 'back' => 'بیرون (در رستوران و...) غذا خوردن', 'pronunciation' => '/it aʊt/'],
            ['front' => 'chicken', 'back' => '(گوشت) مرغ', 'pronunciation' => '/ˈtʃɪkən/'],
            ['front' => 'mussel', 'back' => 'صدف سیاه', 'pronunciation' => '/ˈmʌsəl/'],
            ['front' => 'melon', 'back' => 'ملون (خربزه، طالبی و ...)', 'pronunciation' => '/ˈmel.ən/'],
            ['front' => 'ready-made', 'back' => 'آماده', 'pronunciation' => '/ˌredi ˈmeɪd/'],
            ['front' => 'cucumber', 'back' => 'خیار', 'pronunciation' => '/ˈkjuːkʌmbər/'],
            ['front' => 'peach', 'back' => 'هلو', 'pronunciation' => '/piːtʃ/'],
            ['front' => 'duck', 'back' => '(گوشت) اردک', 'pronunciation' => '/dʌk/'],
            ['front' => 'clean', 'back' => 'تمیز', 'pronunciation' => '/kliːn/'],
            ['front' => 'extended family', 'back' => 'خانواده گسترده', 'pronunciation' => '/ɪkˌstendɪd ˈfæməli/'],
            ['front' => 'cheap', 'back' => 'خسیس', 'pronunciation' => '/tʃiːp/'],
            ['front' => 'boarding school', 'back' => 'مدرسه شبانه روزی', 'pronunciation' => '/ˈbɔːrdɪŋ skuːl/'],
            ['front' => 'pear', 'back' => 'گلابی', 'pronunciation' => '/per/'],
            ['front' => 'eggplant', 'back' => 'بادمجان', 'pronunciation' => '/ˈegplænt/'],
            ['front' => 'cut down', 'back' => 'کاهش دادن', 'pronunciation' => '/kʌt daʊn/'],
            ['front' => 'lamb', 'back' => 'گوشت بره', 'pronunciation' => '/læm/'],
            ['front' => 'raspberry', 'back' => 'تمشک', 'pronunciation' => '/ˈræz.ber.i/'],
            ['front' => 'aubergine', 'back' => 'بادمجان', 'pronunciation' => '/ˈoʊbərʒiːn/'],
            ['front' => 'boiled', 'back' => 'آب‌پز', 'pronunciation' => '/bɔɪld/'],
            ['front' => 'patient', 'back' => 'صبور', 'pronunciation' => '/ˈpeɪʃənt/'],
            ['front' => 'insecure', 'back' => 'عاری از اعتمادبه‌نفس', 'pronunciation' => '/ˈɪnsəkjər/'],
            ['front' => 'bossy', 'back' => 'رئیس‌مآب', 'pronunciation' => '/ˈbɑs.i/'],
            ['front' => 'pork', 'back' => 'گوشت خوک', 'pronunciation' => '/pɔːrk/'],
            ['front' => 'cut out', 'back' => 'حذف کردن', 'pronunciation' => '/kʌt aʊt/'],
            ['front' => 'lazy', 'back' => 'تنبل', 'pronunciation' => '/ˈleɪ.zi/'],
            ['front' => 'charming', 'back' => 'جذاب', 'pronunciation' => '/ˈtʃɑr.mɪŋ/'],
            ['front' => 'quiet', 'back' => 'آرام و کم‌حرف', 'pronunciation' => '/ˈkwɑɪət/'],
            ['front' => 'competitive', 'back' => 'رقابت‌جو', 'pronunciation' => '/kəmˈpet̬.ət̬.ɪv/'],
            ['front' => 'friendly', 'back' => 'دوستانه', 'pronunciation' => '/ˈfrendli/'],
            ['front' => 'brother-in-law', 'back' => 'برادر زن/شوهر', 'pronunciation' => '/ˈbrʌð.ər.ɪn.lɔː/'],
            ['front' => 'great-grandfather', 'back' => 'پدرجد (پدر پدربزرگ)', 'pronunciation' => '/greɪt-ˈgrændˌfɑðər/'],
            ['front' => 'frozen', 'back' => 'منجمد', 'pronunciation' => '/ˈfroʊ.zən/'],
            ['front' => 'grape', 'back' => 'انگور', 'pronunciation' => '/greɪp/'],
            ['front' => 'seafood', 'back' => 'غذای دریایی', 'pronunciation' => '/ˈsiː.fuːd/'],
            ['front' => 'rivalry', 'back' => 'رقابت', 'pronunciation' => '/ˈraɪvlri/'],
            ['front' => 'low-fat', 'back' => 'کم‌چرب', 'pronunciation' => '/ˌloʊ ˈfæt/'],
            ['front' => 'independent', 'back' => 'مستقل', 'pronunciation' => '/ˌɪn.dɪˈpen.dənt/'],
            ['front' => 'affectionate', 'back' => 'مهربان', 'pronunciation' => '/əˈfekʃənət/'],
            ['front' => 'sick', 'back' => 'بیمار', 'pronunciation' => '/sɪk/'],
            ['front' => 'powerful', 'back' => 'قوی (دارو)', 'pronunciation' => '/ˈpɑʊ.ər.fəl/'],
            ['front' => 'salmon', 'back' => 'سالمون', 'pronunciation' => '/ˈsæmən/'],
            ['front' => 'green bean', 'back' => 'لوبیاسبز', 'pronunciation' => '/ˌɡriːn ˈbiːn/'],
            ['front' => 'jealous', 'back' => 'حسود', 'pronunciation' => '/ˈdʒel.əs/'],
            ['front' => 'raw', 'back' => 'نپخته (غذا)', 'pronunciation' => '/rɔː/'],
            ['front' => 'relaxed', 'back' => 'آسوده‌خاطر', 'pronunciation' => '/rɪˈlækst/'],
            ['front' => 'honest', 'back' => 'راستگو', 'pronunciation' => '/ˈɑnɪst/'],
            ['front' => 'value', 'back' => 'ارزش', 'pronunciation' => '/ˈvæl.juː/'],
            ['front' => 'aggressive', 'back' => 'پرخاشگر', 'pronunciation' => '/əˈgres.ɪv/'],
            ['front' => 'parent', 'back' => 'والد', 'pronunciation' => '/ˈpær.ənt/'],
            ['front' => 'share', 'back' => 'سهیم بودن', 'pronunciation' => '/ʃer/'],
            ['front' => 'lemon', 'back' => 'لیمو', 'pronunciation' => '/ˈlemən/'],
            ['front' => 'sleepy', 'back' => 'خواب‌آلود', 'pronunciation' => '/ˈsliːp.i/'],
            ['front' => 'spicy', 'back' => 'تند', 'pronunciation' => '/ˈspɑɪ.si/'],
            ['front' => 'moody', 'back' => 'دمدمی‌مزاج', 'pronunciation' => '/ˈmudi/'],
            ['front' => 'shrimp', 'back' => 'میگو', 'pronunciation' => '/ʃrɪmp/'],
            ['front' => 'fight', 'back' => 'دعوا کردن', 'pronunciation' => '/fɑɪt/'],
            ['front' => 'nephew', 'back' => 'برادرزاده (مذکر)', 'pronunciation' => '/ˈnɛfju/'],
            ['front' => 'mother', 'back' => 'مادر', 'pronunciation' => '/ˈmʌðər/'],
            ['front' => 'ambitious', 'back' => 'بلندپرواز', 'pronunciation' => '/æmˈbɪʃ.əs/'],
            ['front' => 'canned', 'back' => 'کنسرو شده', 'pronunciation' => '/kænd/'],
            ['front' => 'mango', 'back' => 'انبه', 'pronunciation' => '/ˈmæŋgoʊ/'],
            ['front' => 'stressful', 'back' => 'پراسترس', 'pronunciation' => '/ˈstrɛsfəl/'],
            ['front' => 'sympathetic', 'back' => 'دلسوز', 'pronunciation' => '/ˌsɪmpəˈθɛtɪk/'],
            ['front' => 'aware', 'back' => 'آگاه', 'pronunciation' => '/əˈwɛr/'],
            ['front' => 'imaginative', 'back' => 'با قوه تخیل بالا', 'pronunciation' => '/ɪˈmæʤənətɪv/'],
            ['front' => 'anxious', 'back' => 'مضطرب', 'pronunciation' => '/ˈæŋk.ʃəs/'],
            ['front' => 'grandfather', 'back' => 'پدربزرگ', 'pronunciation' => '/ˈgrændˌfɑðər/'],
            ['front' => 'stepmother', 'back' => 'نامادری', 'pronunciation' => '/ˈstepmʌðər/'],
            ['front' => 'reliable', 'back' => 'قابل‌اطمینان', 'pronunciation' => '/rəˈlɑɪ.ə.bəl/'],
            ['front' => 'no wonder', 'back' => 'بیخود نیست که', 'pronunciation' => '/noʊ ˈwʌndər/'],
            ['front' => 'beet', 'back' => 'چغندر', 'pronunciation' => '/biːt/'],
            ['front' => 'neat', 'back' => 'مرتب و منظم', 'pronunciation' => '/niːt/'],
            ['front' => 'kind', 'back' => 'مهربان', 'pronunciation' => '/kɑɪnd/'],
            ['front' => 'niece', 'back' => 'برادرزاده (مونث)', 'pronunciation' => '/nis/'],
            ['front' => 'carbohydrate', 'back' => 'کربوهیدرات', 'pronunciation' => '/ˌkɑːrboʊˈhaɪdreɪt/'],
            ['front' => 'brother', 'back' => 'برادر', 'pronunciation' => '/ˈbrʌðər/'],
            ['front' => 'selfish', 'back' => 'خودخواه', 'pronunciation' => '/ˈsel.fɪʃ/'],
            ['front' => 'shy', 'back' => 'خجالتی', 'pronunciation' => '/ʃaɪ/'],
            ['front' => 'responsible', 'back' => 'وظیفه‌شناس', 'pronunciation' => '/rɪˈspɑn.sə.bəl/'],
            ['front' => 'child', 'back' => 'کودک', 'pronunciation' => '/tʃɑɪld/'],
            ['front' => 'hardworking', 'back' => 'سخت‌کوش', 'pronunciation' => '/ˈhɑrdwɜrkɪŋ/'],
            ['front' => 'cabbage', 'back' => 'کلم', 'pronunciation' => '/ˈkæb.ɪdʒ/'],
            ['front' => 'smart', 'back' => 'باهوش', 'pronunciation' => '/smɑːrt/'],
            ['front' => 'protein', 'back' => 'پروتئین', 'pronunciation' => '/ˈproʊtiːn/'],
            ['front' => 'fried', 'back' => 'سرخ‌شده', 'pronunciation' => '/frɑɪd/'],
            ['front' => 'mature', 'back' => 'بالغ', 'pronunciation' => '/məˈʧʊr/'],
            ['front' => 'only child', 'back' => 'تک فرزند', 'pronunciation' => '/ˈoʊnli ʧaɪld/'],
            ['front' => 'outgoing', 'back' => 'اجتماعی', 'pronunciation' => '/ˈɑʊtˌgoʊ.ɪŋ/'],
            ['front' => 'sensible', 'back' => 'معقول', 'pronunciation' => '/ˈsensəbl/'],
            ['front' => 'sensitive', 'back' => 'حساس', 'pronunciation' => '/ˈsɛnsətɪv/'],
            ['front' => 'awake', 'back' => 'بیدار', 'pronunciation' => '/əˈweɪk/'],
            ['front' => 'gang', 'back' => 'گروه (جوانان)', 'pronunciation' => '/gæŋ/'],
            ['front' => 'organized', 'back' => 'منظم', 'pronunciation' => '/ˈɔːr.gəˌnɑɪzd/'],
            ['front' => 'self-confident', 'back' => 'بااعتمادبه‌نفس', 'pronunciation' => '/ˌself ˈkɑn.fəd.ənt/'],
            ['front' => 'oily', 'back' => 'چرب و چیلی', 'pronunciation' => '/ˈɔɪli/'],
            ['front' => 'fresh', 'back' => 'تازه', 'pronunciation' => '/freʃ/'],
            ['front' => 'father', 'back' => 'پدر', 'pronunciation' => '/ˈfɑðər/'],
            ['front' => 'messy', 'back' => 'شلخته', 'pronunciation' => '/ˈmes.i/'],
            ['front' => 'roasted', 'back' => 'برشته', 'pronunciation' => '/ˈroʊstɪd/'],
            ['front' => 'sociable', 'back' => 'اجتماعی', 'pronunciation' => '/ˈsoʊ.ʃə.bəl/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 1');
    }

    protected function seedLesson2($deck)
    {
        $vocabulary = [
            ['front' => 'brand', 'back' => 'نشان تجاری', 'pronunciation' => '/brænd /'],
            ['front' => 'paddle', 'back' => 'پارو زدن', 'pronunciation' => '/ˈpædl /'],
            ['front' => 'inherit', 'back' => 'به ارث بردن', 'pronunciation' => '/ɪnˈherɪt /'],
            ['front' => 'headmaster', 'back' => 'مدیر مدرسه', 'pronunciation' => '/ˌhedˈmæstər /'],
            ['front' => 'risky', 'back' => 'پرمخاطره', 'pronunciation' => '/ˈrɪs.ki /'],
            ['front' => 'invest', 'back' => 'سرمایه‌گذاری کردن', 'pronunciation' => '/ɪnˈvɛst /'],
            ['front' => 'worth', 'back' => '(دارای) ارزش', 'pronunciation' => '/wɜrθ /'],
            ['front' => 'principal', 'back' => 'مدیر مدرسه', 'pronunciation' => '/ˈprɪn.sə.pəl /'],
            ['front' => 'forward', 'back' => '(رو به) جلو', 'pronunciation' => '/ˈfɔːr.wərd /'],
            ['front' => 'charge', 'back' => '(هزینه) مطالبه کردن', 'pronunciation' => '/tʃɑːrdʒ /'],
            ['front' => 'hilarious', 'back' => '(خیلی) خنده‌دار', 'pronunciation' => '/hɪˈlɛriəs /'],
            ['front' => 'furious', 'back' => 'غضبناک', 'pronunciation' => '/ˈfjʊr.iː.əs /'],
            ['front' => 'credit card', 'back' => 'کارت اعتباری', 'pronunciation' => '/ˈkred.ɪtˌkɑrd /'],
            ['front' => 'live off', 'back' => 'از لحاظ مالی وابسته کسی بودن', 'pronunciation' => '/lɪv ɔf /'],
            ['front' => 'ATM', 'back' => 'دستگاه خودپرداز', 'pronunciation' => '/ˌeɪ tiː ˈem /'],
            ['front' => 'self-made', 'back' => 'خودساخته', 'pronunciation' => '/ˌself ˈmeɪd /'],
            ['front' => 'sponsor', 'back' => 'حمایت مالی کردن', 'pronunciation' => '/ˈspɑːnsər /'],
            ['front' => 'cash', 'back' => 'پول نقد', 'pronunciation' => '/kæʃ /'],
            ['front' => 'tiny', 'back' => 'کوچک', 'pronunciation' => '/ˈtɑɪ.ni /'],
            ['front' => 'wealthy', 'back' => 'ثروتمند', 'pronunciation' => '/ˈwɛlθi /'],
            ['front' => 'live on', 'back' => '(با میزان معینی پول) زندگی کردن', 'pronunciation' => '/lɪv ɑn /'],
            ['front' => 'bill', 'back' => 'صورت‌حساب', 'pronunciation' => '/bɪl /'],
            ['front' => 'blister', 'back' => 'تاول', 'pronunciation' => '/ˈblɪstər /'],
            ['front' => 'exhausted', 'back' => 'به‌شدت خسته', 'pronunciation' => '/ɪgˈzɑstəd /'],
            ['front' => 'charity', 'back' => 'خیریه (موسسه و سازمان)', 'pronunciation' => '/ˈʧɛrɪti /'],
            ['front' => 'mortgage', 'back' => 'وام مسکن', 'pronunciation' => '/ˈmɔːrɡɪdʒ /'],
            ['front' => 'enormous', 'back' => 'عظیم', 'pronunciation' => '/ɪnˈɔrməs /'],
            ['front' => 'customer', 'back' => 'مشتری', 'pronunciation' => '/ˈkʌs.tə.mər /'],
            ['front' => 'lend', 'back' => 'قرض دادن', 'pronunciation' => '/lɛnd /'],
            ['front' => 'cost', 'back' => 'هزینه داشتن', 'pronunciation' => '/kɔːst /'],
            ['front' => 'fantastic', 'back' => 'خارق‌العاده', 'pronunciation' => '/fænˈtæs.tɪk /'],
            ['front' => 'freezing', 'back' => 'منجمد', 'pronunciation' => '/ˈfriː.zɪŋ /'],
            ['front' => 'salary', 'back' => 'حقوق', 'pronunciation' => '/ˈsæl.ə.ri /'],
            ['front' => 'owe', 'back' => 'بدهکار بودن', 'pronunciation' => '/oʊ /'],
            ['front' => 'filthy', 'back' => '(خیلی) کثیف', 'pronunciation' => '/ˈfɪlθi /'],
            ['front' => 'raise', 'back' => '(پول) جمع کردن', 'pronunciation' => '/reɪz /'],
            ['front' => 'cash machine', 'back' => 'دستگاه خودپرداز', 'pronunciation' => '/ˈkæʃ.məˌʃiːn /'],
            ['front' => 'foot the bill', 'back' => 'پرداخت کردن (صورتحساب یا هزینه)', 'pronunciation' => '/fʊt ðə bɪl /'],
            ['front' => 'entrepreneurial', 'back' => 'کارآفرین', 'pronunciation' => '/ˌɑːntrəprəˈnɜːriəl /'],
            ['front' => 'coin', 'back' => 'سکه', 'pronunciation' => '/kɔɪn /'],
            ['front' => 'boiling', 'back' => 'بسیار گرم', 'pronunciation' => '/ˈbɔɪ.lɪŋ /'],
            ['front' => 'shopping spree', 'back' => 'دوره خرید', 'pronunciation' => '/ˈʃɑpɪŋ spri /'],
            ['front' => 'terrified', 'back' => 'وحشت‌زده', 'pronunciation' => '/ˈter.ə.fɑɪd /'],
            ['front' => 'positive', 'back' => 'مطمئن', 'pronunciation' => '/ˈpɑz.ət̬.ɪv /'],
            ['front' => 'delicious', 'back' => 'خوشمزه', 'pronunciation' => '/dɪˈlɪʃ.əs /'],
            ['front' => 'amazed', 'back' => 'متحیر', 'pronunciation' => '/əˈmeɪzd /'],
            ['front' => 'earn', 'back' => '(پول) در آوردن', 'pronunciation' => '/ɜrn /'],
            ['front' => 'starving', 'back' => 'بسیار گرسنه', 'pronunciation' => '/ˈstɑrv.ɪŋ /'],
            ['front' => 'borrow', 'back' => 'قرض گرفتن', 'pronunciation' => '/ˈbɑr.oʊ /'],
            ['front' => 'tax', 'back' => 'مالیات', 'pronunciation' => '/tæks /'],
            ['front' => 'save', 'back' => 'جمع کردن (پول)', 'pronunciation' => '/seɪv /'],
            ['front' => 'consumer', 'back' => 'مصرف‌کننده', 'pronunciation' => '/kənˈsuːmər /'],
            ['front' => 'free', 'back' => 'رایگان', 'pronunciation' => '/friː /'],
            ['front' => 'rich', 'back' => 'ثروتمند', 'pronunciation' => '/rɪtʃ /'],
            ['front' => 'take out', 'back' => 'برداشت کردن (پول از بانک)', 'pronunciation' => '/teɪk aʊt /'],
            ['front' => 'cynical', 'back' => 'بدبین', 'pronunciation' => '/ˈsɪnɪkəl /'],
            ['front' => 'kayak', 'back' => 'کایاک', 'pronunciation' => '/ˈkaɪæk /'],
            ['front' => 'excited', 'back' => 'هیجان‌زده', 'pronunciation' => '/ɪkˈsaɪtɪd /'],
            ['front' => 'material', 'back' => 'مادی', 'pronunciation' => '/məˈtɪriəl /'],
            ['front' => 'waste', 'back' => 'هدر دادن', 'pronunciation' => '/weɪst /'],
            ['front' => 'ache', 'back' => 'درد', 'pronunciation' => '/eɪk /'],
            ['front' => 'offensive', 'back' => 'توهین‌آمیز', 'pronunciation' => '/əˈfen.sɪv /'],
            ['front' => 'holiday', 'back' => 'روز تعطیل', 'pronunciation' => '/ˈhɑːlədeɪ /'],
            ['front' => 'loan', 'back' => 'وام', 'pronunciation' => '/loʊn /'],
            ['front' => 'low-paying', 'back' => 'کم هزینه', 'pronunciation' => '/loʊ-ˈpeɪɪŋ /'],
            ['front' => 'target', 'back' => 'هدف', 'pronunciation' => '/ˈtɑrgət /'],
            ['front' => 'pay back', 'back' => 'پس دادن (پول)', 'pronunciation' => '/peɪ bæk /'],
            ['front' => 'fee', 'back' => 'دستمزد', 'pronunciation' => '/fiː /'],
            ['front' => 'vacation', 'back' => 'مرخصی', 'pronunciation' => '/veɪˈkeɪʃən /'],
            ['front' => 'melt', 'back' => 'آب شدن', 'pronunciation' => '/mɛlt /'],
            ['front' => 'backer', 'back' => 'حامی', 'pronunciation' => '/ˈbækər /'],
            ['front' => 'rejection', 'back' => 'عدم پذیرش', 'pronunciation' => '/rɪˈdʒekʃn /'],
            ['front' => 'lorry', 'back' => 'کامیون', 'pronunciation' => '/ˈlɔri /'],
            ['front' => 'afford', 'back' => 'بضاعت داشتن', 'pronunciation' => '/əˈfɔːrd /'],
            ['front' => 'billionaire', 'back' => 'میلیاردر', 'pronunciation' => '/ˌbɪljəˈnɛr /'],
            ['front' => 'truck', 'back' => 'کامیون', 'pronunciation' => '/trʌk /'],
            ['front' => 'salesman', 'back' => 'فروشنده مرد', 'pronunciation' => '/ˈseɪlz.mən /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 2');
    }

    protected function seedLesson3($deck)
    {
        $vocabulary = [
            ['front' => 'tend', 'back' => 'نگهداری کردن', 'pronunciation' => '/tɛnd /'],
            ['front' => 'crash', 'back' => 'تصادف', 'pronunciation' => '/kræʃ /'],
            ['front' => 'put on', 'back' => '(آرایش) کردن', 'pronunciation' => '/pʊt ɑn /'],
            ['front' => 'famous', 'back' => 'مشهور', 'pronunciation' => '/ˈfeɪ.məs /'],
            ['front' => 'argue', 'back' => 'بحث کردن', 'pronunciation' => '/ˈɑr.gjuː /'],
            ['front' => 'no-wake zone', 'back' => 'منطقه محدودیت سرعت (وسایل نقلیه آبی)', 'pronunciation' => '/noʊ-weɪk zoʊn /'],
            ['front' => 'angry', 'back' => 'عصبانی', 'pronunciation' => '/ˈæŋ.gri /'],
            ['front' => 'claim', 'back' => 'ادعا کردن', 'pronunciation' => '/kleɪm /'],
            ['front' => 'stereotype', 'back' => 'کلیشه', 'pronunciation' => '/ˈstɛriəˌtaɪp /'],
            ['front' => 'good at', 'back' => 'خوب بودن در', 'pronunciation' => '/gʊd æt /'],
            ['front' => 'look out', 'back' => 'مواظب بودن', 'pronunciation' => '/lʊk aʊt /'],
            ['front' => 'pedestrian zone', 'back' => 'پیاده‌رو', 'pronunciation' => '/pəˈdɛstriən zoʊn /'],
            ['front' => 'belong', 'back' => 'متعلق بودن', 'pronunciation' => '/bəˈlɔːŋ /'],
            ['front' => 'turn', 'back' => '(تبدیل) کردن', 'pronunciation' => '/tɜrn /'],
            ['front' => 'ahead', 'back' => 'جلو', 'pronunciation' => '/əˈhed /'],
            ['front' => 'good for you', 'back' => '(برای سلامتی) خوب است', 'pronunciation' => '/gʊd fɔr ju /'],
            ['front' => 'at', 'back' => 'در (اشاره به مهارت در کاری)', 'pronunciation' => '/æt /'],
            ['front' => 'truck', 'back' => 'کامیون', 'pronunciation' => '/trʌk /'],
            ['front' => 'scooter', 'back' => 'موتور (سیکلت) اسکوتر', 'pronunciation' => '/ˈskuː.t̬ər /'],
            ['front' => 'van', 'back' => 'ون', 'pronunciation' => '/væn /'],
            ['front' => 'about', 'back' => 'درباره', 'pronunciation' => '/əˈbɑʊt /'],
            ['front' => 'close', 'back' => 'صمیمی', 'pronunciation' => '/kloʊz /'],
            ['front' => 'skeptical', 'back' => 'مردد', 'pronunciation' => '/ˈskeptɪkl /'],
            ['front' => 'tired', 'back' => 'خسته', 'pronunciation' => '/tɑɪrd /'],
            ['front' => 'reduce', 'back' => 'کاهش دادن', 'pronunciation' => '/rɪˈduːs /'],
            ['front' => 'taxi stand', 'back' => 'ایستگاه تاکسی', 'pronunciation' => '/ˈtæksi stænd /'],
            ['front' => 'subway', 'back' => 'مترو', 'pronunciation' => '/ˈsʌbweɪ /'],
            ['front' => 'almost', 'back' => 'تقریبا', 'pronunciation' => '/ɒːlˈmoʊst /'],
            ['front' => 'ask for', 'back' => 'درخواست چیزی کردن', 'pronunciation' => '/æsk fɔr /'],
            ['front' => 'traffic light', 'back' => 'چراغ راهنمایی', 'pronunciation' => '/ˈtræf.ɪkˌlaɪt /'],
            ['front' => 'transportation', 'back' => 'حمل‌ونقل', 'pronunciation' => '/ˌtrænspərˈteɪʃən /'],
            ['front' => 'bus stop', 'back' => 'ایستگاه اتوبوس', 'pronunciation' => '/ˈbʌs stɑːp /'],
            ['front' => 'believe in', 'back' => 'اعتقاد داشتن', 'pronunciation' => '/bɪˈliv ɪn /'],
            ['front' => 'traffic jam', 'back' => 'راه‌بندان', 'pronunciation' => '/ˈtræf.ɪkˌdʒæm /'],
            ['front' => 'road work', 'back' => 'عملیات اجرایی و تعمیری در خیابان', 'pronunciation' => '/roʊd wɜrk /'],
            ['front' => 'married to', 'back' => 'همسر', 'pronunciation' => '/ˈmɛrid tu /'],
            ['front' => 'between', 'back' => 'بین', 'pronunciation' => '/bɪˈtwiːn /'],
            ['front' => 'rush hour', 'back' => 'ساعت شلوغی', 'pronunciation' => '/ˈrʌʃ.ɑʊr /'],
            ['front' => 'public transportation', 'back' => 'حمل و نقل عمومی', 'pronunciation' => '/ˌpʌb.lɪk.træn.spɔːrˈteɪ.ʃən /'],
            ['front' => 'child seat', 'back' => 'صندلی ایمنی کودک (خودرو)', 'pronunciation' => '/ʧaɪld sit /'],
            ['front' => 'underground', 'back' => 'مترو', 'pronunciation' => '/ˌʌndərˈɡraʊnd /'],
            ['front' => 'turn around', 'back' => 'روی برگرداندن', 'pronunciation' => '/tɜrn əˈraʊnd /'],
            ['front' => 'crosswalk', 'back' => 'گذرگاه عابر پیاده', 'pronunciation' => '/ˈkrɑˌswɑk /'],
            ['front' => 'happy', 'back' => 'راضی', 'pronunciation' => '/ˈhæp.i /'],
            ['front' => 'seat belt', 'back' => 'کمربند ایمنی (اتومبیل، هواپیما و ...)', 'pronunciation' => '/sit bɛlt /'],
            ['front' => 'mile', 'back' => 'مایل', 'pronunciation' => '/mɑɪl /'],
            ['front' => 'vehicle', 'back' => 'وسیله نقلیه', 'pronunciation' => '/ˈviː.ə.kəl /'],
            ['front' => 'gas station', 'back' => 'جایگاه سوخت', 'pronunciation' => '/ˈgæsˌsteɪ.ʃən /'],
            ['front' => 'set off', 'back' => 'عازم شدن', 'pronunciation' => '/sɛt ɔf /'],
            ['front' => 'slightly', 'back' => 'اندکی', 'pronunciation' => '/ˈslɑɪt.li /'],
            ['front' => 'kilometer', 'back' => 'کیلومتر', 'pronunciation' => '/ˈkɪləmiːtər /'],
            ['front' => 'bus', 'back' => 'اتوبوس', 'pronunciation' => '/bʌs /'],
            ['front' => 'proud', 'back' => 'مفتخر', 'pronunciation' => '/prɑʊd /'],
            ['front' => 'speed camera', 'back' => 'دوربین کنترل سرعت', 'pronunciation' => '/spid ˈkæmərə /'],
            ['front' => 'whereas', 'back' => 'در حالی که', 'pronunciation' => '/werˈæz /'],
            ['front' => 'pay', 'back' => 'پرداخت کردن', 'pronunciation' => '/peɪ /'],
            ['front' => 'adjust', 'back' => 'تنظیم کردن', 'pronunciation' => '/əˈʤʌst /'],
            ['front' => 'pick up', 'back' => 'به دنبال رفتن', 'pronunciation' => '/pɪk ʌp /'],
            ['front' => 'parking ticket', 'back' => 'جریمه پارک غیر قانونی (اتومبیل)', 'pronunciation' => '/ˈpɑrkɪŋ ˈtɪkət /'],
            ['front' => 'freeway', 'back' => 'آزادراه', 'pronunciation' => '/ˈfriˌweɪ /'],
            ['front' => 'according to', 'back' => 'طبق', 'pronunciation' => '/əˈkɔːrd.ɪŋ.tuː /'],
            ['front' => 'speed limit', 'back' => 'سرعت مجاز', 'pronunciation' => '/spid ˈlɪmət /'],
            ['front' => 'remind', 'back' => 'به یاد چیزی یا کسی انداختن', 'pronunciation' => '/rɪˈmaɪnd /'],
            ['front' => 'kind', 'back' => 'مهربان', 'pronunciation' => '/kɑɪnd /'],
            ['front' => 'interested', 'back' => 'علاقه‌مند', 'pronunciation' => '/ˈɪn.trə.stəd /'],
            ['front' => 'spend', 'back' => 'خرج کردن', 'pronunciation' => '/spend /'],
            ['front' => 'depend', 'back' => 'بستگی داشتن', 'pronunciation' => '/dəˈpend /'],
            ['front' => 'different', 'back' => 'متفاوت', 'pronunciation' => '/ˈdɪf.rənt /'],
            ['front' => 'rude', 'back' => 'بی‌ادب', 'pronunciation' => '/rud /'],
            ['front' => 'seaplane', 'back' => 'هواپیمای آب‌نشین', 'pronunciation' => '/ˈsiːpleɪn /'],
            ['front' => 'crash into', 'back' => 'به چیزی زدن (با خودرو)', 'pronunciation' => '/kræʃ ˈɪntu /'],
            ['front' => 'afraid', 'back' => 'ترسیده', 'pronunciation' => '/əˈfreɪd /'],
            ['front' => 'worried', 'back' => 'نگران', 'pronunciation' => '/ˈwɜːrid /'],
            ['front' => 'end up', 'back' => 'کار به جایی رسیدن', 'pronunciation' => '/ɛnd ʌp /'],
            ['front' => 'in fact', 'back' => 'در حقیقت', 'pronunciation' => '/ɪn fækt /'],
            ['front' => 'train', 'back' => 'قطار', 'pronunciation' => '/treɪn /'],
            ['front' => 'apologize', 'back' => 'عذرخواهی کردن', 'pronunciation' => '/əˈpɑl.əˌdʒɑɪz /'],
            ['front' => 'stuck', 'back' => 'گیرکرده', 'pronunciation' => '/stʌk /'],
            ['front' => 'reach', 'back' => 'رسیدن', 'pronunciation' => '/riːtʃ /'],
            ['front' => 'laugh', 'back' => 'خندیدن', 'pronunciation' => '/læf /'],
            ['front' => 'run out', 'back' => 'تمام شدن', 'pronunciation' => '/rʌn aʊt /'],
            ['front' => 'worse', 'back' => 'بدتر', 'pronunciation' => '/wɜːrs /'],
            ['front' => 'bicycle lane', 'back' => 'مسیر دوچرخه', 'pronunciation' => '/ˈbaɪsɪkəl leɪn /'],
            ['front' => 'excited', 'back' => 'هیجان‌زده', 'pronunciation' => '/ɪkˈsaɪtɪd /'],
            ['front' => 'light rail', 'back' => 'قطار سبک شهری', 'pronunciation' => '/laɪt reɪl /'],
            ['front' => 'arrive', 'back' => 'رسیدن', 'pronunciation' => '/əˈrɑɪv /'],
            ['front' => 'GPS', 'back' => 'جی‌پی‌اس', 'pronunciation' => '/ʤi-pi-ɛs /'],
            ['front' => 'look forward to', 'back' => '(بی‌صبرانه) در انتظار (چیزی) بودن', 'pronunciation' => '/lʊk ˈfɔrwərd tu /'],
            ['front' => 'watch out', 'back' => 'مراقب بودن', 'pronunciation' => '/wɑʧ aʊt /'],
            ['front' => 'range', 'back' => 'متغیر بودن', 'pronunciation' => '/reɪnʤ /'],
            ['front' => 'platform', 'back' => 'سکو', 'pronunciation' => '/ˈplæt.fɔːrm /'],
            ['front' => 'do', 'back' => 'درست کردن (مو)', 'pronunciation' => '/du /'],
            ['front' => 'fed up', 'back' => 'خسته', 'pronunciation' => '/ˌfedˈʌp /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 3');
    }

    protected function seedLesson4($deck)
    {
        $vocabulary = [
            ['front' => 'step', 'back' => 'حرکت (رقص)', 'pronunciation' => '/step/'],
            ['front' => 'dial', 'back' => 'شماره گرفتن', 'pronunciation' => '/dɑɪl/'],
            ['front' => 'quiet zone', 'back' => 'منطقه بدون آنتن دهی (تلفن همراه)', 'pronunciation' => '/ˈkwaɪət zoʊn/'],
            ['front' => 'behave', 'back' => 'مؤدب بودن', 'pronunciation' => '/bəˈheɪv/'],
            ['front' => 'instant messaging', 'back' => 'پیام‌رسانی فوری', 'pronunciation' => '/ˌɪnstənt ˈmesɪdʒɪŋ/'],
            ['front' => 'leave a message', 'back' => 'پیغام گذاشتن', 'pronunciation' => '/liv ə ˈmɛsəʤ/'],
            ['front' => 'deserve', 'back' => 'سزاوار بودن', 'pronunciation' => '/dɪˈzɜrv/'],
            ['front' => 'text', 'back' => 'پیام دادن (از طریق موبایل)', 'pronunciation' => '/tekst/'],
            ['front' => 'disturb', 'back' => 'مزاحم شدن', 'pronunciation' => '/dɪˈstɜrb/'],
            ['front' => 'voicemail', 'back' => 'پست صوتی', 'pronunciation' => '/ˈvɔɪˌsmeɪl/'],
            ['front' => 'teach yourself book', 'back' => 'کتاب خودآموز', 'pronunciation' => '/tiʧ jərˈsɛlf bʊk/'],
            ['front' => 'multilingual', 'back' => 'چندزبانه', 'pronunciation' => '/ˌmʌltiˈlɪŋɡwəl/'],
            ['front' => 'silent mode', 'back' => 'حالت بی‌صدا (تلفن همراه)', 'pronunciation' => '/ˈsaɪlənt moʊd/'],
            ['front' => 'link', 'back' => 'متصل کردن', 'pronunciation' => '/lɪŋk/'],
            ['front' => 'inappropriate', 'back' => 'نامناسب', 'pronunciation' => '/ˌɪnəˈproʊpriɪt/'],
            ['front' => 'fluently', 'back' => 'فصیحانه', 'pronunciation' => '/ˈfluː.ənt.li/'],
            ['front' => 'insulting', 'back' => 'توهین‌آمیز', 'pronunciation' => '/ɪnˈsʌltɪŋ/'],
            ['front' => 'allergic', 'back' => 'حساسیت (به چیزی)', 'pronunciation' => '/əˈlɜrʤɪk/'],
            ['front' => 'basic', 'back' => 'ساده', 'pronunciation' => '/ˈbeɪ.sɪk/'],
            ['front' => 'phrase', 'back' => 'جمله‌واره', 'pronunciation' => '/freɪz/'],
            ['front' => 'message', 'back' => 'پیام دادن (از طریق موبایل)', 'pronunciation' => '/ˈmes.ɪdʒ/'],
            ['front' => 'vibrate mode', 'back' => 'حالت لرزش (تلفن همراه)', 'pronunciation' => '/ˈvaɪbreɪt moʊd/'],
            ['front' => 'busy', 'back' => 'اشغال (خط تلفن)', 'pronunciation' => '/ˈbɪz.i/'],
            ['front' => 'hang up', 'back' => '(تلفن را) قطع کردن', 'pronunciation' => '/hæŋ ʌp/'],
            ['front' => 'bored', 'back' => 'کسل', 'pronunciation' => '/bɔrd/'],
            ['front' => 'ringtone', 'back' => 'آهنگ زنگ (موبایل)', 'pronunciation' => '/ˈrɪŋtoʊn/'],
            ['front' => 'etiquette', 'back' => 'آداب', 'pronunciation' => '/ˈɛtəkət/'],
            ['front' => 'Skype', 'back' => 'اسکایپ', 'pronunciation' => '/skaɪp/'],
            ['front' => 'boring', 'back' => 'خسته‌کننده', 'pronunciation' => '/ˈbɔːrɪŋ/'],
            ['front' => 'scuba dive', 'back' => 'غواصی با دستگاه اکسیژن', 'pronunciation' => '/ˈskubə daɪv/'],
            ['front' => 'frustrated', 'back' => 'درمانده', 'pronunciation' => '/ˈfrʌˌstreɪtəd/'],
            ['front' => 'call back', 'back' => '(در جواب تماس ازدست‌رفته کسی) با کسی تماس گرفتن', 'pronunciation' => '/kɔl bæk/'],
            ['front' => 'skill', 'back' => 'مهارت', 'pronunciation' => '/skɪl/'],
            ['front' => 'frustrating', 'back' => 'آزاردهنده', 'pronunciation' => '/ˈfrʌˌstreɪtɪŋ/'],
            ['front' => 'manners', 'back' => 'ادب', 'pronunciation' => '/ˈmænərz/'],
            ['front' => 'language barrier', 'back' => 'مانع زبانی', 'pronunciation' => '/ˈlæŋgwəʤ ˈbæriər/'],
            ['front' => 'host', 'back' => 'میزبان', 'pronunciation' => '/hoʊst/'],
            ['front' => 'hostess', 'back' => 'میزبان (زن)', 'pronunciation' => '/ˈhoʊstəs/'],
            ['front' => 'screen saver', 'back' => 'محافظ صفحه نمایش (کامپیوتر)', 'pronunciation' => '/ˈskriːn seɪvər/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 4');
    }

    protected function seedLesson5($deck)
    {
        $vocabulary = [
            ['front' => 'get along', 'back' => 'کنار آمدن', 'pronunciation' => '/gɛt əˈlɔŋ/'],
            ['front' => 'score', 'back' => 'امتیاز کسب کردن', 'pronunciation' => '/skɔːr/'],
            ['front' => 'partner', 'back' => 'شریک (زندگی)', 'pronunciation' => '/ˈpɑrt.nər/'],
            ['front' => 'colleague', 'back' => 'همکار', 'pronunciation' => '/ˈkɑlig/'],
            ['front' => 'track', 'back' => 'زمین (مسابقه)', 'pronunciation' => '/træk/'],
            ['front' => 'sweat', 'back' => 'عرق', 'pronunciation' => '/swet/'],
            ['front' => 'propose', 'back' => 'خواستگاری کردن', 'pronunciation' => '/prəˈpoʊz/'],
            ['front' => 'get in touch', 'back' => 'در تماس بودن', 'pronunciation' => '/gɛt ɪn tʌʧ/'],
            ['front' => 'kick', 'back' => 'شوت کردن', 'pronunciation' => '/kɪk/'],
            ['front' => 'addicted', 'back' => 'معتاد', 'pronunciation' => '/əˈdɪk.tɪd/'],
            ['front' => 'lucky charm', 'back' => 'افسون خوش شانسی', 'pronunciation' => '/ˈlʌki ʧɑrm/'],
            ['front' => 'superstition', 'back' => 'خرافه', 'pronunciation' => '/ˌsuːpərˈstɪʃn/'],
            ['front' => 'sports arena', 'back' => 'زمین ورزشی', 'pronunciation' => '/spɔrts əˈrinə/'],
            ['front' => 'buddy', 'back' => 'رفیق', 'pronunciation' => '/ˈbʌdi/'],
            ['front' => 'shift', 'back' => 'شیفت', 'pronunciation' => '/ʃɪft/'],
            ['front' => 'get injured', 'back' => 'مصدوم شدن', 'pronunciation' => '/gɛt ˈɪnʤərd/'],
            ['front' => 'result', 'back' => 'حاصل شدن', 'pronunciation' => '/rɪˈzʌlt/'],
            ['front' => 'be into', 'back' => 'علاقه داشتن', 'pronunciation' => '/bi ˈɪntu/'],
            ['front' => 'pool', 'back' => 'استخر', 'pronunciation' => '/puːl/'],
            ['front' => 'crowd', 'back' => 'جمعیت', 'pronunciation' => '/krɑʊd/'],
            ['front' => 'couple', 'back' => 'زوج', 'pronunciation' => '/ˈkʌpəl/'],
            ['front' => 'captain', 'back' => 'کاپیتان (تیم ورزشی)', 'pronunciation' => '/ˈkæp.tən/'],
            ['front' => 'win', 'back' => 'پیروز شدن', 'pronunciation' => '/wɪn/'],
            ['front' => 'ex', 'back' => 'همسر سابق', 'pronunciation' => '/eks/'],
            ['front' => 'coach', 'back' => 'مربی', 'pronunciation' => '/koʊtʃ/'],
            ['front' => 'get married', 'back' => 'ازدواج کردن', 'pronunciation' => '/gɛt ˈmærɪd/'],
            ['front' => 'beat', 'back' => 'شکست دادن', 'pronunciation' => '/biːt/'],
            ['front' => 'classmate', 'back' => 'هم‌کلاسی', 'pronunciation' => '/ˈklæsmeɪt/'],
            ['front' => 'get to know', 'back' => '(کسی/چیزی را) شناختن', 'pronunciation' => '/gɛt tu noʊ/'],
            ['front' => 'turn out', 'back' => 'از آب درآمدن', 'pronunciation' => '/tɜrn aʊt/'],
            ['front' => 'fan', 'back' => 'طرفدار', 'pronunciation' => '/fæn/'],
            ['front' => 'get in shape', 'back' => 'روی فرم آمدن (بدن)', 'pronunciation' => '/gɛt ɪn ʃeɪp/'],
            ['front' => 'slope', 'back' => 'شیب', 'pronunciation' => '/sloʊp/'],
            ['front' => 'exchange', 'back' => 'ردوبدل کردن', 'pronunciation' => '/ɪksˈtʃeɪndʒ/'],
            ['front' => 'warm up', 'back' => 'گرم کردن (تمرین ورزشی)', 'pronunciation' => '/wɔrm ʌp/'],
            ['front' => 'player', 'back' => 'بازیکن', 'pronunciation' => '/ˈpleɪ.ər/'],
            ['front' => 'dump', 'back' => 'ول کردن', 'pronunciation' => '/dʌmp/'],
            ['front' => 'referee', 'back' => 'داور', 'pronunciation' => '/ˌref.əˈriː/'],
            ['front' => 'courage', 'back' => 'شجاعت', 'pronunciation' => '/ˈkɜr.ɪdʒ/'],
            ['front' => 'shoelace', 'back' => 'بند کفش', 'pronunciation' => '/ˈʃuːleɪs/'],
            ['front' => 'crush', 'back' => 'علاقه', 'pronunciation' => '/krʌʃ/'],
            ['front' => 'go out', 'back' => 'رابطه (رمانتیک) داشتن', 'pronunciation' => '/goʊ ɑʊt/'],
            ['front' => 'umpire', 'back' => 'داور', 'pronunciation' => '/ˈʌmpaɪər/'],
            ['front' => 'candle', 'back' => 'شمع', 'pronunciation' => '/ˈkæn.dəl/'],
            ['front' => 'be together', 'back' => 'با هم رابطه داشتن (زن و مرد)', 'pronunciation' => '/bi təˈgɛðər/'],
            ['front' => 'commuter', 'back' => 'مسافر (هر روزه)', 'pronunciation' => '/kəmˈjutər/'],
            ['front' => 'split up', 'back' => 'جدا شدن', 'pronunciation' => '/splɪt ʌp/'],
            ['front' => 'fate', 'back' => 'سرنوشت', 'pronunciation' => '/feɪt/'],
            ['front' => 'work out', 'back' => 'بدنسازی کردن', 'pronunciation' => '/wɜrk aʊt/'],
            ['front' => 'course', 'back' => 'زمین (گلف و...)', 'pronunciation' => '/kɔːrs/'],
            ['front' => 'spectator', 'back' => 'تماشاچی', 'pronunciation' => '/ˈspɛkteɪtər/'],
            ['front' => 'have something in common', 'back' => 'در چیزی تفاهم داشتن', 'pronunciation' => '/hæv ˈsʌmθɪŋ ɪn ˈkɑmən/'],
            ['front' => 'court', 'back' => 'زمین بازی (تنیس، والیبال، بسکتبال و ...)', 'pronunciation' => '/kɔːrt/'],
            ['front' => 'knock out', 'back' => 'حذف کردن (از مسابقه)', 'pronunciation' => '/nɑk aʊt/'],
            ['front' => 'go swimming', 'back' => 'شنا کردن', 'pronunciation' => '/goʊ ˈswɪmɪŋ/'],
            ['front' => 'team', 'back' => 'تیم (ورزشی و...)', 'pronunciation' => '/tiːm/'],
            ['front' => 'ritual', 'back' => 'مناسک', 'pronunciation' => '/ˈrɪʧuəl/'],
            ['front' => 'field', 'back' => 'زمین (ورزش و ...)', 'pronunciation' => '/fiːld/'],
            ['front' => 'lose touch', 'back' => 'رابطه با کسی را از دست دادن', 'pronunciation' => '/luz tʌʧ/'],
            ['front' => 'fiancé', 'back' => 'نامزد (مذکر)', 'pronunciation' => '/ˌfiːɑːnˈseɪ/'],
            ['front' => 'lose', 'back' => 'باختن', 'pronunciation' => '/luːz/'],
            ['front' => 'become friends', 'back' => 'دوست شدن', 'pronunciation' => '/bɪˈkʌm frɛndz/'],
            ['front' => 'cute', 'back' => 'ناز', 'pronunciation' => '/kjuːt/'],
            ['front' => 'stadium', 'back' => 'ورزشگاه', 'pronunciation' => '/ˈsteɪdiːəm/'],
            ['front' => 'do yoga', 'back' => 'ورزش یوگا انجام دادن', 'pronunciation' => '/du ˈjoʊgə/'],
            ['front' => 'fiancée', 'back' => 'نامزد (مونث)', 'pronunciation' => '/ˌfiːɑːnˈseɪ/'],
            ['front' => 'bounce', 'back' => 'جهیدن', 'pronunciation' => '/baʊns/'],
            ['front' => 'tie', 'back' => 'مساوی شدن (در مسابقه)', 'pronunciation' => '/taɪ/'],
            ['front' => 'break up', 'back' => 'بهم زدن (رابطه عاشقانه)', 'pronunciation' => '/breɪk ʌp/'],
            ['front' => 'cheat', 'back' => 'خیانت کردن', 'pronunciation' => '/ʧit/'],
            ['front' => 'throw', 'back' => 'پرتاب کردن', 'pronunciation' => '/θroʊ/'],
            ['front' => 'reveal', 'back' => 'آشکار کردن', 'pronunciation' => '/rɪˈvil/'],
            ['front' => 'train', 'back' => 'تمرین کردن', 'pronunciation' => '/treɪn/'],
            ['front' => 'likely', 'back' => 'احتمالاً', 'pronunciation' => '/ˈlɑɪ.kli/'],
            ['front' => 'roommate', 'back' => 'هم اتاقی', 'pronunciation' => '/ˈruːm.meɪt/'],
            ['front' => 'close', 'back' => 'صمیمی', 'pronunciation' => '/kloʊz/'],
            ['front' => 'meet', 'back' => 'ملاقات کردن', 'pronunciation' => '/miːt/'],
            ['front' => 'tollbooth', 'back' => 'باجه اخذ عوارض (جاده)', 'pronunciation' => '/ˈtoʊlbuːθ/'],
            ['front' => 'go out with', 'back' => 'با کسی قرار عاشقانه گذاشتن', 'pronunciation' => '/goʊ aʊt wɪð/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 5');
    }

    protected function seedLesson6($deck)
    {
        $vocabulary = [
            ['front' => 'scary', 'back' => 'ترسناک', 'pronunciation' => '/ˈskɛri /'],
            ['front' => 'smell', 'back' => 'بو کردن', 'pronunciation' => '/smel /'],
            ['front' => 'historical movie', 'back' => 'فیلم تاریخی', 'pronunciation' => '/hɪˈstɔrɪkəl ˈmuvi /'],
            ['front' => 'shoulder', 'back' => 'شانه', 'pronunciation' => '/ˈʃoʊldər /'],
            ['front' => 'smile', 'back' => 'لبخند زدن', 'pronunciation' => '/smaɪl /'],
            ['front' => 'clap', 'back' => 'دست زدن', 'pronunciation' => '/klæp /'],
            ['front' => 'stomach', 'back' => 'شکم (کالبدشناسی)', 'pronunciation' => '/ˈstʌmək /'],
            ['front' => 'spectacular', 'back' => 'تماشایی', 'pronunciation' => '/spɛkˈtækjələr /'],
            ['front' => 'stare', 'back' => 'زل زدن', 'pronunciation' => '/steər /'],
            ['front' => 'ear', 'back' => 'گوش', 'pronunciation' => '/ɪr /'],
            ['front' => 'tooth', 'back' => 'دندان', 'pronunciation' => '/tuθ /'],
            ['front' => 'kick', 'back' => 'شوت کردن', 'pronunciation' => '/kɪk /'],
            ['front' => 'currently', 'back' => 'در حال حاضر', 'pronunciation' => '/ˈkɜr.ənt.li /'],
            ['front' => 'mouth', 'back' => 'دهان', 'pronunciation' => '/mɑʊθ /'],
            ['front' => 'toe', 'back' => 'انگشت پا', 'pronunciation' => '/toʊ /'],
            ['front' => 'eye', 'back' => 'چشم', 'pronunciation' => '/ɑɪ /'],
            ['front' => 'carefree', 'back' => 'بی‌خیال', 'pronunciation' => '/ˈkɛrˌfri /'],
            ['front' => 'neck', 'back' => 'گردن', 'pronunciation' => '/nek /'],
            ['front' => 'direct', 'back' => 'کارگردانی کردن', 'pronunciation' => '/dəˈrekt /'],
            ['front' => 'drama', 'back' => 'درام', 'pronunciation' => '/ˈdrɑmə /'],
            ['front' => 'war movie', 'back' => 'فیلم جنگی', 'pronunciation' => '/wɔr ˈmuvi /'],
            ['front' => 'set', 'back' => 'رخ دادن', 'pronunciation' => '/set /'],
            ['front' => 'face', 'back' => 'صورت', 'pronunciation' => '/feɪs /'],
            ['front' => 'tongue', 'back' => 'زبان (عضو دهان)', 'pronunciation' => '/tʌŋ /'],
            ['front' => 'take seriously', 'back' => 'جدی گرفتن', 'pronunciation' => '/teɪk ˈsɪriəsli /'],
            ['front' => 'location', 'back' => 'لوکیشن', 'pronunciation' => '/loʊˈkeɪʃn /'],
            ['front' => 'audience', 'back' => 'حضار', 'pronunciation' => '/ɔːd.iː.əns /'],
            ['front' => 'action movie', 'back' => 'فیلم اکشن', 'pronunciation' => '/ˈækʃən ˈmuvi /'],
            ['front' => 'aristocratic', 'back' => 'اشرافی', 'pronunciation' => '/əˌrɪstəˈkrætɪk /'],
            ['front' => 'romantic comedy', 'back' => 'کمدی عاشقانه (ژانر فیلم)', 'pronunciation' => '/roʊˈmæntɪk ˈkɑmədi /'],
            ['front' => 'vitally', 'back' => 'به شدت', 'pronunciation' => '/ˈvaɪtəli /'],
            ['front' => 'gangster', 'back' => 'گانگستر', 'pronunciation' => '/ˈɡæŋstər /'],
            ['front' => 'on', 'back' => 'از (تلویزیون، رادیو و ...)', 'pronunciation' => '/ɔːn /'],
            ['front' => 'special effects', 'back' => 'جلوه‌های ویژه', 'pronunciation' => '/ˌspeʃl ɪˈfekts /'],
            ['front' => 'head', 'back' => 'سر', 'pronunciation' => '/hed /'],
            ['front' => 'western', 'back' => '(فیلم) وسترن', 'pronunciation' => '/ˈwestərn /'],
            ['front' => 'servant', 'back' => 'خدمتکار', 'pronunciation' => '/ˈsɜr.vənt /'],
            ['front' => 'alley', 'back' => 'کوچه', 'pronunciation' => '/ˈæli /'],
            ['front' => 'nose', 'back' => 'بینی', 'pronunciation' => '/noʊz /'],
            ['front' => 'star', 'back' => 'ستاره', 'pronunciation' => '/stɑr /'],
            ['front' => 'review', 'back' => 'نقد', 'pronunciation' => '/rɪˈvjuː /'],
            ['front' => 'knee', 'back' => 'زانو', 'pronunciation' => '/niː /'],
            ['front' => 'funny', 'back' => 'بامزه', 'pronunciation' => '/ˈfʌni /'],
            ['front' => 'base on', 'back' => 'بر اساس چیزی بودن', 'pronunciation' => '/beɪs ɑn /'],
            ['front' => 'stage', 'back' => 'صحنه (تئاتر و...)', 'pronunciation' => '/steɪdʒ /'],
            ['front' => 'leg', 'back' => 'پا', 'pronunciation' => '/leg /'],
            ['front' => 'set an example', 'back' => 'الگو بودن', 'pronunciation' => '/sɛt ən ɪgˈzæmpəl /'],
            ['front' => 'lip', 'back' => 'لب', 'pronunciation' => '/lɪp /'],
            ['front' => 'moving', 'back' => 'تکان‌دهنده', 'pronunciation' => '/ˈmuːvɪŋ /'],
            ['front' => 'achieve', 'back' => 'رسیدن (به هدف)', 'pronunciation' => '/əˈtʃiːv /'],
            ['front' => 'arm', 'back' => 'بازو', 'pronunciation' => '/ɑrm /'],
            ['front' => 'go viral', 'back' => 'پربیننده شدن (ویدیوهای اینترنتی)', 'pronunciation' => '/goʊ ˈvaɪrəl /'],
            ['front' => 'dub', 'back' => 'دوبله کردن', 'pronunciation' => '/dʌb /'],
            ['front' => 'dye', 'back' => '(مو و ...) رنگ کردن', 'pronunciation' => '/daɪ /'],
            ['front' => 'foot', 'back' => 'پا (از انگشت‌ها تا مچ)', 'pronunciation' => '/fʊt /'],
            ['front' => 'shoot', 'back' => 'فیلمبرداری کردن', 'pronunciation' => '/ʃuːt /'],
            ['front' => 'back', 'back' => 'پشت', 'pronunciation' => '/bæk /'],
            ['front' => 'grow up', 'back' => 'بزرگ شدن', 'pronunciation' => '/groʊ ʌp /'],
            ['front' => 'finger', 'back' => 'انگشت (دست)', 'pronunciation' => '/ˈfɪŋgər /'],
            ['front' => 'judge', 'back' => 'قضاوت کردن', 'pronunciation' => '/ʤʌʤ /'],
            ['front' => 'nod', 'back' => 'سر تکان دادن', 'pronunciation' => '/nɑd /'],
            ['front' => 'plot', 'back' => 'پیرنگ', 'pronunciation' => '/plɑːt /'],
            ['front' => 'hand', 'back' => 'دست', 'pronunciation' => '/hænd /'],
            ['front' => 'tomb', 'back' => 'مقبره', 'pronunciation' => '/tuːm /'],
            ['front' => 'point', 'back' => 'اشاره کردن', 'pronunciation' => '/pɔɪnt /'],
            ['front' => 'scene', 'back' => 'منظره', 'pronunciation' => '/siːn /'],
            ['front' => 'script', 'back' => 'فیلمنامه', 'pronunciation' => '/skrɪpt /'],
            ['front' => 'fictional', 'back' => 'خیالی', 'pronunciation' => '/ˈfɪkʃənəl /'],
            ['front' => 'comedy', 'back' => 'نمایش خنده‌دار', 'pronunciation' => '/ˈkɑmədi /'],
            ['front' => 'subtitle', 'back' => 'زیرنویس', 'pronunciation' => '/ˈsʌbtaɪtl /'],
            ['front' => 'science fiction movie', 'back' => 'فیلم علمی تخیلی', 'pronunciation' => '/ˈsaɪəns ˈfɪkʃən ˈmuvi /'],
            ['front' => 'taste', 'back' => 'مزه کردن', 'pronunciation' => '/teɪst /'],
            ['front' => 'film', 'back' => 'فیلم', 'pronunciation' => '/fɪlm /'],
            ['front' => 'horror movie', 'back' => 'فیلم ترسناک', 'pronunciation' => '/ˈhɔrər ˈmuvi /'],
            ['front' => 'throw', 'back' => 'پرتاب کردن', 'pronunciation' => '/θroʊ /'],
            ['front' => 'thriller', 'back' => '(فیلم یا رمان) مهیج', 'pronunciation' => '/ˈθrɪlər /'],
            ['front' => 'movie', 'back' => 'فیلم', 'pronunciation' => '/ˈmuː.vi /'],
            ['front' => 'sequel', 'back' => 'دنباله', 'pronunciation' => '/ˈsiːkwəl /'],
            ['front' => 'touch', 'back' => 'لمس کردن', 'pronunciation' => '/tʌtʃ /'],
            ['front' => 'musical', 'back' => 'نمایش موزیکال', 'pronunciation' => '/ˈmjuː.zɪ.kəl /'],
            ['front' => 'play the part of', 'back' => 'نقش کسی را بازی کردن', 'pronunciation' => '/pleɪ ðə pɑrt ʌv /'],
            ['front' => 'soundtrack', 'back' => 'موسیقی متن', 'pronunciation' => '/ˈsaʊndtræk /'],
            ['front' => 'whistle', 'back' => 'سوت زدن', 'pronunciation' => '/ˈwɪs.l /'],
            ['front' => 'violent', 'back' => 'خشن', 'pronunciation' => '/ˈvaɪələnt /'],
            ['front' => 'cast', 'back' => 'هنرپیشگان', 'pronunciation' => '/kæst /'],
            ['front' => 'bite', 'back' => 'گاز گرفتن', 'pronunciation' => '/bɑɪt /'],
            ['front' => 'animated movie', 'back' => 'انیمیشن', 'pronunciation' => '/ˈænəˌmeɪtəd ˈmuvi /'],
            ['front' => 'exciting', 'back' => 'هیجان‌انگیز', 'pronunciation' => '/ɪkˈsaɪtɪŋ /'],
            ['front' => 'extra', 'back' => 'سیاهی لشکر', 'pronunciation' => '/ˈek.strə /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 6');
    }

    protected function seedLesson7($deck)
    {
        $vocabulary = [
            ['front' => 'wood floor', 'back' => 'کف چوبی', 'pronunciation' => '/wʊd flɔr/'],
            ['front' => 'information technology', 'back' => 'فناوری اطلاعات', 'pronunciation' => '/ˌɪnfərˈmeɪʃən tɛkˈnɑləʤi/'],
            ['front' => 'modern', 'back' => 'مدرن', 'pronunciation' => '/ˈmɑːdərn/'],
            ['front' => 'suspend', 'back' => '(موقتاً) اخراج کردن', 'pronunciation' => '/səˈspend/'],
            ['front' => 'twelfth', 'back' => 'دوازدهم', 'pronunciation' => '/twelfθ/'],
            ['front' => 'private school', 'back' => 'مدرسه غیرانتفاعی', 'pronunciation' => '/ˈpraɪvət skuːl/'],
            ['front' => 'literature', 'back' => 'ادبیات', 'pronunciation' => '/ˈlɪt̬.ə.rə.tʃər/'],
            ['front' => 'cheat', 'back' => 'تقلب کردن', 'pronunciation' => '/ʧit/'],
            ['front' => 'city', 'back' => 'شهر', 'pronunciation' => '/ˈsɪt̬.i/'],
            ['front' => 'grade', 'back' => 'کلاس', 'pronunciation' => '/greɪd/'],
            ['front' => 'boarding school', 'back' => 'مدرسه شبانه روزی', 'pronunciation' => '/ˈbɔːrdɪŋ skuːl/'],
            ['front' => 'required', 'back' => 'ضروری', 'pronunciation' => '/riˈkwaɪərd/'],
            ['front' => 'house', 'back' => 'خانه', 'pronunciation' => '/hɑʊs/'],
            ['front' => 'overlook', 'back' => 'چشم‌انداز داشتن', 'pronunciation' => '/ˈoʊvərˌlʊk/'],
            ['front' => 'biology', 'back' => 'زیست شناسی', 'pronunciation' => '/bɑɪˈɑl.ə.dʒi/'],
            ['front' => 'math', 'back' => 'ریاضی', 'pronunciation' => '/mæθ/'],
            ['front' => 'fail', 'back' => 'رد شدن (در امتحان)', 'pronunciation' => '/feɪl/'],
            ['front' => 'sofa', 'back' => 'مبل راحتی', 'pronunciation' => '/ˈsoʊfə/'],
            ['front' => 'chemistry', 'back' => 'شیمی', 'pronunciation' => '/ˈkem.ə.stri/'],
            ['front' => 'physics', 'back' => 'فیزیک', 'pronunciation' => '/ˈfɪz.ɪks/'],
            ['front' => 'washing machine', 'back' => 'ماشین لباسشویی', 'pronunciation' => '/ˈwɑʃ.ɪŋ.məˌʃiːn/'],
            ['front' => 'pupil', 'back' => 'دانش‌آموز', 'pronunciation' => '/ˈpjuːpl/'],
            ['front' => 'pass', 'back' => 'با موفقیت گذراندن', 'pronunciation' => '/pæs/'],
            ['front' => 'graduate', 'back' => 'فارغ‌التحصیل شدن', 'pronunciation' => '/ˈgrædʒʊət/'],
            ['front' => 'forbidden', 'back' => 'ممنوع', 'pronunciation' => '/fərˈbɪd.ən/'],
            ['front' => 'patio', 'back' => 'پاسیو', 'pronunciation' => '/ˈpætioʊ/'],
            ['front' => 'remain', 'back' => 'ماندن', 'pronunciation' => '/rɪˈmeɪn/'],
            ['front' => 'secondary school', 'back' => 'دبیرستان', 'pronunciation' => '/ˈsek.ən.der.iˌskuːl/'],
            ['front' => 'lamp', 'back' => 'چراغ', 'pronunciation' => '/læmp/'],
            ['front' => 'outstanding', 'back' => 'عالی', 'pronunciation' => '/ɑʊtˈstæn.dɪŋ/'],
            ['front' => 'learn', 'back' => 'یاد گرفتن', 'pronunciation' => '/lɜːrn/'],
            ['front' => 'prodigy', 'back' => '(کودک یا نوجوان) نابغه', 'pronunciation' => '/ˈprɑːdədʒi/'],
            ['front' => 'term', 'back' => 'دوره', 'pronunciation' => '/tɜrm/'],
            ['front' => 'settle', 'back' => 'سکنی گزیدن', 'pronunciation' => '/ˈsɛtəl/'],
            ['front' => 'spacious', 'back' => 'جادار', 'pronunciation' => '/ˈspeɪ.ʃəs/'],
            ['front' => 'determined', 'back' => 'مصمم', 'pronunciation' => '/dɪˈtɝmɪnd/'],
            ['front' => 'high school', 'back' => 'دبیرستان', 'pronunciation' => '/ˈhɑɪ skuːl/'],
            ['front' => 'plain', 'back' => 'ساده', 'pronunciation' => '/pleɪn/'],
            ['front' => 'country', 'back' => 'روستا', 'pronunciation' => '/ˈkʌntri/'],
            ['front' => 'elementary school', 'back' => 'دبستان', 'pronunciation' => '/ˌɛləˈmɛntri skul/'],
            ['front' => 'living room', 'back' => 'اتاق نشیمن', 'pronunciation' => '/ˈlɪvɪŋ rʊm/'],
            ['front' => 'outskirts', 'back' => 'حومه', 'pronunciation' => '/ˈɑʊt.skɜrts/'],
            ['front' => 'college', 'back' => 'کالج', 'pronunciation' => '/ˈkɑlɪdʒ/'],
            ['front' => 'public school', 'back' => 'مدرسه دولتی', 'pronunciation' => '/ˌpʌblɪk ˈskuːl/'],
            ['front' => 'kitchen', 'back' => 'آشپزخانه', 'pronunciation' => '/ˈkɪtʃən/'],
            ['front' => 'study', 'back' => 'درس خواندن', 'pronunciation' => '/ˈstʌdi/'],
            ['front' => 'West Coast', 'back' => 'ساحل غربی', 'pronunciation' => '/ˌwest ˈkoʊst/'],
            ['front' => 'elementary', 'back' => 'ابتدایی', 'pronunciation' => '/ˌel.əˈmen.tər.i/'],
            ['front' => 'light', 'back' => 'روشن (هوا و ...)', 'pronunciation' => '/lɑɪt/'],
            ['front' => 'walkway', 'back' => 'دالان', 'pronunciation' => '/ˈwɔːkweɪ/'],
            ['front' => 'floor', 'back' => 'طبقه', 'pronunciation' => '/flɔːr/'],
            ['front' => 'prestigious', 'back' => 'آبرومند', 'pronunciation' => '/preˈstɪdʒəs/'],
            ['front' => 'top floor', 'back' => 'طبقه بالا', 'pronunciation' => '/tɑp flɔr/'],
            ['front' => 'suburb', 'back' => 'حومه', 'pronunciation' => '/ˈsʌb.ɜrb/'],
            ['front' => 'controversy', 'back' => 'مشاجره', 'pronunciation' => '/ˈkɑntrəˌvɜrsi/'],
            ['front' => 'gate', 'back' => 'دروازه', 'pronunciation' => '/geɪt/'],
            ['front' => 'chimney', 'back' => 'دودکش', 'pronunciation' => '/ˈtʃɪm.ni/'],
            ['front' => 'roof', 'back' => 'سقف', 'pronunciation' => '/ruːf/'],
            ['front' => 'take', 'back' => '(امتحان) دادن', 'pronunciation' => '/teɪk/'],
            ['front' => 'balcony', 'back' => 'بالکن', 'pronunciation' => '/ˈbælkəni/'],
            ['front' => 'deck', 'back' => 'ایوان', 'pronunciation' => '/dek/'],
            ['front' => 'step', 'back' => 'پله', 'pronunciation' => '/step/'],
            ['front' => 'push', 'back' => 'وادار کردن', 'pronunciation' => '/pʊʃ/'],
            ['front' => 'apartment building', 'back' => 'مجتمع مسکونی', 'pronunciation' => '/əˈpɑrtmənt ˌbɪldɪŋ/'],
            ['front' => 'village', 'back' => 'روستا', 'pronunciation' => '/ˈvɪləʤ/'],
            ['front' => 'educate', 'back' => 'آموزش دادن', 'pronunciation' => '/ˈɛʤəˌkeɪt/'],
            ['front' => 'resent', 'back' => 'آزرده‌خاطر شدن', 'pronunciation' => '/rɪˈzɛnt/'],
            ['front' => 'town', 'back' => 'شهر (کوچک)', 'pronunciation' => '/tɑʊn/'],
            ['front' => 'university', 'back' => 'دانشگاه', 'pronunciation' => '/ˌjuːnɪˈvɜːrsəti/'],
            ['front' => 'bookcase', 'back' => 'قفسه کتاب', 'pronunciation' => '/ˈbʊkkeɪs/'],
            ['front' => 'wall', 'back' => 'دیوار', 'pronunciation' => '/wɔːl/'],
            ['front' => 'basement', 'back' => 'زیرزمین', 'pronunciation' => '/ˈbeɪs.mənt/'],
            ['front' => 'bring up', 'back' => 'تربیت کردن', 'pronunciation' => '/brɪŋ ʌp/'],
            ['front' => 'head teacher', 'back' => 'مدیر مدرسه', 'pronunciation' => '/ˌhed ˈtiːtʃər/'],
            ['front' => 'take up', 'back' => '(انجام یا یادگیری کاری را) شروع کردن', 'pronunciation' => '/teɪk ʌp/'],
            ['front' => 'property', 'back' => 'دارایی', 'pronunciation' => '/ˈprɑpərti/'],
            ['front' => 'behave', 'back' => 'مؤدب بودن', 'pronunciation' => '/bəˈheɪv/'],
            ['front' => 'log', 'back' => 'کنده (درخت)', 'pronunciation' => '/lɔg/'],
            ['front' => 'geography', 'back' => 'جغرافیا', 'pronunciation' => '/dʒiːˈɑg.rə.fi/'],
            ['front' => 'nursery school', 'back' => 'مهد کودک', 'pronunciation' => '/ˈnɜːrsəri skuːl/'],
            ['front' => 'religious school', 'back' => 'مدرسه مذهبی', 'pronunciation' => '/rɪˈlɪʤəs skul/'],
            ['front' => 'entrance', 'back' => 'ورودی', 'pronunciation' => '/ˈen.trəns/'],
            ['front' => 'tower', 'back' => 'برج', 'pronunciation' => '/ˈtɑʊ.ər/'],
            ['front' => 'bedroom', 'back' => 'اتاق‌خواب', 'pronunciation' => '/ˈbedrʊm/'],
            ['front' => 'punish', 'back' => 'تنبیه کردن', 'pronunciation' => '/ˈpʌn.ɪʃ/'],
            ['front' => 'ceiling', 'back' => 'سقف (درونی)', 'pronunciation' => '/ˈsiː.lɪŋ/'],
            ['front' => 'primary school', 'back' => 'دبستان', 'pronunciation' => '/ˈpraɪmeri skuːl/'],
            ['front' => 'history', 'back' => 'تاریخ', 'pronunciation' => '/ˈhɪs.tə.ri/'],
            ['front' => 'turn into', 'back' => 'تبدیل شدن', 'pronunciation' => '/tɜrn ˈɪntu/'],
            ['front' => 'semester', 'back' => 'نیمسال', 'pronunciation' => '/səˈmes.tər/'],
            ['front' => 'fireplace', 'back' => 'شومینه', 'pronunciation' => '/ˈfaɪərˌpleɪs/'],
            ['front' => 'kindergarten', 'back' => 'مهدکودک', 'pronunciation' => '/ˈkɪndərɡɑːrtn/'],
            ['front' => 'first floor', 'back' => 'طبقه همکف (آمریکا)', 'pronunciation' => '/ˌfɜːrst ˈflɔːr/'],
            ['front' => 'preschool', 'back' => 'پیش‌دبستانی', 'pronunciation' => '/ˈpriːskuːl/'],
            ['front' => 'cozy', 'back' => 'دنج', 'pronunciation' => '/ˈkoʊ.zi/'],
            ['front' => 'hang', 'back' => 'آویزان کردن', 'pronunciation' => '/hæŋ/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 7');
    }

    protected function seedLesson8($deck)
    {
        $vocabulary = [
            ['front' => 'go on a picnic', 'back' => 'پیک‌نیک رفتن', 'pronunciation' => '/goʊ ɔn ə ˈpɪknɪk /'],
            ['front' => 'on foot', 'back' => 'پیاده', 'pronunciation' => '/ɔn fʊt /'],
            ['front' => 'catch', 'back' => 'گرفتن (اتوبوس، قطار، و ...)', 'pronunciation' => '/kætʃ /'],
            ['front' => 'get to', 'back' => 'رسیدن به', 'pronunciation' => '/gɛt tu /'],
            ['front' => 'give someone a lift', 'back' => 'رساندن (با خودرو)', 'pronunciation' => '/gɪv ˈsʌmwʌn ə lɪft /'],
            ['front' => 'walk', 'back' => 'راه رفتن', 'pronunciation' => '/wɔk /'],
            ['front' => 'by car', 'back' => 'با خودرو', 'pronunciation' => '/bɑɪ kɑr /'],
            ['front' => 'be late', 'back' => 'دیر رسیدن', 'pronunciation' => '/bi leɪt /'],
            ['front' => 'miss', 'back' => 'جا ماندن از', 'pronunciation' => '/mɪs /'],
            ['front' => 'hitchhike', 'back' => 'با ماشین مسافری مجانی رفتن', 'pronunciation' => '/ˈhɪtʃhɑɪk /'],
            ['front' => 'hitchhiker', 'back' => 'مسافر مجانی', 'pronunciation' => '/ˈhɪtʃhɑɪkər /'],
            ['front' => 'train station', 'back' => 'ایستگاه قطار', 'pronunciation' => '/treɪn ˈsteɪʃən /'],
            ['front' => 'ferry', 'back' => 'کشتی مسافربری', 'pronunciation' => '/ˈfɛri /'],
            ['front' => 'get off', 'back' => 'پیاده شدن از (اتوبوس، قطار و ...)', 'pronunciation' => '/gɛt ɔf /'],
            ['front' => 'get on', 'back' => 'سوار شدن بر (اتوبوس، قطار و ...)', 'pronunciation' => '/gɛt ɔn /'],
            ['front' => 'run away', 'back' => 'فرار کردن', 'pronunciation' => '/rʌn əˈweɪ /'],
            ['front' => 'run out', 'back' => 'تمام شدن', 'pronunciation' => '/rʌn aʊt /'],
            ['front' => 'come back', 'back' => 'بازگشتن', 'pronunciation' => '/kʌm bæk /'],
            ['front' => 'be a pain', 'back' => 'مایه دردسر بودن', 'pronunciation' => '/bi ə peɪn /'],
            ['front' => 'take turns', 'back' => 'به نوبت انجام دادن', 'pronunciation' => '/teɪk tɜrnz /'],
            ['front' => 'give back', 'back' => 'بازپس دادن', 'pronunciation' => '/gɪv bæk /'],
            ['front' => 'go over', 'back' => 'مرور کردن', 'pronunciation' => '/goʊ ˈoʊvər /'],
            ['front' => 'put away', 'back' => 'کنار گذاشتن', 'pronunciation' => '/pʊt əˈweɪ /'],
            ['front' => 'wake up', 'back' => 'از خواب بیدار شدن', 'pronunciation' => '/weɪk ʌp /'],
            ['front' => 'get up', 'back' => 'از رختخواب بلند شدن', 'pronunciation' => '/gɛt ʌp /'],
            ['front' => 'eat out', 'back' => 'بیرون غذا خوردن', 'pronunciation' => '/it aʊt /'],
            ['front' => 'give up', 'back' => 'رها کردن', 'pronunciation' => '/gɪv ʌp /'],
            ['front' => 'go away', 'back' => 'از جایی رفتن', 'pronunciation' => '/goʊ əˈweɪ /'],
            ['front' => 'come up with', 'back' => 'به چیزی رسیدن (ایده)', 'pronunciation' => '/kʌm ʌp wɪð /'],
            ['front' => 'do over', 'back' => 'دوباره انجام دادن', 'pronunciation' => '/du ˈoʊvər /'],
            ['front' => 'break up', 'back' => 'بهم زدن', 'pronunciation' => '/breɪk ʌp /'],
            ['front' => 'drop someone off', 'back' => 'کسی را رساندن (با خودرو)', 'pronunciation' => '/drɑp ˈsʌmwʌn ɔf /'],
            ['front' => 'turn off', 'back' => 'خاموش کردن', 'pronunciation' => '/tɜrn ɔf /'],
            ['front' => 'set up', 'back' => 'راه‌اندازی کردن', 'pronunciation' => '/sɛt ʌp /'],
            ['front' => 'look forward to', 'back' => '(بی‌صبرانه) در انتظار (چیزی) بودن', 'pronunciation' => '/lʊk ˈfɔrwərd tu /'],
            ['front' => 'get along with', 'back' => 'با کسی ساختن', 'pronunciation' => '/gɛt əˈlɔŋ wɪð /'],
            ['front' => 'get by', 'back' => 'گذران زندگی کردن', 'pronunciation' => '/gɛt bɑɪ /'],
            ['front' => 'call back', 'back' => 'دوباره تلفن زدن', 'pronunciation' => '/kɔl bæk /'],
            ['front' => 'take after', 'back' => 'به کسی رفتن (از نظر ظاهری)', 'pronunciation' => '/teɪk ˈæftər /'],
            ['front' => 'go out', 'back' => 'بیرون رفتن', 'pronunciation' => '/goʊ aʊt /'],
            ['front' => 'go on', 'back' => 'ادامه دادن', 'pronunciation' => '/goʊ ɔn /'],
            ['front' => 'look up', 'back' => 'جستجو کردن', 'pronunciation' => '/lʊk ʌp /'],
            ['front' => 'turn down', 'back' => 'رد کردن', 'pronunciation' => '/tɜrn daʊn /'],
            ['front' => 'pass out', 'back' => 'غش کردن', 'pronunciation' => '/pæs aʊt /'],
            ['front' => 'put off', 'back' => 'به تعویق انداختن', 'pronunciation' => '/pʊt ɔf /'],
            ['front' => 'hang out', 'back' => 'وقت گذراندن', 'pronunciation' => '/hæŋ aʊt /'],
            ['front' => 'bring up', 'back' => 'بزرگ کردن', 'pronunciation' => '/brɪŋ ʌp /'],
            ['front' => 'get away', 'back' => 'فرار کردن', 'pronunciation' => '/gɛt əˈweɪ /'],
            ['front' => 'find out', 'back' => 'کشف کردن', 'pronunciation' => '/fɑɪnd aʊt /'],
            ['front' => 'count on', 'back' => 'روی کسی حساب کردن', 'pronunciation' => '/kaʊnt ɔn /'],
            ['front' => 'fill up', 'back' => 'پر کردن', 'pronunciation' => '/fɪl ʌp /'],
            ['front' => 'look after', 'back' => 'مراقبت کردن از', 'pronunciation' => '/lʊk ˈæftər /'],
            ['front' => 'take off', 'back' => 'از زمین بلند شدن (هواپیما)', 'pronunciation' => '/teɪk ɔf /'],
            ['front' => 'put out', 'back' => 'خاموش کردن (سیگار، آتش)', 'pronunciation' => '/pʊt aʊt /'],
            ['front' => 'run into', 'back' => 'تصادفا کسی را دیدن', 'pronunciation' => '/rʌn ˈɪntu /'],
            ['front' => 'look for', 'back' => 'دنبال چیزی گشتن', 'pronunciation' => '/lʊk fɔr /'],
            ['front' => 'look up to', 'back' => 'تحسین کردن', 'pronunciation' => '/lʊk ʌp tu /'],
            ['front' => 'give away', 'back' => 'بخشیدن', 'pronunciation' => '/gɪv əˈweɪ /'],
            ['front' => 'show up', 'back' => 'حاضر شدن', 'pronunciation' => '/ʃoʊ ʌp /'],
            ['front' => 'break down', 'back' => 'از کار افتادن (خودرو و...)', 'pronunciation' => '/breɪk daʊn /'],
            ['front' => 'get back', 'back' => 'بازگشتن', 'pronunciation' => '/gɛt bæk /'],
            ['front' => 'pull over', 'back' => 'کنار کشیدن (خودرو)', 'pronunciation' => '/pʊl ˈoʊvər /'],
            ['front' => 'slow down', 'back' => 'سرعت کم کردن', 'pronunciation' => '/sloʊ daʊn /'],
            ['front' => 'look forward to', 'back' => '(بی‌صبرانه) در انتظار (چیزی) بودن', 'pronunciation' => '/lʊk ˈfɔrwərd tu /'],
            ['front' => 'get away with', 'back' => 'از مجازات فرار کردن', 'pronunciation' => '/gɛt əˈweɪ wɪð /'],
            ['front' => 'go through', 'back' => 'تجربه کردن', 'pronunciation' => '/goʊ θru /'],
            ['front' => 'stand by', 'back' => 'حمایت کردن از', 'pronunciation' => '/stænd bɑɪ /'],
            ['front' => 'go out with', 'back' => 'قرار گذاشتن با', 'pronunciation' => '/goʊ aʊt wɪð /'],
            ['front' => 'run away from', 'back' => 'از دست کسی/چیزی فرار کردن', 'pronunciation' => '/rʌn əˈweɪ frɑm /'],
            ['front' => 'get together', 'back' => 'دور هم جمع شدن', 'pronunciation' => '/gɛt təˈgɛðər /'],
            ['front' => 'deal with', 'back' => 'سروکار داشتن با', 'pronunciation' => '/dil wɪð /'],
            ['front' => 'get rid of', 'back' => 'از شر چیزی خلاص شدن', 'pronunciation' => '/gɛt rɪd ʌv /'],
            ['front' => 'bring about', 'back' => 'باعث شدن', 'pronunciation' => '/brɪŋ əˈbɑʊt /'],
            ['front' => 'take over', 'back' => 'به دست گرفتن', 'pronunciation' => '/teɪk ˈoʊvər /'],
            ['front' => 'get up to', 'back' => 'دست به شیطنت زدن', 'pronunciation' => '/gɛt ʌp tu /'],
            ['front' => 'get over', 'back' => 'بهبود یافتن', 'pronunciation' => '/gɛt ˈoʊvər /'],
            ['front' => 'get on with', 'back' => 'با کسی ساختن', 'pronunciation' => '/gɛt ɔn wɪð /'],
            ['front' => 'catch up with', 'back' => 'به کسی رسیدن', 'pronunciation' => '/kætʃ ʌp wɪð /'],
            ['front' => 'come across', 'back' => 'به طور تصادفی پیدا کردن', 'pronunciation' => '/kʌm əˈkrɔs /'],
            ['front' => 'look down on', 'back' => 'تحقیر کردن', 'pronunciation' => '/lʊk daʊn ɔn /'],
            ['front' => 'look back on', 'back' => 'به گذشته فکر کردن', 'pronunciation' => '/lʊk bæk ɔn /'],
            ['front' => 'take up', 'back' => 'شروع کردن', 'pronunciation' => '/teɪk ʌp /'],
            ['front' => 'put up with', 'back' => 'تحمل کردن', 'pronunciation' => '/pʊt ʌp wɪð /'],
            ['front' => 'keep up with', 'back' => 'همگام شدن با', 'pronunciation' => '/kip ʌp wɪð /'],
            ['front' => 'grow out of', 'back' => 'دیگر به چیزی علاقه نداشتن', 'pronunciation' => '/groʊ aʊt ʌv /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 8');
    }

    protected function seedLesson9($deck)
    {
        $vocabulary = [
            ['front' => 'USB cable', 'back' => 'کابل یواس‌بی', 'pronunciation' => '/ju-ɛs-bi ˈkeɪbəl/'],
            ['front' => 'plug in', 'back' => 'به پریز برق وصل کردن', 'pronunciation' => '/plʌg ɪn/'],
            ['front' => 'adaptor', 'back' => 'آداپتور (نوعی مبدل الکتریکی)', 'pronunciation' => '/əˈdæptər/'],
            ['front' => 'keyboard', 'back' => 'صفحه‌کلید (کامپیوتر، ماشین تحریر و...)', 'pronunciation' => '/ˈkiː.bɔːrd/'],
            ['front' => 'patience', 'back' => 'صبر', 'pronunciation' => '/ˈpeɪ.ʃəns/'],
            ['front' => 'flash drive', 'back' => 'یواس‌بی فلش درایو', 'pronunciation' => '/flæʃ draɪv/'],
            ['front' => 'unluckily', 'back' => 'بدبختانه', 'pronunciation' => '/ʌnˈlʌkɪli/'],
            ['front' => 'plug', 'back' => 'دوشاخه', 'pronunciation' => '/plʌɡ/'],
            ['front' => 'fortune', 'back' => 'بخت', 'pronunciation' => '/ˈfɔːr.tʃən/'],
            ['front' => 'patient', 'back' => 'صبور', 'pronunciation' => '/ˈpeɪʃənt/'],
            ['front' => 'unplug', 'back' => 'از پریز کشیدن', 'pronunciation' => '/ˌʌnˈplʌɡ/'],
            ['front' => 'information overload', 'back' => 'سرریز داده‌ها', 'pronunciation' => '/ˌɪnfərˈmeɪʃən ˈoʊvərˌloʊd/'],
            ['front' => 'headphones', 'back' => 'هدفون', 'pronunciation' => '/ˈhedfoʊnz/'],
            ['front' => 'remote control', 'back' => 'کنترل (تلویزیون و...)', 'pronunciation' => '/rɪˌmoʊt.kənˈtroʊl/'],
            ['front' => 'hit', 'back' => 'زدن', 'pronunciation' => '/hɪt/'],
            ['front' => 'fortunate', 'back' => 'خوش‌شانس', 'pronunciation' => '/ˈfɔrʧənət/'],
            ['front' => 'pour', 'back' => 'ریختن', 'pronunciation' => '/pɔːr/'],
            ['front' => 'set', 'back' => 'کوک کردن', 'pronunciation' => '/set/'],
            ['front' => 'impatient', 'back' => 'بی‌صبر', 'pronunciation' => '/ɪmˈpeɪ.ʃənt/'],
            ['front' => 'screen', 'back' => 'صفحه نمایش', 'pronunciation' => '/skrin/'],
            ['front' => 'switch off', 'back' => 'خاموش کردن', 'pronunciation' => '/swɪʧ ɔf/'],
            ['front' => 'willpower', 'back' => 'اراده', 'pronunciation' => '/ˈwɪlpaʊər/'],
            ['front' => 'shiver', 'back' => 'لرزیدن (از سرما، ترس و...)', 'pronunciation' => '/ˈʃɪv.ər/'],
            ['front' => 'patiently', 'back' => 'صبورانه', 'pronunciation' => '/ˈpeɪ.ʃənt.li/'],
            ['front' => 'unfortunate', 'back' => 'تأسف‌آور', 'pronunciation' => '/ʌnˈfɔːr.tʃə.nət/'],
            ['front' => 'upset', 'back' => 'ناراحت', 'pronunciation' => '/ʌpˈset/'],
            ['front' => 'unfortunately', 'back' => 'متاسفانه', 'pronunciation' => '/ʌnˈfɔːr.tʃə.nət.li/'],
            ['front' => 'fortunately', 'back' => 'خوشبختانه', 'pronunciation' => '/ˈfɔːr.tʃə.nət.li/'],
            ['front' => 'impatiently', 'back' => 'بی‌صبرانه', 'pronunciation' => '/ɪmˈpeɪ.ʃənt.li/'],
            ['front' => 'outlet', 'back' => 'پریز برق', 'pronunciation' => '/ˈaʊtlet/'],
            ['front' => 'comfort', 'back' => 'راحتی', 'pronunciation' => '/ˈkʌm.fərt/'],
            ['front' => 'switch', 'back' => 'کلید (روشن و خاموش)', 'pronunciation' => '/swɪʧ/'],
            ['front' => 'comfortable', 'back' => 'راحت', 'pronunciation' => '/ˈkʌmf.tə.bəl/'],
            ['front' => 'care', 'back' => 'دقت', 'pronunciation' => '/ker/'],
            ['front' => 'luck', 'back' => 'شانس', 'pronunciation' => '/lʌk/'],
            ['front' => 'comfortably', 'back' => 'به آسودگی', 'pronunciation' => '/ˈkʌmf.tə.bli/'],
            ['front' => 'countryside', 'back' => 'ییلاقات', 'pronunciation' => '/ˈkʌn.triːˌsɑɪd/'],
            ['front' => 'multitask', 'back' => 'چند کار را با هم انجام دادن', 'pronunciation' => '/ˌmʌltiˈtæsk/'],
            ['front' => 'mouse', 'back' => 'ماوس (کامپیوتر)', 'pronunciation' => '/mɑʊs/'],
            ['front' => 'uncomfortable', 'back' => 'نا راحت', 'pronunciation' => '/ʌnˈkʌmftəbl/'],
            ['front' => 'switch on', 'back' => 'روشن کردن', 'pronunciation' => '/swɪʧ ɑn/'],
            ['front' => 'stranger', 'back' => 'غریبه', 'pronunciation' => '/ˈstreɪn.dʒər/'],
            ['front' => 'speaker', 'back' => 'بلندگو', 'pronunciation' => '/ˈspiː.kər/'],
            ['front' => 'careful', 'back' => 'مراقب', 'pronunciation' => '/ˈker.fəl/'],
            ['front' => 'relevant', 'back' => 'مرتبط', 'pronunciation' => '/ˈrel.ə.vənt/'],
            ['front' => 'unlucky', 'back' => 'بدشانس', 'pronunciation' => '/ʌnˈlʌk.i/'],
            ['front' => 'uncomfortably', 'back' => 'به طرز آزاردهنده', 'pronunciation' => '/ʌnˈkʌmftəbli/'],
            ['front' => 'turn down', 'back' => 'کم کردن', 'pronunciation' => '/tɜrn daʊn/'],
            ['front' => 'hitchhike', 'back' => 'رایگان‌سواری کردن', 'pronunciation' => '/ˈhɪtʃ.hɑɪk/'],
            ['front' => 'lonely', 'back' => 'تنها', 'pronunciation' => '/ˈloʊn.li/'],
            ['front' => 'productive', 'back' => 'پربازده', 'pronunciation' => '/prəˈdʌk.tɪv/'],
            ['front' => 'carefully', 'back' => 'بادقت', 'pronunciation' => '/ˈker.fə.li/'],
            ['front' => 'luckily', 'back' => 'خوشبختانه', 'pronunciation' => '/ˈlʌk.ə.li/'],
            ['front' => 'get to', 'back' => 'رسیدن (به مکانی)', 'pronunciation' => '/gɛt tu/'],
            ['front' => 'careless', 'back' => 'بی‌دقت', 'pronunciation' => '/ˈker.ləs/'],
            ['front' => 'miss', 'back' => 'از دست دادن', 'pronunciation' => '/mɪs/'],
            ['front' => 'anxious', 'back' => 'مضطرب', 'pronunciation' => '/ˈæŋk.ʃəs/'],
            ['front' => 'in order to', 'back' => 'به منظور', 'pronunciation' => '/ɪn ˈɔrdər tu/'],
            ['front' => 'carelessly', 'back' => 'با بی دقتی', 'pronunciation' => '/ˈker.ləs.li/'],
            ['front' => 'common sense', 'back' => 'عقل سلیم', 'pronunciation' => '/ˈkɑmən sɛns/'],
            ['front' => 'turn up', 'back' => 'زیاد کردن', 'pronunciation' => '/tɜrn ʌp/'],
            ['front' => 'electronic devices', 'back' => 'لوازم برقی', 'pronunciation' => '/ɪˌlɛkˈtrɑnɪk dɪˈvaɪsəz/'],
            ['front' => 'from time to time', 'back' => 'گهگاه', 'pronunciation' => '/frʌm taɪm tu taɪm/'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 9');
    }

    protected function seedLesson10($deck)
    {
        $vocabulary = [
            ['front' => 'evidence', 'back' => 'مدرک', 'pronunciation' => '/ˈev.əd.əns /'],
            ['front' => 'court', 'back' => 'دادگاه', 'pronunciation' => '/kɔːrt /'],
            ['front' => 'murder', 'back' => 'قتل (عمد)', 'pronunciation' => '/ˈmɜːrdər /'],
            ['front' => 'murder', 'back' => 'به قتل رساندن', 'pronunciation' => '/ˈmɜːrdər /'],
            ['front' => 'trial', 'back' => 'محاکمه', 'pronunciation' => '/ˈtraɪəl /'],
            ['front' => 'murderer', 'back' => 'قاتل', 'pronunciation' => '/ˈmɜːrdərər /'],
            ['front' => 'get promoted', 'back' => 'ترفیع گرفتن', 'pronunciation' => '/gɛt prəˈmoʊtəd /'],
            ['front' => 'prove', 'back' => 'اثبات کردن', 'pronunciation' => '/pruv /'],
            ['front' => 'solve', 'back' => 'حل کردن', 'pronunciation' => '/sɑːlv /'],
            ['front' => 'prosecution', 'back' => 'دادستان', 'pronunciation' => '/ˌprɑːsɪˈkjuːʃn /'],
            ['front' => 'suspect', 'back' => 'مظنون', 'pronunciation' => '/ˈsʌˌspɛkt /'],
            ['front' => 'dock', 'back' => 'جایگاه متهم (در دادگاه)', 'pronunciation' => '/dɑk /'],
            ['front' => 'victim', 'back' => 'قربانی', 'pronunciation' => '/ˈvɪktɪm /'],
            ['front' => 'witness', 'back' => 'شاهد', 'pronunciation' => '/ˈwɪtnəs /'],
            ['front' => 'case', 'back' => 'پرونده', 'pronunciation' => '/keɪs /'],
            ['front' => 'alibi', 'back' => 'مدرک دال بر عدم حضور در صحنه جرم', 'pronunciation' => '/ˈæləbaɪ /'],
            ['front' => 'icon', 'back' => 'تمثال', 'pronunciation' => '/ˈaɪkɑːn /'],
            ['front' => 'soccer field', 'back' => 'زمین فوتبال', 'pronunciation' => '/ˈsɑkər fild /'],
            ['front' => 'acquit', 'back' => 'تبرئه کردن', 'pronunciation' => '/əˈkwɪt /'],
            ['front' => 'speed camera', 'back' => 'دوربین کنترل سرعت', 'pronunciation' => '/spid ˈkæmərə /'],
            ['front' => 'sunglasses', 'back' => 'عینک آفتابی', 'pronunciation' => '/ˈsʌnglæsɪz /'],
            ['front' => 'town hall', 'back' => 'ساختمان شهرداری', 'pronunciation' => '/ˌtaʊn ˈhɔːl /'],
            ['front' => 'cross-examine', 'back' => 'استنطاق کردن از شهود در دادگاه', 'pronunciation' => '/ˌkrɔːs ɪɡˈzæmɪn /'],
            ['front' => 'defense', 'back' => 'وکیل‌مدافع', 'pronunciation' => '/dɪˈfens /'],
            ['front' => 'bookcase', 'back' => 'قفسه کتاب', 'pronunciation' => '/ˈbʊkkeɪs /'],
            ['front' => 'plead', 'back' => 'ادعا کردن (در دادگاه)', 'pronunciation' => '/pliːd /'],
            ['front' => 'classmate', 'back' => 'هم‌کلاسی', 'pronunciation' => '/ˈklæsmeɪt /'],
            ['front' => 'detective', 'back' => 'کارآگاه', 'pronunciation' => '/dɪˈtektɪv /'],
            ['front' => 'crime', 'back' => 'جرم', 'pronunciation' => '/kraɪm /'],
        ];

        $this->seedVocabulary($deck, $vocabulary, 'American English File 3 - Lesson 10');
    }

    private function seedVocabulary($deck, $vocabulary, $lessonName)
    {
        foreach ($vocabulary as $cardData) {
            StaticCard::updateOrCreate(
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                ],
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                    'interval' => 1,
                    'revised_at' => null,
                    'last_reviewed' => null,
                ]
            );
        }

        $this->command->info('Seeded ' . count($vocabulary) . ' cards for ' . $lessonName);
    }
}
