<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\StaticCard;
use App\Models\StaticDeck;
use Illuminate\Database\Seeder;

class StaticCardFile4Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get all Upper-intermediate level static decks
        $upperIntermediateDecks = StaticDeck::where('level', 'upper_intermediate')->get();

        if ($upperIntermediateDecks->isEmpty()) {
            $this->command->error('No Upper-intermediate level static decks found. Please run StaticDeckSeeder first.');

            return;
        }

        // Lesson 1 vocabulary
        $lesson1Deck = $upperIntermediateDecks->where('lesson_number', 1)->first();
        if ($lesson1Deck) {
            $this->seedLesson1($lesson1Deck);
        }

        // Lesson 2 vocabulary
        $lesson2Deck = $upperIntermediateDecks->where('lesson_number', 2)->first();
        if ($lesson2Deck) {
            $this->seedLesson2($lesson2Deck);
        }

        // Lesson 3 vocabulary
        $lesson3Deck = $upperIntermediateDecks->where('lesson_number', 3)->first();
        if ($lesson3Deck) {
            $this->seedLesson3($lesson3Deck);
        }

        // Lesson 4 vocabulary
        $lesson4Deck = $upperIntermediateDecks->where('lesson_number', 4)->first();
        if ($lesson4Deck) {
            $this->seedLesson4($lesson4Deck);
        }

        // Lesson 5 vocabulary
        $lesson5Deck = $upperIntermediateDecks->where('lesson_number', 5)->first();
        if ($lesson5Deck) {
            $this->seedLesson5($lesson5Deck);
        }

        // Lesson 6 vocabulary
        $lesson6Deck = $upperIntermediateDecks->where('lesson_number', 6)->first();
        if ($lesson6Deck) {
            $this->seedLesson6($lesson6Deck);
        }

        // Lesson 7 vocabulary
        $lesson7Deck = $upperIntermediateDecks->where('lesson_number', 7)->first();
        if ($lesson7Deck) {
            $this->seedLesson7($lesson7Deck);
        }

        // Lesson 8 vocabulary
        $lesson8Deck = $upperIntermediateDecks->where('lesson_number', 8)->first();
        if ($lesson8Deck) {
            $this->seedLesson8($lesson8Deck);
        }

        // Lesson 9 vocabulary
        $lesson9Deck = $upperIntermediateDecks->where('lesson_number', 9)->first();
        if ($lesson9Deck) {
            $this->seedLesson9($lesson9Deck);
        }

        // Lesson 10 vocabulary
        $lesson10Deck = $upperIntermediateDecks->where('lesson_number', 10)->first();
        if ($lesson10Deck) {
            $this->seedLesson10($lesson10Deck);
        }

    }

    protected function seedLesson1($deck)
    {
        $vocabulary = [
            ['front' => 'curtain', 'back' => 'پرده', 'pronunciation' => '/ˈkɜr.tən/'],
            ['front' => 'dome', 'back' => 'گنبد', 'pronunciation' => '/doʊm/'],
            ['front' => 'hallucinate', 'back' => 'توهم زدن', 'pronunciation' => '/həˈluːsɪneɪt/'],
            ['front' => 'a little', 'back' => 'کمی', 'pronunciation' => '/ə ˈlɪtəl/'],
            ['front' => 'drag', 'back' => 'روی زمین کشیدن', 'pronunciation' => '/dræg/'],
            ['front' => 'rather', 'back' => 'نسبتاً', 'pronunciation' => '/ˈræð.ər/'],
            ['front' => 'recruitment agency', 'back' => 'بنگاه کاریابی', 'pronunciation' => '/rəˈkrutmənt ˈeɪʤənsi/'],
            ['front' => 'real estate agent', 'back' => 'مشاور املاک', 'pronunciation' => '/ˈriːəl əsteɪt eɪdʒənt/'],
            ['front' => 'think on your feet', 'back' => 'حاضرجواب بودن', 'pronunciation' => '/θɪŋk ɑn jʊər fit/'],
            ['front' => 'job seeker', 'back' => 'جویای کار', 'pronunciation' => '/ˈdʒɑːb siːkər/'],
            ['front' => 'tight-fisted', 'back' => 'خسیس', 'pronunciation' => '/ˌtaɪt ˈfɪstɪd/'],
            ['front' => 'rather than', 'back' => 'به جای', 'pronunciation' => '/ˈræðər ðæn/'],
            ['front' => 'binoculars', 'back' => 'دوربین دوچشمی', 'pronunciation' => '/bəˈnɑkjələrz/'],
            ['front' => 'breeze', 'back' => 'نسیم', 'pronunciation' => '/briːz/'],
            ['front' => 'easy-going', 'back' => 'بی‌خیال', 'pronunciation' => '/ˌIː.ziːˈgoʊ.ɪŋ/'],
            ['front' => 'big-headed', 'back' => 'مغرور', 'pronunciation' => '/ˌbɪɡ ˈhedɪd/'],
            ['front' => 'continue', 'back' => 'ادامه دادن', 'pronunciation' => '/kənˈtɪn.juː/'],
            ['front' => 'good-tempered', 'back' => 'خوش‌اخلاق', 'pronunciation' => '/ˌɡʊd ˈtempərd/'],
            ['front' => 'approach', 'back' => 'رویکرد', 'pronunciation' => '/əˈproʊʧ/'],
            ['front' => 'strong-willed', 'back' => 'بااراده', 'pronunciation' => '/ˌstrɔːŋ ˈwɪld/'],
            ['front' => 'bizarre', 'back' => 'عجیب‌غریب', 'pronunciation' => '/bɪˈzɑr/'],
            ['front' => 'self-centered', 'back' => 'خودخواه', 'pronunciation' => '/ˌself ˈsentərd/'],
            ['front' => 'really', 'back' => 'واقعاً', 'pronunciation' => '/ˈriː.li/'],
            ['front' => 'candidate', 'back' => 'داوطلب (آزمون)', 'pronunciation' => '/ˈkændədeɪt/'],
            ['front' => 'two-faced', 'back' => 'دورو', 'pronunciation' => '/ˌtuː ˈfeɪst/'],
            ['front' => 'incredibly', 'back' => 'به‌طور باور نکردنی', 'pronunciation' => '/ɪnˈkred.ə.bli/'],
            ['front' => 'glide', 'back' => '(به‌آرامی و نرمی) حرکت کردن', 'pronunciation' => '/glaɪd/'],
            ['front' => 'row house', 'back' => 'مجتمع مسکونی آپارتمانی', 'pronunciation' => '/ˈroʊ haʊs/'],
            ['front' => 'crush', 'back' => 'خرد کردن', 'pronunciation' => '/krʌʃ/'],
            ['front' => 'demanding', 'back' => 'دشوار', 'pronunciation' => '/dɪˈmæn.dɪŋ/'],
            ['front' => 'flustered', 'back' => 'گیج', 'pronunciation' => '/ˈflʌstərd/'],
            ['front' => 'laid-back', 'back' => 'آسوده‌خاطر', 'pronunciation' => '/ˌleɪd ˈbæk/'],
            ['front' => 'modifier', 'back' => 'توصیف‌کننده (دستور زبان)', 'pronunciation' => '/ˈmɑːdɪfaɪər/'],
            ['front' => 'open-minded', 'back' => 'روشن‌فکر', 'pronunciation' => '/ˌoʊpən ˈmaɪndɪd/'],
            ['front' => 'pretty', 'back' => 'نسبتاً', 'pronunciation' => '/ˈprɪti/'],
            ['front' => 'narrow-minded', 'back' => 'کوته‌فکر', 'pronunciation' => '/ˈnɛroʊ-ˈmaɪndəd/'],
            ['front' => 'bad-tempered', 'back' => 'تندخو', 'pronunciation' => '/ˌbædˈtemp.ərd/'],
            ['front' => 'absentminded', 'back' => 'حواس پرت', 'pronunciation' => '/ˈæbsənt maɪndəd/'],
            ['front' => 'very', 'back' => 'خیلی', 'pronunciation' => '/ˈveri/'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 1 vocabulary added.');
    }

    protected function seedLesson2($deck)
    {
        $vocabulary = [
            ['front' => 'silk', 'back' => 'ابریشم', 'pronunciation' => '/sɪlk /'],
            ['front' => 'swollen', 'back' => 'متورم', 'pronunciation' => '/ˈswoʊ.lən /'],
            ['front' => 'tight', 'back' => 'تنگ', 'pronunciation' => '/taɪt /'],
            ['front' => 'boot', 'back' => 'چکمه', 'pronunciation' => '/buːt /'],
            ['front' => 'GP', 'back' => 'پزشک خانواده', 'pronunciation' => '/ˌdʒiː ˈpiː /'],
            ['front' => 'diarrhea', 'back' => 'اسهال', 'pronunciation' => '/ˌdaɪəˈriːə /'],
            ['front' => 'pass out', 'back' => 'غش کردن', 'pronunciation' => '/pæs aʊt /'],
            ['front' => 'dress up', 'back' => 'لباس رسمی پوشیدن', 'pronunciation' => '/drɛs ʌp /'],
            ['front' => 'temperature', 'back' => 'تب', 'pronunciation' => '/ˈtemprətʃər /'],
            ['front' => 'life-threatening', 'back' => 'خطرناک', 'pronunciation' => '/ˈlaɪf θretnɪŋ /'],
            ['front' => 'go with', 'back' => 'هماهنگ بودن (لباس، رنگ و...)', 'pronunciation' => '/goʊ wɪð /'],
            ['front' => 'back', 'back' => 'پشت', 'pronunciation' => '/bæk /'],
            ['front' => 'cough', 'back' => 'سرفه', 'pronunciation' => '/kɔːf /'],
            ['front' => 'dizzy', 'back' => 'دچار سرگیجه', 'pronunciation' => '/ˈdɪz.i /'],
            ['front' => 'feel sick', 'back' => 'حالت تهوع داشتن', 'pronunciation' => '/fil sɪk /'],
            ['front' => 'sunburn', 'back' => 'آفتاب‌سوختگی', 'pronunciation' => '/ˈsʌn.bɝːn /'],
            ['front' => 'tumor', 'back' => 'تومور', 'pronunciation' => '/ˈtuːmər /'],
            ['front' => 'come around', 'back' => 'بهوش آمدن', 'pronunciation' => '/kʌm əˈraʊnd /'],
            ['front' => 'headache', 'back' => 'سردرد', 'pronunciation' => '/ˈhedeɪk /'],
            ['front' => 'scarf', 'back' => 'شال (گردن)', 'pronunciation' => '/skɑrf /'],
            ['front' => 'neat', 'back' => 'مرتب و منظم', 'pronunciation' => '/niːt /'],
            ['front' => 'hang up', 'back' => 'آویزان کردن', 'pronunciation' => '/hæŋ ʌp /'],
            ['front' => 'chest', 'back' => 'سینه', 'pronunciation' => '/tʃest /'],
            ['front' => 'get over', 'back' => 'بهبود یافتن', 'pronunciation' => '/gɛt ˈoʊvər /'],
            ['front' => 'break down', 'back' => '(ناگهان) زیر گریه زدن', 'pronunciation' => '/breɪk daʊn /'],
            ['front' => 'undershirt', 'back' => 'زیرپیراهنی', 'pronunciation' => '/ˈʌndərʃɜːrt /'],
            ['front' => 'old-fashioned', 'back' => 'قدیمی', 'pronunciation' => '/ˌoʊld ˈfæʃnd /'],
            ['front' => 'unconscious', 'back' => 'بیهوش', 'pronunciation' => '/ʌnˈkɑn.tʃəs /'],
            ['front' => 'high blood pressure', 'back' => 'فشار خون بالا', 'pronunciation' => '/haɪ blʌd ˈprɛʃər /'],
            ['front' => 'brain', 'back' => 'مغز', 'pronunciation' => '/breɪn /'],
            ['front' => 'ulcer', 'back' => 'زخم', 'pronunciation' => '/ˈʌlsər /'],
            ['front' => 'denim', 'back' => 'پارچه جین', 'pronunciation' => '/ˈden.əm /'],
            ['front' => 'lean', 'back' => 'تکیه دادن', 'pronunciation' => '/liːn /'],
            ['front' => 'faint', 'back' => 'از حال رفتن', 'pronunciation' => '/feɪnt /'],
            ['front' => 'finger', 'back' => 'انگشت (دست)', 'pronunciation' => '/ˈfɪŋgər /'],
            ['front' => 'velvet', 'back' => 'مخمل', 'pronunciation' => '/ˈvelvɪt /'],
            ['front' => 'linen', 'back' => 'کتانی (پارچه)', 'pronunciation' => '/ˈlɪnən /'],
            ['front' => 'deal with', 'back' => 'رسیدگی کردن', 'pronunciation' => '/dil wɪð /'],
            ['front' => 'cancer', 'back' => 'سرطان', 'pronunciation' => '/ˈkæn.sər /'],
            ['front' => 'burn', 'back' => 'سوختگی', 'pronunciation' => '/bɜrn /'],
            ['front' => 'bow tie', 'back' => 'پاپیون', 'pronunciation' => '/baʊ taɪ /'],
            ['front' => 'blister', 'back' => 'تاول', 'pronunciation' => '/ˈblɪstər /'],
            ['front' => 'ER', 'back' => 'بخش اورژانس', 'pronunciation' => '/ˌiː ˈɑːr /'],
            ['front' => 'sore throat', 'back' => 'گلودرد', 'pronunciation' => '/sɔr θroʊt /'],
            ['front' => 'vest', 'back' => 'جلیقه', 'pronunciation' => '/vest /'],
            ['front' => 'elderly', 'back' => 'سالمند', 'pronunciation' => '/ˈɛldərli /'],
            ['front' => 'long-sleeved', 'back' => 'آستین بلند', 'pronunciation' => '/lɔŋ slivd /'],
            ['front' => 'bleed', 'back' => 'خونریزی داشتن', 'pronunciation' => '/bliːd /'],
            ['front' => 'wear', 'back' => 'پوشیدن', 'pronunciation' => '/wer /'],
            ['front' => 'suit', 'back' => 'کت‌شلوار', 'pronunciation' => '/suːt /'],
            ['front' => 'fit', 'back' => 'مناسب', 'pronunciation' => '/fɪt /'],
            ['front' => 'dotted', 'back' => 'خال‌خالی', 'pronunciation' => '/ˈdɑːtɪd /'],
            ['front' => 'earache', 'back' => 'گوش‌درد', 'pronunciation' => '/ˈɪreɪk /'],
            ['front' => 'fur', 'back' => 'مو (حیوانات)', 'pronunciation' => '/fɜːr /'],
            ['front' => 'sick', 'back' => 'دچار حالت تهوع', 'pronunciation' => '/sɪk /'],
            ['front' => 'dress', 'back' => 'لباس پوشیدن', 'pronunciation' => '/dres /'],
            ['front' => 'get dressed', 'back' => 'لباس پوشیدن', 'pronunciation' => '/gɛt drɛst /'],
            ['front' => 'makeup', 'back' => 'آرایش', 'pronunciation' => '/ˈmeɪk.ʌp /'],
            ['front' => 'short-sleeved', 'back' => 'آستین کوتاه', 'pronunciation' => '/ʃɔrt-slivd /'],
            ['front' => 'striped', 'back' => 'راه‌راه', 'pronunciation' => '/straɪpt /'],
            ['front' => 'style', 'back' => 'سبک', 'pronunciation' => '/staɪl /'],
            ['front' => 'stomachache', 'back' => 'دل‌درد', 'pronunciation' => '/ˈstʌm.əkeɪk /'],
            ['front' => 'low blood pressure', 'back' => 'فشار خون پایین', 'pronunciation' => '/loʊ blʌd ˈprɛʃər /'],
            ['front' => 'hurt', 'back' => 'درد داشتن', 'pronunciation' => '/hɜːrt /'],
            ['front' => 'sleeveless', 'back' => 'بی‌آستین', 'pronunciation' => '/ˈslivlɪs /'],
            ['front' => 'vomit', 'back' => 'استفراغ کردن', 'pronunciation' => '/ˈvɑːmɪt /'],
            ['front' => 'cotton', 'back' => 'پنبه‌ای (پارچه)', 'pronunciation' => '/ˈkɑtən /'],
            ['front' => 'suit', 'back' => 'آمدن (لباس به فرد)', 'pronunciation' => '/suːt /'],
            ['front' => 'ache', 'back' => 'درد کردن (به‌طور مداوم)', 'pronunciation' => '/eɪk /'],
            ['front' => 'trendy', 'back' => 'به روز', 'pronunciation' => '/ˈtrendi /'],
            ['front' => 'v-neck', 'back' => 'یقه‌هفت', 'pronunciation' => '/ˈviː nek /'],
            ['front' => 'food poisoning', 'back' => 'مسمومیت غذایی', 'pronunciation' => '/fud ˈpɔɪzənɪŋ /'],
            ['front' => 'trick', 'back' => 'گول زدن', 'pronunciation' => '/trɪk /'],
            ['front' => 'EKG machine', 'back' => 'دستگاه الکتروکاردیوگراف', 'pronunciation' => '/i-keɪ-ʤi məˈʃin /'],
            ['front' => 'match', 'back' => 'جور بودن', 'pronunciation' => '/mætʃ /'],
            ['front' => 'vulnerable', 'back' => 'آسیب‌پذیر', 'pronunciation' => '/ˈvʌlnərəbəl /'],
            ['front' => 'collar', 'back' => 'یقه', 'pronunciation' => '/ˈkɑːlər /'],
            ['front' => 'wool', 'back' => 'پشم', 'pronunciation' => '/wʊl /'],
            ['front' => 'hypochondriac', 'back' => 'خودبیمارانگار', 'pronunciation' => '/ˌhaɪpəˈkɑːndriæk /'],
            ['front' => 'lace', 'back' => 'تور', 'pronunciation' => '/leɪs /'],
            ['front' => 'wig', 'back' => 'کلاه‌گیس', 'pronunciation' => '/wɪɡ /'],
            ['front' => 'treat', 'back' => 'درمان کردن', 'pronunciation' => '/trit /'],
            ['front' => 'cold', 'back' => 'سرماخوردگی', 'pronunciation' => '/koʊld /'],
            ['front' => 'heart rate', 'back' => 'میزان تپش قلب', 'pronunciation' => '/hɑrt reɪt /'],
            ['front' => 'press', 'back' => 'فشار دادن', 'pronunciation' => '/pres /'],
            ['front' => 'allergic', 'back' => 'حساسیت (به چیزی)', 'pronunciation' => '/əˈlɜrʤɪk /'],
            ['front' => 'illness', 'back' => 'بیماری', 'pronunciation' => '/ˈɪl.nəs /'],
            ['front' => 'wise', 'back' => 'عاقل', 'pronunciation' => '/wɑɪz /'],
            ['front' => 'surgery', 'back' => 'جراحی', 'pronunciation' => '/ˈsɜr.dʒə.ri /'],
            ['front' => 'pinch', 'back' => 'نیشگون گرفتن', 'pronunciation' => '/pɪntʃ /'],
            ['front' => 'twist', 'back' => 'پیچ خوردن', 'pronunciation' => '/twɪst /'],
            ['front' => 'alternative remedies', 'back' => 'پزشکی جایگزین', 'pronunciation' => '/ɔlˈtɜrnətɪv ˈrɛmədiz /'],
            ['front' => 'fit', 'back' => 'اندازه بودن', 'pronunciation' => '/fɪt /'],
            ['front' => 'cardigan', 'back' => 'ژاکت (پشمی)', 'pronunciation' => '/ˈkɑːrdɪɡən /'],
            ['front' => 'burn', 'back' => 'سوزاندن', 'pronunciation' => '/bɜrn /'],
            ['front' => 'wrinkle', 'back' => 'چروک', 'pronunciation' => '/ˈrɪŋkl /'],
            ['front' => 'pulse', 'back' => 'نبض', 'pronunciation' => '/pʌls /'],
            ['front' => 'collapse', 'back' => 'غش کردن', 'pronunciation' => '/kəˈlæps /'],
            ['front' => 'toothache', 'back' => 'دندان‌درد', 'pronunciation' => '/ˈtuːθeɪk /'],
            ['front' => 'sprain', 'back' => 'پیچ خوردن', 'pronunciation' => '/spreɪn /'],
            ['front' => 'get changed', 'back' => 'لباس عوض کردن', 'pronunciation' => '/gɛt ʧeɪnʤd /'],
            ['front' => 'top', 'back' => 'تاپ', 'pronunciation' => '/tɑːp /'],
            ['front' => 'leather', 'back' => 'چرم', 'pronunciation' => '/ˈleð.ər /'],
            ['front' => 'Lycra', 'back' => 'پارچه لایکرا', 'pronunciation' => '/ˈlaɪkrə /'],
            ['front' => 'bandage', 'back' => 'بانداژ', 'pronunciation' => '/ˈbæn.dɪdʒ /'],
            ['front' => 'throw up', 'back' => 'بالا آوردن', 'pronunciation' => '/θroʊ ʌp /'],
            ['front' => 'hooded', 'back' => 'کلاه‌دار', 'pronunciation' => '/ˈhʊdɪd /'],
            ['front' => 'get undressed', 'back' => 'لباس در آوردن', 'pronunciation' => '/gɛt ənˈdrɛst /'],
            ['front' => 'open heart surgery', 'back' => 'جراحی قلب باز', 'pronunciation' => '/ˈoʊpən hɑrt ˈsɜrʤəri /'],
            ['front' => 'cut', 'back' => 'زخم', 'pronunciation' => '/kʌt /'],
            ['front' => 'pattern', 'back' => 'طرح', 'pronunciation' => '/ˈpæt̬.ərn /'],
            ['front' => 'sandal', 'back' => 'صندل', 'pronunciation' => '/ˈsæn.dəl /'],
            ['front' => 'rash', 'back' => 'خارش', 'pronunciation' => '/ræʃ /'],
            ['front' => 'infection', 'back' => 'عفونت', 'pronunciation' => '/ɪnˈfek.ʃən /'],
            ['front' => 'miracle', 'back' => 'معجزه', 'pronunciation' => '/ˈmɪr.ə.kəl /'],
            ['front' => 'patterned', 'back' => 'طرحدار', 'pronunciation' => '/ˈpætərnd /'],
            ['front' => 'cure', 'back' => 'درمان', 'pronunciation' => '/kjʊr /'],
            ['front' => 'under the weather', 'back' => 'ناخوش‌احوال', 'pronunciation' => '/ˈʌndər ðə ˈwɛðər /'],
            ['front' => 'plaid', 'back' => 'چهارخانه (طرح پارچه)', 'pronunciation' => '/pleɪd /'],
            ['front' => 'lie down', 'back' => 'دراز کشیدن', 'pronunciation' => '/laɪ daʊn /'],
            ['front' => 'flu', 'back' => 'آنفلوآنزا', 'pronunciation' => '/fluː /'],
            ['front' => 'stylish', 'back' => 'شیک', 'pronunciation' => '/ˈstaɪlɪʃ /'],
            ['front' => 'hot air', 'back' => 'حرف مفت', 'pronunciation' => '/ˌhɑːt ˈer /'],
            ['front' => 'choke', 'back' => 'خفه کردن', 'pronunciation' => '/ʧoʊk /'],
            ['front' => 'cut', 'back' => 'بریدن', 'pronunciation' => '/kʌt /'],
            ['front' => 'plain', 'back' => 'ساده', 'pronunciation' => '/pleɪn /'],
            ['front' => 'sneeze', 'back' => 'عطسه کردن', 'pronunciation' => '/sniːz /'],
            ['front' => 'fashionable', 'back' => 'مد روز', 'pronunciation' => '/ˈfæʃnəbl /'],
            ['front' => 'swimsuit', 'back' => 'مایو (زنانه)', 'pronunciation' => '/ˈswɪm.suːt /'],
            ['front' => 'ankle', 'back' => 'مچ پا', 'pronunciation' => '/ˈæŋkəl /'],
            ['front' => 'wound', 'back' => 'زخم', 'pronunciation' => '/wuːnd /'],
            ['front' => 'loose', 'back' => 'گشاد (لباس)', 'pronunciation' => '/luːs /'],
            ['front' => 'suede', 'back' => 'جیر (پارچه)', 'pronunciation' => '/sweɪd /'],
            ['front' => 'scruffy', 'back' => 'کثیف', 'pronunciation' => '/ˈskrʌfi /'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 2 vocabulary added.');
    }

    protected function seedLesson3($deck)
    {
        $vocabulary = [
            ['front' => 'anyway', 'back' => 'به هر حال', 'pronunciation' => '/ˈen.iːˌweɪ /'],
            ['front' => 'illegal', 'back' => 'غیرقانونی', 'pronunciation' => '/ɪˈligəl /'],
            ['front' => 'airport', 'back' => 'فرودگاه', 'pronunciation' => '/ˈerpɔːrt /'],
            ['front' => 'whistle', 'back' => 'سوت زدن', 'pronunciation' => '/ˈwɪs.l /'],
            ['front' => 'smoothie', 'back' => 'اسموتی (نوشیدنی)', 'pronunciation' => '/ˈsmuːði /'],
            ['front' => 'late', 'back' => 'دیر', 'pronunciation' => '/leɪt /'],
            ['front' => 'dandy', 'back' => 'خیلی خوب', 'pronunciation' => '/ˈdændi /'],
            ['front' => 'boarding pass', 'back' => 'کارت عبور', 'pronunciation' => '/ˈbɔrdɪŋ pæs /'],
            ['front' => 'terminal', 'back' => 'پایانه (اتوبوس، هواپیما و...)', 'pronunciation' => '/ˈtɜr.mɪn.əl /'],
            ['front' => 'travel', 'back' => 'سفر کردن', 'pronunciation' => '/ˈtrævl /'],
            ['front' => 'obviously', 'back' => 'بدیهی است که', 'pronunciation' => '/ˈɑb.viː.ə.sli /'],
            ['front' => 'aisle', 'back' => 'راهرو', 'pronunciation' => '/aɪl /'],
            ['front' => 'inside out', 'back' => 'پشت و رو', 'pronunciation' => '/ɪnˈsaɪd aʊt /'],
            ['front' => 'intention', 'back' => 'قصد', 'pronunciation' => '/ɪnˈten.ʃən /'],
            ['front' => 'long-haul flight', 'back' => 'پرواز طولانی', 'pronunciation' => '/lɔŋ-hɔl flaɪt /'],
            ['front' => 'liquid', 'back' => 'مایع', 'pronunciation' => '/ˈlɪkwɪd /'],
            ['front' => 'beg', 'back' => 'التماس کردن', 'pronunciation' => '/bɛg /'],
            ['front' => 'check in', 'back' => 'پذیرش شدن (در هتل، فرودگاه و ...)', 'pronunciation' => '/ʧɛk ɪn /'],
            ['front' => 'recognize', 'back' => 'تشخیص دادن', 'pronunciation' => '/ˈrɛkəgˌnaɪz /'],
            ['front' => 'curling iron', 'back' => 'فر کننده مو', 'pronunciation' => '/ˈkɜːrlɪŋ aɪərn /'],
            ['front' => 'immediately', 'back' => 'فوراً', 'pronunciation' => '/ɪˈmiː.diː.ət.li /'],
            ['front' => 'sharp', 'back' => 'تیز', 'pronunciation' => '/ʃɑːrp /'],
            ['front' => 'drop off', 'back' => 'رساندن', 'pronunciation' => '/drɑp ɔf /'],
            ['front' => 'chop', 'back' => 'گوشت با استخوان', 'pronunciation' => '/tʃɑːp /'],
            ['front' => 'VIP lounge', 'back' => 'سالن تشریفات فرودگاه', 'pronunciation' => '/vi-aɪ-pi laʊnʤ /'],
            ['front' => 'confrontation', 'back' => 'مقابله', 'pronunciation' => '/ˌkɑnfrənˈteɪʃən /'],
            ['front' => 'cabin crew', 'back' => 'خدمه هواپیما', 'pronunciation' => '/ˈkæbən kru /'],
            ['front' => 'gradually', 'back' => 'به تدریج', 'pronunciation' => '/ˈgræʤuəli /'],
            ['front' => 'scan', 'back' => 'اسکن کردن (کامپیوتر، پزشکی)', 'pronunciation' => '/skæn /'],
            ['front' => 'air traffic controller', 'back' => 'کنترل‌کننده آمد و شد هوایی', 'pronunciation' => '/ɛr ˈtræfɪk kənˈtroʊlər /'],
            ['front' => 'chorus', 'back' => 'گروه کر', 'pronunciation' => '/ˈkɔːrəs /'],
            ['front' => 'slightly', 'back' => 'اندکی', 'pronunciation' => '/ˈslɑɪt.li /'],
            ['front' => 'frantic', 'back' => 'بی‌تاب', 'pronunciation' => '/ˈfræntɪk /'],
            ['front' => 'life jacket', 'back' => 'جلیقه نجات', 'pronunciation' => '/laɪf ˈʤækət /'],
            ['front' => 'comb', 'back' => 'شانه (وسیله)', 'pronunciation' => '/koʊm /'],
            ['front' => 'arrivals', 'back' => 'بخش پروازهای ورودی فرودگاه', 'pronunciation' => '/əˈraɪvlz /'],
            ['front' => 'customs', 'back' => 'گمرک', 'pronunciation' => '/ˈkʌs.təmz /'],
            ['front' => 'lately', 'back' => 'اخیرا', 'pronunciation' => '/ˈleɪt.li /'],
            ['front' => 'nearly', 'back' => 'تقریبا', 'pronunciation' => '/ˈnɪr.li /'],
            ['front' => 'specially', 'back' => 'به ویژه', 'pronunciation' => '/ˈspeʃ.ə.li /'],
            ['front' => 'fabulous', 'back' => 'شگفت‌انگیز', 'pronunciation' => '/ˈfæbjələs /'],
            ['front' => 'first class', 'back' => '(صندلی) درجه یک (هواپیما، قطار و ...)', 'pronunciation' => '/fɜrst klæs /'],
            ['front' => 'departures', 'back' => 'پروازهای خروجی (از یک فرودگاه)', 'pronunciation' => '/dɪˈpɑrʧərz /'],
            ['front' => 'board', 'back' => 'سوار (هواپیما و...) شدن', 'pronunciation' => '/bɔrd /'],
            ['front' => 'in the end', 'back' => 'در پایان', 'pronunciation' => '/ɪn ði ɛnd /'],
            ['front' => 'in the end', 'back' => 'در پایان', 'pronunciation' => '/ɪn ði ɛnd /'],
            ['front' => 'seat belt', 'back' => 'کمربند ایمنی (اتومبیل، هواپیما و ...)', 'pronunciation' => '/sit bɛlt /'],
            ['front' => 'fill out', 'back' => 'تکمیل کردن', 'pronunciation' => '/fɪl aʊt /'],
            ['front' => 'penny', 'back' => 'پنی', 'pronunciation' => '/ˈpen.i /'],
            ['front' => 'ever', 'back' => 'همیشه', 'pronunciation' => '/ˈev.ər /'],
            ['front' => 'take off', 'back' => 'از زمین بلند شدن (هواپیما)', 'pronunciation' => '/teɪk ɔf /'],
            ['front' => 'at the end', 'back' => 'در پایان', 'pronunciation' => '/æt ði ɛnd /'],
            ['front' => 'carry-on', 'back' => 'ساک دستی', 'pronunciation' => '/ˈkæri ɑːn /'],
            ['front' => 'get off', 'back' => 'پیاده شدن (از)', 'pronunciation' => '/gɛt ɔf /'],
            ['front' => 'even', 'back' => 'حتی', 'pronunciation' => '/ˈIː.vən /'],
            ['front' => 'travel', 'back' => 'سفر', 'pronunciation' => '/ˈtrævl /'],
            ['front' => 'bag drop off', 'back' => 'محل تحویل چمدان (فرودگاه)', 'pronunciation' => '/bæg drɑp ɔf /'],
            ['front' => 'goods', 'back' => 'کالا', 'pronunciation' => '/gʊdz /'],
            ['front' => 'domestic', 'back' => 'داخلی', 'pronunciation' => '/dəˈmes.tɪk /'],
            ['front' => 'safety demonstration', 'back' => 'توضیح اقدامات ایمنی در هواپیما (توسط مهماندار)', 'pronunciation' => '/ˈseɪfti ˌdɛmənˈstreɪʃən /'],
            ['front' => 'luggage', 'back' => 'چمدان', 'pronunciation' => '/ˈlʌg.ɪdʒ /'],
            ['front' => 'trip', 'back' => 'سفر', 'pronunciation' => '/trɪp /'],
            ['front' => 'get on', 'back' => 'سوار شدن', 'pronunciation' => '/gɛt ɑn /'],
            ['front' => 'grocer', 'back' => 'خواربار فروش', 'pronunciation' => '/ˈɡroʊsər /'],
            ['front' => 'connecting flight', 'back' => 'پرواز غیرمستقیم', 'pronunciation' => '/kəˈnɛktɪŋ flaɪt /'],
            ['front' => 'journey', 'back' => 'سفر', 'pronunciation' => '/ˈdʒɜr.ni /'],
            ['front' => 'hardly', 'back' => 'به‌سختی', 'pronunciation' => '/hɑrd.li /'],
            ['front' => 'international', 'back' => 'بین‌المللی', 'pronunciation' => '/ˌɪn.tərˈnæʃ.ən.əl /'],
            ['front' => 'shabby', 'back' => 'رنگ و رو رفته', 'pronunciation' => '/ˈʃæbi /'],
            ['front' => 'in fact', 'back' => 'در حقیقت', 'pronunciation' => '/ɪn fækt /'],
            ['front' => 'baggage drop off', 'back' => 'محل تحویل چمدان (فرودگاه)', 'pronunciation' => '/ˈbægəʤ drɑp ɔf /'],
            ['front' => 'flight', 'back' => 'پرواز', 'pronunciation' => '/flɑɪt /'],
            ['front' => 'damage', 'back' => 'صدمه', 'pronunciation' => '/ˈdæmɪdʒ /'],
            ['front' => 'garment', 'back' => 'لباس', 'pronunciation' => '/ˈɡɑːrmənt /'],
            ['front' => 'still', 'back' => 'هنوز', 'pronunciation' => '/stɪl /'],
            ['front' => 'turbulence', 'back' => 'تلاطم', 'pronunciation' => '/ˈtɜrbjələns /'],
            ['front' => 'land', 'back' => 'فرود آمدن', 'pronunciation' => '/lænd /'],
            ['front' => 'long for', 'back' => 'از ته دل خواستن', 'pronunciation' => '/lɔŋ fɔr /'],
            ['front' => 'damage', 'back' => 'آسیب رساندن', 'pronunciation' => '/ˈdæmɪdʒ /'],
            ['front' => 'tear', 'back' => 'اشک', 'pronunciation' => '/ter /'],
            ['front' => 'departures board', 'back' => 'تابلوی اعلانات پروازهای خروجی', 'pronunciation' => '/dɪˈpɑrʧərz bɔrd /'],
            ['front' => 'on time', 'back' => 'به موقع', 'pronunciation' => '/ɑn taɪm /'],
            ['front' => 'yet', 'back' => 'هنوز', 'pronunciation' => '/jet /'],
            ['front' => 'hesitate', 'back' => 'تعلل کردن', 'pronunciation' => '/ˈhɛzəˌteɪt /'],
            ['front' => 'gate', 'back' => 'گیت (فرودگاه)', 'pronunciation' => '/geɪt /'],
            ['front' => 'intake', 'back' => 'مصرف (مواد غذایی)', 'pronunciation' => '/ˈɪnteɪk /'],
            ['front' => 'hard', 'back' => 'سخت', 'pronunciation' => '/hɑːrd /'],
            ['front' => 'baggage claim', 'back' => 'محل دریافت بار/چمدان (فرودگاه)', 'pronunciation' => '/ˈbægəʤ kleɪm /'],
            ['front' => 'emergency', 'back' => '(وضعیت) اضطراری', 'pronunciation' => '/ɪˈmɜrʤənsi /'],
            ['front' => 'sparkle', 'back' => 'درخشیدن', 'pronunciation' => '/ˈspɑːrkl /'],
            ['front' => 'boarding', 'back' => 'عمل سوار شدن (هواپیما و ...)', 'pronunciation' => '/ˈbɔrdɪŋ /'],
            ['front' => 'eventually', 'back' => 'در نهایت', 'pronunciation' => '/əˈven.tʃu.əl.i /'],
            ['front' => 'collect', 'back' => 'گرفتن', 'pronunciation' => '/kəˈlekt /'],
            ['front' => 'pant', 'back' => 'نفس نفس زدن', 'pronunciation' => '/pænt /'],
            ['front' => 'engine', 'back' => 'موتور', 'pronunciation' => '/ˈen.dʒən /'],
            ['front' => 'check-in desk', 'back' => 'میز پذیرش (هتل، فرودگاه و ...)', 'pronunciation' => '/ʧɛk-ɪn dɛsk /'],
            ['front' => 'right now', 'back' => 'همین الان', 'pronunciation' => '/raɪt naʊ /'],
            ['front' => 'ideally', 'back' => 'به طور ایده‌آل', 'pronunciation' => '/ɑɪˈdiːl.i /'],
            ['front' => 'closed', 'back' => 'بسته', 'pronunciation' => '/kloʊzd /'],
            ['front' => 'runway', 'back' => 'باند فرودگاه', 'pronunciation' => '/ˈrʌnweɪ /'],
            ['front' => 'cart', 'back' => 'چرخ‌دستی', 'pronunciation' => '/kɑrt /'],
            ['front' => 'on board', 'back' => 'سوار (کشتی یا هواپیما)', 'pronunciation' => '/ɑn bɔrd /'],
            ['front' => 'delayed', 'back' => 'به تاخیر افتاده', 'pronunciation' => '/dɪˈleɪd /'],
            ['front' => 'actually', 'back' => 'درواقع', 'pronunciation' => '/ˈæk.tʃu.ə.li /'],
            ['front' => 'basically', 'back' => 'اساسا', 'pronunciation' => '/ˈbeɪ.sɪk.li /'],
            ['front' => 'security', 'back' => 'گیت بازرسی', 'pronunciation' => '/sɪˈkjʊrəti /'],
            ['front' => 'baggage', 'back' => 'چمدان', 'pronunciation' => '/ˈbægəʤ /'],
            ['front' => 'announcement', 'back' => 'اطلاعیه', 'pronunciation' => '/əˈnɑʊn.smənt /'],
            ['front' => 'direct flight', 'back' => 'پرواز مستقیم', 'pronunciation' => '/dəˈrɛkt flaɪt /'],
            ['front' => 'especially', 'back' => 'مخصوصاً', 'pronunciation' => '/ɪˈspeʃ.əl.i /'],
            ['front' => 'journey', 'back' => 'مسافرت کردن', 'pronunciation' => '/ˈdʒɜr.ni /'],
            ['front' => 'pick up', 'back' => 'تحویل گرفتن', 'pronunciation' => '/pɪk ʌp /'],
            ['front' => 'apparently', 'back' => 'ظاهرا', 'pronunciation' => '/əˈpɛrəntli /'],
            ['front' => 'smuggle', 'back' => 'قاچاق کردن', 'pronunciation' => '/ˈsmʌɡl /'],
            ['front' => 'check', 'back' => 'تحویل دادن (بار و ...)', 'pronunciation' => '/tʃek /'],
            ['front' => 'jet lag', 'back' => 'پرواززدگی', 'pronunciation' => '/ʤɛt læg /'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 3 vocabulary added.');
    }

    protected function seedLesson4($deck)
    {
        $vocabulary = [
            ['front' => 'damp', 'back' => 'مرطوب', 'pronunciation' => '/dæmp/'],
            ['front' => 'take after', 'back' => 'به کسی رفتن', 'pronunciation' => '/teɪk ˈæftər/'],
            ['front' => 'install', 'back' => 'نصب کردن', 'pronunciation' => '/ɪnˈstɔːl/'],
            ['front' => 'speed', 'back' => 'سرعت', 'pronunciation' => '/spiːd/'],
            ['front' => 'rage', 'back' => 'تلاطم', 'pronunciation' => '/reɪʤ/'],
            ['front' => 'take place', 'back' => 'برگزار شدن', 'pronunciation' => '/teɪk pleɪs/'],
            ['front' => 'potentially', 'back' => '(به طور) بالقوه', 'pronunciation' => '/pəˈten.tʃə.li/'],
            ['front' => 'drive someone nuts', 'back' => 'کسی را عصبانی کردن', 'pronunciation' => '/draɪv ˈsʌmˌwʌn nʌts/'],
            ['front' => 'shovelful', 'back' => '(به اندازه) یک بیل', 'pronunciation' => '/ˈʃʌvlfʊl/'],
            ['front' => 'risky', 'back' => 'پرمخاطره', 'pronunciation' => '/ˈrɪs.ki/'],
            ['front' => 'drizzling', 'back' => 'بارانی', 'pronunciation' => '/ˈdrɪzlɪŋ/'],
            ['front' => 'reusable', 'back' => 'قابل استفاده مجدد', 'pronunciation' => '/ˌriːˈjuːzəbl/'],
            ['front' => 'addicted', 'back' => 'معتاد', 'pronunciation' => '/əˈdɪk.tɪd/'],
            ['front' => 'freezing', 'back' => 'منجمد', 'pronunciation' => '/ˈfriː.zɪŋ/'],
            ['front' => 'sense', 'back' => 'حس', 'pronunciation' => '/sens/'],
            ['front' => 'humid', 'back' => 'مرطوب (آب‌وهوا)', 'pronunciation' => '/ˈhjuməd/'],
            ['front' => 'charity', 'back' => 'خیریه (موسسه و سازمان)', 'pronunciation' => '/ˈʧɛrɪti/'],
            ['front' => 'heat wave', 'back' => 'موج گرما', 'pronunciation' => '/hit weɪv/'],
            ['front' => 'get caught', 'back' => 'گیر افتادن', 'pronunciation' => '/gɛt kɑt/'],
            ['front' => 'take part', 'back' => 'شرکت کردن', 'pronunciation' => '/teɪk pɑrt/'],
            ['front' => 'recyclable', 'back' => 'قابل بازیافت', 'pronunciation' => '/riˈsaɪkləbəl/'],
            ['front' => 'mild', 'back' => 'ملایم', 'pronunciation' => '/mɑɪld/'],
            ['front' => 'take seriously', 'back' => 'جدی گرفتن', 'pronunciation' => '/teɪk ˈsɪriəsli/'],
            ['front' => 'electrical charge', 'back' => 'بار الکتریکی', 'pronunciation' => '/ɪˈlɛktrɪkəl ʧɑrʤ/'],
            ['front' => 'make tempers boil', 'back' => 'عصبانی کردن', 'pronunciation' => '/meɪk ˈtɛmpərz bɔɪl/'],
            ['front' => 'ban', 'back' => 'قدغن کردن', 'pronunciation' => '/bæn/'],
            ['front' => 'run out', 'back' => 'تمام شدن', 'pronunciation' => '/rʌn aʊt/'],
            ['front' => 'global warming', 'back' => 'گرمایش جهانی', 'pronunciation' => '/ˌgloʊ.bəlˈwɔːr.mɪŋ/'],
            ['front' => 'take one\'s time', 'back' => 'عجله نکردن', 'pronunciation' => '/teɪk wʌnz taɪm/'],
            ['front' => 'cut down', 'back' => 'قطع کردن', 'pronunciation' => '/kʌt daʊn/'],
            ['front' => 'take care', 'back' => 'مراقب بودن', 'pronunciation' => '/teɪk kɛr/'],
            ['front' => 'take off', 'back' => 'از زمین بلند شدن (هواپیما)', 'pronunciation' => '/teɪk ɔf/'],
            ['front' => 'pouring', 'back' => 'شدیدا بارانی', 'pronunciation' => '/ˈpɔːrɪŋ/'],
            ['front' => 'ion', 'back' => 'یون', 'pronunciation' => '/ˈaɪən/'],
            ['front' => 'cognition', 'back' => 'ادراک', 'pronunciation' => '/kɑgˈnɪʃən/'],
            ['front' => 'shower', 'back' => 'رگبار (باران یا برف)', 'pronunciation' => '/ˈʃɑʊər/'],
            ['front' => 'warm', 'back' => 'گرم', 'pronunciation' => '/wɔrm/'],
            ['front' => 'to take advantage of', 'back' => 'بهره بردن', 'pronunciation' => '/tə tˈeɪk ɐdvˈæntɪdʒ ʌv/'],
            ['front' => 'desert wind', 'back' => 'باد کویری', 'pronunciation' => '/ˈdɛzɜrt wɪnd/'],
            ['front' => 'below', 'back' => 'زیر', 'pronunciation' => '/bɪˈləʊ/'],
            ['front' => 'take up', 'back' => '(انجام یا یادگیری کاری را) شروع کردن', 'pronunciation' => '/teɪk ʌp/'],
            ['front' => 'forecast', 'back' => 'پیش‌بینی', 'pronunciation' => '/ˈfɔːrkæst/'],
            ['front' => 'take into account', 'back' => 'در نظر گرفتن', 'pronunciation' => '/teɪk ˈɪntu əˈkaʊnt/'],
            ['front' => 'boiling', 'back' => 'بسیار گرم', 'pronunciation' => '/ˈbɔɪ.lɪŋ/'],
            ['front' => 'take out', 'back' => 'سند، مدرک یا وام گرفتن', 'pronunciation' => '/teɪk aʊt/'],
            ['front' => 'extreme', 'back' => 'شدید', 'pronunciation' => '/ɛkˈstrim/'],
            ['front' => 'change', 'back' => 'تغییر', 'pronunciation' => '/tʃeɪndʒ/'],
            ['front' => 'break', 'back' => 'شکستن (قانون، قول و ...)', 'pronunciation' => '/breɪk/'],
            ['front' => 'get straight to the point', 'back' => 'سر اصل مطلب رفتن', 'pronunciation' => '/gɛt streɪt tu ðə pɔɪnt/'],
            ['front' => 'temperature', 'back' => 'دما', 'pronunciation' => '/ˈtemprətʃər/'],
            ['front' => 'speed limit', 'back' => 'سرعت مجاز', 'pronunciation' => '/spid ˈlɪmət/'],
            ['front' => 'breeze', 'back' => 'نسیم', 'pronunciation' => '/briːz/'],
            ['front' => 'blizzard', 'back' => 'کولاک', 'pronunciation' => '/ˈblɪzərd/'],
            ['front' => 'chilly', 'back' => 'سرد', 'pronunciation' => '/ˈʧɪli/'],
            ['front' => 'drought', 'back' => 'خشکسالی', 'pronunciation' => '/draʊt/'],
            ['front' => 'solar panel', 'back' => 'صفحه خورشیدی', 'pronunciation' => '/ˌsoʊlər ˈpænl/'],
            ['front' => 'fatal', 'back' => 'زیان‌بار', 'pronunciation' => '/ˈfeɪt̬.əl/'],
            ['front' => 'susceptible', 'back' => 'حساس', 'pronunciation' => '/səˈsɛptəbəl/'],
            ['front' => 'cool', 'back' => 'خنک', 'pronunciation' => '/kuːl/'],
            ['front' => 'in advance', 'back' => 'از پیش', 'pronunciation' => '/ɪn ədˈvæns/'],
            ['front' => 'flood', 'back' => 'سیل', 'pronunciation' => '/flʌd/'],
            ['front' => 'take risk', 'back' => 'خطر کردن', 'pronunciation' => '/teɪk rɪsk/'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 4 vocabulary added.');
    }

    protected function seedLesson5($deck)
    {
        $vocabulary = [
            ['front' => 'depressed', 'back' => 'افسرده', 'pronunciation' => '/dɪˈprest /'],
            ['front' => 'stressed', 'back' => 'مضطرب', 'pronunciation' => '/strest /'],
            ['front' => 'lay the blame at somebody else\'s door', 'back' => 'تقصیر را گردن دیگری انداختن', 'pronunciation' => '/leɪ ðə bleɪm æt ˈsʌmˌbɑdi ˈɛlsɪz dɔr /'],
            ['front' => 'sick and tired', 'back' => 'خسته', 'pronunciation' => '/sɪk ænd ˈtaɪərd /'],
            ['front' => 'keep calm', 'back' => 'خونسردی خود را حفظ کردن', 'pronunciation' => '/kip kɑm /'],
            ['front' => 'sad', 'back' => 'غمگین', 'pronunciation' => '/sæd /'],
            ['front' => 'lonely', 'back' => 'تنها', 'pronunciation' => '/ˈloʊn.li /'],
            ['front' => 'thrilling', 'back' => 'هیجان‌انگیز', 'pronunciation' => '/ˈθrɪl.ɪŋ /'],
            ['front' => 'stressful', 'back' => 'پراسترس', 'pronunciation' => '/ˈstrɛsfəl /'],
            ['front' => 'grateful', 'back' => 'سپاسگزار', 'pronunciation' => '/ˈgreɪtfəl /'],
            ['front' => 'absolutely', 'back' => 'مسلماً', 'pronunciation' => '/ˈæb.səˌluːt.li /'],
            ['front' => 'happy', 'back' => 'خوشحال', 'pronunciation' => '/ˈhæp.i /'],
            ['front' => 'survival', 'back' => 'بقا', 'pronunciation' => '/sərˈvɑɪ.vəl /'],
            ['front' => 'love life', 'back' => 'روابط جنسی و عاشقانه یک فرد', 'pronunciation' => '/ˈlʌv laɪf /'],
            ['front' => 'overcome', 'back' => 'غالب آمدن', 'pronunciation' => '/ˈoʊvərˌkʌm /'],
            ['front' => 'scared', 'back' => 'ترسیده', 'pronunciation' => '/skeəd /'],
            ['front' => 'shocked', 'back' => 'بهت‌زده', 'pronunciation' => '/ʃɑkt /'],
            ['front' => 'really', 'back' => 'واقعاً', 'pronunciation' => '/ˈriː.li /'],
            ['front' => 'task', 'back' => 'کار', 'pronunciation' => '/tæsk /'],
            ['front' => 'bewildered', 'back' => 'گیج', 'pronunciation' => '/bɪˈwɪldərd /'],
            ['front' => 'relieved', 'back' => 'آرام شده', 'pronunciation' => '/rɪˈliːvd /'],
            ['front' => 'delighted', 'back' => 'شادمان', 'pronunciation' => '/dəˈlɑɪt̬.ɪd /'],
            ['front' => 'annoy', 'back' => 'آزار دادن', 'pronunciation' => '/əˈnɔɪ /'],
            ['front' => 'amaze', 'back' => 'شگفت‌زده کردن', 'pronunciation' => '/əˈmeɪz /'],
            ['front' => 'argue', 'back' => 'بحث کردن', 'pronunciation' => '/ˈɑr.gjuː /'],
            ['front' => 'guilty', 'back' => 'گناهکار', 'pronunciation' => '/ˈgɪl.ti /'],
            ['front' => 'panic', 'back' => 'هراس', 'pronunciation' => '/ˈpænɪk /'],
            ['front' => 'amazed', 'back' => 'متحیر', 'pronunciation' => '/əˈmeɪzd /'],
            ['front' => 'career', 'back' => 'شغل', 'pronunciation' => '/kəˈrɪr /'],
            ['front' => 'scary', 'back' => 'ترسناک', 'pronunciation' => '/ˈskɛri /'],
            ['front' => 'stunned', 'back' => 'بهت زده', 'pronunciation' => '/stʌnd /'],
            ['front' => 'remote', 'back' => 'دوردست', 'pronunciation' => '/rɪˈmoʊt /'],
            ['front' => 'annoying', 'back' => 'آزاردهنده', 'pronunciation' => '/əˈnɔɪ.ɪŋ /'],
            ['front' => 'amazing', 'back' => 'شگفت‌آور', 'pronunciation' => '/əˈmeɪ.zɪŋ /'],
            ['front' => 'desperate', 'back' => 'ناامیدانه', 'pronunciation' => '/ˈdes.pə.rət /'],
            ['front' => 'infuriate', 'back' => '(به‌شدت) خشمگین کردن', 'pronunciation' => '/ɪnˈfjʊriˌeɪt /'],
            ['front' => 'embarrass', 'back' => 'شرمنده کردن', 'pronunciation' => '/ɪmˈbɛrəs /'],
            ['front' => 'totally', 'back' => 'کاملاً', 'pronunciation' => '/ˈtoʊt̬.əl.i /'],
            ['front' => 'frustrate', 'back' => 'مستأصل کردن', 'pronunciation' => '/ˈfrʌstreɪt /'],
            ['front' => 'fed up', 'back' => 'خسته', 'pronunciation' => '/ˌfedˈʌp /'],
            ['front' => 'delightful', 'back' => 'جذاب', 'pronunciation' => '/dəˈlɑɪt.fəl /'],
            ['front' => 'scared stiff', 'back' => 'وحشت‌زده', 'pronunciation' => '/skɛrd stɪf /'],
            ['front' => 'embarrassed', 'back' => 'خجالت‌زده', 'pronunciation' => '/ɪmˈbær.əst /'],
            ['front' => 'completely', 'back' => 'کاملا', 'pronunciation' => '/kəmˈpliːt.li /'],
            ['front' => 'give up', 'back' => 'ترک کردن', 'pronunciation' => '/gɪv ʌp /'],
            ['front' => 'terrify', 'back' => 'سخت ترساندن', 'pronunciation' => '/ˈter.ə.faɪ /'],
            ['front' => 'exhausted', 'back' => 'به‌شدت خسته', 'pronunciation' => '/ɪgˈzɑstəd /'],
            ['front' => 'impressed', 'back' => 'تحت تاثیر قرار گرفته', 'pronunciation' => '/ɪmˈprest /'],
            ['front' => 'rescue', 'back' => 'نجات دادن', 'pronunciation' => '/ˈres.kjuː /'],
            ['front' => 'devastated', 'back' => 'بسیار ناراحت', 'pronunciation' => '/ˈdɛvəˌsteɪtəd /'],
            ['front' => 'bored', 'back' => 'کسل', 'pronunciation' => '/bɔrd /'],
            ['front' => 'embarrassing', 'back' => 'شرم‌آور', 'pronunciation' => '/ɪmˈbær.ə.sɪŋ /'],
            ['front' => 'terrifying', 'back' => 'وحشتناک', 'pronunciation' => '/ˈtɛrəˌfaɪɪŋ /'],
            ['front' => 'offensive', 'back' => 'توهین‌آمیز', 'pronunciation' => '/əˈfen.sɪv /'],
            ['front' => 'get on the property ladder', 'back' => 'اولین خانه خود را خریدن', 'pronunciation' => '/gɛt ɑn ðə ˈprɑpərti ˈlædər /'],
            ['front' => 'worn out', 'back' => 'خسته‌وکوفته', 'pronunciation' => '/wɔrn aʊt /'],
            ['front' => 'set off', 'back' => 'عازم شدن', 'pronunciation' => '/sɛt ɔf /'],
            ['front' => 'impressive', 'back' => 'تحسین‌برانگیز', 'pronunciation' => '/ɪmˈprɛsɪv /'],
            ['front' => 'jump for joy', 'back' => 'بسیار خوشحال شدن', 'pronunciation' => '/ʤʌmp fɔr ʤɔɪ /'],
            ['front' => 'down', 'back' => 'غمگین', 'pronunciation' => '/dɑʊn /'],
            ['front' => 'frustrated', 'back' => 'درمانده', 'pronunciation' => '/ˈfrʌˌstreɪtəd /'],
            ['front' => 'inspire', 'back' => 'ترغیب کردن', 'pronunciation' => '/ɪnˈspaɪr /'],
            ['front' => 'believe one\'s eyes', 'back' => 'آنچه را دیدن باور کردن', 'pronunciation' => '/bɪˈliv wʌnz aɪz /'],
            ['front' => 'proud', 'back' => 'مفتخر', 'pronunciation' => '/prɑʊd /'],
            ['front' => 'unhappy', 'back' => 'ناراحت', 'pronunciation' => '/ʌnˈhæp.i /'],
            ['front' => 'challenge', 'back' => 'به چالش کشیدن', 'pronunciation' => '/ˈʧælənʤ /'],
            ['front' => 'terrified', 'back' => 'وحشت‌زده', 'pronunciation' => '/ˈter.ə.fɑɪd /'],
            ['front' => 'irritated', 'back' => 'آزرده', 'pronunciation' => '/ˈɪr.əˌteɪ.t̬ɪd /'],
            ['front' => 'thrilled', 'back' => 'هیجان‌زده', 'pronunciation' => '/θrɪld /'],
            ['front' => 'on average', 'back' => 'معمولا', 'pronunciation' => '/ɑn ˈævərɪʤ /'],
            ['front' => 'frustrating', 'back' => 'آزاردهنده', 'pronunciation' => '/ˈfrʌˌstreɪtɪŋ /'],
            ['front' => 'offended', 'back' => 'دلخور', 'pronunciation' => '/əˈfendɪd /'],
            ['front' => 'regret', 'back' => 'پشیمانی', 'pronunciation' => '/rɪˈgret /'],
            ['front' => 'nervous', 'back' => 'مضطرب', 'pronunciation' => '/ˈnɜr.vəs /'],
            ['front' => 'overwhelmed', 'back' => 'متاثر', 'pronunciation' => '/ˌoʊvərˈwelmd /'],
            ['front' => 'regret', 'back' => 'پشیمان شدن', 'pronunciation' => '/rɪˈgret /'],
            ['front' => 'exhaust', 'back' => '(به‌شدت) خسته کردن', 'pronunciation' => '/ɪgˈzɑst /'],
            ['front' => 'infuriated', 'back' => 'خشمگین', 'pronunciation' => '/ɪnˈfjʊrieɪtɪd /'],
            ['front' => 'exhausting', 'back' => 'بسیار خسته‌کننده', 'pronunciation' => '/ɪgˈzɔː.stɪŋ /'],
            ['front' => 'infuriating', 'back' => 'آزاردهنده', 'pronunciation' => '/ɪnˈfjʊriˌeɪtɪŋ /'],
            ['front' => 'learn', 'back' => 'درس (عبرت) گرفتن', 'pronunciation' => '/lɜːrn /'],
            ['front' => 'upset', 'back' => 'ناراحت', 'pronunciation' => '/ʌpˈset /'],
            ['front' => 'confuse', 'back' => 'گیج کردن', 'pronunciation' => '/kənˈfjuz /'],
            ['front' => 'make up', 'back' => 'آشتی کردن', 'pronunciation' => '/meɪk ʌp /'],
            ['front' => 'disappoint', 'back' => 'مایوس کردن', 'pronunciation' => '/ˌdɪs.əˈpɔɪnt /'],
            ['front' => 'confused', 'back' => 'گیج', 'pronunciation' => '/kənˈfjuːzd /'],
            ['front' => 'homesick', 'back' => 'دلتنگی (برای وطن)', 'pronunciation' => '/ˈhoʊmˌsɪk /'],
            ['front' => 'inspired', 'back' => 'باانگیزه', 'pronunciation' => '/ɪnˈspaɪərd /'],
            ['front' => 'confusing', 'back' => 'گیج‌کننده', 'pronunciation' => '/kənˈfjuː.zɪŋ /'],
            ['front' => 'drive crazy', 'back' => 'آزردن (کسی)', 'pronunciation' => '/draɪv ˈkreɪzi /'],
            ['front' => 'astonished', 'back' => 'متحیر', 'pronunciation' => '/əˈstɑn.ɪʃt /'],
            ['front' => 'disappointing', 'back' => 'مأیوس‌کننده', 'pronunciation' => '/ˌdɪs.əˈpɔɪnt.ɪŋ /'],
            ['front' => 'disappointed', 'back' => 'ناامید', 'pronunciation' => '/ˌdɪs.əˈpɔɪnt.əd /'],
            ['front' => 'horrified', 'back' => 'وحشت‌زده', 'pronunciation' => '/ˈhɔːrɪfaɪd /'],
            ['front' => 'thrill', 'back' => 'به هیجان آوردن', 'pronunciation' => '/θrɪl /'],
            ['front' => 'inspiring', 'back' => 'الهام‌بخش', 'pronunciation' => '/ɪnˈspaɪrɪŋ /'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 5 vocabulary added.');
    }

    protected function seedLesson6($deck)
    {
        $vocabulary = [
            ['front' => 'fall asleep', 'back' => 'به خواب رفتن', 'pronunciation' => '/fɔl əˈslip/'],
            ['front' => 'orchestra', 'back' => 'ارکستر', 'pronunciation' => '/ˈɔːr.kɪ.strə/'],
            ['front' => 'villa', 'back' => 'ویلا', 'pronunciation' => '/ˈvɪlə/'],
            ['front' => 'pillow', 'back' => 'بالش', 'pronunciation' => '/ˈpɪl.oʊ/'],
            ['front' => 'chauffeur', 'back' => 'شوفر', 'pronunciation' => '/ʃoʊˈfɜːr/'],
            ['front' => 'soprano', 'back' => 'سوپرانو (زیرترین صدا)', 'pronunciation' => '/səˈprɑːnoʊ/'],
            ['front' => 'syndrome', 'back' => 'نشانگان', 'pronunciation' => '/ˈsɪndroʊm/'],
            ['front' => 'sheet', 'back' => 'روتختی', 'pronunciation' => '/ʃiːt/'],
            ['front' => 'piece', 'back' => 'قطعه', 'pronunciation' => '/piːs/'],
            ['front' => 'chef', 'back' => 'آشپز (حرفه‌ای)', 'pronunciation' => '/ʃef/'],
            ['front' => 'profoundly', 'back' => 'عمیقا', 'pronunciation' => '/proʊˈfaʊndli/'],
            ['front' => 'jet-lagged', 'back' => 'پرواززده', 'pronunciation' => '/ˈdʒet læɡd/'],
            ['front' => 'virtual reality', 'back' => 'واقعیت مجازی', 'pronunciation' => '/ˌvɜr.tʃu.əl.riːˈæl.ət̬.i/'],
            ['front' => 'sleepy', 'back' => 'خواب‌آلود', 'pronunciation' => '/ˈsliːp.i/'],
            ['front' => 'rhythm', 'back' => 'ریتم', 'pronunciation' => '/ˈrɪðəm/'],
            ['front' => 'alarm', 'back' => 'ساعت زنگدار', 'pronunciation' => '/əˈlɑrm/'],
            ['front' => 'solo', 'back' => 'تک‌نوازی', 'pronunciation' => '/ˈsoʊloʊ/'],
            ['front' => 'weep', 'back' => 'گریه کردن', 'pronunciation' => '/wiːp/'],
            ['front' => 'symphony', 'back' => 'سمفونی', 'pronunciation' => '/ˈsɪmfəni/'],
            ['front' => 'blanket', 'back' => 'پتو', 'pronunciation' => '/ˈblæŋ.kɪt/'],
            ['front' => 'chic', 'back' => 'شیک', 'pronunciation' => '/ʃiːk/'],
            ['front' => 'flute', 'back' => 'فلوت', 'pronunciation' => '/flut/'],
            ['front' => 'ballet', 'back' => 'باله (رقص)', 'pronunciation' => '/bælˈeɪ/'],
            ['front' => 'nightmare', 'back' => 'کابوس', 'pronunciation' => '/ˈnɑɪt.mer/'],
            ['front' => 'croissant', 'back' => 'کروسان', 'pronunciation' => '/krəˈsɑːnt/'],
            ['front' => 'oversleep', 'back' => 'خواب ماندن', 'pronunciation' => '/ˌoʊvərˈslip/'],
            ['front' => 'violin', 'back' => 'ویولن', 'pronunciation' => '/ˌvɑɪ.əˈlɪn/'],
            ['front' => 'snore', 'back' => 'خروپف کردن', 'pronunciation' => '/snɔːr/'],
            ['front' => 'encore', 'back' => 'اجرای اضافه (در آخر کنسرت)', 'pronunciation' => '/ˈɑːŋkɔːr/'],
            ['front' => 'bass guitar', 'back' => 'گیتار بیس', 'pronunciation' => '/beɪs gɪˈtɑr/'],
            ['front' => 'fiancé', 'back' => 'نامزد (مذکر)', 'pronunciation' => '/ˌfiːɑːnˈseɪ/'],
            ['front' => 'keyboard', 'back' => 'کیبورد (موسیقی)', 'pronunciation' => '/ˈkiː.bɔːrd/'],
            ['front' => 'genre', 'back' => 'ژانر', 'pronunciation' => '/ˈʒɑːnrə/'],
            ['front' => 'awake', 'back' => 'بیدار', 'pronunciation' => '/əˈweɪk/'],
            ['front' => 'cacophony', 'back' => 'صدای گوش خراش', 'pronunciation' => '/kəˈkɑːfəni/'],
            ['front' => 'yawn', 'back' => 'خمیازه کشیدن', 'pronunciation' => '/jɔn/'],
            ['front' => 'deaf', 'back' => 'ناشنوا', 'pronunciation' => '/def/'],
            ['front' => 'architecture', 'back' => 'معماری', 'pronunciation' => '/ˈɑrkəˌtɛkʧər/'],
            ['front' => 'saxophone', 'back' => 'ساکسوفون', 'pronunciation' => '/ˈsæksəˌfoʊn/'],
            ['front' => 'insomnia', 'back' => 'بی‌خوابی', 'pronunciation' => '/ɪnˈsɑm.ni.ə/'],
            ['front' => 'move', 'back' => 'متاثر ساختن', 'pronunciation' => '/muːv/'],
            ['front' => 'century', 'back' => 'قرن', 'pronunciation' => '/ˈsɛnʧəri/'],
            ['front' => 'set', 'back' => 'کوک کردن', 'pronunciation' => '/set/'],
            ['front' => 'graffiti', 'back' => 'دیوارنگاری', 'pronunciation' => '/ɡrəˈfiːti/'],
            ['front' => 'deep', 'back' => 'عمیق', 'pronunciation' => '/diːp/'],
            ['front' => 'choir', 'back' => 'گروه کر', 'pronunciation' => '/kwɑɪr/'],
            ['front' => 'hypochondriac', 'back' => 'خودبیمارانگار', 'pronunciation' => '/ˌhaɪpəˈkɑːndriæk/'],
            ['front' => 'paparazzi', 'back' => 'عکاسان', 'pronunciation' => '/ˌpæpəˈrætsi/'],
            ['front' => 'philosophy', 'back' => 'فلسفه', 'pronunciation' => '/fəˈlɑsəfi/'],
            ['front' => 'sleeping pill', 'back' => 'قرص خواب', 'pronunciation' => '/ˈsliːpɪŋ pɪl/'],
            ['front' => 'fast asleep', 'back' => 'خوابیده', 'pronunciation' => '/fæst əˈslip/'],
            ['front' => 'concerto', 'back' => 'کنسرتو', 'pronunciation' => '/kənˈtʃɜːrtoʊ/'],
            ['front' => 'sleep like a log', 'back' => 'به خواب سنگین فرو رفتن', 'pronunciation' => '/slip laɪk ə lɔg/'],
            ['front' => 'photograph', 'back' => 'عکس', 'pronunciation' => '/ˈfoʊt̬.əˌgræf/'],
            ['front' => 'nightfall', 'back' => 'هنگام غروب', 'pronunciation' => '/ˈnaɪtfɔːl/'],
            ['front' => 'conductor', 'back' => 'رهبر ارکستر', 'pronunciation' => '/kənˈdʌktər/'],
            ['front' => 'loyal', 'back' => 'وفادار', 'pronunciation' => '/ˈlɔɪ.əl/'],
            ['front' => 'mezzo-soprano', 'back' => 'متزو-سوپرانو', 'pronunciation' => '/ˌmetsoʊ səˈprɑːnoʊ/'],
            ['front' => 'barista', 'back' => 'باریستا', 'pronunciation' => '/bəˈriːstə/'],
            ['front' => 'nap', 'back' => 'چرت', 'pronunciation' => '/næp/'],
            ['front' => 'macchiato', 'back' => 'کافه ماکیاتو (نوشیدنی ایتالیایی)', 'pronunciation' => '/ˌmækiˈɑːtoʊ/'],
            ['front' => 'drum', 'back' => 'طبل', 'pronunciation' => '/drʌm/'],
            ['front' => 'pray', 'back' => 'دعا کردن', 'pronunciation' => '/preɪ/'],
            ['front' => 'chorus', 'back' => 'گروه کر', 'pronunciation' => '/ˈkɔːrəs/'],
            ['front' => 'bouquet', 'back' => 'دسته گل', 'pronunciation' => '/buˈkeɪ/'],
            ['front' => 'sleepwalk', 'back' => 'خوابگردی کردن', 'pronunciation' => '/ˈsliˌpwɔk/'],
            ['front' => 'cappuccino', 'back' => 'کاپوچینو', 'pronunciation' => '/ˌkæp.əˈtʃiː.noʊ/'],
            ['front' => 'psychic', 'back' => 'ماوراءالطبیعی', 'pronunciation' => '/ˈsaɪkɪk/'],
            ['front' => 'make a fool of oneself', 'back' => 'مسخره کردن', 'pronunciation' => '/meɪk ə ful ʌv ˌwʌnˈsɛlf/'],
            ['front' => 'psychologist', 'back' => 'روانشناس', 'pronunciation' => '/sɑɪˈkɑl.ə.dʒɪst/'],
            ['front' => 'siesta', 'back' => 'خواب نیمروز', 'pronunciation' => '/siˈestə/'],
            ['front' => 'nostalgia', 'back' => 'حسرت گذشته', 'pronunciation' => '/nəˈstældʒə/'],
            ['front' => 'comforter', 'back' => 'لحاف', 'pronunciation' => '/ˈkʌmfərtər/'],
            ['front' => 'microphone', 'back' => 'میکروفن', 'pronunciation' => '/ˈmaɪkrəfoʊn/'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 6 vocabulary added.');
    }

    protected function seedLesson7($deck)
    {
        $vocabulary = [
            ['front' => 'comb', 'back' => 'شانه زدن', 'pronunciation' => '/koʊm /'],
            ['front' => 'threaten', 'back' => 'تهدید کردن', 'pronunciation' => '/ˈθret.ən /'],
            ['front' => 'shrug', 'back' => 'شانه بالا انداختن (به نشانه ندانستن، تحقیر یا بی‏‌اعتنایی)', 'pronunciation' => '/ʃrʌɡ /'],
            ['front' => 'discuss', 'back' => 'مطرح کردن', 'pronunciation' => '/dɪˈskʌs /'],
            ['front' => 'expect', 'back' => 'انتظار داشتن', 'pronunciation' => '/ɪkˈspekt /'],
            ['front' => 'shake hands', 'back' => 'دست دادن (با کسی)', 'pronunciation' => '/ʃeɪk hændz /'],
            ['front' => 'swear word', 'back' => 'فحش', 'pronunciation' => '/ˈswer wɜːrd /'],
            ['front' => 'wait', 'back' => 'صبر کردن', 'pronunciation' => '/weɪt /'],
            ['front' => 'eyelid', 'back' => 'پلک', 'pronunciation' => '/ˈaɪlɪd /'],
            ['front' => 'notice', 'back' => 'متوجه شدن', 'pronunciation' => '/ˈnoʊtɪs /'],
            ['front' => 'achieve', 'back' => 'رسیدن (به هدف)', 'pronunciation' => '/əˈtʃiːv /'],
            ['front' => 'wish', 'back' => 'آرزو کردن', 'pronunciation' => '/wɪʃ /'],
            ['front' => 'realize', 'back' => 'فهمیدن', 'pronunciation' => '/ˈrɪə.laɪz /'],
            ['front' => 'body language', 'back' => 'زبان بدن', 'pronunciation' => '/ˈbɑdi ˈlæŋgwəʤ /'],
            ['front' => 'hope', 'back' => 'امیدوار بودن', 'pronunciation' => '/hoʊp /'],
            ['front' => 'wink', 'back' => 'چشمک زدن', 'pronunciation' => '/wɪŋk /'],
            ['front' => 'heart', 'back' => 'قلب', 'pronunciation' => '/hɑːrt /'],
            ['front' => 'heel', 'back' => 'پاشنه (پا، کفش و جوراب)', 'pronunciation' => '/hiːl /'],
            ['front' => 'beat', 'back' => 'شکست دادن', 'pronunciation' => '/biːt /'],
            ['front' => 'chew', 'back' => 'جویدن (غذا)', 'pronunciation' => '/ʧu /'],
            ['front' => 'look', 'back' => 'به نظر رسیدن', 'pronunciation' => '/lʊk /'],
            ['front' => 'kidney', 'back' => 'کلیه', 'pronunciation' => '/ˈkɪdni /'],
            ['front' => 'elbow', 'back' => 'آرنج', 'pronunciation' => '/ˈelboʊ /'],
            ['front' => 'confrontation', 'back' => 'مقابله', 'pronunciation' => '/ˌkɑnfrənˈteɪʃən /'],
            ['front' => 'win', 'back' => 'پیروز شدن', 'pronunciation' => '/wɪn /'],
            ['front' => 'hug', 'back' => 'بغل کردن', 'pronunciation' => '/hʌg /'],
            ['front' => 'fist', 'back' => 'مشت', 'pronunciation' => '/fɪst /'],
            ['front' => 'liver', 'back' => 'کبد (کالبدشناسی)', 'pronunciation' => '/ˈlɪvər /'],
            ['front' => 'seem', 'back' => 'به نظر رسیدن', 'pronunciation' => '/siːm /'],
            ['front' => 'telltale', 'back' => 'آشکارساز', 'pronunciation' => '/ˈtelteɪl /'],
            ['front' => 'back up', 'back' => 'حمایت کردن', 'pronunciation' => '/bæk ʌp /'],
            ['front' => 'refuse', 'back' => 'رد کردن', 'pronunciation' => '/rɪˈfjuːz /'],
            ['front' => 'nail', 'back' => 'ناخن', 'pronunciation' => '/neɪl /'],
            ['front' => 'scratch', 'back' => 'خاراندن', 'pronunciation' => '/skrætʃ /'],
            ['front' => 'lung', 'back' => 'ریه', 'pronunciation' => '/lʌŋ /'],
            ['front' => 'wave', 'back' => 'دست تکان دادن', 'pronunciation' => '/weɪv /'],
            ['front' => 'deny', 'back' => 'رد کردن', 'pronunciation' => '/dɪˈnɑɪ /'],
            ['front' => 'forehead', 'back' => 'پیشانی', 'pronunciation' => '/ˈfɑr.əd /'],
            ['front' => 'palm', 'back' => 'کف دست', 'pronunciation' => '/pɑːm /'],
            ['front' => 'lay', 'back' => '(روی چیزی) گذاشتن', 'pronunciation' => '/leɪ /'],
            ['front' => 'bite', 'back' => 'جویدن', 'pronunciation' => '/bɑɪt /'],
            ['front' => 'wrist', 'back' => 'مچ دست', 'pronunciation' => '/rɪst /'],
            ['front' => 'fold one\'s arms', 'back' => 'دست به سینه شدن', 'pronunciation' => '/foʊld wʌnz ɑrmz /'],
            ['front' => 'lie', 'back' => 'دراز کشیدن', 'pronunciation' => '/lɑɪ /'],
            ['front' => 'remind', 'back' => 'یادآوری کردن', 'pronunciation' => '/rɪˈmɑɪnd /'],
            ['front' => 'in contrast', 'back' => 'در مقابل', 'pronunciation' => '/ɪn ˈkɑntræst /'],
            ['front' => 'bottom', 'back' => 'باسن', 'pronunciation' => '/ˈbɑːtəm /'],
            ['front' => 'hold hands', 'back' => 'دست همدیگر را گرفتن', 'pronunciation' => '/hoʊld hændz /'],
            ['front' => 'steal', 'back' => 'دزدیدن', 'pronunciation' => '/stiːl /'],
            ['front' => 'pursue', 'back' => 'دنبال کردن', 'pronunciation' => '/pərˈsu /'],
            ['front' => 'blow', 'back' => '(بینی) گرفتن', 'pronunciation' => '/bloʊ /'],
            ['front' => 'remember', 'back' => 'به یاد آوردن', 'pronunciation' => '/rəˈmem.bər /'],
            ['front' => 'rob', 'back' => 'دزدی کردن', 'pronunciation' => '/rɑːb /'],
            ['front' => 'spot', 'back' => 'دیدن', 'pronunciation' => '/spɑt /'],
            ['front' => 'touch', 'back' => 'لمس کردن', 'pronunciation' => '/tʌtʃ /'],
            ['front' => 'lip', 'back' => 'لب', 'pronunciation' => '/lɪp /'],
            ['front' => 'bother', 'back' => 'مزاحم شدن', 'pronunciation' => '/ˈbɑð.ər /'],
            ['front' => 'prevent', 'back' => 'جلوگیری کردن', 'pronunciation' => '/prɪˈvent /'],
            ['front' => 'suspicion', 'back' => 'شک', 'pronunciation' => '/səˈspɪʃ.ən /'],
            ['front' => 'advise', 'back' => 'توصیه کردن', 'pronunciation' => '/ədˈvɑɪz /'],
            ['front' => 'suck', 'back' => 'مکیدن', 'pronunciation' => '/sʌk /'],
            ['front' => 'kneel', 'back' => 'زانو زدن', 'pronunciation' => '/nil /'],
            ['front' => 'neck', 'back' => 'گردن', 'pronunciation' => '/nek /'],
            ['front' => 'avoid', 'back' => 'دوری کردن', 'pronunciation' => '/əˈvɔɪd /'],
            ['front' => 'bring up', 'back' => 'مطرح کردن', 'pronunciation' => '/brɪŋ ʌp /'],
            ['front' => 'eyelash', 'back' => 'مژه', 'pronunciation' => '/ˈɑɪ.læʃ /'],
            ['front' => 'warn', 'back' => 'هشدار دادن', 'pronunciation' => '/wɔːrn /'],
            ['front' => 'frown', 'back' => 'اخم کردن', 'pronunciation' => '/fraʊn /'],
            ['front' => 'wrinkle', 'back' => 'چروک', 'pronunciation' => '/ˈrɪŋkl /'],
            ['front' => 'blame', 'back' => 'مقصر شناختن', 'pronunciation' => '/bleɪm /'],
            ['front' => 'stare', 'back' => 'زل زدن', 'pronunciation' => '/steər /'],
            ['front' => 'mind', 'back' => 'ناراحت شدن', 'pronunciation' => '/mɑɪnd /'],
            ['front' => 'ankle', 'back' => 'مچ پا', 'pronunciation' => '/ˈæŋkəl /'],
            ['front' => 'yawn', 'back' => 'خمیازه کشیدن', 'pronunciation' => '/jɔn /'],
            ['front' => 'insult', 'back' => 'توهین', 'pronunciation' => '/ˈɪnsʌlt /'],
            ['front' => 'chest', 'back' => 'سینه', 'pronunciation' => '/tʃest /'],
            ['front' => 'insult', 'back' => 'توهین کردن', 'pronunciation' => '/ˈɪnsʌlt /'],
            ['front' => 'calf', 'back' => 'نرمه ساق پا', 'pronunciation' => '/kæf /'],
            ['front' => 'stretch', 'back' => 'کش و قوس دادن', 'pronunciation' => '/stretʃ /'],
            ['front' => 'hip', 'back' => 'مفصل ران', 'pronunciation' => '/hɪp /'],
            ['front' => 'cheek', 'back' => 'گونه', 'pronunciation' => '/tʃiːk /'],
            ['front' => 'rise', 'back' => 'افزایش یافتن', 'pronunciation' => '/raɪz /'],
            ['front' => 'thigh', 'back' => 'ران', 'pronunciation' => '/θɑɪ /'],
            ['front' => 'point', 'back' => 'اشاره کردن', 'pronunciation' => '/pɔɪnt /'],
            ['front' => 'chin', 'back' => 'چانه', 'pronunciation' => '/tʃɪn /'],
            ['front' => 'raise', 'back' => 'بلند کردن', 'pronunciation' => '/reɪz /'],
            ['front' => 'waist', 'back' => 'کمر', 'pronunciation' => '/weɪst /'],
            ['front' => 'brush', 'back' => 'مسواک زدن', 'pronunciation' => '/brʌʃ /'],
            ['front' => 'eyebrow', 'back' => 'ابرو', 'pronunciation' => '/ˈɑɪbrɑʊ /'],
            ['front' => 'brain', 'back' => 'مغز', 'pronunciation' => '/breɪn /'],
            ['front' => 'argue', 'back' => 'بحث کردن', 'pronunciation' => '/ˈɑr.gjuː /'],
            ['front' => 'shake', 'back' => 'تکان دادن', 'pronunciation' => '/ʃeɪk /'],
            ['front' => 'matter', 'back' => 'اهمیت داشتن', 'pronunciation' => '/ˈmæt̬.ər /'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 7 vocabulary added.');
    }

    protected function seedLesson8($deck)
    {
        $vocabulary = [
            ['front' => 'evidence', 'back' => 'مدرک', 'pronunciation' => '/ˈev.əd.əns/'],
            ['front' => 'burgle', 'back' => 'دزدی کردن', 'pronunciation' => '/ˈbɜːrɡl/'],
            ['front' => 'censorship', 'back' => 'سانسور', 'pronunciation' => '/ˈsɛnsərˌʃɪp/'],
            ['front' => 'hijack', 'back' => 'دزدیدن (هواپیما، کشتی یا وسیله نقلیه)', 'pronunciation' => '/ˈhaɪˌʤæk/'],
            ['front' => 'blackmail', 'back' => 'حق السکوت', 'pronunciation' => '/ˈblækmeɪl/'],
            ['front' => 'guilty', 'back' => 'گناهکار', 'pronunciation' => '/ˈgɪl.ti/'],
            ['front' => 'false', 'back' => 'دروغین', 'pronunciation' => '/fɔls/'],
            ['front' => 'vandalize', 'back' => 'آسیب رساندن', 'pronunciation' => '/ˈvændəlaɪz/'],
            ['front' => 'forgery', 'back' => 'جعل', 'pronunciation' => '/ˈfɔːrdʒəri/'],
            ['front' => 'stalker', 'back' => 'مزاحم', 'pronunciation' => '/ˈstɔːkər/'],
            ['front' => 'newscaster', 'back' => 'مجری خبری (تلویزیون و رادیو)', 'pronunciation' => '/ˈnuzˌkæstər/'],
            ['front' => 'axe', 'back' => 'برکنار کردن', 'pronunciation' => '/æks/'],
            ['front' => 'hesitate', 'back' => 'تعلل کردن', 'pronunciation' => '/ˈhɛzəˌteɪt/'],
            ['front' => 'murder', 'back' => 'به قتل رساندن', 'pronunciation' => '/ˈmɜːrdər/'],
            ['front' => 'skip', 'back' => 'جلو زدن (فیلم، کتاب)', 'pronunciation' => '/skɪp/'],
            ['front' => 'paparazzi', 'back' => 'عکاسان', 'pronunciation' => '/ˌpæpəˈrætsi/'],
            ['front' => 'stalk', 'back' => 'تعقیب کردن', 'pronunciation' => '/stɔːk/'],
            ['front' => 'murderer', 'back' => 'قاتل', 'pronunciation' => '/ˈmɜːrdərər/'],
            ['front' => 'ignore', 'back' => 'بی‌توجهی کردن', 'pronunciation' => '/ɪgˈnɔr/'],
            ['front' => 'split', 'back' => 'جدا شدن', 'pronunciation' => '/splɪt/'],
            ['front' => 'forger', 'back' => 'جعل‌کننده', 'pronunciation' => '/ˈfɔːrdʒər/'],
            ['front' => 'robbery', 'back' => 'سرقت', 'pronunciation' => '/ˈrɑːbəri/'],
            ['front' => 'forge', 'back' => 'جعل کردن', 'pronunciation' => '/fɔːrdʒ/'],
            ['front' => 'rob', 'back' => 'دزدی کردن', 'pronunciation' => '/rɑːb/'],
            ['front' => 'objective', 'back' => 'بی‌طرفانه', 'pronunciation' => '/əbˈdʒek.tɪv/'],
            ['front' => 'arrest', 'back' => 'دستگیر کردن', 'pronunciation' => '/əˈrest/'],
            ['front' => 'innocent', 'back' => 'بی‌گناه', 'pronunciation' => '/ˈɪnəsnt/'],
            ['front' => 'smuggling', 'back' => 'قاچاق', 'pronunciation' => '/ˈsmʌɡlɪŋ/'],
            ['front' => 'overprotective', 'back' => 'بیش از حد مراقب و محتاط', 'pronunciation' => '/ˌoʊvərprəˈtektɪv/'],
            ['front' => 'accurate', 'back' => 'دقیق', 'pronunciation' => '/ˈækjərət/'],
            ['front' => 'fraud', 'back' => 'کلاهبرداری', 'pronunciation' => '/frɔːd/'],
            ['front' => 'terrorism', 'back' => 'تروریسم', 'pronunciation' => '/ˈter.əˌrɪz.əm/'],
            ['front' => 'question', 'back' => 'سوال پرسیدن', 'pronunciation' => '/ˈkwes.tʃən/'],
            ['front' => 'quiz', 'back' => 'سوال پرسیدن', 'pronunciation' => '/kwɪz/'],
            ['front' => 'judge', 'back' => 'قاضی', 'pronunciation' => '/ʤʌʤ/'],
            ['front' => 'news', 'back' => 'خبر', 'pronunciation' => '/nuːz/'],
            ['front' => 'fraudster', 'back' => 'کلاهبردار', 'pronunciation' => '/ˈfrɔːdstər/'],
            ['front' => 'spat', 'back' => 'مشاجره', 'pronunciation' => '/spæt/'],
            ['front' => 'tab', 'back' => 'انتخاب کردن', 'pronunciation' => '/tæb/'],
            ['front' => 'against', 'back' => 'مخالف', 'pronunciation' => '/əˈgenst/'],
            ['front' => 'terrorist', 'back' => 'تروریست', 'pronunciation' => '/ˈterərɪst/'],
            ['front' => 'bid', 'back' => 'تلاش کردن', 'pronunciation' => '/bɪd/'],
            ['front' => 'reporter', 'back' => 'گزارشگر', 'pronunciation' => '/rəˈpɔːrt̬.ər/'],
            ['front' => 'illegal', 'back' => 'غیرقانونی', 'pronunciation' => '/ɪˈligəl/'],
            ['front' => 'freelance', 'back' => 'آزاد', 'pronunciation' => '/ˈfriːlæns/'],
            ['front' => 'quit', 'back' => 'استعفا دادن', 'pronunciation' => '/kwɪt/'],
            ['front' => 'burglar', 'back' => 'دزد', 'pronunciation' => '/ˈbɜːrɡlər/'],
            ['front' => 'censor', 'back' => 'سانسور کردن', 'pronunciation' => '/ˈsɛnsər/'],
            ['front' => 'cab', 'back' => 'تاکسی', 'pronunciation' => '/kæb/'],
            ['front' => 'violent', 'back' => 'خشن', 'pronunciation' => '/ˈvaɪələnt/'],
            ['front' => 'advice columnist', 'back' => 'نویسنده ستون مشاوره (روزنامه و مجله)', 'pronunciation' => '/ædˈvaɪs ˈkɑləmnəst/'],
            ['front' => 'commit', 'back' => 'مرتکب شدن', 'pronunciation' => '/kəˈmɪt/'],
            ['front' => 'charge', 'back' => 'متهم کردن', 'pronunciation' => '/tʃɑːrdʒ/'],
            ['front' => 'mugger', 'back' => 'زورگیر', 'pronunciation' => '/ˈmʌɡər/'],
            ['front' => 'commentator', 'back' => 'گزارشگر', 'pronunciation' => '/ˈkɑːmənteɪtər/'],
            ['front' => 'hacking', 'back' => 'هک کردن', 'pronunciation' => '/ˈhækɪŋ/'],
            ['front' => 'smuggle', 'back' => 'قاچاق کردن', 'pronunciation' => '/ˈsmʌɡl/'],
            ['front' => 'print', 'back' => 'عکس چاپی', 'pronunciation' => '/prɪnt/'],
            ['front' => 'jury', 'back' => 'هیئت‌منصفه', 'pronunciation' => '/ˈdʒʊr.i/'],
            ['front' => 'pickpocket', 'back' => 'جیب بر', 'pronunciation' => '/ˈpɪkpɑːkɪt/'],
            ['front' => 'stalking', 'back' => 'تعقیب', 'pronunciation' => '/ˈstɔːkɪŋ/'],
            ['front' => 'proof', 'back' => 'مدرک', 'pronunciation' => '/pruːf/'],
            ['front' => 'kidnapping', 'back' => 'آدم‌ربایی', 'pronunciation' => '/ˈkɪdˌnæpɪŋ/'],
            ['front' => 'robber', 'back' => 'سارق', 'pronunciation' => '/ˈrɑːbər/'],
            ['front' => 'online', 'back' => 'آنلاین', 'pronunciation' => '/ˌɑːnˈlaɪn/'],
            ['front' => 'bother', 'back' => 'مزاحم شدن', 'pronunciation' => '/ˈbɑð.ər/'],
            ['front' => 'punishment', 'back' => 'مجازات', 'pronunciation' => '/ˈpʌnɪʃmənt/'],
            ['front' => 'kidnapper', 'back' => 'آدم‌ربا', 'pronunciation' => '/ˈkɪdˌnæpər/'],
            ['front' => 'get caught', 'back' => 'گیر افتادن', 'pronunciation' => '/gɛt kɑt/'],
            ['front' => 'private', 'back' => 'خصوصی', 'pronunciation' => '/ˈpraɪvət/'],
            ['front' => 'kidnap', 'back' => 'آدم‌ربایی کردن', 'pronunciation' => '/ˈkɪdnæp/'],
            ['front' => 'sentence', 'back' => 'محکوم کردن', 'pronunciation' => '/ˈsen.t̬əns/'],
            ['front' => 'investigate', 'back' => 'بررسی کردن', 'pronunciation' => '/ɪnˈvestɪɡeɪt/'],
            ['front' => 'sensational', 'back' => 'مهیج', 'pronunciation' => '/senˈseɪʃənl/'],
            ['front' => 'taxi', 'back' => 'تاکسی', 'pronunciation' => '/ˈtæksi/'],
            ['front' => 'theft', 'back' => 'دزدی', 'pronunciation' => '/θeft/'],
            ['front' => 'hacker', 'back' => 'هکر', 'pronunciation' => '/ˈhækər/'],
            ['front' => 'trial', 'back' => 'محاکمه', 'pronunciation' => '/ˈtraɪəl/'],
            ['front' => 'biased', 'back' => 'متعصبانه', 'pronunciation' => '/ˈbaɪəst/'],
            ['front' => 'steal', 'back' => 'دزدیدن', 'pronunciation' => '/stiːl/'],
            ['front' => 'hack', 'back' => 'هک کردن (رایانه)', 'pronunciation' => '/hæk/'],
            ['front' => 'blackmailer', 'back' => 'باج‌گیر', 'pronunciation' => '/ˈblækmeɪlər/'],
            ['front' => 'critic', 'back' => 'منتقد', 'pronunciation' => '/ˈkrɪtɪk/'],
            ['front' => 'vandalism', 'back' => 'تخریب آثار عمومی و باارزش', 'pronunciation' => '/ˈvændəlɪzəm/'],
            ['front' => 'blackmail', 'back' => 'اخاذی کردن', 'pronunciation' => '/ˈblækmeɪl/'],
            ['front' => 'watch out', 'back' => 'مراقب بودن', 'pronunciation' => '/wɑʧ aʊt/'],
            ['front' => 'hijacking', 'back' => 'سرقت (هواپیما)', 'pronunciation' => '/ˈhaɪˌʤækɪŋ/'],
            ['front' => 'accuse', 'back' => 'متهم کردن', 'pronunciation' => '/əˈkjuz/'],
            ['front' => 'law', 'back' => 'قانون', 'pronunciation' => '/lɔ/'],
            ['front' => 'vandal', 'back' => 'خرابکار', 'pronunciation' => '/ˈvændəl/'],
            ['front' => 'bribery', 'back' => 'رشوه‌خواری', 'pronunciation' => '/ˈbraɪbəri/'],
            ['front' => 'clash', 'back' => 'جر و بحث کردن', 'pronunciation' => '/klæʃ/'],
            ['front' => 'hijacker', 'back' => 'سارق (هواپیما، کشتی و...)', 'pronunciation' => '/ˈhaɪˌʤækər/'],
            ['front' => 'editor', 'back' => 'سردبیر (روزنامه، مجله و ...)', 'pronunciation' => '/ˈed.ə.tər/'],
            ['front' => 'bribe', 'back' => 'رشوه دادن', 'pronunciation' => '/braɪb/'],
            ['front' => 'mugging', 'back' => 'زورگیری', 'pronunciation' => '/ˈmʌɡɪŋ/'],
            ['front' => 'witness', 'back' => 'شاهد', 'pronunciation' => '/ˈwɪtnəs/'],
            ['front' => 'news anchor', 'back' => 'گوینده خبر', 'pronunciation' => '/njuz ˈæŋkər/'],
            ['front' => 'vow', 'back' => 'قسم خوردن', 'pronunciation' => '/vaʊ/'],
            ['front' => 'journalist', 'back' => 'روزنامه‌نگار', 'pronunciation' => '/ˈʤɜrnələst/'],
            ['front' => 'celebrity', 'back' => 'آدم مشهور', 'pronunciation' => '/səˈlɛbrɪti/'],
            ['front' => 'burglary', 'back' => 'دزدی', 'pronunciation' => '/ˈbɜːrɡləri/'],
            ['front' => 'shoplifter', 'back' => 'دزد مغازه/فروشگاه', 'pronunciation' => '/ˈʃɑːplɪftər/'],
            ['front' => 'wed', 'back' => 'ازدواج کردن', 'pronunciation' => '/wed/'],
            ['front' => 'acquit', 'back' => 'تبرئه کردن', 'pronunciation' => '/əˈkwɪt/'],
            ['front' => 'mug', 'back' => 'زورگیری کردن', 'pronunciation' => '/mʌg/'],
            ['front' => 'thief', 'back' => 'دزد', 'pronunciation' => '/θiːf/'],
            ['front' => 'media', 'back' => 'رسانه', 'pronunciation' => '/ˈmidiə/'],
            ['front' => 'break in', 'back' => 'به زور وارد شدن (معمولاً برای دزدی)', 'pronunciation' => '/breɪk ɪn/'],
            ['front' => 'back', 'back' => 'حمایت کردن', 'pronunciation' => '/bæk/'],
            ['front' => 'court', 'back' => 'دادگاه', 'pronunciation' => '/kɔːrt/'],
            ['front' => 'gossip', 'back' => 'شایعه', 'pronunciation' => '/ˈgɑs.əp/'],
            ['front' => 'verdict', 'back' => 'حکم', 'pronunciation' => '/ˈvɜrdɪkt/'],
            ['front' => 'download', 'back' => 'دانلود کردن', 'pronunciation' => '/ˈdɑʊn.loʊd/'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 8 vocabulary added.');
    }

    protected function seedLesson9($deck)
    {
        $vocabulary = [
            ['front' => 'coldness', 'back' => 'سردی', 'pronunciation' => '/ˈkoʊldnəs /'],
            ['front' => 'postgraduate', 'back' => 'تحصیلات تکمیلی', 'pronunciation' => '/ˌpoʊstˈɡrædʒuət /'],
            ['front' => 'market research', 'back' => 'مطالعات بازار', 'pronunciation' => '/ˌmɑːrkɪt rɪˈsɜːrtʃ /'],
            ['front' => 'pollution', 'back' => 'آلودگی', 'pronunciation' => '/pəˈluʃən /'],
            ['front' => 'deal', 'back' => 'قرارداد', 'pronunciation' => '/diːl /'],
            ['front' => 'manufacture', 'back' => 'تولید کردن', 'pronunciation' => '/ˌmænjuˈfæktʃər /'],
            ['front' => 'megacity', 'back' => 'کلان‌شهر', 'pronunciation' => '/ˈmeɡəsɪti /'],
            ['front' => 'homeless', 'back' => 'بی‌خانمان', 'pronunciation' => '/ˈhoʊmləs /'],
            ['front' => 'brand', 'back' => 'نشان تجاری', 'pronunciation' => '/brænd /'],
            ['front' => 'manager', 'back' => 'مدیر', 'pronunciation' => '/ˈmæn.ɪdʒ.ər /'],
            ['front' => 'market', 'back' => 'به بازار عرضه کردن', 'pronunciation' => '/ˈmɑr.kɪt /'],
            ['front' => 'money', 'back' => 'پول', 'pronunciation' => '/ˈmʌn.i /'],
            ['front' => 'misleading', 'back' => 'گمراه‌کننده', 'pronunciation' => '/mɪsˈliːd.ɪŋ /'],
            ['front' => 'customer', 'back' => 'مشتری', 'pronunciation' => '/ˈkʌs.tə.mər /'],
            ['front' => 'hopeless', 'back' => 'مأیوس‌کننده', 'pronunciation' => '/ˈhoʊ.pləs /'],
            ['front' => 'owner', 'back' => 'مالک', 'pronunciation' => '/ˈoʊ.nər /'],
            ['front' => 'market', 'back' => 'بازار', 'pronunciation' => '/ˈmɑr.kɪt /'],
            ['front' => 'careful', 'back' => 'مراقب', 'pronunciation' => '/ˈker.fəl /'],
            ['front' => 'well', 'back' => 'به‌خوبی', 'pronunciation' => '/wel /'],
            ['front' => 'alienation', 'back' => 'بیگانگی', 'pronunciation' => '/ˌeɪliəˈneɪʃn /'],
            ['front' => 'staff', 'back' => 'پرسنل', 'pronunciation' => '/stæf /'],
            ['front' => 'decision', 'back' => 'تصمیم', 'pronunciation' => '/dɪˈsɪʒ.ən /'],
            ['front' => 'autopilot', 'back' => 'خلبان خودکار', 'pronunciation' => '/ˈɔːtəʊpaɪlət /'],
            ['front' => 'population', 'back' => 'جمعیت', 'pronunciation' => '/ˌpɑpjəˈleɪʃən /'],
            ['front' => 'useful', 'back' => 'سودمند', 'pronunciation' => '/ˈjuːs.fəl /'],
            ['front' => 'automated', 'back' => 'خودکار', 'pronunciation' => '/ˈɔtəˌmeɪtɪd /'],
            ['front' => 'badly', 'back' => 'بد', 'pronunciation' => '/ˈbædli /'],
            ['front' => 'investment', 'back' => 'سرمایه‌گذاری', 'pronunciation' => '/ɪnˈvestmənt /'],
            ['front' => 'grow', 'back' => 'رشد کردن', 'pronunciation' => '/groʊ /'],
            ['front' => 'racism', 'back' => 'نژادپرستی', 'pronunciation' => '/ˈreɪˌsɪz.əm /'],
            ['front' => 'commuter', 'back' => 'مسافر (هر روزه)', 'pronunciation' => '/kəmˈjutər /'],
            ['front' => 'job', 'back' => 'شغل', 'pronunciation' => '/dʒɑːb /'],
            ['front' => 'waterproof', 'back' => 'ضد آب', 'pronunciation' => '/ˈwɔːt̬.ərˌpruːf /'],
            ['front' => 'inhabitant', 'back' => 'ساکن', 'pronunciation' => '/ɪnˈhæb.ɪ.tənt /'],
            ['front' => 'expand', 'back' => 'گسترش دادن', 'pronunciation' => '/ɪkˈspænd /'],
            ['front' => 'reporter', 'back' => 'گزارشگر', 'pronunciation' => '/rəˈpɔːrt̬.ər /'],
            ['front' => 'underdeveloped', 'back' => 'توسعه‌نیافته', 'pronunciation' => '/ˌʌndərdɪˈveləpt /'],
            ['front' => 'loss', 'back' => 'ضرر', 'pronunciation' => '/lɑːs /'],
            ['front' => 'ad', 'back' => 'آگهی', 'pronunciation' => '/æd /'],
            ['front' => 'loneliness', 'back' => 'تنهایی', 'pronunciation' => '/ˈloʊnlinəs /'],
            ['front' => 'merge', 'back' => 'ادغام شدن', 'pronunciation' => '/mɜrʤ /'],
            ['front' => 'absent', 'back' => 'غایب', 'pronunciation' => '/ˈæb.sənt /'],
            ['front' => 'chief executive officer', 'back' => 'مدیر عامل اجرایی', 'pronunciation' => '/ˌtʃiːf ɪɡˈzekjətɪv ɑːfɪsər /'],
            ['front' => 'prefix', 'back' => 'پیشوند', 'pronunciation' => '/ˈpriːfɪks /'],
            ['front' => 'poverty', 'back' => 'فقر', 'pronunciation' => '/ˈpɑːvərti /'],
            ['front' => 'profit', 'back' => 'سود', 'pronunciation' => '/ˈprɑːfɪt /'],
            ['front' => 'firm', 'back' => 'شرکت', 'pronunciation' => '/fɜːrm /'],
            ['front' => 'advertisement', 'back' => 'تبلیغات', 'pronunciation' => '/ˌæd.vərˈtɑɪz.mənt /'],
            ['front' => 'convenience', 'back' => 'سهولت', 'pronunciation' => '/kənˈviːn.jəns /'],
            ['front' => 'business', 'back' => 'کار', 'pronunciation' => '/ˈbɪz.nɪs /'],
            ['front' => 'suffix', 'back' => 'پسوند', 'pronunciation' => '/ˈsʌf.ɪks /'],
            ['front' => 'distance', 'back' => 'مسافت', 'pronunciation' => '/ˈdɪs.təns /'],
            ['front' => 'sue', 'back' => 'شکایت کردن', 'pronunciation' => '/suː /'],
            ['front' => 'absenteeism', 'back' => 'غیبت', 'pronunciation' => '/ˌæbsənˈtiːɪzəm /'],
            ['front' => 'multicultural', 'back' => 'چند فرهنگی', 'pronunciation' => '/ˌmʌltiˈkʌlʧərəl /'],
            ['front' => 'unbreakable', 'back' => 'غیر قابل شکستن', 'pronunciation' => '/ənˈbreɪkəbəl /'],
            ['front' => 'company', 'back' => 'شرکت', 'pronunciation' => '/ˈkʌm.pə.ni /'],
            ['front' => 'produce', 'back' => 'تولید کردن', 'pronunciation' => '/prəˈduːs /'],
            ['front' => 'antisocial behavior', 'back' => 'رفتار ضداجتماعی', 'pronunciation' => '/ˌæntɪˈsoʊʃəl bɪˈheɪvjər /'],
            ['front' => 'research', 'back' => 'پژوهش', 'pronunciation' => '/rɪˈsɜrtʃ /'],
            ['front' => 'subway', 'back' => 'مترو', 'pronunciation' => '/ˈsʌbweɪ /'],
            ['front' => 'entertainment', 'back' => 'سرگرمی', 'pronunciation' => '/ˌɛntərˈteɪnmənt /'],
            ['front' => 'commercial', 'back' => 'پیام بازرگانی', 'pronunciation' => '/kəˈmɜr.ʃəl /'],
            ['front' => 'misunderstand', 'back' => 'اشتباه فهمیدن', 'pronunciation' => '/ˌmɪsəndərˈstænd /'],
            ['front' => 'client', 'back' => 'مشتری', 'pronunciation' => '/ˈklaɪənt /'],
            ['front' => 'bilingual', 'back' => 'دو زبانه', 'pronunciation' => '/baɪˈlɪŋgwəl /'],
            ['front' => 'export', 'back' => 'صادر کردن', 'pronunciation' => '/ekˈspɔːrt /'],
            ['front' => 'become', 'back' => 'شدن', 'pronunciation' => '/bɪˈkʌm /'],
            ['front' => 'in charge of', 'back' => 'مسئول', 'pronunciation' => '/ɪn ʧɑrʤ ʌv /'],
            ['front' => 'set up', 'back' => 'برپا کردن', 'pronunciation' => '/sɛt ʌp /'],
            ['front' => 'excitement', 'back' => 'هیجان', 'pronunciation' => '/ɪkˈsɑɪt.mənt /'],
            ['front' => 'colleague', 'back' => 'همکار', 'pronunciation' => '/ˈkɑlig /'],
            ['front' => 'fumes', 'back' => 'دود', 'pronunciation' => '/fjuːmz /'],
            ['front' => 'import', 'back' => 'وارد کردن', 'pronunciation' => '/ˈɪmpɔːrt /'],
            ['front' => 'reduction', 'back' => 'کاهش', 'pronunciation' => '/rɪˈdʌk.ʃən /'],
            ['front' => 'close down', 'back' => 'تعطیل کردن (موقتی یا برای همیشه)', 'pronunciation' => '/kloʊs daʊn /'],
            ['front' => 'take over', 'back' => 'تصاحب کردن', 'pronunciation' => '/teɪk ˈoʊvər /'],
            ['front' => 'claim', 'back' => 'ادعا کردن', 'pronunciation' => '/kleɪm /'],
            ['front' => 'branch', 'back' => 'شعبه', 'pronunciation' => '/bræntʃ /'],
            ['front' => 'friendliness', 'back' => 'صمیمیت', 'pronunciation' => '/ˈfren.dli.nəs /'],
            ['front' => 'contract', 'back' => 'قرارداد', 'pronunciation' => '/ˈkɑːntrækt /'],
            ['front' => 'terrorism', 'back' => 'تروریسم', 'pronunciation' => '/ˈter.əˌrɪz.əm /'],
            ['front' => 'unthinkable', 'back' => 'غیرممکن', 'pronunciation' => '/ʌnˈθɪŋkəbl /'],
            ['front' => 'launch', 'back' => 'به بازار معرفی کردن', 'pronunciation' => '/lɔːntʃ /'],
            ['front' => 'wealthy', 'back' => 'ثروتمند', 'pronunciation' => '/ˈwɛlθi /'],
            ['front' => 'campaign', 'back' => 'کمپین', 'pronunciation' => '/kæmˈpeɪn /'],
            ['front' => 'monorail', 'back' => 'مونوریل', 'pronunciation' => '/ˈmɑːnoʊreɪl /'],
            ['front' => 'employee', 'back' => 'کارمند', 'pronunciation' => '/ɛmˈplɔɪi /'],
            ['front' => 'appeal', 'back' => 'جذابیت داشتن', 'pronunciation' => '/əˈpil /'],
            ['front' => 'consumer', 'back' => 'مصرف‌کننده', 'pronunciation' => '/kənˈsuːmər /'],
            ['front' => 'governance', 'back' => 'حکمرانی', 'pronunciation' => '/ˈɡʌvərnəns /'],
            ['front' => 'chain', 'back' => 'زنجیره', 'pronunciation' => '/tʃeɪn /'],
            ['front' => 'management', 'back' => 'مدیریت', 'pronunciation' => '/ˈmænɪdʒmənt /'],
            ['front' => 'ugliness', 'back' => 'زشتی', 'pronunciation' => '/ˈʌɡlinəs /'],
            ['front' => 'airbrush', 'back' => 'با قلم بادی نقاشی کشیدن', 'pronunciation' => '/ˈerbrʌʃ /'],
            ['front' => 'headquarters', 'back' => 'اداره کل', 'pronunciation' => '/ˈhɛdˌkwɔrtərz /'],
            ['front' => 'celebrity', 'back' => 'آدم مشهور', 'pronunciation' => '/səˈlɛbrɪti /'],
            ['front' => 'government', 'back' => 'دولت', 'pronunciation' => '/ˈgʌvərmənt /'],
            ['front' => 'under', 'back' => 'تحت رهبری', 'pronunciation' => '/ˈʌndər /'],
            ['front' => 'product', 'back' => 'محصول', 'pronunciation' => '/ˈprɑːdʌkt /'],
            ['front' => 'drop', 'back' => 'کاهش یافتن', 'pronunciation' => '/drɑːp /'],
            ['front' => 'weakness', 'back' => 'ضعف', 'pronunciation' => '/ˈwiːk.nəs /'],
            ['front' => 'jingle', 'back' => 'جرینگ جرینگ صدا دادن', 'pronunciation' => '/ˈʤɪŋgəl /'],
            ['front' => 'multinational', 'back' => 'چندملیتی', 'pronunciation' => '/ˌmʌlˌtaɪˈnæʃənəl /'],
            ['front' => 'ignorance', 'back' => 'جهالت', 'pronunciation' => '/ˈɪgnərəns /'],
            ['front' => 'leader', 'back' => 'رهبر', 'pronunciation' => '/ˈliːdər /'],
            ['front' => 'slogan', 'back' => 'شعار', 'pronunciation' => '/ˈsloʊɡən /'],
            ['front' => 'improvement', 'back' => 'بهبود', 'pronunciation' => '/ɪmˈpruːv.mənt /'],
            ['front' => 'overcrowded', 'back' => 'پر ازدحام', 'pronunciation' => '/ˌoʊvərˈkraʊdɪd /'],
            ['front' => 'drinkable', 'back' => 'آشامیدنی', 'pronunciation' => '/ˈdrɪŋkəbl /'],
            ['front' => 'endorse', 'back' => 'تایید کردن', 'pronunciation' => '/ɪnˈdɔːrs /'],
            ['front' => 'intention', 'back' => 'قصد', 'pronunciation' => '/ɪnˈten.ʃən /'],
            ['front' => 'airbrush', 'back' => 'قلم بادی', 'pronunciation' => '/ˈerbrʌʃ /'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 9 vocabulary added.');
    }

    protected function seedLesson10($deck)
    {
        $vocabulary = [
            ['front' => 'laboratory', 'back' => 'آزمایشگاه', 'pronunciation' => '/ˈlæb.rəˌtɔːr.i /'],
            ['front' => 'scientist', 'back' => 'دانشمند', 'pronunciation' => '/ˈsɑɪ.ən.tɪst /'],
            ['front' => 'blood donor', 'back' => 'اهداکننده خون', 'pronunciation' => '/ˈblʌd doʊnər /'],
            ['front' => 'research', 'back' => 'پژوهش', 'pronunciation' => '/rɪˈsɜrtʃ /'],
            ['front' => 'scientific', 'back' => 'علمی', 'pronunciation' => '/ˌsɑɪ.ənˈtɪf.ɪk /'],
            ['front' => 'inhale', 'back' => 'استنشاق کردن', 'pronunciation' => '/ɪnˈheɪl /'],
            ['front' => 'geographer', 'back' => 'جغرافیدان', 'pronunciation' => '/dʒiˈɑːɡrəfər /'],
            ['front' => 'side effects', 'back' => 'عوارض جانبی', 'pronunciation' => '/ˈsaɪd ɪfekts /'],
            ['front' => 'hunger strike', 'back' => 'اعتصاب غذا', 'pronunciation' => '/ˈhʌŋɡər straɪk /'],
            ['front' => 'give and take', 'back' => 'بده‌بستان', 'pronunciation' => '/gɪv ænd teɪk /'],
            ['front' => 'geographic', 'back' => 'جغرافیایی', 'pronunciation' => '/ˌʤiəˈgræfɪk /'],
            ['front' => 'science', 'back' => 'علوم', 'pronunciation' => '/ˈsɑɪ.əns /'],
            ['front' => 'invasion', 'back' => 'اشغال', 'pronunciation' => '/ɪnˈveɪ.ʒən /'],
            ['front' => 'test', 'back' => 'آزمون', 'pronunciation' => '/test /'],
            ['front' => 'geography', 'back' => 'جغرافیا', 'pronunciation' => '/dʒiːˈɑg.rə.fi /'],
            ['front' => 'theory', 'back' => 'نظریه', 'pronunciation' => '/ˈθɪri /'],
            ['front' => 'prove', 'back' => 'اثبات کردن', 'pronunciation' => '/pruv /'],
            ['front' => 'carry out', 'back' => 'انجام دادن', 'pronunciation' => '/ˈkæri aʊt /'],
            ['front' => 'make a speech', 'back' => 'سخنرانی کردن', 'pronunciation' => '/meɪk ə spiʧ /'],
            ['front' => 'pharmaceutical', 'back' => 'دارویی', 'pronunciation' => '/ˌfɑːrməˈsuːtɪkl /'],
            ['front' => 'quote', 'back' => 'نقل‌قول کردن', 'pronunciation' => '/kwoʊt /'],
            ['front' => 'discovery', 'back' => 'اکتشاف', 'pronunciation' => '/dɪˈskʌv.ə.ri /'],
            ['front' => 'sacred', 'back' => 'مقدس', 'pronunciation' => '/ˈseɪkrəd /'],
            ['front' => 'volunteer', 'back' => 'داوطلب', 'pronunciation' => '/ˌvɑlənˈtɪr /'],
            ['front' => 'chemist', 'back' => 'شیمی‌دان', 'pronunciation' => '/ˈkem.əst /'],
            ['front' => 'drug', 'back' => 'دارو', 'pronunciation' => '/drʌg /'],
            ['front' => 'ups and downs', 'back' => 'بالا و پایین', 'pronunciation' => '/ʌps ænd daʊnz /'],
            ['front' => 'sacrifice', 'back' => 'فدا کردن', 'pronunciation' => '/ˈsækrəˌfaɪs /'],
            ['front' => 'lead poisoning', 'back' => 'مسمومیت سرب', 'pronunciation' => '/lid ˈpɔɪzənɪŋ /'],
            ['front' => 'clinical', 'back' => 'پزشکی', 'pronunciation' => '/ˈklɪnɪkl /'],
            ['front' => 'surrender', 'back' => 'تسلیم شدن', 'pronunciation' => '/səˈrendər /'],
            ['front' => 'lethal', 'back' => 'مهلک', 'pronunciation' => '/ˈliːθl /'],
            ['front' => 'trial', 'back' => 'آزمایش', 'pronunciation' => '/ˈtraɪəl /'],
            ['front' => 'dose', 'back' => 'مقدار (دارو)', 'pronunciation' => '/doʊs /'],
            ['front' => 'chemistry', 'back' => 'شیمی', 'pronunciation' => '/ˈkem.ə.stri /'],
            ['front' => 'law and order', 'back' => 'نظم و قانون', 'pronunciation' => '/lɔ ænd ˈɔrdər /'],
            ['front' => 'nuclear', 'back' => 'هسته‌ای', 'pronunciation' => '/ˈnuː.kliː.ər /'],
            ['front' => 'biologist', 'back' => 'زیست‌شناس', 'pronunciation' => '/baɪˈɑləʤɪst /'],
            ['front' => 'safe and sound', 'back' => 'امن و امان', 'pronunciation' => '/seɪf ænd saʊnd /'],
            ['front' => 'radiation', 'back' => 'تشعشع', 'pronunciation' => '/ˌreɪdiˈeɪʃn /'],
            ['front' => 'biological', 'back' => 'زیستی', 'pronunciation' => '/ˌbɑɪ.əˈlɑdʒ.ɪ.kəl /'],
            ['front' => 'sooner or later', 'back' => 'دیر یا زود', 'pronunciation' => '/ˈsunər ɔr ˈleɪtər /'],
            ['front' => 'biology', 'back' => 'زیست شناسی', 'pronunciation' => '/bɑɪˈɑl.ə.dʒi /'],
            ['front' => 'physicist', 'back' => 'فیزیکدان', 'pronunciation' => '/ˈfɪzɪsɪst /'],
            ['front' => 'physical', 'back' => 'جسمی', 'pronunciation' => '/ˈfɪz.ɪ.kəl /'],
            ['front' => 'anesthetic', 'back' => '(داروی) بی‌حس‌کننده', 'pronunciation' => '/ˌænəˈsθɛtɪk /'],
            ['front' => 'more or less', 'back' => 'کم و بیش', 'pronunciation' => '/mɔr ɔr lɛs /'],
            ['front' => 'apartheid', 'back' => 'آپارتاید (نوعی تبعیض نژادی)', 'pronunciation' => '/əˈpɑːrtaɪt /'],
            ['front' => 'physics', 'back' => 'فیزیک', 'pronunciation' => '/ˈfɪz.ɪks /'],
            ['front' => 'once or twice', 'back' => 'چند دفعه', 'pronunciation' => '/wʌns ɔr twaɪs /'],
            ['front' => 'geneticist', 'back' => 'متخصص ژنتیک', 'pronunciation' => '/dʒəˈnetɪsɪst /'],
            ['front' => 'battle', 'back' => 'نبرد', 'pronunciation' => '/ˈbæt̬.əl /'],
            ['front' => 'odds and ends', 'back' => 'خرت‌وپرت', 'pronunciation' => '/ɑdz ænd ɛndz /'],
            ['front' => 'experiment', 'back' => 'آزمایش', 'pronunciation' => '/ɪkˈsper.ə.mənt /'],
            ['front' => 'genetics', 'back' => '(علم) ژنتیک', 'pronunciation' => '/dʒəˈnet̬.ɪks /'],
            ['front' => 'now and then', 'back' => 'گاهی', 'pronunciation' => '/naʊ ænd ðɛn /'],
            ['front' => 'blood transfusion', 'back' => 'انتقال خون', 'pronunciation' => '/ˈblʌd trænsfjuːʒn /'],
            ['front' => 'guinea pig', 'back' => 'موش آزمایشگاهی', 'pronunciation' => '/ˈɡɪni pɪɡ /'],
            ['front' => 'go on', 'back' => 'ادامه دادن', 'pronunciation' => '/goʊ ɑn /'],
            ['front' => 'genetic', 'back' => 'ژنتیکی (زیست شناسی)', 'pronunciation' => '/ʤəˈnɛtɪk /'],
        ];

        foreach ($vocabulary as $item) {
            $deck->vocabulary()->create([
                'front' => $item['front'],
                'back' => $item['back'],
                'pronunciation' => $item['pronunciation'],
            ]);
        }

        $this->command->info('Lesson 10 vocabulary added.');
    }

    private function seedVocabulary($deck, $vocabulary, $lessonName)
    {
        foreach ($vocabulary as $cardData) {
            StaticCard::updateOrCreate(
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                ],
                [
                    'static_deck_id' => $deck->id,
                    'front' => $cardData['front'],
                    'back' => $cardData['back'],
                    'interval' => 1,
                    'revised_at' => null,
                    'last_reviewed' => null,
                ]
            );
        }

        $this->command->info('Seeded ' . count($vocabulary) . ' cards for ' . $lessonName);
    }
}
